/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.spbu.pldoctoolkit.graph.validation;

import org.spbu.pldoctoolkit.graph.InfElemRef;
import org.spbu.pldoctoolkit.graph.NestPoint;

/**
 * A sample validator interface for {@link org.spbu.pldoctoolkit.graph.InfElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfElementValidator {
	boolean validate();

	boolean validateNestPoints(NestPoint value);
	boolean validateOwnerInfElemRef(InfElemRef value);
}
