/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.spbu.pldoctoolkit.graph.validation;

import org.spbu.pldoctoolkit.graph.DocumentationCore;
import org.spbu.pldoctoolkit.graph.PLScheme;
import org.spbu.pldoctoolkit.graph.ProductDocumentation;

/**
 * A sample validator interface for {@link org.spbu.pldoctoolkit.graph.ProductLine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductLineValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateProductDocumentations(ProductDocumentation value);
	boolean validateDocumentationCore(DocumentationCore value);
	boolean validateScheme(PLScheme value);
}
