<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" filename="Drugie_funkcii_prilozeniya.drl">
   <d:InfElement id="join_in_applications" name="Другие функции Приложения"
                 parenttype="DocumentationCore"
                 filename="Drugie_funkcii_prilozeniya.drl">









      <section>
         <title>3.4. Техническое обслуживание</title>
         <section>
            <title>3.4.1. Тест номеронабирателя</title>
            <section>
               <title>Обзор</title>
               <para>Данное приложениие предназначено для проверки импульсного
и тонового номеронабирателя телефонного аппарата абонента. С его
помощью оператор может:</para>
               <itemizedlist>
                  <listitem>
                     <para>проверить статистику (параметры) номеронабирателя
телефонного аппарата любого абонента, подключённого к станции</para>
                  </listitem>
                  <listitem>
                     <para>посмотреть цифры набираемые абонентом в режиме реального
времени</para>
                  </listitem>
                  <listitem>
                     <para>помотреть диаграмму импульсов, посылаемых телефонным
аппаратом абонента при наборе номера</para>
                  </listitem>
                  <listitem>
                     <para>при тестированиии импульсного номеронабирателя,
выбрать канал<xref linkend="МЧП" role="Undefined Cross-Reference"/>который
будет использоваться для анализа поступающих импульсов</para>
                  </listitem>
               </itemizedlist>
            </section>
            <section>
               <title>Главное окно</title>
               <para>После запуска приложения появляется главное окно, которое
выглядит следующим образом:</para>
               <informalfigure float="0">
                  <graphic width="5.514in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/test-nomeronabiratelja.gif"/>
               </informalfigure>
               <para>В этом окне вы увидите следующее:</para>
               <para>
                  <command moreinfo="none">Элементы управления приложения Тест номеронабирателя
(см. разд. «3.4.1 Тест номеронабирателя»)</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Номер абонента</entry>
                           <entry colname="2">Элемент с выпадающим меню для введения (выбора) телефонного
номера тестируемого абонента</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тип набора</entry>
                           <entry colname="2">Тип номеронабирателя (имульсный/тоновый)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Диаграмма</entry>
                           <entry colname="2">Графическое отображение отсканированных импульсов исходящих от абонента</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Набранные цифры</entry>
                           <entry colname="2">Упорядоченная последовательность цифр (номер), распознанных станцией по входящим импульсам</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Инструментальная панель</entry>
                           <entry colname="2">Состоит из функциональных кнопок:<command moreinfo="none">Старт, Стоп, Статистика, Абонент, Легенда, Справка</command>
                           </entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Перед началом тестирования необходимо выбрать телефонный номер
абонента которого нужно тестировать из выпадающего меню (предполагается,
что оператор в это время находится в телефонном разговоре с этим
абонентом). После чего нужно выбрать тип номеронабирателя. Имеется
возможность тестировать импульсный и тоновый номеронабиратели:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Импульсный</entry>
                           <entry colname="2">В этом случае необходимо нажать на радио-кнопку<command moreinfo="none">Импульсный</command>(она
нажата по умолчанию)</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Тоновый</entry>
                           <entry colname="2">В этом случае необходимо нажать на радио-кнопку<command moreinfo="none">Тоновый</command>
                           </entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>После этого можно начать исполнение нажатием кнопки<command moreinfo="none">Старт</command>,
которая находится на инструментальной панели в верхней части окна.
После этого оператор сообщает абоненту, что тот должен набрать номер
(цифру) на своём телефоне. После набора абонентом всех цифр оператор
должен нажать кнопку<command moreinfo="none">Стоп</command>, которая расположена
рядом с кнопкой<command moreinfo="none">Старт</command>. В приложении анализируются
цифры, набранные абонентом за последние десять секунд до нажатия
оператором кнопки<command moreinfo="none">Стоп</command>. Выполнив анализ, приложение
сообщает следующую информацию:</para>
               <itemizedlist>
                  <listitem>
                     <para>Диаграмма импульсов полученных от
телефонного аппарата абонента</para>
                  </listitem>
                  <listitem>
                     <para>Последовательный набор цифр (номер), распознанных
станцией по входящим импульсам</para>
                  </listitem>
                  <listitem>
                     <para>Статистика (параметры) номеронабирателя (находится
в окне<emphasis>Статистика</emphasis>, которое открывается нажатием
соответствующей кнопки на инструментальной панели)</para>
                  </listitem>
               </itemizedlist>
               <para>Для каждого из типов набора номера диаграмма отображается
по-своему, а именно:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Импульсный</entry>
                           <entry colname="2">Диаграмма представляет собой последовательность вертикальных
линий разных цветов, каждая из которых на временной оси равна 10мс: тёмно-серый (импульса нет)
и красный (импульс есть)</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Тоновый</entry>
                           <entry colname="2">Диаграмма также представляет собой последовательность вертикальных
линий разных цветов, которую можно расшифровать согласно Легенде. Как
и в предыдущем пункте, одна линия равна 10 мс интервалу времени</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>При тестировании в видимой области диаграммы может быть отображена
не вся информация. Для просмотра неотображённой части можно прокручивать
диаграмму мышкой если нажать правую кнопку мыши и не отпуская двигать
диаграмму. Кроме того можно увеличить представляющий интерес фрагмент.
Для этого выделите этот фрагмент мышкой (от левого верхнего угла
до правого нижнего) на диаграмме. Чтобы вернуться к первоначальному
масштабу нужно дважды нажать левую кнопку мыши («double click»)
на диаграмме. При этом левая часть видимой области диаграммы будет
совпадать с началом диаграммы.</para>
               <para>Для удобства оператора в приложении предусмотрена возможность
запуска приложения Абонентская панель (см. разд. «<xref linkend="tri_tri_odin" role="Undefined Cross-Reference"/>»).
При необходимости это можно осуществить нажатием соответствующей
кнопки на функциональной панели. При этом фокусировка будет произведена
на того абонента, номер которого выбран в элементе<emphasis>Номер
абонента</emphasis>.</para>
               <important>
                  <para>
                     <command moreinfo="none">Внимание!</command>Если промежуток времени
от момента нажатия оператором кнопки<command moreinfo="none">Старт</command>до момента
нажатия оператором кнопки<command moreinfo="none">Стоп</command>превышает десять
секунд, то будут анализироваться цифры, набранные абонентом за последние
десять секунд до момента нажатия оператором кнопки<command moreinfo="none">Стоп</command>.
Набранные абонентом цифры, исключая последние десять секунд, учитываться
не будут.</para>
               </important>
            </section>
            <section>
               <title>Статистика</title>
               <para>Окно статистики предназначено для вывода статистики (параметров) номеронабирателя.
Выглядит оно следующим образом:</para>
               <para>В состав статистики входят:</para>
               <informalfigure float="0">
                  <graphic width="2.736in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/test-nomeronabiratelja-stati.gif"/>
               </informalfigure>
               <para>
                  <command moreinfo="none">Значения, входящие в состав статистики</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Скорость (имп/сек)</entry>
                           <entry colname="2">Вычисляется как обратное значение к сумме среднего имульса
и средней паузы</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Импульсный коэффициент</entry>
                           <entry colname="2">Вычисляется как отношение среднего импульса
к средней паузе</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Имульс (*10 мс)</entry>
                           <entry colname="2">Время продолжительности одного импульса</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Пауза (*10 мс)</entry>
                           <entry colname="2">Время между двумя соседними импульсами в серии</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Межпауза (*10 мс)</entry>
                           <entry colname="2">Время между двумя соседними сериями импульсов (цифрами)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
         </section>
         <section>
            <title>3.4.2. Тест соединительных линий</title>
            <section>
               <title>Обзор</title>
               <para>Тест<xref linkend="СЛ" role="Undefined Cross-Reference"/>предназначен
для автоматического тестирования соединительных линий станции, а именно
осуществления дозвона по заданному оператором сценарию. Сценарий
состоит из заданий, которые включают в себя следующую информацию:</para>
               <itemizedlist>
                  <listitem>
                     <para>Соединительная линия по которой будет
осуществляться дозвон</para>
                  </listitem>
                  <listitem>
                     <para>Телефонный номер который будет набираться по выбранной
линии</para>
                  </listitem>
                  <listitem>
                     <para>Телефонный номер от лица которого будет осуществляться
дозвон</para>
                  </listitem>
                  <listitem>
                     <para>Признак проверки частоты 700 Герц в разговорном
тракте (для ОКС и DSS)</para>
                  </listitem>
               </itemizedlist>
               <para>Результатом работы этого приложения является выяснение работоспособности
станции в части соединительных линий, а именно возможности дозвона
по всем исходящим направлениям направлениям имеющимся на данной<xref linkend="АТС" role="Undefined Cross-Reference"/>.</para>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Главное окно программы выглядит так:</para>
               <informalfigure float="0">
                  <graphic width="8.889in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/tsl-obtsh.-vid.gif"/>
               </informalfigure>
               <para>Главное окно по функциональным признакам можно разделить на
4 части (сверху вниз):</para>
               <itemizedlist>
                  <listitem>
                     <para>Панель инструментов (кнопок)</para>
                  </listitem>
                  <listitem>
                     <para>Список заданий для тестирования</para>
                  </listitem>
                  <listitem>
                     <para>Область вывода информации о ходе тестирования (журнал)</para>
                  </listitem>
                  <listitem>
                     <para>Полоска статуса, несущая в себе информацию о станции
на которой будет осуществляться тестирование и загруженном файле
сценария</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Панель инструментов</emphasis>
               </para>
               <para>Эта часть является основным управляющим элементом приложения.
Она состоит из следующих элементов (кнопок):</para>
               <para>
                  <command moreinfo="none">Элементы панели управления</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Новый</entry>
                           <entry colname="2">Создаёт новый файл сценария. Только после его создания возможно добавление заданий
в сценарий</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Загрузить</entry>
                           <entry colname="2">Загружает сценарий из файла (<filename moreinfo="none">*.tsl</filename>), который был
ранее записан с помощью этого приложения</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Записать</entry>
                           <entry colname="2">Записывает текущий сценарий в файл (<filename moreinfo="none">*.tsl</filename>)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Добавить</entry>
                           <entry colname="2">Вызывает окно<emphasis>Новое задание</emphasis>и заносит
это задание в текущий сценарий</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Удалить</entry>
                           <entry colname="2">Удаляет выбранное задание в текущем сценарии</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тестировать</entry>
                           <entry colname="2">Начинает тестирование по текущему сценарию
с того задания, которое выделено. Причём тестированию подлежат только задания,
у которых выставлены флажки (если ни одно из заданий не выделено, то тестирование начинается с
первого задания в списке)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Стоп</entry>
                           <entry colname="2">Останавливает выполнение сценария после окончания выполнения
текущего выполняющегося задания</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Журнал Т<xref linkend="СЛ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Открывает журнал тестирования соединительных линий</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Справка</entry>
                           <entry colname="2">Открывает справку по приложению Тест<xref linkend="СЛ" role="Undefined Cross-Reference"/>(см. разд.
«3.4.2 Тест соединительных линий»)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <emphasis>Список заданий для тестирования</emphasis>
               </para>
               <para>В этой области показан список заданий сценария с краткой информацией
по каждому из заданий(слева направо):</para>
               <para>
                  <command moreinfo="none">Информация по заданиям</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Флажок</entry>
                           <entry colname="2">Показывает включённсть данного задания в общий сценарий. Если
он не поставлен то при тестировании это задание не будет выполняться</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Картинка в виде кружка</entry>
                           <entry colname="2">Показывает состояние задания: синий – не тестировалось, зелёный
– тестировалось и не было ошибок, красный – тестировалось, и была ошибка (невозможность дозвона) при тестировании</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Линия</entry>
                           <entry colname="2">Логический номер соединительной линии</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Аб. А</entry>
                           <entry colname="2">Телефонный номер, от лица которого будет осуществляться дозвон. (вызывающий)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Аб. Б</entry>
                           <entry colname="2">Телефонный номер, который в ходе тестирования
будет набираться по<xref linkend="СЛ" role="Undefined Cross-Reference"/>. (вызываемый)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Повторить</entry>
                           <entry colname="2">Показывает количество повторений выполнения
задания в ходе тестирования</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Закончено</entry>
                           <entry colname="2">Показывает количество выполненных повторений тестирования
задания</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Ошибок</entry>
                           <entry colname="2">Показывает количество выполненный повторений тестирования
задания, в которых произошли ошибки</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <emphasis>Журнал</emphasis>
               </para>
               <para>В журнал заносятся информационные сообщения о ходе тестирования.
Каждое сообщение состоит из 3-х частей:</para>
               <para>
                  <command moreinfo="none">Составные части сообщений</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Картинка</entry>
                           <entry colname="2">Обозначает категорию(группу) сообщения</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Состояние</entry>
                           <entry colname="2">Как правило указывается логический номер линии
к которой относится данное сообщение</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Текст сообщения</entry>
                           <entry colname="2">Несёт информационную часть произошедшего события</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
            <section>
               <title>Новое задание</title>
               <para>Для добавления нового задания в список нужно вызвать соответствующее
окно программы. Сделать это можно двумя способами:</para>
               <itemizedlist>
                  <listitem>
                     <para>Нажав на кнопку<command moreinfo="none">Добавить</command>(<graphic width="0.708in" align="aleft"
                                 fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/tsl-knopka-nov.-zad..gif"/>)
в верхней панели кнопок</para>
                  </listitem>
                  <listitem>
                     <para>Посредством выбора соответствующего пункта в контекстном
меню области<emphasis>Список заданий для тестирования</emphasis>
                     </para>
                  </listitem>
               </itemizedlist>
               <para>Окно выглядит следующим образом:</para>
               <informalfigure float="0">
                  <graphic width="4.736in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/tsl-novoe-zadanie.gif"/>
               </informalfigure>
               <para>Это диалоговое окно предлагает оператору ввести данные задания
для тестирования, а именно:</para>
               <para>
                  <command moreinfo="none">Данные задания для тестирования</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Направление</entry>
                           <entry colname="2">Название направления по базе данных<xref linkend="РМО" role="Undefined Cross-Reference"/>в котором будет производиться автоматический дозвон</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Пучок</entry>
                           <entry colname="2">Пучок в котором будет производиться автоматический дозвон</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Логический номер</entry>
                           <entry colname="2">Логический номер линии по которой будет осуществляться дозвон. При
этом после добавления задания (нажатия кнопки<command moreinfo="none">ОК</command>) будут добавлены задания
на все исходящие линии выбранного пучка</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Абонент А</entry>
                           <entry colname="2">Телефонный номер от лица которого будет осуществляться
дозвон</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Абонент Б</entry>
                           <entry colname="2">Телефонный номер, который будет набираться по<xref linkend="СЛ" role="Undefined Cross-Reference"/>в ходе тестирования</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Категория</entry>
                           <entry colname="2">Категория абонента от лица которого будет осуществляться
дозвон</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">DPC</entry>
                           <entry colname="2">Код сигнализации пункта назначения (станции вызываемого абонента). Это
поле не заполняется, а считывается из<xref linkend="БД" role="Undefined Cross-Reference"/>
                              <xref linkend="РМО" role="Undefined Cross-Reference"/>. Имеет значение только
для ОКС</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тип</entry>
                           <entry colname="2">Тип тестового вызова. (местный/<xref linkend="МГ" role="Undefined Cross-Reference"/>,<xref linkend="МН" role="Undefined Cross-Reference"/>)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Повторить</entry>
                           <entry colname="2">Число повторений задания</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Время ожидания (с)</entry>
                           <entry colname="2">Время в секундах, в течении которого будут ожидаться сообщения от встречной станции</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Ожидать частоту 700 Герц</entry>
                           <entry colname="2">После установления соединения будет ожидаться (проверяться)
частота 700 Герц в разговорном тракте</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Для добавления задания в общий сценарий необходимо заполнить
все поля предлагаемые приложением для ввода данных и нажать кнопку<command moreinfo="none">OK</command>.
Для отмены добавления задания необходимо нажать кнопку<command moreinfo="none">Cancel</command>.</para>
            </section>
            <section>
               <title>Стандартные задачи</title>
               <para>
                  <command moreinfo="none">Задача 1. Создание нового задания</command>
               </para>
               <itemizedlist>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1a)</emphasis>Нажать
на кнопку<command moreinfo="none">Новый</command>
                     </para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1b)</emphasis>Нажать кнопку<command moreinfo="none">Добавить</command>,
либо выбрать пункт<command moreinfo="none">Добавить</command>в контекстном меню,
которое появляется при нажатии правой кнопки мыши в верхней части
окна</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1c)</emphasis>В предложенном диалоговом
окне заполнить левую половину. Выбрать нужное направление в поле<emphasis>Направление</emphasis>
                     </para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1d)</emphasis>В поле<emphasis>Пучок</emphasis>выбрать
нужный пучок</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1e)</emphasis>В поле<emphasis>Логический
номер</emphasis>выбрать номер</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1f)</emphasis>В правой половине окна
выбрать<emphasis>Вызывающего</emphasis>абонента</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1g)</emphasis>Выбрать<emphasis>Вызываемого</emphasis>абонента</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1h)</emphasis>В следующем поле выбрать
категорию<emphasis>Вызывающего</emphasis>абонента</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1i)</emphasis>Уточнить<emphasis>Тип
Вызываемого абонента</emphasis>и<emphasis>DPC</emphasis>, если это
возможно</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1j)</emphasis>В поле<emphasis>Повторить</emphasis>,
проставить количество повторов</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1k)</emphasis>В поле<emphasis>Время
ожидания</emphasis>проставить время ожидания в секундах</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1l)</emphasis>Если необходимо, проставить
галочку в окошке<emphasis>Ожидать частоту 700 Герц</emphasis>
                     </para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1m)</emphasis>Нажать кнопку<command moreinfo="none">Ок</command>
                     </para>
                  </listitem>
               </itemizedlist>
            </section>
         </section>
         <section>
            <title>3.4.3. Диагностика</title>
            <section>
               <title>Главное окно</title>
               <informalfigure float="0">
                  <graphic width="11.000in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika.gif"/>
               </informalfigure>
               <para>Главное окно приложения состоит из трех основных частей: рабочей
области, панели навигации и окна вывода.</para>
               <para>Размеры главного окна и вспомогательных панелей могут быть
изменены при помощи указателя мыши. Панели навигации и вывода также
могут быть закрыты нажатием на крестик в их заголовках. Чтобы вновь
отобразить вспомогательные панели, можно использовать меню<emphasis>Вид</emphasis>.</para>
               <para>Рабочая область занимает основное пространство на экране и
представлена как набор закладок. Отдельные страницы могут быть открыты
при помощи панели навигации или меню<emphasis>Окно</emphasis>.</para>
               <para>Панель навигации используется для быстрого выбора страницы
в рабочей области, а также для переключения между модулями в пределах
одной страницы.</para>
               <para>Область вывода состоит из трех страниц – окно вывода, консоль
и окно отладки. Окно вывода используется для информирования оператора,
консоль – для ввода команд, окно отладки используется для отображения
отладочных сообщений.</para>
            </section>
            <section>
               <title>Станция</title>
               <para>При запуске приложения оператором, после установления соединения
с<xref linkend="АТС" role="Undefined Cross-Reference"/>,
в рабочей области автоматически открывается страница<emphasis>Станция</emphasis>.</para>
               <informalfigure float="0">
                  <graphic width="9.042in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-stantzija.gif"/>
               </informalfigure>
               <para>Страница отображает физическую структуру<xref linkend="АТС" role="Undefined Cross-Reference"/>, с разделением на модули,
платы и комплекты. В списке<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>ов отображаются только те
типы плат, которые могут быть протестированы приложением. Цветные
символы рядом с номерами модулей,<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>ов и комплектов отображают
состояние оборудования:</para>
               <para>
                  <command moreinfo="none">Значения цветов</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Желтый</entry>
                           <entry colname="2">Элемент опрашивается</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Зеленый</entry>
                           <entry colname="2">Элемент найден</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Фиолетовый</entry>
                           <entry colname="2">Плата ДГН5 занята</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Красный</entry>
                           <entry colname="2">Элемент не найден</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Желтый пополам с голубым</entry>
                           <entry colname="2">Элемент опрашивается, помещен в очередь</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Фиолетовый пополам с голубым</entry>
                           <entry colname="2">Плата ДГН5 занята, элемент в очереди</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Голубой</entry>
                           <entry colname="2">Элемент находится в очереди</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Синий</entry>
                           <entry colname="2">Элемент диагностируется</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Для запуска диагностики достаточно последовательно выбрать
нужный модуль, плату и комплект, затем нажать на кнопку<command moreinfo="none">Диагностика</command>.
Выбрав только некоторый модуль или плату, на диагностику могут быть
назначены все комплекты или платы модуля. Запустить диагностику
всей станции можно нажатием на кнопку<command moreinfo="none">Диагностика</command>,
когда в списке модулей нет выбранного элемента.</para>
               <para>Кнопка<command moreinfo="none">Отмена</command>выполняет обратное действие
– убирает из очереди ранее назначенные на диагностику комплекты,
соответствующие выбранным элементам в списках.</para>
               <para>Правая кнопка мыши на элементах списка открывает контекстные
меню.</para>
               <para>При установленном флажке<command moreinfo="none">Повторная</command>на диагностику
будут назначаться только те комплекты, которые проверялись ранее
и были отмечены как неисправные.</para>
               <para>Флажок<command moreinfo="none">Сокращенная</command>позволяет использовать
сокращенные сценарии диагностики. Оператор может изменять состав
входящих в сокращенные сценарии тестов при помощи страницы<emphasis>Сценарии</emphasis>.</para>
               <para>Если установлен флажок<command moreinfo="none">Открывать журнал</command>,
то при запуске диагностики из страницы станции будет автоматически
открываться страница<emphasis>Журнал</emphasis>для модуля, назначенного
на диагностику.</para>
            </section>
            <section>
               <title>Менеджер</title>
               <para>Страница<emphasis>Менеджер</emphasis>отображает состояние
процесса диагностики всей станции.</para>
               <informalfigure float="0">
                  <graphic width="9.028in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-menedger1.gif"/>
               </informalfigure>
               <para>В списке содержится информация о размере очереди для каждого
независимого процесса диагностики, прошедшее и оставшееся время,
текущее состояние.</para>
               <para>Положение уровня<emphasis>Нагрузка</emphasis>определяет максимальное
число одновременно запущенных процессов диагностики. Работа при
большой нагрузке сокращает время диагностики, однако при этом увеличивается
поток сообщений через общий канал, что понижает производительность
других приложений<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
               <para>Кнопка<command moreinfo="none">Отменить</command>очищает выбранную очередь,<command moreinfo="none">Отменить
все</command>– прекращает диагностику всей станции.</para>
            </section>
            <section>
               <title>Журнал</title>
               <para>Страница<emphasis>Журнал</emphasis>позволяет следить за выбранным
процессом диагностики.</para>
               <informalfigure float="0">
                  <graphic width="9.028in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-gurnal1.gif"/>
               </informalfigure>
               <para>Во время диагностики в списке отображаются названия тестов
и результаты проведенных измерений. Зеленая отметка рядом с названием
теста означает его успешное завершение, красная отметка свидетельствует
о неполадке.</para>
               <para>Кнопка<command moreinfo="none">Очистить</command>очищает список, кнопка<command moreinfo="none">Пропустить</command>завершает
диагностику текущего элемента.</para>
               <para>При установленном флажке<command moreinfo="none">Показывать только ошибки</command>в
журнал будут попадать лишь записи, свидетельствующие о неисправности.</para>
            </section>
            <section>
               <title>Очередь</title>
               <para>Страница<emphasis>Очередь</emphasis>отображает список назначенного
на диагностику оборудования.</para>
               <informalfigure float="0">
                  <graphic width="9.028in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-ochered.gif"/>
               </informalfigure>
               <para>Цветные символы рядом с элементами списка имеют следующий
смысл:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Синий</entry>
                           <entry colname="2">Элемент диагностируется</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Голубой</entry>
                           <entry colname="2">Ожидание начала диагностики</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Зеленый</entry>
                           <entry colname="2">Диагностика завершена</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Кнопка<command moreinfo="none">В начало</command>перемещает выбранные элементы
в начало очереди; кнопка<command moreinfo="none">Удалить</command>убирает из очереди
выбранные элементы; кнопка<command moreinfo="none">Удалить все</command>очищает очередь.
Нажатие на кнопку<command moreinfo="none">Удалить завершенные</command>убирает все
элементы, помеченные как проверенные; при установленном флажке<command moreinfo="none">Удалять
завершенные</command>такие элементы будут убираться автоматически.</para>
            </section>
            <section>
               <title>Тест АЛ</title>
               <para>При помощи страницы<emphasis>Тест</emphasis>
                  <xref linkend="АЛ" role="Undefined Cross-Reference"/>осуществляется запуск теста
абонентских линий.</para>
               <informalfigure float="0">
                  <graphic width="8.861in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-test-al.gif"/>
               </informalfigure>
               <para>Когда в поле ввода<emphasis>Номер абонента</emphasis>оператор
вводит телефонный номер абонента, чью линию необходимо проверить,
через секунду рядом отобразится конструктивный адрес (см. «конструктивный
адрес») комплекта, к которому подключена линия, в виде «модуль.тэз.комплект».
Оператор может установить флажок<emphasis>Проверить комплект</emphasis>,
чтобы запустить сценарий<xref linkend="АК" role="Undefined Cross-Reference"/>для данного комплекта. При
установленном флажке<emphasis>Измерить линию</emphasis>будет проверена
выбранная абонентская линия (сценарий «<xref linkend="АК" role="Undefined Cross-Reference"/>линия»). Если существует подозрение
на короткое замыкание, следует установить флажок<emphasis>Проверка</emphasis>
                  <xref linkend="КЗ" role="Undefined Cross-Reference"/>– иначе диагностика
не будет продолжена, если комплект окажется в состоянии, отличным
от исходного.</para>
               <para>Нажатием на кнопку<command moreinfo="none">Диагностика</command>запускаются
выбранные сценарии.</para>
            </section>
            <section>
               <title>Результаты</title>
               <para>Страница<emphasis>Результаты</emphasis>содержит историю результатов
диагностики оборудования.</para>
               <informalfigure float="0">
                  <graphic width="9.028in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/diagnostika-rezultaty.gif"/>
               </informalfigure>
               <para>В верхней части страницы распологаются поля, при помощи которых
можно задать фильтр для отображаемых результатов. В поле ввода<emphasis>Адрес</emphasis>можно
вводить маску для адресов проверенных элементов, символу «?» в маске
может соответствовать произвольный символ адреса.</para>
               <para>В верхнем списке показываются элементы, соответствующие заданному
фильтру, в нижней – журнал диагностики для выбранного элемента.
При установленном флажке<emphasis>Показывать только ошибки</emphasis>в
журнале будут отображаться только записи, показывающие ошибки.</para>
               <para>Кнопка<command moreinfo="none">Сохранить</command>позволяет записать отображаемые
на экране результаты в текстовый файл. Кнопка<command moreinfo="none">Очистить</command>удаляет
все записи из базы данных.</para>
            </section>
         </section>
         <section>
            <title id="tri_4_4" xreflabel="3.4.4. Тесты и скрипты">3.4.4.
Тесты и скрипты</title>
            <section>
               <title>Обзор</title>
               <para>В состав<xref linkend="РМО" role="Undefined Cross-Reference"/>входит набор тестов и скриптов
вывода состояния различных объектов станции. Далее будет приведено
их описание. Для каждого теста или скрипта указано его предназначение,
откуда он запускается и документированы сообщения, выводимые в журнал
запуска.</para>
            </section>
            <section>
               <title>Описание фоновых тестов</title>
               <para>Система встроенных тестов<xref linkend="АТС" role="Undefined Cross-Reference"/>предназначена для непрерывного
контроля состояние оборудование станции с целью исключения возможности
использования неисправной аппаратуры в процессе обслуживания вызовов.</para>
               <para>Работа системы заключается в периодическом запуске тестовых
процедур. В случае обнаружения неисправности выполняются следующие
действия:</para>
               <itemizedlist>
                  <listitem>
                     <para>выдается аварийная индикация на консоль<xref linkend="РМО" role="Undefined Cross-Reference"/>или световая
индикация на лицевой панели блока</para>
                  </listitem>
                  <listitem>
                     <para>выдается соответствующая индикация в объекты<xref linkend="ФПО" role="Undefined Cross-Reference"/>(блокировка
линии, потока, промтракта (см. «промтракт») и т.п.)</para>
                  </listitem>
                  <listitem>
                     <para>при необходимости инициируются процедуры управления
конфигурацией аппаратных средств</para>
                  </listitem>
               </itemizedlist>
               <para>Помимо фоновых тестов, другим (и, фактически, основным) источником
аварийной сигнализации являются процедуры обработки первичной информации
о состоянии аппаратуры каналов приема/передачи телефонной сигнализации.
Эти процедуры выявляют ситуации, специфицированные протоколами сигнализаций
как ошибочные и выполняют соответствующие специфицированные действия.
Именно в результате исполнения такого рода процедур, на консоли<xref linkend="РМО" role="Undefined Cross-Reference"/>могут
появиться сообщения типа «сбой в линии», «авария тракта Е1», «закрылось
направление» и т.п.</para>
               <para>Фоновое тестирование, в отличие от обработки протокольных
ошибок, не имеет жестких регламентаций и может быть частично или
полностью отключено автоматически или по команде оператора.</para>
               <para>Ниже приводится описание основных встроенных программных средств, обеспечивающих
фоновое тестирование станции.</para>
               <para>
                  <command moreinfo="none">Основные встроенные программные средства, обеспечивающие фоновое
тестирование станции</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Средства контроля живучести системы управления, основанные
на использовании аппаратного сторожа</entry>
                           <entry colname="2">Используется стандартная схема – все программные компоненты,
включая службы операционной системы, модули ТО и<xref linkend="ФПО" role="Undefined Cross-Reference"/>, периодически подтверждают
свою работоспособность. При «зависании» одной из программных подсистем срабатывает аппаратура формирования сигнала рестарта процессора.
Этот вид встроенного контроля не может быть отключен</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Контроль наличия межпроцессорных связей</entry>
                           <entry colname="2">Позволяет обнаруживать отключившиеся модули.
На консоль сервера выдается сообщение<command moreinfo="none">Потеря связи с модулем</command>. Если
это модуль обеспечивает работу соединительных линий, то в данных<xref linkend="ФПО" role="Undefined Cross-Reference"/>связанные
с модулем линии будут заблокированы, при этом специального сообщения о блокировке на
консоль не выдается, но изменение состония линий можно увидеть в панели «Соединительные линии» (см.
разд. «<xref linkend="tri_tri_tri" role="Undefined Cross-Reference"/>»).
Этот вид контроля также не отключается</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Сканирование аппаратных регистров состояния</entry>
                           <entry colname="2">В основном обработка значений аппаратных регистров выполняется
в протокольных процедурах. Дополнительно в режиме фоновой деятельности регистры состояния могут сканироваться
с целью:<itemizedlist>
                                 <listitem>
                                    <para>определения текущего уровня ошибок
для цифровых трактов</para>
                                 </listitem>
                                 <listitem>
                                    <para>синхронизации световой индикации</para>
                                 </listitem>
                                 <listitem>
                                    <para>обнаружения «выпавших»<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>ов в модулях<xref linkend="БАЛ" role="Undefined Cross-Reference"/>(выполняется путем считывания значений кодов плат).</para>
                                 </listitem>
                              </itemizedlist>В принципе, этот
вид фоновой деятельности отключается битом «сканирование регистров состояния оборудования» значения параметра «режим фоновых тестов»,
но большого смысла в этом нет</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тестирование коммутационных полей</entry>
                           <entry colname="2">Проверка работоспособности коммутационных полей. Имеет смысл только
для модуля УКС32 с резервированным полем, поскольку может повлиять на
решение о выборе рабочей плоскости поля. Поскольку физически поле УКС32 состоит
из нескольких<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>ов, процедура его тестирования
с целью локализации возможной неисправности разбита на несколько частей. Тест
поля для УКС32 включает:<itemizedlist>
                                 <listitem>
                                    <para>Тест адресной памяти
поля (плата РАУ)</para>
                                 </listitem>
                                 <listitem>
                                    <para>Тест памяти управления блока ГВВ</para>
                                 </listitem>
                                 <listitem>
                                    <para>Тест памяти сканирования блока ГВВ без использования внешних трактов (ошибка локализует неисправность
до пары РАУ+ГВВ)</para>
                                 </listitem>
                                 <listitem>
                                    <para>Тест плат ТП с организацией цифровых шлейфов через подключенные
к УКСу модули<xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д или
Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>
                                    </para>
                                 </listitem>
                              </itemizedlist>При обнаружении
ошибки поля выдается сообщение на консоль («сбой теста поля», «сбой
теста памяти ГВВ», «сбой теста памяти сканирования», «Нет живых модулей через
ТП») и зажигается светодиод на панели блока УУС32. Если сбой в поле фиксируется многократно
за короткий промежуток времени (сейчас это 5 раз за минуту), выполняется
переход на резервное поле, если к этому моменту не накоплена информация
о его более тяжелом состоянии. На консоль будет выдано сообщение «переход на
другое поле». Нужно отметить, что возможны неиправности отдельных блоков,
при которых невозможно диагностировать ситуацию до<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>а (ошибки обнаруживаются сразу
по нескольким тестам), что объясняется многочисленными взаимозависимостями плат
на схемном уровне. Грубая имитация неисправности путем «вытаскивания»<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>а обычно приводит именно
к этому. Тестирование поля полностью отключается битом «тест поля» значения параметра «режим фоновых тестов». Отдельно может
быть включен или отключен тест плат ТП с использованием промтрактов
(бит «тест ТП через подключенные модули»). Этот же тест отключается автоматически
при фиксации существенной нагрузки, определяемой по количеству проключений
в поле за одноминутный интервал времени. Пороговое значение определяется параметром
объекта ТО «порог нагрузки» (значение по умолчанию – 4), может быть определено для каждого модуля отдельно</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тестирование резервного оборудования</entry>
                           <entry colname="2">В силу особенностей организации аппаратуры УКС, работа
с резервным полем приводит к нарушению функционирования основного. В
то же время, станция должна уметь автоматически определять состояние резервного оборудования,
чтобы избежать попыток переключения на неисправное (или совсем отсутствующее) оборудование.
Тест выполняется при установленном бите «тест резервного поля» значения параметра «режим фоновых тестов»
и только при отсутствии существенной нагрузки (см. предыдущий пункт)</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Проверка постоянных проключений</entry>
                           <entry colname="2">Полупостоянные проключения в полях организуются
главным образом для обеспечения внутренней системной сигнализации.
Для этого используются весь нулевой тракт и нулевые каналы остальных трактов
в модулях УКС32, и нулевые каналы нулевых трактов полей<xref linkend="БАЛ" role="Undefined Cross-Reference"/>ов. Другие причины формирования системных постоянных проключений
– генерация в DSP-процессоре модуля<xref linkend="БАЛ" role="Undefined Cross-Reference"/>тональных сигналов для УКСа, а
также организация постоянных каналов в интересах системы<xref linkend="СОРМ" role="Undefined Cross-Reference"/>. При обнаружении
ошибки, тест выдает на консоль<xref linkend="РМО" role="Undefined Cross-Reference"/>сообщение<command moreinfo="none">Потеря проключения</command>. Включение/отключение
режима управляется битом «проверка постоянных проключений» значения параметра «режим фоновых тестов»</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Тест модуля ЦП16У</entry>
                           <entry colname="2">Неисправность модуля также может привести к решению
о смене рабочего поля. Одиночная ошибка теста никак не индицируется, многократный
сбой приведет к переходу на другой поле с указанием на неисправность
блока ЦП16У в качестве причины перехода. Включается/отключается
битом «тест ЦП16» значения параметра «режим фоновых тестов». Возможность отключения
связана главным образом только с возможным отсутствием данного блока
в конфигурации модуля УКС32</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <emphasis>Кодировка значения параметра "режим фоновых тестов"</emphasis>
               </para>
               <para>Значение этого параметра объекта ТО, управляющего процедурой
фонового тестирования, изначально устанавливается в зависимости
от конфигурации модуля и затем может быть изменено отдельно для
каждого управляющего модуля при помощи скрипта<emphasis>режим фонового
тестирования</emphasis>(может быть запущен одноименной командой
из панели<emphasis>станция</emphasis>
                  <xref linkend="РМО" role="Undefined Cross-Reference"/>).</para>
               <para>Единичное значение каждого бита означает активизацию фоновой
деятельности, нулевое – ее отключение.</para>
               <para>
                  <command moreinfo="none">Кодировка значения параметра "режим фоновых тестов"</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Бит параметра</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Бит 1xxxxxxx (80h)</entry>
                           <entry colname="2">Проверка постоянных проключений, имеет смысл только
для модулей<xref linkend="БАЛ" role="Undefined Cross-Reference"/>и УКС</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Бит x1xxxxxx (40h)</entry>
                           <entry colname="2">Тест резервного поля (только УКС)</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Бит xx1xxxxx (20h)</entry>
                           <entry colname="2">Тест старшегоТП через заглушку в 31 тракте (только УКС)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Для конфигураций УКС со свободным 31м входом поля наличие
заглушки в этом входе позволяет автоматически определять наличие
соответствующей платы ТП в резервном поле (для резервного поля тесты
ТП через подключенные модули выполняться не могут).</para>
               <para>
                  <command moreinfo="none">Кодировка значения параметра "режим фоновых тестов"</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Бит параметра</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Бит xxxx1xxx (08h)</entry>
                           <entry colname="2">Тест ЦП16</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Бит xxxxx1xx (04h)</entry>
                           <entry colname="2">Тест ТП через подключенные модули (имеет значение только
при установленном бите "тест поля")</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Бит xxxxxx1x (02h)</entry>
                           <entry colname="2">Тест поля</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Бит xxxxxxx1 (01h)</entry>
                           <entry colname="2">Сканирование регистров состояния оборудования</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
            <section>
               <title>Тесты</title>
               <para>
                  <emphasis>Плата АК. Тест АК</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Проверка прохождения сигнала через первый комплект платы.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Производим идентификацию кода<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>а. При его несоответствии
на экране появится сообщение<emphasis>не соответствует коду платы</emphasis>
                  <xref linkend="АК" role="Undefined Cross-Reference"/>5, и тест
прервётся. Производим захват платы ДГН5,<emphasis>блокируем</emphasis>абонента
(при отсутствии возможности блокировки на экране появится сообщение),
подключаем абонента к тестовой линии ETL и анализируем прохождение сигнала,
затем отключаемся от ETL и<emphasis>разблокируем</emphasis>. По
окончании теста на экране появляется сообщение либо<emphasis>AK5
- исправен.</emphasis>, либо<emphasis>Тест не может подтвердить исправность
AK5.</emphasis>
               </para>
               <para>
                  <emphasis>Плата АКТ. Тестирование платы АКТ</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Проверка прохождения сигнала через первый комплект платы.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Производим идентификацию кода<xref linkend="ТЭЗ" role="Undefined Cross-Reference"/>а. При его несоответствии
на экране появится сообщение «не соответствует коду платы<xref linkend="АКТ" role="Undefined Cross-Reference"/>» и тест
прервётся. Производим захват платы ДГН5, блокируем абонента (при
отсутствии возможности блокировки на экране появится сообщение),подключаем
абонента к тестовой линии ETL и смотрим прохождение сигнала, затем
отключаемся от ETL и разблокируем . По окончании теста на экране
появляется сообщение либо<emphasis>AKТ - исправен.</emphasis>либо<emphasis>Тест
не может подтвердить исправность AKТ.</emphasis>
               </para>
               <para>
                  <emphasis>Плата ГВВ. Тест платы ГВВ модуля УКС</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа пердназначена для проверки работы платы ГВВ модуля
УКС.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Производим многократную проверку по следующей схеме: Записываем
в передатчик модуля УКС произвольные данные. После этого они должны
попасть в ГВВ, откуда мы их и считываем. При совпадении этих данных
проверка прошла успешно и на экране появляется +, иначе -.</para>
               <para>По окончании тестирования выводится конечный результат:<emphasis>ГВВ
исправен</emphasis>, если все +, либо<emphasis>ГВВ неисправен</emphasis>,
если есть один или более -.</para>
               <para>
                  <emphasis>Плата РАУ. Тест платы РАУ</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа пердназначена для проверки поля.</para>
               <para>Проверка производится по всем временным каналам.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Пишем тестовое значение проключения для модуля УКС, затем
читаем его и сравниваем с тестовым. При совпадении этих значений
тестирование прошло успешно, и на экран выводится временной канал
по которому тестировали и<emphasis>ok</emphasis>, иначе временной
канал по которому тестировали и<emphasis>ошибка!!!</emphasis>. По
окончании тестирования выводится результат тестирования: либо<emphasis>плата
РАУ исправна.</emphasis>, если по всем временным каналам всё хорошо, иначе
–<emphasis>тест не может подтвердить исправность платы</emphasis>.
Далее восстанавливаем старое проключение (которое было до тестирования)
и завершаем тест.</para>
               <para>
                  <emphasis>Плата СК. Тестирование связи с УКС всех БАЛов</emphasis>
               </para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Тестируем тракты, по которым подключены модули, по следующей
схеме: проключаем УКС на нужный тракт (данные записанные в передатчик
УКС попадут теперь в нужный модуль), затем подключенный по этому
тракту модуль переводим в режим возврата получаемых данных обратно
в УКС (теперь записанные в передатчик УКС данные попадут в его приёмник,
откуда мы их и считаем). Записываем данные в передатчик, затем считываем
данные из приемника УКС. Если данные которые мы послали и получили совпали,
то тест прошел успешно и на экране отобразится информация о подключенном
к УКС модуле и<emphasis>ok</emphasis>, иначе информация о подключенном
к УКС модуле и<emphasis>ошибка</emphasis>. Ошибка может возникнуть
либо по причине разрыва в тракте, либо по причине неработоспособности<xref linkend="БАЛ" role="Undefined Cross-Reference"/>а, либо
по причине неработоспособности УКС на приём/отправку сообщений.</para>
               <para>
                  <emphasis>Плата СК. Тестирование тракта связи с УКС</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа пердназначена для проверки связи модуля<xref linkend="БАЛ" role="Undefined Cross-Reference"/>с УКС.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Тестируем тракт, по которому подключен модуль по следующей
схеме: проключаем УКС на нужный тракт (данные записанные в передатчик
УКС попадут теперь в нужный модуль), затем тестируемый<xref linkend="БАЛ" role="Undefined Cross-Reference"/>переводим
в режим возврата получаемых данных обратно в УКС (теперь записанные
в передатчик УКС данные попадут в его приёмник откуда мы их и считаем).
Записываем данные в передатчик, затем считываем данные из приемника
УКС. Если данные которые мы послали и получили совпали, то тест
прошел успешно и на экране отобразится информация о модуле и +,
иначе информация о модуле и -. Ошибка может возникнуть либо по причине
разрыва в тракте, либо по причине неработоспособности<xref linkend="БАЛ" role="Undefined Cross-Reference"/>а либо,
по причине неработоспособности УКС на приём/отправку сообщений.</para>
               <para>
                  <emphasis>Плата ТП. Проверка трактов связи УКС для данного
ТП</emphasis>
               </para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Тестируем тракты, по которым подключены различные модули по
следующей схеме: проключаем УКС на нужный тракт (данные записанные
в передатчик УКС попадут теперь в нужный тракт), затем подключенный
по этому тракту модуль переводим в режим возврата получаемых данных
обратно в УКС (теперь записанные в передатчик УКС данные попадут
в его приёмник откуда мы их и считаем). Записываем данные в передатчик,
затем считываем данные из приемника УКС. Если данные которые мы
послали и получили совпали, то тест прошел успешно и на экране отобразится
информация о подключенном к УКС модуле и сообщение ok, иначе информация
о подключенном к УКС модуле и сообщение ошибка. Ошибка может возникнуть
либо по причине разрыва в тракте, либо по причине неработоспособности
в модуле подключенном к УКС, либо по причине неработоспособности
УКС на приём/отправку сообщений.</para>
               <para>
                  <emphasis>Плата ЦСЛ. Внешняя перемычка transmit mode</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа пердназначена для проверки работы фреймера (приём/отправление
данных – внешний шлейф).</para>
               <para>Тест производится по всем временным каналам (временные каналы
1-0F соответствуют странице 0F фреймера, временные каналы 11-1F
соответствуют странице 10 фреймера). А так же тест производится
по обоим трактам в Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>(оба фреймера на плате).</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Записываем в передатчик на плате Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>данные и переводим фреймер
в режим передачи данных. Данные начинают передаваться во внешний
шлейф. На экране появляется сообщение<emphasis>Временной канал</emphasis>:
и далее номер временного канала в котором посылаем данные, затем
появляется сообщение<emphasis>Послали</emphasis>и далее данные,
которые мы хотим передать. Далее проверяем, что у нас попало в передатчик
(что же мы посылаем на самом деле), сообщение<emphasis>Передатчик</emphasis>и
данные, которые передал фреймер. Если внешний шлейф установлен и
нормально функционирует, то передаваемые данные попадают в приёмник второго
фреймера на плате Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>. После этого происходит
сравнение переданных и полученных данных. Успешное завершение теста
– совпадение этих данных. При успешном завершении теста появляется
сообщение<emphasis>Результат: Выполнено!</emphasis>иначе<emphasis>Результат:
Сбой!</emphasis>. В конце выполнения теста отключаем режим передачи данных.
Сбой теста является следствием разрыва внешнего шлейфа или нарушения
связи с Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>или
нарушения работы платы Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>.</para>
               <para>Примечание</para>
               <para>При запуске теста убедитесь в наличии внешнего шлейфа на Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>!</para>
               <para>
                  <emphasis>Плата ЦСЛ. Проверка режимов фреймера на плате ЦСЛ
лок шлейф</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа пердназначена для проверки работы фреймера (приём/отправление
данных – локальный шлейф).</para>
               <para>Тест производит проверку четырех режимов: Time Slot Loopback,
ST-bus Loopback, Digital Loopback и Metallic Loopback. Все они переводят
фреймер в режим отправления полученных данных обратно по тому же
пути, по которому они в него попали (в данном случае обратно в УКС),
что и означает локальный шлейф. Проверка этих четырех режимов обязательна,
поскольку механизм возврата данных у каждого режима свой и требует отдельного
рассмотрения. Тест каждого режима производится по обоим трактам
в Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>(оба фреймера
на плате).</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>Проключаем УКС на тестируемый ЦСЛ (данные записанные в передатчик
УКС теперь попадают в нужный нам Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>). Затем последовательно
проверяем каждый из режимов по следующей схеме: Переводим фреймер
Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>'а в
нужный режим (любой из режимов, которые мы тестируем, заставит фреймер
отсылать принимаемые данные обратно в УКС, а именно в его приёмник).
На экране появляется сообщение отображающее тестируемый режим. Затем
появляется сообщение о том, какой ЦСЛ мы тестируем и какой тракт
(фреймер) на этой плате. Далее производим многократную (10 раз)
проверку (посылка данных из передатчика УКС, считывание данных из
приёмника УКС, куда они должны попасть и сравнение их), если посылаемые
данные совпадают с принимаемыми, то проверка прошла успешно и на
экране отображается +, иначе -. В конце проверки на экране вы увидите результат
тестирования режима:<emphasis>Плата работает</emphasis>(все +) или<emphasis>Плата
сбоит</emphasis>(есть один или более -). Далее производим проверку
второго фреймера (если Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>подключен к данному УКС только
по одному тракту, то проверки второго фреймера не производим), по
завершении которой тестируемый режим отключается и проверяем следующий
режим. По окончании тестирования выводится окончательный результат:<emphasis>Плата
работает</emphasis>– все режимы проверены без ошибок, иначе<emphasis>Плата
сбоит</emphasis>.</para>
               <para>Тест проверяет маршрут приёма-передачи</para>
               <para>УКСgтракт с определенным Временным каналомg Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>gлок шлейф</para>
               <para>УКСfтракт с определенным Временным каналомf Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>fлок шлейф</para>
               <para>
                  <emphasis>Модуль УКС. Проверка поля через заглушку</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Программа проверяет поля через заглушку.</para>
               <para>Запуск</para>
               <para>Запуск скрипта производится из приложения панель Станции (см.
разд. «<xref linkend="tri_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Действия</para>
               <para>После запуска программы выводится диалоговое окно, в котором
должен быть указан номер тракта по которому была поставлена заглушка
(замыкание тракта на себя, то есть данные возвращаются обратно).
После ввода на экране отображается введенный номер тракта. Затем
производим многократное (10 раз) тестирование каждого временного
канала по следующей схеме: Путем прямой записи в передатчик заранее
указаных данных происходит передача из передатчика УКС в заглушку.
Если всё в порядке, то данные должны попасть в приёмник УКС, откуда
мы их и считываем. Если передаваемые данные совпали с полученными,
то тест прошел успешно и на экране отобразится +, иначе – -. После
тестирования выводится окончательный результат:<emphasis>Модуль
работает</emphasis>(все +) либо<emphasis>Обнаружены ошибки в процессе
приёма\передачи</emphasis>(присутствует один или более -). Обнаружение
ошибки не всегда означает неправильную работу модуля. В большинстве случаев
причиной сбоев может быть участие УКС в иных процессах станции.</para>
               <para>Замечание</para>
               <para>Необходимо установить заглушку на тракте.</para>
            </section>
            <section>
               <title>Скрипты</title>
               <para>
                  <emphasis>Фильтр абонентов</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Выбор абонентов, удовлетворяющих заданным параметрам фильтрации.</para>
               <para>Действия</para>
               <para>Фильтр абонентов анализирует всех абонентов одного модуля,
либо всех модулей станции; режим выбора предоставляется оператору
в начале выполнения скрипта. Проверяется наличие абонентов, удовлетворяющих
заданным параметрам фильтрации в файле Params.inc.</para>
               <para>Задание параметров фильтрации</para>
               <para>Используется простой механизм задания параметров. Параметры
фильтрации абонентов по смыслу объеденены в разделы. Большинству
разделов соответствует общая переменная, которая является маской
включения/исключения раздела из фильтра, обычно имеющая в названии
слово «inc». Значение такой переменной равное «1» означает учитывать
данный раздел, если значение «0», то пропускать(введено для ускорения
поиска, так как процедура чтения из станции занимает много времени).
Далее в разделе следует список конкретных параметров, где значение
первой переменной на каждой строке является значением параметра
абонентов, которых мы ищем. Вторая переменная, расположенная на
той же строке, имеющая в названии слово «mask», является маской
этого параметра, то есть, учитывать этот параметр в фильтре(=1)
или не учитывать(=0). Логические параметры передаются значениями
1 = ДА и 0 = НЕТ. Допустимые численные значения переменных некоторых
разделов описаны в шапке раздела.</para>
               <para>
                  <emphasis>Состояние сигнальных звеньев</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Скрипт выводит информацию о состоянии сигнальных звеньев направлений
ОКС №7.</para>
               <para>Запуск</para>
               <para>В приложении Скрипты CMM в папке<emphasis>Общие скрипты</emphasis>запустить
скрипт<emphasis>Состояние сигнальных звеньев</emphasis>.</para>
               <para>Выводимая инфромация</para>
               <para>
                  <command moreinfo="none">Состояния протокола</command>
                  <xref linkend="MTP" role="Undefined Cross-Reference"/>
                  <command moreinfo="none">, Level 3 (см.
Q.704 Белой Книги)</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Неактивно</entry>
                           <entry colname="2">Звено не введено в работу</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Активация/Восстановление</entry>
                           <entry colname="2">См. Q.704.12</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Возврат с резерва</entry>
                           <entry colname="2">См. Q.704.6</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Доступно</entry>
                           <entry colname="2">Звено активно и используется для передачи/приема траффика</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Переход на резерв</entry>
                           <entry colname="2">См. Q.704.5</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Недоступно</entry>
                           <entry colname="2">Звено активно, но не используется для передачи/приема траффика (заблокировано
или запрещено)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Состояния протокола</command>
                  <xref linkend="MTP" role="Undefined Cross-Reference"/>
                  <command moreinfo="none">, Level 2 (см.
Q.703 Белой Книги)</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Вне обслуживания</entry>
                           <entry colname="2">Звено вне обслуживания</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Начальное фазирование</entry>
                           <entry colname="2">См. Q.703.7</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Сфазировано/Готово</entry>
                           <entry colname="2">Сфазировано и готово к передаче/приему MSU</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Сфазировано/Не готово</entry>
                           <entry colname="2">Звено сфазировано, но неготово к передаче/приему MSU</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">В обслуживании</entry>
                           <entry colname="2">Звено в состоянии обслуживания</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Отключение процессора</entry>
                           <entry colname="2">См. Q.703.8</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <emphasis>Управление обслуживанием абонентов</emphasis>
               </para>
               <para>Предназначение</para>
               <para>Скрипт осуществляет управление состоянием обслуживания абонентов
в соответствии с данными приложения Конфигуратор.</para>
               <para>Запуск</para>
               <para>Сначала установить статус обслуживания абонентов приложением
Конфигуратор, дождаться завершения работы приложения Конфигуратор.
Затем в приложении Скрипты CMM (см. разд. «<xref linkend="tri_dva_dva" role="Undefined Cross-Reference"/>») в папке<emphasis>Общие
скрипты\Служебные</emphasis>запустить скрипт<emphasis>Управление обслуживанием
абонентов</emphasis>.</para>
               <para>Выводимая инфромация</para>
               <para>Для тех абонентов, статус обслуживания которых был изменен,
выводится их новый статус обслуживания.</para>
            </section>
         </section>
         <section>
            <title>3.4.5. Поиск абонента</title>
            <section>
               <title>Обзор</title>
               <para>Поиск абонента позволяет по номеру абонента соединиться со
станцией, которой принадлежит указанный абонент, и выполнить действия
из списка, например запустить приложение<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Поиск абонента позволяет осуществить запуск приложений диагностики
и номеронабирателя по выбранному номеру абонента. Программа автоматически
произведет поиск номера в установленных базах данных, выполнит соедниение
с требуемой станцией и запустит выбранное приложение, передав ему
в качестве параметра заданный телефонный номер.</para>
               <informalfigure float="0">
                  <graphic width="3.944in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/поиск-абонента.gif"/>
               </informalfigure>
               <para>В поле ввода<emphasis>Номер</emphasis>оператор указывает телефонный
номер. После нажатия на кнопку &gt; или клавишу<command moreinfo="none">Enter</command>программа
соединится с нужной базой данных. Далее оператор может выбрать приложения,
которые должны быть запущены для указанного номера телефона. Запуск
выбранных приложений осуществляется нажатием кнопки<command moreinfo="none">Выполнить</command>.</para>
            </section>
         </section>
      </section>
      <section>
         <title>3.5. Управление коммутацией</title>
         <section>
            <title id="tri_5_odin" xreflabel="3.5.1 Коммутационное поле">3.5.1
Коммутационное поле</title>
            <section>
               <title>Обзор</title>
               <para>Программа Коммутационное поле предназначена для просмотра
текущего состояния коммутационных полей в модулях станции.</para>
               <para>С помощью программы можно:</para>
               <itemizedlist>
                  <listitem>
                     <para>Узнавать куда проключен каждый временной
канал любого тракта</para>
                  </listitem>
                  <listitem>
                     <para>Производить непрерывное сканирование текущих проключений
в поле</para>
                  </listitem>
                  <listitem>
                     <para>Пройти по шнуру</para>
                  </listitem>
                  <listitem>
                     <para>Осуществлять проключения</para>
                  </listitem>
               </itemizedlist>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Главное окно программы выглядит так:</para>
               <informalfigure float="0">
                  <graphic width="9.792in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/коммутационное-поле.gif"/>
               </informalfigure>
               <para>Основную часть окна занимает собственно поле, представленное
в виде таблицы. Столбцы – тракты, строки – временные каналы. В ячейке
указывается, куда проключен данный канал этого тракта в виде:</para>
               <para>
                  <command moreinfo="none">Тракт.Канал Усиление</command>
               </para>
               <para>Двойной щелчок мышью по ячейке позволяет увидеть текущее проключение. Альтернативным
способом просмотра состояния является режим непрерывного сканирования
поля.</para>
            </section>
            <section>
               <title>Режим сканирования</title>
               <para>Предназначен для непрерывного контроля за состоянием коммутационного
поля. Запуск и останов производится нажатием на кнопку<command moreinfo="none">Старт</command>(<command moreinfo="none">Стоп</command>).</para>
               <para>По умолчанию производится сканирование всего поля. Чтобы пометить
для сканирования только определенные тракты, следует выбрать их,
производя двойной щелчок по самой верхней ячейке (там, где написан
номер тракта) соответствующих столбцов.</para>
               <para>Если тракт выбран для сканирования, то рядом с его номером
отображается значок #</para>
               <para>При возникновении ошибок в процессе сканирования он автоматически
прерывается.</para>
            </section>
            <section>
               <title>Проход по шнуру</title>
               <para>С помощью этой команды можно узнать, куда реально проключен
данный элемент поля. Это необходимо, если осуществлено межмодульное
проключение. В таком случае адресат проключения в текущем поле является
выходом на промлинию (см. «промлиния»), которая идет в другой модуль.
Программа следуя всей цепочке проключений добирается до конечного
абонента.</para>
               <para>Для выполнения этой команды следует нажать правую кнопку мыши
на ячейке поля и в появившемся контекстном меню выбрать пункт<emphasis>Пройти
по шнуру</emphasis>. Будет вызвано приложение Проход по шнуру (см.
разд. «<xref endterm="tri_5_dva" linkend="tri_5_dva" role="Undefined Cross-Reference"/>»).</para>
            </section>
            <section>
               <title>Проключение</title>
               <para>При нажатии в главном окне на кнопку<command moreinfo="none">Проключение</command>появляется
диалог:</para>
               <informalfigure float="0">
                  <graphic width="2.819in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/КМ-проключения.gif"/>
               </informalfigure>
               <para>Указав соответствующие параметры проключения, можно осуществить
его, нажав на кнопку<command moreinfo="none">Проключение</command>в диалоге.</para>
               <para>По умолчанию производится дуплексное проключение. Чтобы осуществить симплексное
проключение, нужно поставить соответствующий флажок.</para>
            </section>
         </section>
         <section>
            <title id="tri_5_dva" xreflabel="3.5.2. Проход по шнуру">3.5.2. Проход
по шнуру</title>
            <section>
               <title>Обзор</title>
               <para>Приложение Проход по шнуру предназначено для исследования
цепочек проключений, установленных для обеспечения связи между абонентами
и (или) между внешними соединительными линиями.</para>
               <para>С помощью программы вы можете проследить всю цепочку проключений
от абонента до другого абонента или до внешней<xref linkend="СЛ" role="Undefined Cross-Reference"/>и наоборот.</para>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Главное окно приложения выглядит следующим образом:</para>
               <informalfigure float="0">
                  <graphic width="6.708in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/проход-по-шнуру.gif"/>
               </informalfigure>
               <para>В верхней панели находится группа элементов управления, формирующая
адрес в едином коммутационном поле станции:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Модуль</entry>
                           <entry colname="2">Выбор модуля станции</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тракт</entry>
                           <entry colname="2">Ввод номера тракта в<xref linkend="КП" role="Undefined Cross-Reference"/>этого модуля</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Dec/Hex</entry>
                           <entry colname="2">Указание системы счисления (десятичная или шестнадцатиричная), используемой
при интерпретации числа, введенного в поле<emphasis>Тракт</emphasis>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Канал</entry>
                           <entry colname="2">Ввод номера канала в<xref linkend="КП" role="Undefined Cross-Reference"/>модуля (в десятичной системе счисления)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Замечание.</command>Модули Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>не обладают собственным
коммутационным полем. Вводимый в поле<emphasis>Тракт</emphasis>номер
тракта является порядковым номером тракта в этом Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>. Номера трактов считаются
с 0. Например, для платы Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>, обслуживающей два тракта,
первый из них будет иметь номер 0, второй – 1. Номер канала, вводимый
в поле<emphasis>Канал</emphasis>определяет канальную позицию внутри
тракта.</para>
               <para>Нажатие на кнопку<command moreinfo="none">Перейти</command>начинает процесс
трассировки от точки в<xref linkend="КП" role="Undefined Cross-Reference"/>, адрес которой указан с
помощью элементов управления. Результаты процесса выводятся в список.</para>
               <para>
                  <command moreinfo="none">Столбцы списка</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Модуль</entry>
                           <entry colname="2">Название модуля</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тракт</entry>
                           <entry colname="2">Тракт в<xref linkend="КП" role="Undefined Cross-Reference"/>модуля, выводится в двух
с/с: десятичной и шестнадцатиричной</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Канал</entry>
                           <entry colname="2">Канал в<xref linkend="КП" role="Undefined Cross-Reference"/>модуля</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Информация</entry>
                           <entry colname="2">Дополнительная информация об объекте станции, относящемуся
к данной точке<xref linkend="КП" role="Undefined Cross-Reference"/>(абонент, внешний тракт, внешняя<xref linkend="СЛ" role="Undefined Cross-Reference"/>)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Нажатие на кнопку<command moreinfo="none">Обновить</command>повторяет последний
процесс трассировки, начиная<emphasis>с его стартовой точки</emphasis>(а
не с указанного в элементах управления адреса, в отличие от кнопки<command moreinfo="none">Перейти</command>).</para>
               <para>Кнопка<command moreinfo="none">Очистить</command>очищает содержимое списка.</para>
               <para>Двойной щелчок мышью по строке списка заносит адрес точки<xref linkend="КП" role="Undefined Cross-Reference"/>в элементы
управления и вызывает приложение<xref linkend="РМО" role="Undefined Cross-Reference"/>Коммутационное поле (см.
разд. «<xref endterm="tri_5_odin" linkend="tri_5_odin" role="Undefined Cross-Reference"/>») для этой точки.</para>
            </section>
         </section>
      </section>
      <section>
         <title>3.6. Статистика и тарификация</title>
         <section>
            <title id="tri_6_odin" xreflabel="3.6.1. Менеджер групп телетрафика">3.6.1.
Менеджер групп телетрафика</title>
            <section>
               <title>Обзор</title>
               <para>Приложение Менеджер групп телетрафика предназначено для работы
с группами статистики.</para>
               <para>Приложение позволяет осуществлять следующие операции:</para>
               <itemizedlist>
                  <listitem>
                     <para>Создание и удаление групп статистики,
создаваемых пользователем</para>
                  </listitem>
                  <listitem>
                     <para>Изменение состава групп статистики</para>
                  </listitem>
                  <listitem>
                     <para>Изменение интервала времени скачивания данных статистики
из станции для выбранной группы статистики</para>
                  </listitem>
                  <listitem>
                     <para>Включение и выключение выбранных групп статистики
из процесса скачивания данных статистики из станции</para>
                  </listitem>
               </itemizedlist>
               <para>Группы статистики, с которыми работает приложение, бывают
двух видов:</para>
               <para>
                  <command moreinfo="none">Виды групп статистики</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Группы, созданные автоматически</entry>
                           <entry colname="2">Пользователь не может удалять и изменять состав таких групп.
В такие группы включаются объекты объединенные по какому либо признаку, который присутствует
в названии группы («Все аналоговые<xref linkend="АЛ" role="Undefined Cross-Reference"/>», «<xref linkend="СЛ" role="Undefined Cross-Reference"/>тракта 0.3.10.0», ….). Пользователь
может изменять интервал времени выкачки для таких групп и включать
и исключать такие группы из процесса запроса данных статистики</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Группы, создаваемые пользователем</entry>
                           <entry colname="2">Пользователь может создавать такие группы, удалять, изменять их
состав, изменять интервал времени выкачки и включать и исключать такие группы
из процесса запроса данных статистики</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Более подробно про группы статистики можно прочитать в разделе
Сервер статистики в подраздел « Функции».</para>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Главное окно программы выглядит так:</para>
               <informalfigure float="0">
                  <graphic width="8.306in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/menedger-gr.-teletrafika.gif"/>
               </informalfigure>
               <para>Окно делится на три основных части:</para>
               <itemizedlist>
                  <listitem>
                     <para>Главное меню</para>
                  </listitem>
                  <listitem>
                     <para>Группы</para>
                  </listitem>
                  <listitem>
                     <para>Объекты</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Главное меню</emphasis>
               </para>
               <para>
                  <command moreinfo="none">Меню Файл</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Прочитать</entry>
                           <entry colname="2">Этот пункт позволяет осуществить чтение данных
о группах с сервера. Для быстрого доступа к этому пункту можно использовать комбинацию клавиш<command moreinfo="none">Ctrl-O</command>
                           </entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Сохранить</entry>
                           <entry colname="2">Этот пункт позволяет осуществлять сохранение изменений на
сервер. Для быстрого доступа к этому пункту можно использовать комбинацию клавиш<command moreinfo="none">Ctrl-S</command>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Выход</entry>
                           <entry colname="2">Этот пункт позволяет осуществлять выход из приложения.
Для быстрого доступа к этому пункту можно использовать комбинацию клавиш<command moreinfo="none">Ctrl-X</command>
                           </entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Подробнее о этих оперциях можно прочитать в разделе « Загрузка
и сохранение данных».</para>
               <para>Меню<emphasis>Справка</emphasis>позволяет вывести на экран
данную справку.</para>
               <para>
                  <emphasis>Группы</emphasis>
               </para>
               <para>При помощи этой части приложения можно осуществлять следующие
операции:</para>
               <para>
                  <command moreinfo="none">Операции, осуществляемые при помощи части Группы</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Просмотр списка существующих групп статистики</entry>
                           <entry colname="2">Имена групп выводятся разными цветами. Эти
цвета зависят от цветовой схемы, выбранной пользователем для операционной системы. На приведенном
в начале раздела рисунке имена группы, созданных автоматически,
имеют серый цвет, а имена групп, созданных пользователем, черный цвет</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Включение или исключение выбранной группы статистики из процесса запроса данных статистики из
станции</entry>
                           <entry colname="2">Рядом с именем каждой группы (слева) имеется место,
в котором можно поставить галочку. Если галочка стоит, то соответствующая группа, включена
в процесс запроса данных статистики из станции. Имена всех групп, включенных
в такой процесс, будут показываться в соответствующем окне Сервера статистики (см.
разд. «<xref linkend="tri_odin_9" role="Undefined Cross-Reference"/>»).
Все группы, созданные автоматически, по умолчанию выключены из этого процесса,
т. е. галочки рядом с именем такой группы нет</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Изменение интервала считывания данных статистики из
станции для выбранной группы</entry>
                           <entry colname="2">Над списком существующих групп расположено
место для ввода интервала считывания. Формат ввода и вывода в это
место интервала считывания следующий: «часы»:«минуты»:«секунды». Для каждой группы выводится ее собственный
интервал считывания. По умолчанию интервал считывания для групп, созданных автоматически,
и групп, вновь созданных пользователем, равен нулю. Рекомендуемый интервал считывания
равен 15 минутам</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Создание новой группы</entry>
                           <entry colname="2">Под списком существующих групп расположена кнопка<command moreinfo="none">Создать</command>.
При нажатии на эту кнопку появится диалог, в котором можно ввести
имя новой группы. После ввода имени новой группы и нажатии на кнопку<command moreinfo="none">Да</command>, имя
новой группы появится в списке существующих групп, и для вновь созданной группы можно осуществлять
все предусмотренные операции. Для быстрого доступа к операции создания новой группы можно использовать комбинацию клавиш<command moreinfo="none">Ctrl-Ins</command>
                           </entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Удаление выбранной группы, созданной пользователем</entry>
                           <entry colname="2">Под списком существующих групп расположена кнопка<command moreinfo="none">Удалить</command>.
При нажатии на эту кнопку появится диалог, с предупреждением. В случае утвердительного ответа
на это предупреждении имя соответствующей группы будет уничтожено
из списка существующих групп. Для быстрого доступа к операции удаления группы, созданной пользователем,
можно использовать комбинацию клавиш<command moreinfo="none">Ctrl-Del</command>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Изменение имени выбранной группы, созданной пользователем</entry>
                           <entry colname="2">Под списком существующих групп расположена кнопка<command moreinfo="none">Имя</command>.
При нажатии на эту кнопку появится диалог, в котором можно изменить существующее
имя группы. После изменения имени группы и нажатии на кнопку<command moreinfo="none">Да</command>, имя выбранной группы изменится в
списке существующих групп</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Замечание:</command>Если некоторая группа включена
в процесс запроса данных статистики из станции, но интервал скачивания
данных статистики из станции для этой группы будет равен нулю, то
такая группа будет показываться в соответствующем окне Сервера статистики
(см. разд. «<xref linkend="tri_odin_9" role="Undefined Cross-Reference"/>»), но данные статистики
из станции для такой группы запрашиваться не будут.</para>
               <para>
                  <emphasis>Объекты</emphasis>
               </para>
               <para>Эта часть приложения доступна для изменения только для групп,
созданных пользователем. В этой части приложения можно осуществлять
следующие операции:</para>
               <para>
                  <command moreinfo="none">Операции, осуществляемые при помощи части Объекты</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Выбор для группы, созданной пользователем,
типа объектов</entry>
                           <entry colname="2">
                              <para>В выпадающем списке можно выбрать следующие типы объектов:</para>
                              <itemizedlist>
                                 <listitem>
                                    <para>Аналоговые<xref linkend="АЛ" role="Undefined Cross-Reference"/>
                                    </para>
                                 </listitem>
                                 <listitem>
                                    <para>
                                       <xref linkend="СЛ" role="Undefined Cross-Reference"/>
                                    </para>
                                 </listitem>
                                 <listitem>
                                    <para>Цифровые тракты</para>
                                 </listitem>
                                 <listitem>
                                    <para>Линки ОКС №7</para>
                                 </listitem>
                              </itemizedlist>
                              <para>Список типов объектов читается
из базы данных<xref linkend="РМО" role="Undefined Cross-Reference"/>для станции. Наличие или отсутствие в
этом списке некоторых значений зависит от конфигурации станции</para>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Включение или исключение из группы, созданной пользователем, объектов определенного
типа</entry>
                           <entry colname="2">Под выпадающим списком для выбора типа объектов
в группе расположено два списка:<itemizedlist>
                                 <listitem>
                                    <para>
                                       <emphasis>Доступные объекты</emphasis>.
В этом списке находятся имена объектов заданного типа, которые присутствуют в станции,
но не включены в выбранную группу</para>
                                 </listitem>
                                 <listitem>
                                    <para>
                                       <emphasis>Объекты в группе</emphasis>. В этом списке находятся имена объектов заданного типа уже включенные в выбранную группу.</para>
                                 </listitem>
                              </itemizedlist>Между двумя этими списками расположены
две кнопки:<itemizedlist>
                                 <listitem>
                                    <para>
                                       <command moreinfo="none">&gt;&gt; –</command>При нажатии
на эту кнопку объекты, выбранные в списке с именем<emphasis>Доступные объекты</emphasis>перемещаются
в список с именем<emphasis>Объекты в группе</emphasis>(включение объектов
в группу).</para>
                                 </listitem>
                                 <listitem>
                                    <para>
                                       <command moreinfo="none">&lt;&lt; –</command>При нажатии на эту кнопку объекты, выбранные
в списке с именем<emphasis>Объекты в группе</emphasis>перемещаются
в список с именем<emphasis>Доступные объекты</emphasis>(исключение объектов
из группы).</para>
                                 </listitem>
                              </itemizedlist>В группу могут быть включены только объекты одного
и того же типа. Для изменения типа объектов в группе нужно сначала исключить из
группы уже добавленные объекты другого типа</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Замечание:</command>Конфигурация станции может быть
такой, что для некоторых типов объектов список<emphasis>Доступные
объекты</emphasis>окажется пустым.</para>
            </section>
            <section>
               <title>Загрузка и сохранение данных</title>
               <para>Для загрузки и сохранения данных приложение использует<xref linkend="DCOM" role="Undefined Cross-Reference"/>-компоненту,
реализованную в приложении Сервер статистики (см. разд. «<xref linkend="tri_odin_9" role="Undefined Cross-Reference"/>»).
Данные статистики хранятся только на компьютере, на котором запущены
Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»).
В существующей версии доступ к данным групп статистики может быть
осуществлен одновременно только с одного компьютера на котором запущен
Панель<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_4etn" role="Undefined Cross-Reference"/>»).</para>
               <para>Замечание: Для корректной работы этих операций требуется настройка
прав доступа для соответствующие DCOM-компонеты. Эта процедура осуществляется
автоматически при инсталляции РМО. Но если по каким то причинам
процедура настройки прав не была выполнена или была выполнена некорректно,
то вы можете совершить ее самостоятельно. Для этого ознакомьтесь
с соответствующим разделом справки.</para>
               <para>При загрузке и сохранении данных внизу окна приложения появляется
панель, на которой показывается состояние производимой операции.</para>
               <para>
                  <emphasis>Сохранение данных</emphasis>
               </para>
               <para>Эта операция служит для сохранения изменений произведенных
пользователем. Все изменения передаются на Сервер статистики (см.
разд. «<xref linkend="tri_odin_9" role="Undefined Cross-Reference"/>»),
который и сохраняет изменения в базу данных<xref linkend="РМО" role="Undefined Cross-Reference"/>. При начале данной операции
Сервер статистики автоматически останавливает работу по выкачке
данных статистики из станции, а после успешного сохранения изменений
в базе данных статистики автоматически восстанавливает процесс по
выкачке данных статистики из станции с измененными данными.</para>
               <para>Замечание: При изменение состава групп, создаваемых пользователем,
автоматически создается группа, содержащая старый набор объектов.
Имя для этой группы строится автоматически. Это имя имеет вид: {имя,
измененной группы} – старые данные (создана автоматически, {время
изменения состава группы}). Эти действия делаются для того, чтобы
данные статистики, собранные для старого набора объектов в группе,
были доступны из приложения Обозреватель телетрафика (см. разд.
«<xref endterm="tri_6_dva" linkend="tri_6_dva" role="Undefined Cross-Reference"/>»). Автоматически созданная
группа не видна в приложении Менеджер групп телетрафика (см. разд.
«<xref endterm="tri_6_odin" linkend="tri_6_odin" role="Undefined Cross-Reference"/>») и не участвует в процессе
выкачки данных статистики из станции.</para>
               <para>
                  <emphasis>Загрузка данных</emphasis>
               </para>
               <para>Эта операция служит для получения данных по группам статистики
с компьютера, на котором запущены Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»).
Ели перед этой операцией данные уже были загружены, и были произведены
изменения этих данных, то появится диалоговое окно с предупреждением.
В этом диалоговом окне пользователю будет предложено выбрать сохранять
или нет изменения. В случае, если пользователь выберет сохранение
изменений, перед операцией загрузки данных будет выполнена операция
сохранения данных. Операция загрузки данных выполняется автоматически
при старте приложения, если Панель<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_4etn" role="Undefined Cross-Reference"/>»)
соединен со станцией. Если приложение запущено, но Панель<xref linkend="РМО" role="Undefined Cross-Reference"/>соединен
со станцией, эта операция выполнится автоматически, как только Панель РМО
соединится со станцией.</para>
               <para>
                  <emphasis>Выход из приложения</emphasis>
               </para>
               <para>При выходе из приложения, если перед этим не были сохранены
изменения, пользователю будет показано диалоговое окно с предупреждением
и предложено три варианта дальнейшего поведения:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Сохранить</entry>
                           <entry colname="2">Перед выходом из приложения будет произведена
операция сохранения изменений</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Не сохранять</entry>
                           <entry colname="2">Операция сохранения не будет произведена перед выходом
из приложения. Все измения будут потеряны</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Отменить</entry>
                           <entry colname="2">Отменяет выход из приложения</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
         </section>
         <section>
            <title id="tri_6_dva" xreflabel="3.6.2. Обозреватель телетрафика">3.6.2.
Обозреватель телетрафика</title>
            <section>
               <title>Обзор</title>
               <para>Программа Обозреватель телетрафика предназначена для просмотра
собранной статистики.</para>
               <para>Статистика отображается в виде графика, на котором отображается
зависимость выбранного измерения для выбранной группы объектов от
времени.</para>
               <para>Программа может работать как в составе<xref linkend="РМО" role="Undefined Cross-Reference"/>, так и как отдельное приложение.</para>
            </section>
            <section>
               <title>Главное окно</title>
               <para>Главное окно программы выглядит так:</para>
               <informalfigure float="0">
                  <graphic width="10.000in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/обозреватель-телетрафика.gif"/>
               </informalfigure>
               <para>Окно делится на шесть основных частей:</para>
               <itemizedlist>
                  <listitem>
                     <para>Главное меню</para>
                  </listitem>
                  <listitem>
                     <para>Группы (список доступных групп)</para>
                  </listitem>
                  <listitem>
                     <para>Измерения (список доступных измерений)</para>
                  </listitem>
                  <listitem>
                     <para>Дата (выбор даты, для которой будет просматриваться
статистика)</para>
                  </listitem>
                  <listitem>
                     <para>Время (выбор временного интервала, для которой будет
просматриваться статистика)</para>
                  </listitem>
                  <listitem>
                     <para>Кнопки</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Главное меню</emphasis>
               </para>
               <para>В данной версии приложения главное меню имеет единственный
раздел<emphasis>Файл</emphasis>. Этот раздел всегда содержит пункт<emphasis>Выход</emphasis>,
который служит для выхода из приложения. Наличие других пунктов
зависит от соединения со станцией. Если соединения со станцией не установлено
или разорвано в процессе работы приложения, то появляется пункт<emphasis>Открыть</emphasis>. Подробнее
об этом можно прочитать в разделе « Загрузка данных».</para>
               <para>
                  <emphasis>Группы</emphasis>
               </para>
               <para>Эта часть главной формы отображает список доступных групп
статистики. Список позволяет выбрать группу, по которой хочется
просматривать статистику. Содержание списка изменяется в зависимости
от выбранной даты. Если список пустой, то для выбранной даты нет
статистики.</para>
               <para>
                  <emphasis>Измерения</emphasis>
               </para>
               <para>Эта часть главной формы отображает список доступных измерений
для выбранной группы статистики. Список позволяет выбрать измерение,
по которому хочется просматривать статистику. Содержание списка
меняется в зависимости от выбранной группы и даты. Если список пустой,
то для выбранной группы и даты нет статистики.</para>
               <para>
                  <emphasis>Дата</emphasis>
               </para>
               <para>Эта часть главной формы отображает календарь, в котором можно
выбрать требуемую дату. Переключение даты можно осуществлять как
по дням, так и по месяцам и годам. После выбора даты приложение
попытается открыть базу статистики, соответствующую выбранной дате.
Если базы не существует, то будет выдано предупреждение об ошибке следующего
вида:</para>
               <informalfigure float="0">
                  <graphic width="8.625in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-oshibka2.gif"/>
               </informalfigure>
               <para>Вторая строка этого предупреждения содержит текст сообщения,
выданное сервером доступа к данным и группам телетрафика, и представляет
собой системное сообщение об ошибке. Язык этого сообщения зависит
от локализации операционной системы и не может быть изменен.</para>
               <para>
                  <emphasis>Время</emphasis>
               </para>
               <para>В этой части главной формы можно установить начальное и конечное
время для отображаемой на графике статистики. Если эти времена не
указаны, то соответственно статистика будет отображаться от начала
(если не задано начальное время) и до конца (если не задано конечное
время) суток.</para>
               <para>
                  <emphasis>Кнопки</emphasis>
               </para>
               <para>
                  <command moreinfo="none">Кнопки обозревателя телетрафика</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Перечитать группы и измерения…</entry>
                           <entry colname="2">При нажатии на эту кнопку данные о группах
и измерениях перечитываются из базы статистики</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Построить график…</entry>
                           <entry colname="2">При нажатии на эту кнопку открывается новое окно,
в котором для выбранной группы и выбранного измерения строится график зависимости измерений от
времени</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Численные значения измерений…</entry>
                           <entry colname="2">При нажатии на эту кнопку открывается новое окно,
в котором для выбранной группы выводятся численные значения по всем измерениям</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>После изменения состава группы и перезапуска серверов, если
по группе уже были собраны данные статистики, автоматически создастся
группа с именем вида %Имя измененной группы% старые данные (создана
автоматически) %номер%. Эта группа содержит предыдущие (до изменения
состава группы) данные статистики для измененной группы.</para>
            </section>
            <section>
               <title>Загрузка данных</title>
               <para>
                  <emphasis>Загрузка данных из клиента РМО</emphasis>
               </para>
               <para>При запуске приложения из клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>, в котором установлено
соеденение со станцией, или соеденение со станцией происходит при
запущеном приложении, то автоматически загружаются необходимые данные
из базы данных телетрафика, которая соответствует выбранной дате
(при старте приложения в качестве даты устанавливается текущая дата)
и станции, с которой установлено соеденение. При этом данные телетрафика
находятся на компьютере, где запущен сервер телетрафика. Это может
быть как локальный компьютер, так и комьпьютер, расположенный в
локальной сети. Для компьютера, расположенного в локальной сети,
предоставление доступа к данным через локальную сеть необязателено.</para>
               <para>Если при старте приложения для выбранной даты отсутствует
база со статистикой, то будет выдано предупреждение об ошибке следующего
вида:</para>
               <informalfigure float="0">
                  <graphic width="8.625in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-oshibka-podkljuchen.gif"/>
               </informalfigure>
               <para>В первой строке указано имя компьютера на котором ведется
сбор статистики (запущен сервер телетрафика).</para>
               <para>
                  <emphasis>Загрузка данных при работе не из клиента РМО или
отсутствующем соеденении</emphasis>
               </para>
               <para>При запуске приложения не из клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>или при отсутствии в клиенте<xref linkend="РМО" role="Undefined Cross-Reference"/>соеденения
со станцией в меню<emphasis>Файл</emphasis>становится доступным
пункт<emphasis>Открыть</emphasis>. При нажатии на него появится
окно, в котором можно выбрать путь к данным<xref linkend="РМО" role="Undefined Cross-Reference"/>:</para>
               <para>В этом окне вы можете указать путь к данным<xref linkend="РМО" role="Undefined Cross-Reference"/>(папку
в которую установлены данные<xref linkend="РМО" role="Undefined Cross-Reference"/>), для которых хочется просматривать
статистику. Данные<xref linkend="РМО" role="Undefined Cross-Reference"/>должны находится на локальном компьютере
или быть доступными через локальную сеть. Работа с данными, загруженными таким
образом, ничем не отличается от работы с данными, загруженными из
клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
               <informalfigure float="0">
                  <graphic width="4.667in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika_obzor-papok.gif"/>
               </informalfigure>
               <para>Для работы с данными телетрафика приложение использует<xref linkend="DCOM" role="Undefined Cross-Reference"/>-компоненту, реализованную
в приложении<filename moreinfo="none">RMOStatisticServer.exe</filename>.</para>
            </section>
            <section>
               <title>Графики</title>
               <para>
                  <emphasis>Внешний вид</emphasis>
               </para>
               <para>В настоящей версии приложения на графике синим цветом отображается
зависимость значений измерения, выраженые в эрлангах или количестве
в минуту, от времени.</para>
               <informalfigure float="0">
                  <graphic width="6.306in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-grafiki-vneshnij-vid.gif"/>
               </informalfigure>
               <para>Над графиком расположено название измерения и название группы.</para>
               <para>На графике по горизонтали отображается время, по вертикали
отображаются значения измерения, выраженые в эрлангах или количестве
в минуту (В настоящей версии приложения в эрлангах отображается
только измерение<emphasis>Нагрузка</emphasis>).</para>
               <para>Красными вертикальными полосами на графике отображается промежуток
времени, когда нет данных для вычисления эрлангов или количества
в минуту (Рестарт модуля, перезапуск сервера статистики, значения
измерения получены по другому количеству объектов…).</para>
               <para>
                  <emphasis>Работа с графиком</emphasis>
               </para>
               <para>В настоящей версии приложения вы можете производить с графиком
следующие операции:</para>
               <itemizedlist>
                  <listitem>
                     <para>Увеличение части графика</para>
                  </listitem>
                  <listitem>
                     <para>Перемещение</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Увеличение части графика</emphasis>
               </para>
               <para>На графике вы можете выделить область, которую хотите увеличить:</para>
               <informalfigure float="0">
                  <graphic width="6.264in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-grafiki-uvelichenie.gif"/>
               </informalfigure>
               <para>Это можно осуществить, выделив c помощью мышки требуемую область,
удерживая левую кнопку мышки, и перемещая мышку от левого верхнего
угла к правому нижнему. Когда требуемая область будет выделена,
отпустите левую кнопку мышки, и выбранная область увеличится:</para>
               <informalfigure float="0">
                  <graphic width="6.361in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-grafiki-uvelichennyj.gif"/>
               </informalfigure>
               <para>Для восcтановления изначального вида графика проделайте ту
жу операцию, но выделение производите от правого нижнего угла к
верхнему левому:</para>
               <informalfigure float="0">
                  <graphic width="6.250in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-grafiki-umenshenie.gif"/>
               </informalfigure>
               <para>
                  <emphasis>Перемещение</emphasis>
               </para>
               <para>Для перемещения графика используйте перемещение мышки с нажатой
правой кнопкой мышки.</para>
               <informalfigure float="0">
                  <graphic width="6.361in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-grafiki-peremetshenie.gif"/>
               </informalfigure>
            </section>
            <section>
               <title>Численные значения измерений</title>
               <para>
                  <emphasis>Внешний вид</emphasis>
               </para>
               <para>В настоящей версии приложения окно, содержащее численные значения
измерений, выглядит следующим образом.</para>
               <informalfigure float="0">
                  <graphic width="9.833in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-chislennye-znachenija.gif"/>
               </informalfigure>
               <para>В графе<emphasis>Потерянное время</emphasis>содержится общее
за данный период время (например, рестарт модуля) про которое нет
данных в базе статистики.</para>
               <para>Нагрузка выводится как суммарное время занятости всех объектов
в группе, так и в эрлангах, которые получаются следующем образом:
суммарное время / (период измерения * количество объектов в группе)</para>
               <para>В настоящей версии приложения окно, содержащее численные значения
измерений, имеет единственный пункт меню<emphasis>Файл</emphasis>.
В этом пункте содержится два подпункта<emphasis>Печать</emphasis>и<emphasis>Выход</emphasis>.
С помощью подпункта<emphasis>Печать</emphasis>вы можете распечатать содержимое
окна. Подпункт<emphasis>Выход</emphasis>закрывает окно.</para>
            </section>
         </section>
         <section>
            <title id="tri_6_tri" xreflabel="3.6.3. Тарификация">3.6.3.
Тарификация</title>
            <section>
               <title>Обзор</title>
               <para>Программа Тарификация является приложением-клиентом для учета
тарификации, регистрации входящих вызовов (<xref linkend="РВВ" role="Undefined Cross-Reference"/>) и использования дополнительных
видов обслуживания (<xref linkend="ДВО" role="Undefined Cross-Reference"/>).</para>
            </section>
            <section>
               <title>Главное окно</title>
               <informalfigure float="0">
                  <graphic width="6.736in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/tarifikatzija.gif"/>
               </informalfigure>
               <para>Идеология пользования программой такова: есть база данных,
в которую сваливается вся тарификационная информация; для работы
следует отфильтровать требуемые данные; результат фильтрации называется
просмотром; над данными в просмотре можно осуществлять различные
действия (сейчас можно создавать по просмотру текстовый отчет).</para>
               <para>
                  <emphasis>Главное меню</emphasis>
               </para>
               <para>
                  <command moreinfo="none">Меню База</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Начать скачивание</entry>
                           <entry colname="2">Скачать новые данные с сервера тарификации.
Вместо скачивания можно применить технику прямого копирования базы
(см. разд. «<xref linkend="tri_odin_5" role="Undefined Cross-Reference"/>»)</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Выход</entry>
                           <entry colname="2">Выйти из программы</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Меню Просмотр</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Показать</entry>
                           <entry colname="2">В подменю данного пункта следует выбрать одно
из названий фильтра для создания нового просмотра</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Закрыть</entry>
                           <entry colname="2">Закрыть текущий просмотр</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Закрыть все</entry>
                           <entry colname="2">Закрыть все просмотры</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Создать отчет…</entry>
                           <entry colname="2">Создать на основе данных просмотра текстовый отчет</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Меню Фильтр</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Задать…</entry>
                           <entry colname="2">Задать фильтр в активном просмотре</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Отключить</entry>
                           <entry colname="2">Отключить фильтр в активном просмотре (показать все
записи)</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Удалить…</entry>
                           <entry colname="2">Удалить ненужные фильтры</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>База данных хранится в подкаталоге<emphasis>Tarif</emphasis>каталога
данных<xref linkend="РМО" role="Undefined Cross-Reference"/>.
Разрешены манипуляции над составляющими ее файлами:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Резервное копирование данных</entry>
                           <entry colname="2">Для этого следует полностью скопировать содержимое
каталога базы тарификации в безопасное место. Возможно осуществлять частичное резервирование данных
(по годам, месяцам). При восстановлении из резервной копии следует убедиться
в правильности полученной структуры каталогов и файлов базы: сначала идут каталоги
за каждый год (с именами вида<filename moreinfo="none">ГГГГ</filename>), в них подкаталоги
за каждый месяц (с именами вида<filename moreinfo="none">ГГГГММ</filename>), каждый файл хранит записи
за одни сутки (по времени окончания разговора) и имеет имя вида<filename moreinfo="none">ГГГГММДД.rdb</filename>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Частичное архивирование данных</entry>
                           <entry colname="2">При нехватке места на диске допускается перемещение
части файлов базы в другое место хранения. Работоспособность базы
при этом не теряется, но просмотреть перемещенные данные невозможно</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
            <section>
               <title/>
               <informalfigure float="0">
                  <graphic width="8.111in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/тарификация-окно-просм..gif"/>
               </informalfigure>
               <para>В верхней части окна просмотра находятся кнопки перемещения
по записям таблицы:</para>
               <itemizedlist>
                  <listitem>
                     <para>на первую запись</para>
                  </listitem>
                  <listitem>
                     <para>на предыдущую запись</para>
                  </listitem>
                  <listitem>
                     <para>на следующую запись</para>
                  </listitem>
                  <listitem>
                     <para>на последнюю запись</para>
                  </listitem>
               </itemizedlist>
               <para>Окно просмотра представляет из себя таблицу, каждая строка
в которой соответствует состоявшемуся разговору, записи<xref linkend="РВВ" role="Undefined Cross-Reference"/>или<xref linkend="ДВО" role="Undefined Cross-Reference"/>.</para>
               <para>Ниже расписан смысл информации по столбцам. Следует отметить,
что не все столбцы имеют смысл (и, соответственно, не заполнены
данными) для разных типов записей.</para>
               <para>
                  <command moreinfo="none">Описание столбцов</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Столбец</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Тип</entry>
                           <entry colname="2">Для записей о разговоре – тип соединения (см.
ниже); для записей<xref linkend="ДВО" role="Undefined Cross-Reference"/>и<xref linkend="РВВ" role="Undefined Cross-Reference"/>– глифы (см. «глифы»)<xref linkend="ДВО" role="Undefined Cross-Reference"/>и<xref linkend="РВВ" role="Undefined Cross-Reference"/>соответственно</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Вызывающий</entry>
                           <entry colname="2">Цифры номера вызывающего абонента</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Вызываемый</entry>
                           <entry colname="2">Цифры номера вызываемого абонента</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Начало</entry>
                           <entry colname="2">Дата и время начала разговора</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Продолжительность</entry>
                           <entry colname="2">Продолжительность разговора</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Завершение</entry>
                           <entry colname="2">Дата и время завершения разговора</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Информация</entry>
                           <entry colname="2">Дополнительная информация: для разговора может стоять признак переадресации,
для записи<xref linkend="РВВ" role="Undefined Cross-Reference"/>– тип<xref linkend="АОН" role="Undefined Cross-Reference"/>, для записи<xref linkend="ДВО" role="Undefined Cross-Reference"/>– название услуги</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Коды типов соединений</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Элемент меню</entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="ВС" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Внутристанционное</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="МС" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Межстанционное</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="МГ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Междугороднее</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="МН" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Международное</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="МТ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Межстоечное</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="СБ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Спецслужбы бесплатные</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="СП" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Спецслужбы платные</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="СЭ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Спецслужбы экстренные</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <xref linkend="СГ" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Спецслужбы междугородние</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">
                              <xref linkend="СН" role="Undefined Cross-Reference"/>
                           </entry>
                           <entry colname="2">Спецслужбы международные</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Для сортировки данных по одному из столбцов нужно щелкнуть
по нему мышью. Название столбца становится выделенным жирным шрифтом.
Для отмены сортировки нужно повторно щелкнуть мышью по этому столбцу.</para>
            </section>
            <section>
               <title>Задание фильтра</title>
               <informalfigure float="0">
                  <graphic width="5.042in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/тарификация-фильтр.gif"/>
               </informalfigure>
               <para>Для каждого из имеющихся в просмотре столбцов можно задать
фильтр для отбора интересующих записей. Для текстовых полей задается
строка отбора – чтобы запись попала в просмотр, значение в этом
столбце должно в точности соответствовать заданной строке. Для полей,
содержащих дату и время, задаются временный рамки, в которые должно
попасть значение в этом столбце. Для поля продолжительность ограничения задаются
в секундах.</para>
               <para>
                  <command moreinfo="none">Задача 1. Задание фильтра</command>
               </para>
               <itemizedlist>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1a)</emphasis>Выбрать
меню<emphasis>Фильтр -&gt; Задать</emphasis>
                     </para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1b)</emphasis>В поле<emphasis>Тип</emphasis>выбирать
из предложенного списка тип разговоров</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1c)</emphasis>В полях<emphasis>Вызывающий</emphasis>и<emphasis>Вызываемый</emphasis>прописать
конкретные номера телефонов</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1d)</emphasis>В поле<emphasis>Продолжительность</emphasis>можно
установить минимальную и максимальную продолжительность разговоров,
которые будут пропущены фильтром. Чтобы установить минимальную продолжительность,
следует проставить галочку в поле «с» и задать время в секундах
в поле рядом. Чтобы установить максимальную продолжительность, надо
сделать тоже самое для поля «по».</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1e)</emphasis>При необходимости сделать
выборку по конкретным датам для полей, содержащих дату и время,
задаются временные рамки, в которые должно попасть значения Тарификации</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1f)</emphasis>В поле<emphasis>Информация</emphasis>выбрать
из предложенного списка интересующий вариант (заполнять необязательно)</para>
                  </listitem>
                  <listitem>
                     <para>
                        <emphasis>Шаг 1g)</emphasis>Нажать кнопку<command moreinfo="none">Ок</command>
                     </para>
                  </listitem>
               </itemizedlist>
            </section>
            <section>
               <title>Удаление фильтров</title>
               <informalfigure float="0">
                  <graphic width="4.708in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/тарификация-удалить-фильтр.gif"/>
               </informalfigure>
               <para>Все заданные пользователем фильтры сохраняются от сеанса к
сеансу, и в скором времени фильтров может набраться достаточно много.
Удалить ненужные фильтры проще простого – выбираем<emphasis>Фильтр-&gt;Удалить</emphasis>…,
помечаем галочкой все ненужные фильтры и нажимаем<command moreinfo="none">Удалить
выбранные</command>. Если не нужен ни один фильтр, нажимаем<command moreinfo="none">Удалить все</command>.
Если в момент удаления открыты просмотры, использующие удаляемые
фильтры, они автоматически будут закрыты.</para>
            </section>
         </section>
      </section>
   </d:InfElement>
</d:DocumentationCore>