<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" filename="Opisanie_realizacii.drl">
   <d:InfElement id="implementation_specification" name="Описание реализации"
                 parenttype="DocumentationCore"
                 filename="Opisanie_realizacii.drl">









      <chapter>
         <title>Описание реализации</title>
         <section>
            <title>1.1. Назначение</title>
            <para>Комплекс программных средств, объединенных под общим названием
Рабочее Место Оператора (<xref linkend="РМО" role="Undefined Cross-Reference"/>), предназначен для обеспечения
следующих функций технического обслуживания и эксплуатации<xref linkend="ЭАТС" role="Undefined Cross-Reference"/>«Квант-Е
Сокол»:</para>
            <itemizedlist>
               <listitem>
                  <para>управление встроенным<xref linkend="ПО" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>обслуживание и управление абонентскими линиями</para>
               </listitem>
               <listitem>
                  <para>обслуживание и управление межстанционными каналами</para>
               </listitem>
               <listitem>
                  <para>управление маршрутизацией</para>
               </listitem>
               <listitem>
                  <para>мониторинг состояния оборудования</para>
               </listitem>
               <listitem>
                  <para>обслуживание коммутационного поля</para>
               </listitem>
               <listitem>
                  <para>сбор статистической информации</para>
               </listitem>
               <listitem>
                  <para>учет телетрафика</para>
               </listitem>
            </itemizedlist>
         </section>
         <section>
            <title>1.2. Структура РМО</title>
            <para>
               <xref linkend="ПО" role="Undefined Cross-Reference"/>
               <xref linkend="РМО" role="Undefined Cross-Reference"/>поставляется
как пакет взаимодействующих между собой приложений. Обмен данными между
приложениями обеспечивается по внутреннему протоколу и обеспечивает
простоту расширения функциональности.</para>
            <para>
               <xref linkend="ПО" role="Undefined Cross-Reference"/>
               <xref linkend="РМО" role="Undefined Cross-Reference"/>может
работать со станцией либо используя локальную связь через последовательный порт
RS232, либо удаленную – через модем или по протоколу<xref linkend="TCPIP" role="Undefined Cross-Reference"/>. Удаленный
доступ к станции всегда производится через компьютер, локально подключенный
к<xref linkend="АТС" role="Undefined Cross-Reference"/>.
При этом на обслуживающем компьютере должно работать приложение<emphasis>Маршрутизатор</emphasis>,
входящее в поставку<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
            <para>Каждая станция комплектуется обслуживающим компьютером конфигурации, указанной
в разделе Аппаратно-программные требования. В поставку также входит
CD-диск с дистрибутивом<xref linkend="РМО" role="Undefined Cross-Reference"/>. Процесс установки<xref linkend="ПО" role="Undefined Cross-Reference"/>
               <xref linkend="РМО" role="Undefined Cross-Reference"/>подробно
описывается в разделе «<xref linkend="dva_odin" role="Undefined Cross-Reference"/>».</para>
            <para>Одно<xref linkend="РМО" role="Undefined Cross-Reference"/>может
обслуживать несколько<xref linkend="АТС" role="Undefined Cross-Reference"/>«Квант-Е Сокол».</para>
         </section>
         <section>
            <title>1.3. Философия РМО 1.5</title>
            <section>
               <title>1.3.1. Введение</title>
               <para>Данный документ посвящен описанию концепций заложенных в комплекс
приложений «Рабочее место оператора 1.5». Предполагается рассмотреть
следующие архитектурные особенности комплекса:</para>
               <itemizedlist>
                  <listitem>
                     <para>Архитектура работы с базой данных<xref linkend="РМО" role="Undefined Cross-Reference"/>1.5</para>
                  </listitem>
                  <listitem>
                     <para>Архитектура работы взаимодействия с функциональным
программным обеспечением<xref linkend="АТС" role="Undefined Cross-Reference"/>
                     </para>
                  </listitem>
                  <listitem>
                     <para>Распределенная архитектура серверов<xref linkend="РМО" role="Undefined Cross-Reference"/>1.5</para>
                  </listitem>
               </itemizedlist>
            </section>
            <section>
               <title>1.3.2. Работа с базой данных РМО 1.5</title>
               <para>В комплексе приложений «Рабочее место оператора 1.5» введены
ограничения в доступе к базе данных<xref linkend="РМО" role="Undefined Cross-Reference"/>– только серверные приложения
имеют к базе данных полный доступ, клиентским же приложениям данные
доступны только на чтение. К серверным приложениям относятся:</para>
               <itemizedlist>
                  <listitem>
                     <para>Конфигуратор</para>
                  </listitem>
                  <listitem>
                     <para>Маршрутизатор</para>
                  </listitem>
                  <listitem>
                     <para>Приложение Серверы<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)</para>
                  </listitem>
                  <listitem>
                     <para>Все приложения, интегрированные в Серверы<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)</para>
                  </listitem>
               </itemizedlist>
               <para>Это было сделано для того, чтобы обеспечить целостность данных
и препятствовать их несанкционированному изменению. Однако, клиентские
приложения могут вносить изменения в базу данных<xref linkend="РМО" role="Undefined Cross-Reference"/>посредством взаимодействия
с серверным приложениями. Схема работы с базой данных изображена
на следующем рисунке:</para>
               <informalfigure float="0">
                  <graphic width="9.139in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/RMOBDScheme.gif"/>
               </informalfigure>
               <para>Основным приложением, ответственным за изменение базы данных<xref linkend="РМО" role="Undefined Cross-Reference"/>является<emphasis>Конфигуратор</emphasis>,
позволяющее в достаточно удобное форме изменять комплексные настройки<xref linkend="АТС" role="Undefined Cross-Reference"/>(в том
числе на ходу). Приложение<emphasis>Конфигуратор</emphasis>активно взаимодействует
с интегрированным сервером синхронизации.</para>
               <para>Если клиентскому приложению нужно хранить свои временные данные,
то он помещаются не в базу данных<xref linkend="РМО" role="Undefined Cross-Reference"/>(т.к. база данных доступна
только на чтение), а в специально отведенный для этого каталог в
виде отдельного файла.</para>
               <para>В отличие от более ранних версий комплекса в<xref linkend="РМО" role="Undefined Cross-Reference"/>1.5 приложения
получают путь для подключения к данным станции не как параметр клиентской
конфигурации (элемент файла<filename moreinfo="none">osmain.ini</filename>), а от
серверного приложения<emphasis>Маршрутизатор</emphasis>(см. разд.
«<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»).
Так же у пользователя появилась возможность быстро добавить в список
станций новую запись благодаря команде<emphasis>Новая станция…</emphasis>меню<emphasis>Станция</emphasis>.</para>
            </section>
            <section>
               <title>1.3.3. Работа с функциональным программным обеспечением
АТС</title>
               <para>С целью предотвратить нарушение целостности данных функционального программного
обеспечения и несанкционированный доступ к данным<xref linkend="ФПО" role="Undefined Cross-Reference"/>в комплексе приложений
Рабочее место оператора 1.5 были введены ограничения на доступ к статическим
параметрам объектов<xref linkend="ФПО" role="Undefined Cross-Reference"/>. Теперь изменять статические
параметры объектов<xref linkend="ФПО" role="Undefined Cross-Reference"/>могут только серверные приложения
(о составе группы серверных приложений см. выше), а клиентские приложения
имеют к статике доступ только на чтение. Однако, клиентские приложения
могут изменять статические параметры объектов<xref linkend="ФПО" role="Undefined Cross-Reference"/>опосредованно – через взаимодействие
с серверными приложениями.</para>
               <para>Основным приложением ответственным за изменение статических
параметров объектов<xref linkend="ФПО" role="Undefined Cross-Reference"/>является интегрированный
сервер синхронизации, основная задача которого заключается в поддержании
соответствия данных<xref linkend="ФПО" role="Undefined Cross-Reference"/>и базы данных<xref linkend="РМО" role="Undefined Cross-Reference"/>. Во
время работы сервера синхронизации все остальные интегрированные
сервера получают соответствующие уведомления и должны на время приостановить
работу.</para>
            </section>
            <section>
               <title id="odin_tri_4et"
                      xreflabel="1.3.4. Распределенная архитектура серверов РМО 1.5">1.3.4.
Распределенная архитектура серверов РМО 1.5</title>
               <para>Одним из основных отличий комплекса приложения Рабочее место
оператора 1.5 от комплекса приложений Рабочее место оператора является
архитектура серверных приложений. В<xref linkend="РМО" role="Undefined Cross-Reference"/>1.5, для увеличения надежности
серверных приложений, была применена технология<xref linkend="DCOM" role="Undefined Cross-Reference"/>и организована распределенная
работа серверов. В новом подходе к организации серверных приложений
можно выделить следующие сущности:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Приложение Маршрутизатор (см. разд. «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»)</entry>
                           <entry colname="2">Как и более ранних версиях комплекса, приложение Маршрутизатор
(см. разд. «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>») осуществляет обмен данных между функциональным программным обеспечением<xref linkend="АТС" role="Undefined Cross-Reference"/>и программами комплекса<xref linkend="РМО" role="Undefined Cross-Reference"/>. В дополнение
к этой функциональности, в приложение были добавлены механизмы контроля корректности
работы приложения Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. ниже) и перезапуск его
в случае обнаружения некорректной работы. Если после перезапуска приложение продолжает
вести себя не устойчиво, оно будет закрыто без перезапуска</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Приложение Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)</entry>
                           <entry colname="2">Главный элемент в новой технологии. Это приложение координирует
работу всех интегрированных серверов (см. ниже) и осуществляет контроль корректности
их работы. Может перезапустить тот или иной интегрированный сервер
в случае обнаружения проблем в работе. В случае, если интегрированный сервер продолжает
работать неустойчиво даже после перезапуска, закрывает интегрированный сервер. Приложение Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>») интегрируется
с приложением Маршрутизатор (см. разд. «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>») на уровне пользовательского интерфейса</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Интегрированный сервер</entry>
                           <entry colname="2">Отдельное приложение выполняющее ряд функции по
работе с<xref linkend="АТС" role="Undefined Cross-Reference"/>, объединенных
в единую логическую совокупность. Интегрируется с приложением Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «3.1.2 Серверы РМО») на уровне пользовательского интерфейса и
работает под его контролем</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Основная цель такой организации работы серверных приложений
– добиться отказоустойчивости системы в целом. Если при работе в
одном из интегрированных серверов возникает ошибка и приложение
выгружается из памяти операционной системой, то это не может повлиять
на работу других интегрированных серверов и работоспособность системы
в целом. Приложение Сервера<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)
реагирует на сбои в работе отдельных интегрированных серверов и
пытается перезапустить их в случае обнаружения сбоя, благодаря чему
достигается обеспечение максимально полной функциональности.</para>
               <para>Для большего удобства пользователей комплекса приложений Рабочее
место оператора 1.5 все серверные приложения комплекса интегрированы
на уровне пользовательского интерфейса, т.е. визуально на экране
компьютера пользователь может увидеть одно окно с несколькими раскладками,
но на самом деле серверные приложения работают в отдельных процессах.
Для большей наглядности предлагаемой концепции приведем две диаграммы:</para>
               <para>Такую картину пользователь может наблюдать на экране:</para>
               <informalfigure float="0">
                  <graphic width="10.181in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/View1.gif"/>
               </informalfigure>
               <para>А так ситуация выглядит с точки зрения операционной системы:</para>
               <informalfigure float="0">
                  <graphic width="9.139in" align="aleft"
                           fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/View2.gif"/>
               </informalfigure>
               <para>Сплошными стрелками показаны связи с использование технологии<xref linkend="DCOM" role="Undefined Cross-Reference"/>(новшество
в<xref linkend="РМО" role="Undefined Cross-Reference"/>1.5),
а пунктирными стрелками показаны связи организованные по тому же
принципу, что и более ранних версиях<xref linkend="РМО" role="Undefined Cross-Reference"/>(через канал разделяемой
памяти).</para>
            </section>
         </section>
         <section>
            <title>1.4. Аппаратно-программные требования</title>
            <para>Комплекс программных средств<xref linkend="РМО" role="Undefined Cross-Reference"/>(программное обеспечение<xref linkend="РМО" role="Undefined Cross-Reference"/>–<xref linkend="ПО" role="Undefined Cross-Reference"/>
               <xref linkend="РМО" role="Undefined Cross-Reference"/>) предназначено
для использования в среде Microsoft Windows 2000 Professional или
Microsoft Windows XP Professional на компьютерах, соответствующих
нижепреведенной аппаратно-программной конфигурации:</para>
            <para>
               <command moreinfo="none">Аппаратно-программные требования</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Аппаратно-программные средства</entry>
                        <entry colname="2">Минимальная конфигурация</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Процессор</entry>
                        <entry colname="2">Не ниже Pentium III 700 МГц</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Оперативная память</entry>
                        <entry colname="2">Не менее 512 Мб</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Жесткий диск</entry>
                        <entry colname="2">От 40 Гб</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Монитор и видеокарта</entry>
                        <entry colname="2">Поддержка режима 1024х768x256 цветов</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Модем (если необходим удаленный доступ)</entry>
                        <entry colname="2"/>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <xref linkend="ОС1" role="Undefined Cross-Reference"/>Microsoft Windows 2000 Professional
/ Microsoft Windows XP Professional</entry>
                        <entry colname="2">Лицензионное<xref linkend="ПО" role="Undefined Cross-Reference"/>
                        </entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обновления системных компонент</entry>
                        <entry colname="2">MDAC 2.6,<xref linkend="XML" role="Undefined Cross-Reference"/>DOM 3.2, Scripting Host
5.6</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Характеристики оборудования, не указанные в таблице, не являются
существенными и могут выбираться поставщиком или заказчиком.</para>
         </section>
      </chapter>
   </d:InfElement>
</d:DocumentationCore>