<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" filename="Provodnik_CMM_scripti_MMO.drl">
   <d:InfElement id="join_in_embsoft" name="Проводник СММ, скрипты РМО">









      <section>
         <title id="tri_dva_dva" xreflabel="3.2.2. Проводник CMM">3.2.2.
Проводник CMM</title>
         <section>
            <title>Обзор</title>
            <para>Программа Проводник CMM предназначена для управления скриптами
CMM. Скрипты CMM представляют собой небольшие программы, способные
общаться с<xref linkend="ПО" role="Undefined Cross-Reference"/>телефонной
станции и предназначены, в основном, для диагностических целей.</para>
            <para>С помощью проводника можно:</para>
            <itemizedlist>
               <listitem>
                  <para>Создавать, переименовывать и удалять
файлы скриптов</para>
               </listitem>
               <listitem>
                  <para>Группировать файлы скриптов</para>
               </listitem>
               <listitem>
                  <para>Запускать скрипты на исполнение</para>
               </listitem>
               <listitem>
                  <para>Вызывать файлы скриптов на редактирование</para>
               </listitem>
            </itemizedlist>
         </section>
         <section>
            <title>Главное окно</title>
            <informalfigure float="0">
               <graphic entityref="graphic1" width="10.833in" align="aleft"/>
            </informalfigure>
            <para>По внешнему виду программа очень похожа на Проводник, входящий
в состав операционной системы Windows®. Операции над файлами скриптов
и папками, содержащими скрипты можно производить используя команды
главного меню программы и контекстного меню, вызываемого щелчком
правой кнопки мыши. В каждый момент времени одна из папок или один
из файлов скриптов могут являются текущими, о чем свидетельствует
измененный значок (для папки) и подсвечивание названия (для папки
и файла).</para>
         </section>
         <section>
            <title>Главное меню</title>
            <para>
               <command moreinfo="none">Меню Файл</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Создать -&gt; Папку</entry>
                        <entry colname="2">Создать подпапку в текущей папке</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать -&gt; Скрипт</entry>
                        <entry colname="2">Создать новый файл скрипта в текущей папке</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать связь</entry>
                        <entry colname="2">Создать в текущей папке файл-ссылку на выделенный
файл; после создания ссылку можно переместить в другую папку и использовать
для вызова скрипта</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">Удалить текущий файл или папку</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Переименовать</entry>
                        <entry colname="2">Переименовать текущий файл или папку (доступно и
через одинарный щелчок мышью на названии папки или файла)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Свойства</entry>
                        <entry colname="2">Вызвать панель свойств файла или папки</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Закрыть</entry>
                        <entry colname="2">Выйти из программы</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Меню Правка</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Вырезать</entry>
                        <entry colname="2">Пометить файл(ы) для последующего перемещения
по команде вставить</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Копировать</entry>
                        <entry colname="2">Пометить файл(ы) для последующего копирования
по команде вставить</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вставить</entry>
                        <entry colname="2">Произвести операцию перемещения или копирования
для файлов, ранее помеченных командой вырезать или копировать</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Выделить все</entry>
                        <entry colname="2">Выделить все файлы в текущей папке</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обратить выделение</entry>
                        <entry colname="2">Обратить состояние выделения для файлов текущей папки</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Меню Вид – управление показом значков файлов</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Крупные значки</entry>
                        <entry colname="2">Отображать файлы в виде крупных значков</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Мелкие значки</entry>
                        <entry colname="2">Отображать файлы в виде мелких значков</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Список</entry>
                        <entry colname="2">Отображать файлы в виде списка</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Таблица</entry>
                        <entry colname="2">Отображать файлы в виде таблицы</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">На один уровень вверх</entry>
                        <entry colname="2">Перейти в родительскую папку</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обновить</entry>
                        <entry colname="2">Обновить содержимое окна</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Контекстное меню</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Выполнить</entry>
                        <entry colname="2">Запустить скрипт на выполнение</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Редактировать</entry>
                        <entry colname="2">Вызвать редактор для файла скрипта</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать связь</entry>
                        <entry colname="2">Создать в текущей папке файл-ссылку на выделенный
файл. После создания ссылку можно переместить в другую папку и использовать
для вызова скрипта</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">Удалить текущий файл или папку</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Переименовать</entry>
                        <entry colname="2">Переименовать текущий файл или папку (доступно и
через одинарный щелчок мышью на названии папки или файла)</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Свойства</entry>
                        <entry colname="2">Вызвать панель свойств файла</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Язык CMM-скриптов</para>
            <para>
               <command moreinfo="none">Описание языка CMM-скриптов</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Набор символов</entry>
                        <entry colname="2">Идентификаторы и ключевые слова не чувствительны
к регистру. Русские буквы в них не допускаются.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Константы</entry>
                        <entry colname="2">Целочисленные записываются либо в десятичном представлении,
либо в шестнадцатиричном (с префиксом $). Строковые записываются
в одинарных кавычках ('), чтобы включить в строку этот символ, следует написать его дважды.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Переменные</entry>
                        <entry colname="2">Тип только целочисленный (знаковый 32-битный), предварительное описание не требуется, инициализируются нулем,
имя не может быть зарезервированным словом.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Операции</entry>
                        <entry colname="2">Присваивание: :=, сравнение: = &lt;&gt; &lt; &gt;
&gt;= &lt;=, арифметика: + - * /, сдвиги: &lt;&lt; &gt;&gt;, логика: &amp;&amp;
|| ^ NOT, скобки: ( ).</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Операторы</entry>
                        <entry colname="2">
                           <para>Каждый оператор должен завершаться точкой
с запятой (;). Метка оператора задается указанием идентификатора
с двоеточием (:).</para>
                           <para>IF &lt;условие&gt; THEN &lt;операторы&gt;
[ELSE &lt;операторы&gt;] FI.</para>
                           <para>FOR &lt;переменная&gt; FROM &lt;значение&gt;
TO &lt;значение&gt; DO &lt;операторы&gt; OD.</para>
                           <para>GOTO &lt;метка оператора&gt;.</para>
                        </entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Функции</entry>
                        <entry colname="2">Имеются только внешние. Параметры при вызове отделяются
запятой. Вызов: &lt;имя функции&gt; (&lt;параметры&gt;)</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
      </section>
      <section>
         <title>3.2.3.
Скрипты РМО</title>
         <section>
            <title>Обзор</title>
            <para>Приложение Скрипты<xref linkend="РМО" role="Undefined Cross-Reference"/>подключается к Серверу скриптов<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_10" role="Undefined Cross-Reference"/>»)
и предоставляет следующую функциональность:</para>
            <itemizedlist>
               <listitem>
                  <para>Управление файлами сценариев (создание,
удаление и т.д.)</para>
               </listitem>
               <listitem>
                  <para>Запуск сценария на выполнение</para>
               </listitem>
               <listitem>
                  <para>Управление ходом выполнения сценария</para>
               </listitem>
               <listitem>
                  <para>Отображение результатов работы сценария</para>
               </listitem>
               <listitem>
                  <para>Редактирование сценария</para>
               </listitem>
            </itemizedlist>
         </section>
         <section>
            <title>Главное окно и окно проводника</title>
            <informalfigure float="0">
               <graphic entityref="graphic2" width="9.833in" align="aleft"/>
            </informalfigure>
            <para>Главное окно позволяет проводить операции с дочерними окнами,
такими как окно проводника или окнами исполнения и редактирования
сценариев. Проводник предназначен для управления файлами сценариев.
По своему внешнему виду и функциональности напоминает проводник
Windows. Главное окно и окно проводника содержат следующие элементы
управления:</para>
            <itemizedlist>
               <listitem>
                  <para>Дерево каталогов</para>
               </listitem>
               <listitem>
                  <para>Список содержимого папки</para>
               </listitem>
               <listitem>
                  <para>Главное меню</para>
               </listitem>
               <listitem>
                  <para>Контекстное меню (вызывается нажатием) правой кнопки</para>
               </listitem>
               <listitem>
                  <para>Панель управления</para>
               </listitem>
               <listitem>
                  <para>Строка состояния</para>
               </listitem>
            </itemizedlist>
            <para>Дерево каталогов предназначено для отображения структуры папок
и внесение в нее изменений. Находится в левой части окна проводника
и имеет вид дерева.</para>
            <para>Список содержимого папки отображает содержимое папки, выбранной
в дереве каталогов и позволяет изменять его.</para>
         </section>
         <section>
            <title>Главное меню</title>
            <para>
               <command moreinfo="none">Меню Файл</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Сохранить</entry>
                        <entry colname="2">Сохранить изменения в сценарии</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Сохранить все</entry>
                        <entry colname="2">Сохранить все измененные сценарии</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Выход</entry>
                        <entry colname="2">Завершить работу приложения</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Меню Правка</command>
            </para>
            <d:Nest id="vid"/>
            <para>Меню<emphasis>Вид</emphasis>доступно только если активно окно
проводника.</para>
            <para>
               <command moreinfo="none">Меню Вид</command>
            </para>
            <d:Nest id="vid"/>
            <para>
               <command moreinfo="none">Меню Скрипт</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Крупные значки</entry>
                        <entry colname="2">Отображать содержимое в виде крупных значков</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Мелкие значки</entry>
                        <entry colname="2">Отображать содержимое в виде мелких значков</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Список</entry>
                        <entry colname="2">Отображать содержимое в виде списка</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Таблица</entry>
                        <entry colname="2">Отображать содержимое в виде таблицы</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обновить</entry>
                        <entry colname="2">Обновить содержимое</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Меню<emphasis>Скрипт</emphasis>доступно только если активно
окно исполнения и редактирования сценария.</para>
            <para>
               <command moreinfo="none">Меню Окна</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Каскадом</entry>
                        <entry colname="2">Расположить окна каскадом</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Горизонтально</entry>
                        <entry colname="2">Расположить окна горизонтально</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вертикально</entry>
                        <entry colname="2">Расположить окна вертикально</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Проводник</entry>
                        <entry colname="2">Перейти к окну проводника</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">1 – Проверка Трактов.js<footnote>
                              <para>Данный
пункт позволяет перйти к окну сценария Проверка Трактов.js. Если
открыто несколько окон сценариев, то в меню каждому такому окну будет
соответствовать отдельный пункт, позволяюший к нему перейти</para>
                           </footnote>
                        </entry>
                        <entry colname="2">Перейти к окну исполнения сценария</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Меню Справка</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="0">
                        <entry colname="1">Содержание</entry>
                        <entry colname="2">Показать эту справку</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section>
            <title>Контекстное меню проводника</title>
            <para>
               <command moreinfo="none">Контекстное меню проводника</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Выполнить</entry>
                        <entry colname="2">Выполнить выбранный сценарий. Выбор этой операции аналогичен двойному щелчку
по объекту. При этом будет открыто окно исполнения сценария</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Открыть</entry>
                        <entry colname="2">Начать редактировать выбранный сценарий</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вырезать</entry>
                        <entry colname="2">Перемещает выделенные объекты в буфер обмена</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Копировать</entry>
                        <entry colname="2">Копирует выделенные объекты в буфер обмена</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вставить</entry>
                        <entry colname="2">Вставляет содержимое буфера обмена</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">Удаляет выделенные объекты</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Переименовать</entry>
                        <entry colname="2">Переименовать выделенный объект</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать</entry>
                        <entry colname="2">Создать объект</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать -&gt; Папку</entry>
                        <entry colname="2">Создать папку</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать -&gt; VBScript файл</entry>
                        <entry colname="2">Создать сценарий на языке VBScript</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Создать -&gt; JScript файл</entry>
                        <entry colname="2">Создать сценарий на языке JScript</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Создать -&gt; WSF файл</entry>
                        <entry colname="2">Создать Windows Script Host файл</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section>
            <title>Панель управления</title>
            <para>
               <command moreinfo="none">Элементы панели управления</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Кнопка</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic3" width="0.625in" align="aleft"/>
                        </entry>
                        <entry colname="2">Сохранить изменения в сценарии</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic4" width="0.597in" align="aleft"/>
                        </entry>
                        <entry colname="2">Сохранить изменения во всех сценариях</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic5" width="0.528in" align="aleft"/>
                        </entry>
                        <entry colname="2">Переместить выделенное в буфер</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic6" width="0.542in" align="aleft"/>
                        </entry>
                        <entry colname="2">Копировать выделенное в буфер</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic7" width="0.583in" align="aleft"/>
                        </entry>
                        <entry colname="2">Вставить содержимое буфера</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic8" width="0.486in" align="aleft"/>
                        </entry>
                        <entry colname="2">Начать выполнение сценария</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic9" width="0.514in" align="aleft"/>
                        </entry>
                        <entry colname="2">Прервать выполнение сценария</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic10" width="0.597in" align="aleft"/>
                        </entry>
                        <entry colname="2">Подняться на уровень вверх</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">
                           <graphic entityref="graphic11" width="0.500in" align="aleft"/>
                        </entry>
                        <entry colname="2">Обновить содержимое</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section>
            <title>Строка состояния</title>
            <para>Строка состояния состоит из двух областей. В левой части отображается
количество выделенных объектов, в правой – их суммарный размер,
без учета вложенных папок.</para>
            <para>Окно выполнения сценария</para>
            <para>Окно исполнения и редактирования сценария отображает результаты
выполнения сценария, а также позволяет редактировать и отлаживать
код сценария. Состоит из четырех вкладок:</para>
            <para>
               <command moreinfo="none">Вкладки окна выполнения сценария</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Примерный вид окна</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic12" width="7.917in" align="aleft"/>
                        </entry>
                        <entry colname="2">
                           <emphasis>Поле вывода сценария.</emphasis>Отображает результаты совершенной
в процессе выполнения сценария работы. Может отображать как простой текст,
так и HTML, в зависимости от формата вывода заданного сценария. Результаты отображаются
после завершения работы сценария, для отображения промежуточных результатов воспользуйтесь кнопкой<command moreinfo="none">Обновить</command>из панели управления</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic13" width="7.431in" align="aleft"/>
                        </entry>
                        <entry colname="2">
                           <emphasis>Список сообщений лога.</emphasis>Отображает список сообщений, добавленных
в лог сценарием. В случае если в логе нет ни одного сообщения соответствующая вкладка
не видна</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">
                           <graphic entityref="graphic14" width="7.917in" align="aleft"/>
                        </entry>
                        <entry colname="2">
                           <emphasis>Список ошибок времени выполнения.</emphasis>Отображает
список ошибок возникших в процессе выполнения сценария, с указанием места
их возникновения – скрипта, строки и символа. Список виден только
в случае возникновения ошибок, при успешном выполнении сценария список
не выводится</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">
                           <graphic entityref="graphic15" width="7.917in" align="aleft"/>
                        </entry>
                        <entry colname="2">
                           <emphasis>Поле редактирования сценария.</emphasis>Отображает текст сценария
и позволяет его редактировать. По умолчание не показывается. Для того
чтобы показать поле редактирования воспользуйтесь командой<command moreinfo="none">Редактировать</command>меню<emphasis>Скрипт</emphasis>. Сделанные изменения необходимо
отослать на сервер используя команды<command moreinfo="none">Сохранить</command>или<command moreinfo="none">Сохранить все</command>меню<emphasis>Файл</emphasis>
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Передача аргументов в сценарий</para>
            <para>Сценарий может принять произвольное количество аргументов
типа «строка». Аргументы передаются в сценарий одной строчкой в
формате SDF, и автоматически разбиваются на отдельные пары «имя=значение».
Формат SDF предполагает:</para>
            <itemizedlist>
               <listitem>
                  <para>Передаваемая строка имеет вид: Имя1=Значение1,Имя2=Значение1…</para>
               </listitem>
               <listitem>
                  <para>Если в значении аргумента содержатся пробелы или
знак «,», то ВСЯ ПАРА должна быть взята в кавычки: «Имя=значение».</para>
               </listitem>
               <listitem>
                  <para>Если в значении аргумента содержатся кавычки ("),
то ВСЯ ПАРА должна быть взята в кавычки, а внутренний символ " должен
быть продублирован: «Имя=значе""ние».</para>
               </listitem>
            </itemizedlist>
            <para>Визуальная библиотека</para>
            <para>Описание визуальной библиотеки см. в Разделе «<xref linkend="vb" role="Undefined Cross-Reference"/>».</para>
         </section>
      </section>
   </d:InfElement>
</d:DocumentationCore>