<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns="http://docbook.org/ns/docbook" xmlns:d="http://math.spbu.ru/drl">
   <d:InfElement id="rate_CTO" name="Работа в режиме ЦТО">









      <chapter >
         <title id="rvrCTO" xreflabel="Работа в режиме ЦТО">Работа
в режиме ЦТО</title>
         <para>В данном документе описано, как организовать работу РМО в
режиме ЦТО</para>
         <section>
            <title>4.1. Варианты организации ЦТО</title>
            <section>
               <title>4.1.1. Доступ по выделенной линии</title>
               <para>
                  <emphasis>Аппаратные требования</emphasis>
               </para>
               <itemizedlist>
                  <listitem>
                     <para>Наличие выделенных линий (см. «<xref linkend="dedl" role="Undefined Cross-Reference"/>») от обслуживаемых
станций к<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
                  </listitem>
                  <listitem>
                     <para>Модемы с поддержкой работы по выделенным линиям
(например, ZyXEL U-336E Plus) – для каждой станции необходимо 2
модема: один на стороне станции, другой на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
                  </listitem>
                  <listitem>
                     <para>Мультипортовая карта на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>(при необходимости подключения
более 2 станций).</para>
                  </listitem>
                  <listitem>
                     <para>Наличие на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>не менее 512 Мб оперативной
памяти для обслуживания 4 станций, не менее 1024 Мб для обслуживания
8 станций.</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Настройка модемов</emphasis>
               </para>
               <para>Строки инициализации модемов зависят от конкретной модели
модема. В соответствии с руководством пользователя модема необходимо
составить строку инициализации выполняющую следующие настройки:</para>
               <itemizedlist>
                  <listitem>
                     <para>Сбросить настройки в заводскую конфигурацию</para>
                  </listitem>
                  <listitem>
                     <para>Включить режим работы по выделенной линии (см. «<xref linkend="dedl" role="Undefined Cross-Reference"/>»)</para>
                  </listitem>
                  <listitem>
                     <para>Установить один из модемов в режим приема, другой
в режим вызова</para>
                  </listitem>
                  <listitem>
                     <para>Установить скорость работы: V.34 19200</para>
                  </listitem>
                  <listitem>
                     <para>Отключить управление потоком данных DTE/DCE</para>
                  </listitem>
                  <listitem>
                     <para>Выбрать асинхронный режим передачи данных с буферизацией</para>
                  </listitem>
                  <listitem>
                     <para>На вызываемом модеме:</para>
                     <itemizedlist>
                        <listitem>
                           <para>Игнорировать сигнал DTR</para>
                        </listitem>
                        <listitem>
                           <para>Отвечать после первого звонка</para>
                        </listitem>
                     </itemizedlist>
                  </listitem>
                  <listitem>
                     <para>Cохранить настройки в профиле работы по умолчанию</para>
                  </listitem>
               </itemizedlist>
               <para>Для модемов ZyXEL U-336E Plus строки инициализации выглядят
следующим образом:</para>
               <itemizedlist>
                  <listitem>
                     <para>Вызывающий модем: at&amp;f&amp;l1&amp;h0&amp;m0*m0&amp;n66&amp;w0z0</para>
                  </listitem>
                  <listitem>
                     <para>Вызываемый модем: at&amp;f&amp;d0&amp;h0&amp;1&amp;m0*m1s0=1&amp;n66&amp;w0z0</para>
                  </listitem>
               </itemizedlist>
               <para>Вызываемым модемом рекомендуется сделать модем, подключенный
к станции, а вызывающим – подключенный к<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
               <para>Настройка модемов должна быть произведена посредством терминальной
программы, например приложения<emphasis>Гипертерминал (HyperTerminal)</emphasis>,
входящей в состав<xref linkend="ОС1" role="Undefined Cross-Reference"/>Windows.</para>
               <para>
                  <emphasis>Настройка серверных приложений РМО</emphasis>
               </para>
               <para>На<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>необходимо
запустить комплект серверных приложений (Маршрутизатор и серверы) для
каждой обслуживаемой станции (см разделы «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»
и «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»).
Для этого необходимо создать набор файлов настройки Маршрутизатора
– свой файл для каждой станции. Файлы можно называть как угодно.
Рекомендуется разместить их в каталоге<xref linkend="РМО" role="Undefined Cross-Reference"/>и назвать<filename moreinfo="none">routerN.ini</filename>,
где вместо N указать номер обслуживаемой станции.</para>
               <para>В этих файлах должны различаться:</para>
               <itemizedlist>
                  <listitem>
                     <para>
                        <xref linkend="TCPIP" role="Undefined Cross-Reference"/>порт сервера, т.е. значение
параметра port секции [TCP<xref linkend="IP" role="Undefined Cross-Reference"/>]. Рекомендуется использовать порты
по порядку, начиная с 1234</para>
                  </listitem>
                  <listitem>
                     <para>Используемый COM-порт (секция [Channels] и соответствующая
секция с описанием параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»))</para>
                  </listitem>
                  <listitem>
                     <para>Название станции, т.е. значение параметра Название
секции [Station]</para>
                  </listitem>
                  <listitem>
                     <para>Путь к данным станции, т.е. значение параметра Путь_К_Данным
секции [Station]</para>
                  </listitem>
               </itemizedlist>
               <para>В секции параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>») нужно указать только
имя порта (например, COM1) и скорость соединения – 19200. Таким
образом, секция описания параметров COM-порта может выглядеть так:</para>
               <programlisting format="linespecific">[COM1] port=COM1 speed=19200</programlisting>
               <para>Запуск приложения Маршрутизатор необходимо осуществлять с
указанием параметра ini следующим образом:</para>
               <para>Router.exe /ini:routerN.ini</para>
               <para>Вместо routerN.ini нужно подставить имя соответствующего файла
настроек Маршрутизатора.</para>
               <important>
                  <para>
                     <command moreinfo="none">Внимание!</command>Следует обратить внимание
на содержимое файла<filename moreinfo="none">servers\tarif.ini</filename>в катологах
данных обслуживаемых станций перед одновременным запуском нескольких копий
серверов. Необходимо убедиться, что в параметрах секции [Daily]
записаны правильные пути данных. В случае несовпадения указанных
там путей с названием каталога данных нужно заменить файл<filename moreinfo="none">servers\tariff.ini</filename>на
файл из комплекта «для пустых данных» или вручную стереть в нём
всё, кроме секции [Buffer]. Минимальная версия файла tarif.ini состоит
из 2-х строчек:</para>
                  <programlisting format="linespecific">[Buffer] Address=$38150000</programlisting>
               </important>
               <para>В файле конфигурации клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>(<filename moreinfo="none">osmain.ini</filename>)
для соединения с требуемым сервером нужно указать соответствующий
порт<xref linkend="TCPIP" role="Undefined Cross-Reference"/>(параметр
tcpport).</para>
            </section>
            <section>
               <title>4.1.2. Постоянный доступ по коммутируемой линии</title>
               <para>
                  <emphasis>Аппаратные требования</emphasis>
               </para>
               <itemizedlist>
                  <listitem>
                     <para>Модемы – для каждой станции необходимо
2 модема: один на стороне станции, другой на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
                  </listitem>
                  <listitem>
                     <para>Мультипортовая карта на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>(при необходимости подключения
более 2 станций).</para>
                  </listitem>
                  <listitem>
                     <para>Наличие на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>не менее 512 Мб оперативной
памяти для обслуживания 4 станций, не менее 1024 Мб для обслуживания
8 станций.</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Настройка модемов</emphasis>
               </para>
               <para>Строки инициализации модемов зависят от конкретной модели
модема. В соответствии с руководством пользователя модема необходимо
составить строку инициализации, выполняющую следующие настройки:</para>
               <itemizedlist>
                  <listitem>
                     <para>Для модема на стороне станции:</para>
                     <itemizedlist>
                        <listitem>
                           <para>Выключить режим эха</para>
                        </listitem>
                        <listitem>
                           <para>Игнорировать сигнал DTR</para>
                        </listitem>
                        <listitem>
                           <para>Выключить коррекцию ошибок и сжатие данных</para>
                        </listitem>
                        <listitem>
                           <para>Отключить управление потоком данных DTE/DCE</para>
                        </listitem>
                        <listitem>
                           <para>Отключить автоматический ответ модема</para>
                        </listitem>
                        <listitem>
                           <para>Убедиться, что при поступлении на модем звонка,
он выдаёт строчку RING (впрочем, все известные нам модемы не требуют
для этого специальных настроек). Это можно сделать, подключившись
к COM-порту (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»), к которому подключен
модем, программой<emphasis>HyperTerminal</emphasis>и позвонив на
этот модем</para>
                        </listitem>
                        <listitem>
                           <para>Модем не должен периодически выдавать строчку RINGING
в процессе дозвона. Если после подачи команды atd... модем выдаёт
не строчку CONNECT..., то это воспринимется станцией как ошибка
соединения. Чтобы отключить строчку RINGING на модеме ZyXEL U-336E
Plus требуется записать в 6-ой бит регистра 42 единицу при помощи
команды ats42.6=1</para>
                        </listitem>
                     </itemizedlist>
                  </listitem>
                  <listitem>
                     <para>Для модема на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>:</para>
                     <itemizedlist>
                        <listitem>
                           <para>Выдавать строку сообщения о соединения
в виде CONNECT скорость</para>
                        </listitem>
                        <listitem>
                           <para>Включить режим эха</para>
                        </listitem>
                        <listitem>
                           <para>Сигнал CD отслеживает наличие несущей в линии</para>
                        </listitem>
                        <listitem>
                           <para>Выключение сигнала DTR прерывает соединение</para>
                        </listitem>
                        <listitem>
                           <para>Включить выдачу результирующих кодов</para>
                        </listitem>
                        <listitem>
                           <para>Результирующие коды выводить в виде слов</para>
                        </listitem>
                        <listitem>
                           <para>Отключить автоматический ответ модема</para>
                        </listitem>
                     </itemizedlist>
                  </listitem>
               </itemizedlist>
               <para>Для модемов ZyXEL U-336E Plus строки инициализации выглядят
следующим образом:</para>
               <itemizedlist>
                  <listitem>
                     <para>Модем на стороне станции: ate0&amp;d0&amp;k0&amp;h0s0=0s42.6=1</para>
                  </listitem>
                  <listitem>
                     <para>Модем на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>: ats0=0v1&amp;c1&amp;d2e1q0x4</para>
                  </listitem>
               </itemizedlist>
               <para>Строку инициализации модема станции необходимо указать в приложении Конфигуратор
в диалоге Параметры системы.</para>
               <para>Строку инициализации модема ЦТО необходимо занести в параметр
initializationString файла driver.cto (точнее, того файла, в котором
хранится драйвер-скрипт модема).</para>
               <para>
                  <emphasis>Настройка станции</emphasis>
               </para>
               <para>В приложении Конфигуратор в диалоге Станция нужно указать,
что станция обслуживается<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
               <important>
                  <para>Если модуль ЦСЛ30-01 сконфигурирован для работы
с<xref linkend="ЦТО" role="Undefined Cross-Reference"/>,
то прямое включение в него (без модема) невозможно, поскольку<xref linkend="ОС1" role="Undefined Cross-Reference"/>будет
ожидать, что к нему подключается модем, а не<xref linkend="РМО" role="Undefined Cross-Reference"/>. Если с диагностическими
целями требуется подключиться к станции напрямую, то нужно использовать
модуль 20 (правый модуль кассеты) и подключаться клиентским приложением
РМО (см. разд. «<xref linkend="tri_odin_4etn" role="Undefined Cross-Reference"/>»), а не Маршрутизатором.</para>
               </important>
               <para>
                  <emphasis>Настройка серверных приложений РМО</emphasis>
               </para>
               <para>На<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>необходимо
запустить комплект серверных приложений (Маршрутизатор и серверы) для
каждой обслуживаемой станции (см разделы «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»
и «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»).
Для этого необходимо создать набор файлов настройки Маршрутизатора
– свой файл для каждой станции. Файлы можно называть как угодно.
Рекомендуется разместить их в каталоге<xref linkend="РМО" role="Undefined Cross-Reference"/>и назвать<filename moreinfo="none">routerN.ini</filename>,
где вместо N указать номер обслуживаемой станции.</para>
               <para>В этих файлах должны различаться:</para>
               <itemizedlist>
                  <listitem>
                     <para>
                        <xref linkend="TCPIP" role="Undefined Cross-Reference"/>порт сервера, т.е. значение
параметра port секции [TCP<xref linkend="IP" role="Undefined Cross-Reference"/>]. Рекомендуется использовать порты
по порядку, начиная с 1234</para>
                  </listitem>
                  <listitem>
                     <para>Используемый COM-порт (секция [Channels] и соответствующая
секция с описанием параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»))</para>
                  </listitem>
                  <listitem>
                     <para>Название станции, т.е. значение параметра Название
секции [Station]</para>
                  </listitem>
                  <listitem>
                     <para>Путь к данным станции, т.е. значение параметра Путь_К_Данным
секции [Station]</para>
                  </listitem>
               </itemizedlist>
               <para>В секции параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>») нужно указать только
имя порта (например, COM1) и скорость соединения – 19200. Таким
образом, секция описания параметров COM-порта может выглядеть так:</para>
               <programlisting format="linespecific">[COM1] port=COM1 speed=19200 modem=1 modemDriverScript=Driver.cto
modemMainScript=Main.cto phoneNumber=p320004</programlisting>
               <para>Запуск приложения Маршрутизатор необходимо осуществлять с
указанием параметра ini следующим образом:</para>
               <para>Router.exe /ini:routerN.ini</para>
               <para>Вместо routerN.ini нужно подставить имя соответствующего файла
настроек Маршрутизатора.</para>
               <important>
                  <para>
                     <command moreinfo="none">Внимание!</command>Следует обратить внимание
на содержимое файла<filename moreinfo="none">servers\tarif.ini</filename>в катологах
данных обслуживаемых станций перед одновременным запуском нескольких копий
серверов. Необходимо убедиться, что в параметрах секции [Daily]
записаны правильные пути данных. В случае несовпадения указанных
там путей с названием каталога данных нужно заменить файл<filename moreinfo="none">servers\tariff.ini</filename>на
файл из комплекта «для пустых данных» или вручную стереть в нём
всё, кроме секции [Buffer]. Минимальная версия файла tarif.ini состоит
из 2-х строчек:</para>
                  <programlisting format="linespecific">[Buffer] Address=$38150000</programlisting>
               </important>
               <para>В файле конфигурации клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>(<filename moreinfo="none">osmain.ini</filename>)
для соединения с требуемым сервером нужно указать соответствующий
порт<xref linkend="TCPIP" role="Undefined Cross-Reference"/>(параметр
tcpport).</para>
            </section>
            <section>
               <title id="et_odin_tri" xreflabel="4.1.3. Периодический доступ по коммутируемой линии">4.1.3.
Периодический доступ по коммутируемой линии</title>
               <para>
                  <emphasis>Аппаратные требования</emphasis>
               </para>
               <itemizedlist>
                  <listitem>
                     <para>Модемы – для каждой станции необходим
1 модем (на стороне станции), на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>требуется как минимум 2
модема (а рекомендуется иметь 3) вне зависимости от количества обслуживаемых
станций</para>
                  </listitem>
                  <listitem>
                     <para>Наличие на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>2-х (3-х) COM-портов (см.
«<xref linkend="COM-p" role="Undefined Cross-Reference"/>»).
Последнее возможно с использованием мультипортовой платы</para>
                  </listitem>
                  <listitem>
                     <para>Наличие на<xref linkend="ПК" role="Undefined Cross-Reference"/>
                        <xref linkend="ЦТО" role="Undefined Cross-Reference"/>не менее 512 Мб оперативной
памяти</para>
                  </listitem>
               </itemizedlist>
               <para>
                  <emphasis>Настройка модемов</emphasis>
               </para>
               <para>Модем на стороне станции настраивается точно таким же образом,
как в случае постоянного доступа по коммутируемой линии. Кроме того,
требуется составить строку дозвона на модем<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, используемую в случае
возникновения на станции аварийной ситуации.</para>
               <para>Для любых моделей модемов эта строка выглядит следующим образом:
atdНомер, где вместо Номер нужно подставить номер модема<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, используемого
для принятия аварийных вызовов, предваренный префиксом p для импульсного
набора или префиксом t для тонового.</para>
               <para>Строку набора номера аварийного дозвона необходимо указать
в приложении Конфигуратор в диалоге Параметры системы.</para>
               <para>Специальных настроек для модема<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, принимающего аварийные
вызовы, не требуется. Необходимо убедиться, что при поступлении
на модем звонка, он выдаёт строчку RING (впрочем, все известные
нам модемы не требуют для этого специальных настроек). Это можно
сделать, открыв COM-порт (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»), к которому подключен
модем, программой<emphasis>HyperTerminal</emphasis>и позвонив на
этот модем.</para>
               <para>
                  <emphasis>Настройка станции</emphasis>
               </para>
               <para>В приложении Конфигуратор в диалоге Станция нужно указать,
что станция обслуживается<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
               <important>
                  <para>Если модуль ЦСЛ30-01 сконфигурирован для работы
с<xref linkend="ЦТО" role="Undefined Cross-Reference"/>,
то прямое включение в него (без модема) невозможно, поскольку<xref linkend="ОС1" role="Undefined Cross-Reference"/>будет
ожидать, что к нему подключается модем, а не<xref linkend="РМО" role="Undefined Cross-Reference"/>. Если с диагностическими
целями требуется подключиться к станции напрямую, то нужно использовать
модуль 20 (правый модуль кассеты) и подключаться клиентским приложением<xref linkend="РМО" role="Undefined Cross-Reference"/>(см.
разд. «<xref linkend="tri_odin_4etn" role="Undefined Cross-Reference"/>»), а не Маршрутизатором.</para>
               </important>
               <para>
                  <emphasis>Настройка серверных приложений РМО</emphasis>
               </para>
               <para>На<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>необходимо
использовать приложение Маршрутизаторы для осуществления периодического
обзвона обслуживаемых станций и запустить один комплект серверных приложений
(Маршрутизатор и серверы) для принятия аварийных звонков от станций
в специальной конфигурации (см разделы «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>» и «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»).</para>
               <para>Для этого необходимо создать набор файлов настройки Маршрутизатора
– свой файл для каждой станции. Файлы можно называть как угодно.
Рекомендуется разместить их в каталоге<xref linkend="РМО" role="Undefined Cross-Reference"/>и назвать<filename moreinfo="none">routerN.ini</filename>,
где вместо N указать номер обслуживаемой станции.</para>
               <para>В этих файлах должны различаться:</para>
               <itemizedlist>
                  <listitem>
                     <para>
                        <xref linkend="TCPIP" role="Undefined Cross-Reference"/>порт сервера, т.е. значение
параметра port секции [TCP<xref linkend="IP" role="Undefined Cross-Reference"/>]. Рекомендуется использовать порты
по порядку, начиная с 1234</para>
                  </listitem>
                  <listitem>
                     <para>Название станции, т.е. значение параметра Название
секции [Station]</para>
                  </listitem>
                  <listitem>
                     <para>Путь к данным станции, т.е. значение параметра Путь_К_Данным
секции [Station]</para>
                  </listitem>
               </itemizedlist>
               <para>Используемый COM-порт (секция [Channels] и соответствующая
секция с описанием параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»)) для всех станций должен
быть<command moreinfo="none">одинаковый</command>– COM-порт модема, используемого
для периодического обзвона.</para>
               <important>
                  <para>Все остальные COM-порты в этих файлах обязательно
должны быть закомментированы.</para>
               </important>
               <para>В секции параметров COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>») нужно указать только
имя порта (например, COM1) и скорость соединения – 19200), а также
выставить признак доступа по модему и указать имена файлов со скриптами
настройки на модем. Кроме того, необходимо задать телефонный номер
модема обслуживаемой станции, предварив его префиксом p для импульсного
набора или префиксом t для тонового. Таким образом, секция описания параметров
COM-порта (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>») может выглядеть так:</para>
               <programlisting format="linespecific">[COM1] port=COM1 speed=19200 modem=1 modemDriverScript=Driver.cto
modemMainScript=Main.cto phoneNumber=p320004</programlisting>
               <para>Кроме того, нужно создать файл настроек Маршрутизатора для
экземпляра приложения Маршрутизатор (см. разд. «<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»),
осуществляющего прием аварийных вызовов со станций. В нем должен
быть указан собственный номер порта<xref linkend="TCPIP" role="Undefined Cross-Reference"/>и COM-порт модема (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>»), используемого
для аварийного дозвона. Этот файл обязательно должен называться<filename moreinfo="none">waitRouter.ini</filename>.</para>
               <para>Также нужно создать файл настроек приложения Маршрутизаторы
– файл<filename moreinfo="none">routers.ini</filename>. В нем для каждой обслуживаемой
станции нужно создать свою секцию с именем, совпадающим с названием
станции, указанным в диалоге Параметры системы приложения Конфигуратор.
Внутри этой секции нужно указать имя файла настроек Маршрутизатора
и название станции для вывода на экран. Таким образом, секция описания
станции может выглядеть так:</para>
               <programlisting format="linespecific">[STATION_0001] caption=Станция 1 ini=router1.ini
password=</programlisting>
               <para>В секции параметров, общих для всех станций, можно задать
интервал обзвона (время между разрывом предыдущего соединения и
следующим звонком) в миллисекундах. Рекомендуется задавать значения
больше 300000 (30 секунд).</para>
               <programlisting format="linespecific">[params_for_all_staions] interval=300000</programlisting>
               <para>После запуска приложения Маршрутизаторы оно начнет последовательно
через заданный интервал запускать приложение Маршрутизатор с использованием соответствующего
файла настроек Маршрутизатора в режиме выкачки информации. Этот режим
характеризуется во-первых, сокращенным набором серверных приложений,
а во-вторых, тем что после выкачки необходимой информации серверными
приложениями Маршрутизатор автоматически закрывается.</para>
               <para>Запуск приложения Маршрутизатор в режиме принятия аварийных
вызовов осуществляется с помощью приложения Маршрутизаторы, запускаемого
с параметром wait следующим образом:</para>
               <para>Routers.exe /wait</para>
               <para>Для работы с клиентскими приложениями<xref linkend="РМО" role="Undefined Cross-Reference"/>необходимо либо освободить
модем, используемый для периодического обзвона (т.е. закрыть приложение
Маршрутизаторы и дождаться завершения работы приложения Маршрутизатор),
либо использовать дополнительный (третий) модем.</para>
               <para>В файле конфигурации клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>(<filename moreinfo="none">osmain.ini</filename>)
для соединения с требуемым сервером нужно указать соответствующий
порт<xref linkend="TCPIP" role="Undefined Cross-Reference"/>(параметр
tcpport).</para>
            </section>
         </section>
         <section>
            <title>4.2. Мониторинг аварий</title>
            <section>
               <title>4.2.1. Настройка станции</title>
               <para>На станции для контроля состояния помещения используются датчики,
подключенные к контактам порта платы<xref linkend="СК" role="Undefined Cross-Reference"/>2. Для мониторинга аварий,
создаваемых датчиками, нужно сделать требуемые настройки в диалоге<emphasis>Мониторинг</emphasis>приложения<emphasis>Конфигуратор</emphasis>.</para>
               <para>Если требуется, чтобы при возникновении аварий станция звонила
на<xref linkend="ЦТО" role="Undefined Cross-Reference"/>,
то нужно также сделать требуемые настройки в диалоге<emphasis>Транзитные</emphasis>
                  <xref linkend="СЛ" role="Undefined Cross-Reference"/>.</para>
               <para>Пример настроек приведен ниже:</para>
               <para>
                  <command moreinfo="none">Настройки диалога «Мониторинг»</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Авария №</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Описание</entry>
                           <entry colname="2">Авария</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Тип источника</entry>
                           <entry colname="2">Контакт СК</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Контакт СК модуля</entry>
                           <entry colname="2">7</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">№ (контакта)</entry>
                           <entry colname="2">2</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Эталонное значение</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Аварийное</entry>
                           <entry colname="2">включено</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Таймаут</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Преобразование</entry>
                           <entry colname="2">Без изменений</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Состояние получателя</entry>
                           <entry colname="2">0</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Настройки диалога «Транзитные СЛ»</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Тип источника</entry>
                           <entry colname="2">Контакт СК</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Контакт СК модуля</entry>
                           <entry colname="2">7</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">№ (контакта)</entry>
                           <entry colname="2">2</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Получатель</entry>
                           <entry colname="2">ОС</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Таймаут</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Преобразование</entry>
                           <entry colname="2">Без изменений</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Состояние получателя</entry>
                           <entry colname="2">0</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Если требуется, чтобы при рестарте модулей станция звонила
на<xref linkend="ЦТО" role="Undefined Cross-Reference"/>,
то нужно добавить соответствующий транзит:</para>
               <para>
                  <command moreinfo="none">Настройки диалога «Транзитные СЛ»</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Тип источника</entry>
                           <entry colname="2">Рестарт модулей</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Получатель</entry>
                           <entry colname="2">ОС</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Таймаут</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Преобразование</entry>
                           <entry colname="2">Без изменений</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Состояние получателя</entry>
                           <entry colname="2">0</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
            <section>
               <title>4.2.2. Настройка приложений РМО</title>
               <para>Необходимо задать все обслуживаемые станции в файле конфигурации клиента<xref linkend="РМО" role="Undefined Cross-Reference"/>(<filename moreinfo="none">osmain.ini</filename>).
Для каждой станции должен быть указан свой путь к данным и номер
порта<xref linkend="TCPIP" role="Undefined Cross-Reference"/>.</para>
               <para>При использовании периодического доступа к обслуживаемым станциям,
в настройках приложения Монитор (см. разд. «<xref linkend="tri_tri_4et" role="Undefined Cross-Reference"/>»)
нужно включить<emphasis>Режим обзвона</emphasis>в контекстном меню дерева,
изображающего сеть станций.</para>
            </section>
            <section>
               <title>4.2.3. Настройка табло аварийной сигнализации</title>
               <para>«Хозяином» табло аварийной сигнализации необходимо указать
приложение Монитор. В текущей реализации<xref linkend="РМО" role="Undefined Cross-Reference"/>приложение Монитор использует
единую конфигурацию аварий для всех станций (она хранится в файле<filename moreinfo="none">tablo.xml</filename>в
каталоге исполняемых файлов<xref linkend="РМО" role="Undefined Cross-Reference"/>), поэтому численные идентификаторы
аварий (задаваемые в диалоге Мониторинг приложения Конфигуратор)
должны быть уникальными среди всех обслуживаемых станций.</para>
            </section>
         </section>
         <section>
            <title>4.3. Подробнее о настройках модема - общие замечания</title>
            <itemizedlist>
               <listitem>
                  <para>В принципе, наборы команд у разных
модемов не полностью одинаковы (особенно это верно про команды,
начинающиеся с $, #, * и т.д.), поэтому использовать приведённые в
качестве примера к модему Zyxel строчки инициализации можно, но
лишь предварительно проверив с помощью инструкции, что они делает
именно то, что от них ожидается</para>
               </listitem>
               <listitem>
                  <para>Описание команд конкретного модема поставляется
к нему в виде бумажной книжки (редко), на диске с драйверами (чаще),
или его можно найти в инернете (тоже не всегда)</para>
               </listitem>
               <listitem>
                  <para>Чтобы из несколких команд инициализации получить
одну, надо их «склеить» - отбросить префиксы at у всех, кроме первой
и записать в одну строчку (можно через пробелы). То есть последовательности</para>
                  <programlisting format="linespecific">atl2 atm1 at&amp;c1 ats0=0</programlisting>
                  <para>соответствует одна строка atl2 m1 &amp;c1 s0=0. Можно и по-другому:
atl2m1&amp;c1s0=0</para>
               </listitem>
               <listitem>
                  <para>Значение статусного регистра модема устанавливается
командой atsномер регистра=значение, например, ats11=123</para>
               </listitem>
               <listitem>
                  <para>Громкость и продолжительность звучания динамика
управляются, соответственно, командами atl и atm</para>
               </listitem>
            </itemizedlist>
            <para>Кроме того, в случае некачественной связи или некачественного
модема следует обратить внимание на:</para>
            <itemizedlist>
               <listitem>
                  <para>искуственное ограничение скорости
модема</para>
               </listitem>
               <listitem>
                  <para>настройку регистров S7, S9, S10</para>
               </listitem>
            </itemizedlist>
            <para>Первый способ следует использовать если модем изначально соединяется
на чрезмерно высокой скорости, после чего несколько раз снижает
скорость соединения (что выражается в сильных задержках в обмене
данными). Иногда может бросить трубку. Если выполнить при инициализации
команду atm2, то модем не будет выключать динамик и можно будет слышать
всё, что он делает. Если сразу после того, как модем повесил трубку, подсоединиться
к нему терминальной программой, например,<emphasis>HyperTerminal</emphasis>,
и выполнить команду ati11, то он покажет начальную и конечную скорости
соединения, количество пересоединений, и много другой полезной информации.
Искуственное ограничение скорости может осуществляться командой
at&amp;n, возможно и какой-то другой. Лучше уточнять в документации
модема.</para>
            <para>По поводу второго позволю себе привести рекомендации по этому
поводу из текста «РУКОВОДСТВО HАЧИHАЮЩЕГО ПОЛЬЗОВАТЕЛЯ СЕТИ FidoNet»,
Beta Version 4.0, 25.03.92.</para>
            <itemizedlist>
               <listitem>
                  <para>S7 - Ожидание несущей после набора.
Определяет время, в течение которого модем будет ожидать ответа
вызываемой системы. В случае, если Ваш модем плохо определяет сигнал
ЗАHЯТО, следует стремиться задать этому регистру как можно меньшее
значение. Hо здесь следует помнить, что нижняя граница значения
этого регистра должна обеспечивать минимальный промежуток времени
между набором номера и ответом вызываемого модема. (Т.е, к примеру,
если вызываемый модем отвечает только на третий звонок, а Вы установили
значение для S7 4 секунды, то вызываемый модем только успее поднять
трубку, как Ваш уже положит ее). Hо и не следует слишком увлекаться
большими значениями для этого регистра, так как, если Ваш модем
плохо определяет сигнал ЗАHЯТО и Вы, к примеру, установили значение 180,
то модем после набора номера будет ожидать целых 3 минуты, прежде
чем положит трубку! Приемлемыми пределами, как правило, являются:
для внутригородского вызова: 20-40; для междугороднего вызова: 40-70;
для международного вызова: 40-180...</para>
               </listitem>
               <listitem>
                  <para>S9,S10 - Регистры S9 и S10 между собой очень сильно
связаны, поэтому позволю себе привести здесь их более подробное
описание: Регистр S9 задает минимально необходимое время присутствия
на линии несущей удаленного модема для ее опознания вашим модемом.
Типичные установки - от 0.5 до 1.2 секунды. Регистр S10 устанавливает
интервал времени между моментом потери несущей удаленного модема и
моментом разрыва связи вашим модемом. Типичные установки - от 1.0
до 2.5 секунды. (В действительности интервал времени задается не
S10, а разностью (S10 - S9) с типичным значением от 0.5 до 2.0 секунд.
Установка большого значения S10 может привести к «залипанию» модема
на линии после потери связи из-за ошибочного распознавания сигналов
‘занято’ и(или) шумов на линии как несущей удаленного модема. Более
того, как показали эксперименты попытки программного окончания связи
во время такого «залипания» не всегда срабатывают! Это относится
и к командам типа +++ ATH0 и к переключению сигнала DTR. По-видимому,
это связано с логикой работы hayes-совместимых модемов. Hа самом
деле, трудно определить что было причиной завершения связи - попытки
программного окончания или все-таки срабатывание модема по S10.
Очевидно, что «залипание» совершенно неприемлимо для любой автоматической
связи (например, с использованием автоматисеских Почтовых Систем
FIDO). С другой стороны, в телефонных линиях наших стран возможны
исчезновения сигналов на достаточно длительный промежуток времени
(&gt; 2 секунд) с последующим восстановлением связи. Hаблюдение за
сигналом Carrier Detect (CD) после действительной потери соединения
показало, что при больших значениях S10 (8-10 секунд) вероятность
появления CD (из-за ошибочного опознания 'занято' или шумов) длительностью
больше чем S9 весьма высока, после чего модем начинает отсчет по
S10 заново! Таким образом, модем может держать линию весьма и весьма
долгое время.</para>
               </listitem>
            </itemizedlist>
            <para>Вывод – смысл небольшого значения S10 в том, что за небольшой
интервал времени вероятность достаточно долгого (&gt; S9) ошибочного
появления сигнала CD невелика.</para>
            <para>Следствие №1 – для безболезненного увеличения S10 необходимо
уменьшить вероятность ошибочного появления сигнала CD длительностью
более S9.</para>
            <para>Следствие №2 (самое главное) – для этого необходимо увеличить
S9!!!</para>
            <para>Как показали эксперименты, комбинация S9=30 S10=80 работает
хорошо и надежно, в то время как уже S10=40 при S9=10 способна надолго
завесить модем на линии. Можно порекомендовать даже S9=35-40 и S10=100.</para>
         </section>
         <section>
            <title>4.4. Замечания о синтаксисе и семантике скриптового
языка</title>
            <para>Речь пойдёт о языке, на котором написаны файлы типа<filename moreinfo="none">driver.cto</filename>и<filename moreinfo="none">main.cto</filename>(скрипты,
управляющие поведением модема<xref linkend="ЦТО" role="Undefined Cross-Reference"/>).</para>
            <para>Комментарии начинаются символом # и продолжаются до конца
строки. Идентификаторы - состоят из латинских букв и цифр (первый
символ - не цифра). Единственный тип переменных - строка. Переменные
не объявляются, но создаются при первом упоминании (если первое
упоминание - чтение, то это ошибка).</para>
            <para>Пример:</para>
            <programlisting format="linespecific">v1 := "atm1l3"; v2:= "\n${v1}x1\x0d\x0a";</programlisting>
            <para>В результате, v2 будет равно &lt;перевод строки&gt;atm1l3x1&lt;перевод
строки&gt;.</para>
            <para>Строки всегда пишутся в двойных кавычках, вместо ${v1} во
второй строке примера подставится её текст. \n - это тоже самое,
что \x0d\x0a, т.е. символ с шестнадцатеричным кодом 0D, за которым
следует символ с кодом 0A.</para>
            <para>В часности, чтобы присвоить переменной x значение переменной
t надо писать x:="${t}". Более простого способа нет. Чтобы вставить
в строку один из символов: {, }, $, \, ", надо его заэкранировать
символом \, например x := "\$\{foo\}" будет равно ${foo}, а не значению
переменной foo.</para>
            <para>Кроме того, \r - аналог \x0d, \l - \x0a, \t - \x08.</para>
            <para>Если цель читателя - не только послать модему какую-то допольнительную
команду при инициализации или перед набором номера, то дальнейшее
описание ситаксиса и встроенных функций содержится в разделе «4.4.2
Более полное описание синтаксиса и семантики».</para>
            <section>
               <title>4.4.1. Основные параметры, касающиеся настройки
модема</title>
               <para>Основные параметры, касающиеся настройки модема, находятся
в файле<filename moreinfo="none">driver.ctov</filename>(точнее, в файле, указанном
в качестве значения параметра<command moreinfo="none">modemDriverScript</command>в
файле настройки Маршрутизатора):</para>
               <para>
                  <command moreinfo="none">Переменные</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">scriptCR</entry>
                           <entry colname="2">Символ (символ - это строка из одного символа) «Carriage Return», т.е.
тот, которым должна завершаться почти любая команда (кроме +++,
A/, A&gt;), посланная модему</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">scriptLF</entry>
                           <entry colname="2">Символ «Line feed», т.е. тот, которым модем завершает свой
ответ на любую команду</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">initializationString</entry>
                           <entry colname="2">Команда, подаваемая модему при инициализации
после получения ответа на atz. В ответ, если строчка была не пустая, ожидается OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">dialPreInitString</entry>
                           <entry colname="2">Аналог initializationString, но скармливается
модему каждый раз перед попыткой звонить. В ответ, если строчка была
не пустая, ожидается OK</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">waitRingPreInitString</entry>
                           <entry colname="2">Используется аналогично dialPreInitString перед началом ожидания входящего звонка</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Переменные, задающие таймауты (в миллисекундах)</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">longTO</entry>
                           <entry colname="2">Таймаут, используемый при ожидании CONNECT'а после набора номера
или поднятия трубки</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">shrTO</entry>
                           <entry colname="2">(short remote timeout) используется только после соединения при аутентификации
- сколько нужно ждать от другого конца ответа на посланный логин, пароль
или приглашение</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">shlTO</entry>
                           <entry colname="2">(short local timeout) используется в командном режиме при ожидании от
модема ответа на команду</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">atzTO</entry>
                           <entry colname="2">Персональный shlTO для команды atz. Обычно устанавливается
в большее, чем shlTO значение, т. к. многие модемы иницилизируются порядка секунды</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>
                  <command moreinfo="none">Функции</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">reset</entry>
                           <entry colname="2">Выполняет atz и initializaionString</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">dialPreInit</entry>
                           <entry colname="2">Посылает модему строчку dialPreInitString</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">waitRingPreInit</entry>
                           <entry colname="2">Посылает модему строчку waitRingPreInitString</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">disconnect</entry>
                           <entry colname="2">
                              <para>Бросает трубку путём сброса сигнала DTR
и установки его обратно по прошествии shlTO</para>
                              <para>Множество фунций, призванных распознавать конкретный
ответ модема (ok, no_carrier, no_dt, ring, и т.д, кроме parseConnect).
Если ответ модема на какое-либо событие нестандартен, то надо в соответствующей функции заменить строчку внури шаблона (строчки
в обратных кавычках), напечатанную большими буквами, на требуемую. Например, `[\s]\*BUSY[\s]\*`
на `[\s]\*Zanjato[\s]\*`, если вместо BUSY модем склонен возвращать Zanjato. Обычно, все
модемы возвращают именно те строчки, которые уже прописаны в скрипте по умолчанию</para>
                           </entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">parseConnect</entry>
                           <entry colname="2">Призвана выявить, верно ли что её параметр
- это 'CONNECT ...', выудить из этой строки скорость соединения,
протокол защиты от ошибок и сжатия и занести их в глобальные переменные
speed, errorCorr, compr</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Общий вид шаблона для разбора выглядит примерно так:</para>
               <para>[\s]\*CONNECT[\s]\*([.\d\w]\+)[\s]\*([.\d\w]\+)[\s]\*[\.]\*`,</para>
               <para>т.е. строка, которую вернул модем - это пробелы, потом слово
CONNECT, потом пробелы, буквы или цифры, которые заносятся в переменную
m0 (т.к. соответствующая часть шаблона заключена в круглые скобки),
пробелы, буквы или цифры, которые заносятся в переменную m1, снова
пробелы. Дальше в переменных m0, m1, ... оказываются отдельные слова,
которые вернул модем, и, пользуясь инструкцией к нему, можно делать выводы
о параметрах соединения. Конкретный формат строки соединения, выдаваемой модемом,
зависит как от модема, так и от его настроек. Обычно он указывается
в инструкции к модему, в разделе про результирующие коды. Например,
модем zyxel U-336E Plus будет выдавать строчку соединения вида CONNECT
скорость соединения, если при настройке была выполнена команда atx1.
Выделить скорость из такого ответа позволяет выражение `[\s]\*CONNECT[\s]\*([\d\w]\+)[\.]\*`
Соответственно, функция будет такая:</para>
               <para>
                  <command moreinfo="none">function parseConnect</command>
               </para>
               <para>
                  <command moreinfo="none">if `[\s]\*CONNECT[\s]\*([.\d\w]\+)[\.]\*` then begin</command>
               </para>
               <para>
                  <command moreinfo="none">speed:="${m0}"; # запомнили скорость</command>
               </para>
               <para>
                  <command moreinfo="none">errorCorr:="";</command>
               </para>
               <para>
                  <command moreinfo="none">compr:=""; # другие параметры нам неизвестны</command>
               </para>
               <para>
                  <command moreinfo="none">success ""; # переданная строчка действительно является строчкой
CONNECT..., поэтому функция завершается успешно</command>
               </para>
               <para>
                  <command moreinfo="none">end else</command>
               </para>
               <para>
                  <command moreinfo="none">failure ""; # переданная строчка не является строчкой
CONNECT..., поэтому функция завершается неудачей</command>
               </para>
               <para>
                  <command moreinfo="none">endf;</command>
               </para>
               <para>Поскольку большинство модемов в любой конфигурации после слова
CONNECT пишут в первую очередь скорость соединения, и лишь потом
другие параметры, приведённой функции должно быть достаточно для
случая, когда другие параметры соединения не столь интересны.</para>
               <para>Если не важна и информация о скорости, то функцию можно ещё
больше упростить:</para>
               <para>
                  <command moreinfo="none">function parseConnect</command>
               </para>
               <para>
                  <command moreinfo="none">if `[\s]\*CONNECT[\.]\*` then begin</command>
               </para>
               <para>
                  <command moreinfo="none">speed:="";</command>
               </para>
               <para>
                  <command moreinfo="none">errorCorr:="";</command>
               </para>
               <para>
                  <command moreinfo="none">compr:=""; # никакие параметры нам неизвестны</command>
               </para>
               <para>
                  <command moreinfo="none">success ""; # переданная строчка действительно является строчкой
CONNECT..., поэтому функция завершается успешно</command>
               </para>
               <para>
                  <command moreinfo="none">end else</command>
               </para>
               <para>
                  <command moreinfo="none">failure ""; # переданная строчка не является строчкой
CONNECT..., поэтому функция завершается неудачей</command>
               </para>
               <para>
                  <command moreinfo="none">endf;</command>
               </para>
               <para>Lucent Win modem при настройках по умочанию будет выдавать
«CONNECT скорость Слово». Причём слово может принимать следующие
значения:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">V42bis</entry>
                           <entry colname="2">Значит, протокол коррекции ошибок - V.42, сжатия
- V.42bis</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">V42</entry>
                           <entry colname="2">Протокол коррекции ошибок - V.42, сжатие отсутствует</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">MNP5</entry>
                           <entry colname="2">Протокол коррекции ошибок - MNP4, сжатия - MNP5</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">MNP4</entry>
                           <entry colname="2">Протокол коррекции ошибок - MNP4, сжатия отсутствует</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">NoEC</entry>
                           <entry colname="2">Коррекция ошибок и сжатие отсутсвуют</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Функция выделяет это слово и разбирает соответствующие 5 случаев:</para>
               <programlisting format="linespecific">function parseConnect if `[\s]\*CONNECT[\s]\*([\d]\+)[\s]\*([\d\w]\+)[\s]\*[\.]\*`
"${p0}" then begin speed:="${m0}"; if equal "${m1}" "V42bis" then
begin errorCorr:="V.42"; compr:="V.42bis"; end else if equal "${m1}"
"V42" then begin errorCorr:="V.42"; compr:=""; end else if equal
"${m1}" "MNP5" then begin errorCorr:="MNP4"; compr:="MNP5"; end
else if equal "${m1}" "MNP4" then begin errorCorr:="MNP4"; compr:="";
end else if equal "${m1}" "NoEC" then begin errorCorr:=""; compr:="";
end; end else failure ""; endf;</programlisting>
            </section>
            <section>
               <title>4.4.2. Более полное описание синтаксиса и семантики</title>
               <para>Синтаксис</para>
               <programlisting format="linespecific">SCRIPT ::= { FUNCTION-DEFINITION | STATEMENT }+
FUNCTION-DEFINITION::= function FUNCTION-NAME SCRIPT endf STATEMENT::=
STRING | begin STATEMENT end | FUNCTION-NAME {PARAM}* | if STATEMENT
then STATEMENT [else STATEMENT] | repeat COUNT STATEMENT | VARIABLE-NAME
:= STATEMENT | not STATEMENT | STATMENT; STATEMENT | break | continue
| failure PARAM | success PARAM | PATTERN PARAM PARAM::= STATEMENT</programlisting>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">FUNCTION-NAME, VARIABLE-NAME</entry>
                           <entry colname="2">Соответсвующие идентификаторы</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">COUNT</entry>
                           <entry colname="2">Число итераций цикла (т.е. строка, состоящая только
из целого числа) или строка forever.</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">break</entry>
                           <entry colname="2">Оборвать выполнение цикла</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">continue</entry>
                           <entry colname="2">Начать следующую итерацию цикла досрочно</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">PATTERN</entry>
                           <entry colname="2">Это шаблон, похожий на несколько упрощенноё регулярное выражение языка
Perl, позволяющий разбить строку, лежащую в параметре, на куски. По назначению используется
только при извлечении параметров соединения из строки CONNECT ...,
которую возвращает модем</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Шаблон всегда заключается в обратные кавычки (символ `) и
представляет собой строчку из символов и классов символов. Класс
символов - это заключённая в квадратные скобки строка, в которой
перечислены все символы, принадлежащие данному классу. При этом
можно использовать сокращения: \d - все цифры, \w - все большие
и маленькие латинские буквы, \s - символы с шестнадцатеричными кодами
08, 09, 0a, 0d, 20 (пробельные символы). Также в описании шаблона
можно использовать обозначения, аналогичные используемым в обычных
строчках (\n, \l, \r, \t, \x??, \\, \`). После любого символа или
класса символов можно использовать квантификатор \*, \+, \? с естественным смыслом.
Часть шаблона можно заключить в круглые скобки. Тогда, в случае
успешного сопоставления, часть сопоставленной строки, соответствующая
первой паре скобок, будет занесена в глобальную переменную m0, второй
паре - в m1 и т.д. Вложенные скобки использовать запрещено. Смысл
квантификатора, поставленного после скобки не определён. Чтобы вставить
скобку в текст шаблона следует пользоваться последовательностями
\( и \).</para>
               <para>Например, после выполнения следующей программы:</para>
               <programlisting format="linespecific">x:="CONNECT 1234/ARQ 5678/V.42bis"; `[\s]\*CONNECT[\s]\+([\d]\+)/([\w]\+)[\s]\+([\d]\+)/([.\w\d]\+)[\.]\*`
"${x}";</programlisting>
               <para>значения переменных будут такими:</para>
               <programlisting format="linespecific">m0 = "1234" m1 = "ARQ" m2 = "5678" m3 = "V.42bis"</programlisting>
               <para>Любой STATEMENT всегда возвращает значение - пару (boolean,
строка). Строковую часть возвращаемого значения можно использовать
явно - оператор := позволяет присвоить её переменной. Булевскую
часть, которая отражает мнение оператора о том, удачно ли он выполнился,
можно анализировать конструкцией if ... then ... else .... При этом
присваивание возвращает булевскую часть своей правой части, а оператор
not инвертирует её. Составной оператор возвращает значение последнего
опертора, из которого состоит. Выполнение failure t в теле функции
прекращает её выполнение, причём функция возвращает пару (false,
t), т.е., она завершилась неудачно и вернула t. Выполнение success
t возвращает (true, t). Встроенная функция echo пишет свой аргумент
в LOG файл. Пример:</para>
               <programlisting format="linespecific">function alwaysFails failure "Oblom"; endf; if not
result:=alwaysFailures then echo "${result}. It failed again.";</programlisting>
               <para>Этот скрипт напишет в лог следующее:</para>
               <para>
                  <command moreinfo="none">Oblom. It failed again.</command>
               </para>
               <para>При вызове функции, её параметры заносятся в локальные переменные
p0, p1, p2, ... Соответственно, при написании функции, этим можно
пользоваться. Например, следующая функция пишет в лог свой аргумент,
а потом перевод строки:</para>
               <programlisting format="linespecific">function echon echo "${p0}\n" endf;</programlisting>
               <para>
                  <command moreinfo="none">Замечание.</command>В текущей версии переменные scriptCR
и scriptLF используются не так, как описано ниже. Вместо этого они
объединяются в одну переменную Delimiter, которая и посылается в
модем, и ожидается от него.</para>
               <para>Для работы с модемом через COM порт (см. «<xref linkend="COM-p" role="Undefined Cross-Reference"/>») используются следующие
функции:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">
                              <para>Пункт меню</para>
                              <para>Параметр1</para>
                              <para>Параметр2...</para>
                           </entry>
                           <entry colname="2">Описание</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">readCom timeout</entry>
                           <entry colname="2">Читает из порта, пока не истечёт таймаут или
не придёт символ, лежащий в переменной Delimiter. В первом случае завершается
не успешно, во втором успешно</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">waitRing timeout</entry>
                           <entry colname="2">Аналог readCom, но также ждёт прихода от модема сигнала RING,
в последнем случае завершается успешно, возвращая строчку RING</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">writeCom timeout string</entry>
                           <entry colname="2">Пишет в порт строчку string с таймаутом timeout</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">at timeout string</entry>
                           <entry colname="2">Пишет string, завершая её символом Delimiter
(в отличие от writeCom!) с данным таймаутом, потом с таким же таймаутом читает строчку
до Delimiter и возвращает её</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">clrdtr</entry>
                           <entry colname="2">Сбрасывает сигнал DTR</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">setdtr</entry>
                           <entry colname="2">Устанавливает сигнал DTR</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">equal s1 s2</entry>
                           <entry colname="2">Завершается успешно тогда и только тогда, когда строчки
s1 и s2 посимвольно совпадают</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">communicate</entry>
                           <entry colname="2">Передаёт управление драйверу сетевого протокола «IO
Beta». Следует вызывать после установления модемного соединения и аутентификации,
для начала обмена сообщениями</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">connection_state timeout</entry>
                           <entry colname="2">В течение timeout'а ожидает от модема сообщений о соединении/рассоединении/звонке. В
случае звонка возвращает RING, при таймауте - timeout и завершается неуспешно. При получении двух других событий, возвращает пустую строчку
и завершается успешно если пришло событие о соединении, неуспешно, если
о рассоединении. Следует применять для сброса лишних сообщений,
чтобы они не влияли на другие части программы (например, в функции disconnect, вызов connection_state
нужен чтобы сбросить сообщение о рассоединении, иначе при последующем
вызове communicate оно будет понято неверно)</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
            </section>
         </section>
         <section>
            <title>4.5. Установление причин неисправностей</title>
            <para>В данном разделе описаны методики, позволяющие проверить правильность функционирования
компонент системы<xref linkend="ЦТО" role="Undefined Cross-Reference"/>. Их следует применять,
если имеются проблемы с доступом к станциям, обслуживаемым<xref linkend="ЦТО" role="Undefined Cross-Reference"/>. Поскольку
система<xref linkend="ЦТО" role="Undefined Cross-Reference"/>состоит
из нескольких взаимосвязанных компонент (<xref linkend="ПК" role="Undefined Cross-Reference"/>
               <xref linkend="ЦТО" role="Undefined Cross-Reference"/>, модемы, телефонная линия,<xref linkend="ПО" role="Undefined Cross-Reference"/>станции,
оборудование станции), неисправность или неправильная настройка
любой из компонент приводит к неработоспособности всей системы.</para>
            <section>
               <title id="et_5_odin" xreflabel="4.5.1. Проверка соединения между модемами">4.5.1.
Проверка соединения между модемами</title>
               <para>В данном разделе описана методика проверки процесса установки
соединения между модемом<xref linkend="ЦТО" role="Undefined Cross-Reference"/>и модемом станции. Она позволяет
произвести проверку правильности используемых настроек модемов.</para>
               <para>Для осуществления проверки необходимо подключить модем ЦТО
и модем станции к одному<xref linkend="ПК" role="Undefined Cross-Reference"/>(или к двум<xref linkend="ПК" role="Undefined Cross-Reference"/>, стоящим
рядом друг с другом, поскольку будет необходимо оперативно взаимодействовать
попеременно с обоими модемами). Модемы необходимо включить в телефонную
сеть.</para>
               <para>Каждый из COM-портов, к которому присоединен модем, необходимо
открыть приложением<emphasis>Гипертерминал</emphasis>(<emphasis>Hyperterminal</emphasis>).
При открытии портов использовать настройки:</para>
               <para>
                  <command moreinfo="none">Настройки портов</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="3" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <colspec colnum="3" colname="3" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Настройка</entry>
                           <entry colname="2">Модем ЦТО</entry>
                           <entry colname="3">Модем станции</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Скорость</entry>
                           <entry colname="2">19200</entry>
                           <entry colname="3">19200</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Биты данных</entry>
                           <entry colname="2">8</entry>
                           <entry colname="3">8</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Четность</entry>
                           <entry colname="2">Нет</entry>
                           <entry colname="3">Нет</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Стоповые биты</entry>
                           <entry colname="2">1</entry>
                           <entry colname="3">1</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Управление потоком</entry>
                           <entry colname="2">Аппаратное</entry>
                           <entry colname="3">Нет</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Затем необходимо попытаться организовать соединение между
модемами, используя те же самые настройки, которые заданы для модемов
станции и<xref linkend="ЦТО" role="Undefined Cross-Reference"/>в<xref linkend="РМО" role="Undefined Cross-Reference"/>. Для
примера будут взяты настройки, приведенные в данном руководстве
(см. разд. «<xref endterm="et_odin_tri" linkend="et_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Процесс установления соединения представлен в виде таблицы.
В левой части приводятся сообщения, появляющиеся в окне приложения<emphasis>Гипертерминал</emphasis>,
в котором открыт порт модема<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, в правой – порт модема
станции. Если в левой колонке стоит символ<command moreinfo="none">М</command>, то
указанную в правой колонке строку выдает модем, а если символ<command moreinfo="none">К</command>,
то указанную в правой колонке строку нужно ввести с клавиатуры,
а затем нажать клавишу<command moreinfo="none">Enter</command>. Вместо прямого ввода
строчек инициализации с клавиатуры рекомендуется их копирование
из соответствующих файлов инициализации или диалогов и вставка в приложении<emphasis>Гипертерминал</emphasis>с
помощью команды<command moreinfo="none">Правка -&gt; Вставить</command>.</para>
               <para>
                  <command moreinfo="none">Процесс установки соединения между модемами</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Модем ЦТО</entry>
                           <entry colname="2">Модем станции</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">К</command>atz</entry>
                           <entry colname="2">
                              <command moreinfo="none">К</command>atz</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">M</command>OK</entry>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">К</command>ats0=0v1&amp;c1&amp;d2e1q0x4</entry>
                           <entry colname="2">
                              <command moreinfo="none">К</command>ate0&amp;d0&amp;k0&amp;h0s0=0s42.6=1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">M</command>OK</entry>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">K</command>atd&lt;номер модема станции&gt;</entry>
                           <entry colname="2"/>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">M</command>RINGING<footnote>
                                 <para>В
зависимости от модели модема, выдаваемая строка может отличаться
от приведенной или вообще отсутствовать.</para>
                              </footnote>
                           </entry>
                           <entry colname="2">
                              <command moreinfo="none">M</command>RING</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>ata</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">
                              <command moreinfo="none">M</command>CARRIER 19200</entry>
                           <entry colname="2">
                              <command moreinfo="none">M</command>CONNECT 19200/V.34 19200/NONE<footnote>
                                 <para>Строка может отличаться от приведенной, однако в ней точно
должны присутствовать слова CONNECT и 19200.</para>
                              </footnote>
                           </entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">PROTOCOL: NONE</entry>
                           <entry colname="2"/>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">COMPRESSION: NONE</entry>
                           <entry colname="2"/>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">CONNECT 19200</entry>
                           <entry colname="2"/>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>+++</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>ath0</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">
                              <command moreinfo="none">M</command>NO CARRIER</entry>
                           <entry colname="2">
                              <command moreinfo="none">M</command>NO CARRIER</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Если на команды инициализации модем вместо OK отвечает ERROR,
это означает, что в строках инициализации есть ошибки. Следует перепроверить
составленные строки, пользуясь справочником по командам модема.</para>
               <important>
                  <para>
                     <command moreinfo="none">Внимание!</command>При «общении» с модемом
вводимые с клавиатуры символы не всегда отображаются на экране.
Это связано с тем, что в окне приложения<emphasis>Гипертерминал</emphasis>по умолчанию
пишутся только те символы, которые присылает модем. Если у модема
включен режим «эха», то посылаемые ему символы автоматически присылаются
обратно и становятся видимыми в окне приложения<emphasis>Гипертерминал</emphasis>.
В режиме передачи данных (после установления соединения) модем отключает
режим «эха».</para>
                  <para>В приложении Гипертерминал можно включить режим «локального
эха», при котором вводимые с клавиатуры символы тоже попадают в
окно вывода модема. Однако включение режима «локального эха» в<emphasis>Гипертерминале</emphasis>при
работающем режиме «эха» в модеме приведет к тому, что вводимые с
клавиатуры символы будут появляться при вводе команд дважды, например,
так: aattzz</para>
               </important>
            </section>
            <section>
               <title>4.5.2. Проверка правильности конфигурации ЦТО</title>
               <para>В данном разделе описана методика проверки процесса установки
соединения между модемом ЦТО и модемом станции. Она позволяет произвести
проверку правильности задание настроек модема<xref linkend="ЦТО" role="Undefined Cross-Reference"/>в конфигурационных файлах<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
               <para>Для осуществления проверки необходимо произвести конфигурацию<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, т.е.
подключить модем к<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>и настроить файлы конфигурации<xref linkend="ЦТО" role="Undefined Cross-Reference"/>. Затем
к<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>или отдельному<xref linkend="ПК" role="Undefined Cross-Reference"/>необходимо
подключить модем станции. Модемы необходимо включить в телефонную
сеть.</para>
               <para>
                  <xref linkend="COM-p" role="Undefined Cross-Reference"/>,
к которому присоединен модем станции, необходимо открыть приложением<emphasis>Гипертерминал</emphasis>(<emphasis>Hyperterminal</emphasis>).
При открытии порта использовать настройки:</para>
               <para>
                  <command moreinfo="none">Настройки порта</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">Настройка</entry>
                           <entry colname="2">Модем станции</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">Скорость</entry>
                           <entry colname="2">19200</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Биты данных</entry>
                           <entry colname="2">8</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Четность</entry>
                           <entry colname="2">Нет</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Стоповые биты</entry>
                           <entry colname="2">1</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">Управление потоком</entry>
                           <entry colname="2">Нет</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Затем необходимо попытаться организовать соединение между
модемами, используя для модема станции те настройки, которые заданы
для него в приложении<emphasis>Конфигуратор</emphasis>. Для примера
будут взяты настройки, приведенные в данном руководстве (см. разд.
«<xref endterm="et_odin_tri" linkend="et_odin_tri" role="Undefined Cross-Reference"/>»).</para>
               <para>Процесс установления соединения представлен в виде таблицы.
В левой части приводятся действия пользователя на стороне<xref linkend="ЦТО" role="Undefined Cross-Reference"/>, в правой
– сообщения приложения<emphasis>Гипертерминал</emphasis>для модема
станции. Если в левой колонке для модема станции стоит символ<command moreinfo="none">М</command>,
то указанную в правой колонке строку выдает модем, а если символ<command moreinfo="none">К</command>,
то указанную в правой колонке строку нужно ввести с клавиатуры,
а затем нажать клавишу<command moreinfo="none">Enter</command>. Вместо прямого ввода
строчек инициализации с клавиатуры рекомендуется их копирование
из соответствующих файлов инициализации или диалогов и вставка в
приложении<emphasis>Гипертерминал</emphasis>с помощью команды<emphasis>Правка
-&gt; Вставить</emphasis>.</para>
               <para>
                  <command moreinfo="none">Процесс установки соединения между модемами</command>
               </para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <colspec colnum="2" colname="2" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">ЦТО</entry>
                           <entry colname="2">Модем станции</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">К</command>atz</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">К</command>ate0&amp;d0&amp;k0&amp;h0s0=0s42.6=1</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">Запустить приложение<emphasis>Маршрутизаторы</emphasis>(<filename moreinfo="none">routers.exe</filename>) для проверки периодического доступа или приложение<emphasis>Маршрутизатор</emphasis>(<filename moreinfo="none">routers.exe</filename>)
для проверки постоянного доступа</entry>
                           <entry colname="2"/>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>RING</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>ata</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>CONNECT 19200/V.34 19200/NONE</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>+++</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">K</command>ath0</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>OK</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1"/>
                           <entry colname="2">
                              <command moreinfo="none">M</command>NO CARRIER</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Если на команды инициализации модем станции вместо OK отвечает
ERROR, это означает, что в строках инициализации есть ошибки. Следует
перепроверить составленные строки, пользуясь справочником по командам
модема.</para>
               <important>
                  <para>
                     <command moreinfo="none">Внимание!</command>При «общении» с модемом
вводимые с клавиатуры символы не всегда отображаются на экране.
Это связано с тем, что в окне приложения<emphasis>Гипертерминал</emphasis>по умолчанию
пишутся только те символы, которые присылает модем. Если у модема
включен режим «эха», то посылаемые ему символы автоматически присылаются
обратно и становятся видимыми в окне приложения<emphasis>Гипертерминал</emphasis>.
В режиме передачи данных (после установления соединения) модем отключает
режим «эха».</para>
                  <para>В приложении<emphasis>Гипертерминал</emphasis>можно включить
режим «локального эха», при котором вводимые с клавиатуры символы
тоже попадают в окно вывода модема. Однако включение режима «локального
эха» в<emphasis>Гипертерминале</emphasis>при работающем режиме «эха»
в модеме приведет к тому, что вводимые с клавиатуры символы будут
появляться при вводе команд дважды, например, так: aattzz</para>
               </important>
               <para>Если модем<xref linkend="ЦТО" role="Undefined Cross-Reference"/>не пытается «дозвониться»
до станции, то это означает, что заданы неправильные настройки в
файлах конфигурации<xref linkend="ЦТО" role="Undefined Cross-Reference"/>. Следует проверить, что:</para>
               <itemizedlist>
                  <listitem>
                     <para>В файлах конфигурации<filename moreinfo="none">main.cto</filename>и<filename moreinfo="none">driver.cto</filename>заданы
правильные строки инициализации (это можно сделать пользуясь инструкциями
предыдущего раздела – см. описание диалога «<xref endterm="et_5_odin" linkend="et_5_odin" role="Undefined Cross-Reference"/>»).</para>
                  </listitem>
                  <listitem>
                     <para>В файле конфигурации приложения<emphasis>Маршрутизатор</emphasis>
                        <filename moreinfo="none">routerN.ini</filename>(настоящее
имя файла может отличаться) указан неправильный<xref linkend="COM-p" role="Undefined Cross-Reference"/>, или не указано, что следует использовать
доступ по модему.</para>
                  </listitem>
                  <listitem>
                     <para>В файле конфигурации приложения<emphasis>Маршрутизаторы</emphasis>
                        <filename moreinfo="none">routers.ini</filename>неправильно задано
имя файла<filename moreinfo="none">routerN.ini</filename>.</para>
                  </listitem>
               </itemizedlist>
               <para>Если при периодическом обзвоне после набора номера модемом<xref linkend="ЦТО" role="Undefined Cross-Reference"/>он сразу
же кладёт трубку, закрывается приложение<emphasis>Маршрутизаторы</emphasis>и
тут же открывается новое, следует проверить что:</para>
               <itemizedlist>
                  <listitem>
                     <para>В файле конфигурации приложения<emphasis>Маршрутизатор</emphasis>
                        <filename moreinfo="none">routerN.ini</filename>(настоящее
имя файла может отличаться) указан только правильный<xref linkend="COM-p" role="Undefined Cross-Reference"/>, к которому
подсоединён модем, а все остальные закомментированы либо не описаны
вовсе.</para>
                  </listitem>
               </itemizedlist>
            </section>
            <section>
               <title>4.5.3. Проверка работоспособности порта платы СК2</title>
               <para>В данном разделе описана методика проверки работоспособности
порта платы СК2, используемого для подключения датчиков. В случае
неработоспособности этого порта станция не будет реагировать на
изменение состояния датчиков и не будет звонить на<xref linkend="ЦТО" role="Undefined Cross-Reference"/>.</para>
               <para>Для осуществления проверки необходимо установить постоянное
соединение между<xref linkend="ПК" role="Undefined Cross-Reference"/>
                  <xref linkend="ЦТО" role="Undefined Cross-Reference"/>и станцией. Установку соединения
можно произвести, запустив приложение<emphasis>Маршрутизатор</emphasis>.</para>
               <para>Диагностика работоспособности порта платы СК2 производится
с помощью CMM-скрипта<emphasis>Чтение Порта СК</emphasis>, размещенного
в папке<emphasis>Служебные</emphasis>. После запуска скрипт непрерывно
читает состояние порта ADSP-процессора, ответственного за работу
с портом СК и выводит результаты в нижеприведенном виде:</para>
               <informaltable frame="all" colsep="1" rowsep="1">
                  <tgroup cols="1" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                     <colspec colnum="1" colname="1" colwidth="1.000in"/>
                     <thead>
                        <row rowsep="1">
                           <entry colname="1">212A - адрес ADSP куда считывается нужная информация:</entry>
                        </row>
                     </thead>
                     <tbody>
                        <row rowsep="1">
                           <entry colname="1">1| 2| 3| 4| 5| 6| 7| 8|all</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">-| -| -| -| -| -| +| -| BF</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">-| -| -| -| -| -| +| -| BF</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">-| -| -| -| -| -| +| -| BF</entry>
                        </row>
                        <row rowsep="1">
                           <entry colname="1">-| -| -| -| -| -| +| -| BF</entry>
                        </row>
                        <row rowsep="0">
                           <entry colname="1">. . .</entry>
                        </row>
                     </tbody>
                  </tgroup>
               </informaltable>
               <para>Необходимо проверить, что при замыкании/размыкании контактов
на порте платы СК2 изменяется строка вывода скрипта – символы +
меняются на - и наоборот. Следует обратить внимание, что номера,
указанные в заголовке вывода скрипта, не являются номерами контактов
порта.</para>
               <para>Если при замыкании/размыкании контактов изменений в выводе
скрипта не происходит, то, возможно, плата СК2 неисправна.</para>
            </section>
            <section>
               <title>4.5.4. Проверка целостностности настроек ЦТО</title>
               <para>В данном разделе описывается методика проверки того, что настройки
ЦТО, распределённые по системе соответствуют друг другу. Важным
параметром является имя станции. Оно обязательно должно начинаться
с префикса «station_» и упоминается в 2х местах:</para>
               <orderedlist inheritnum="ignore" continuation="restarts">
                  <listitem>
                     <para>Файл routers.ini</para>
                  </listitem>
                  <listitem>
                     <para>Прожиг модуля станции (например, t40.040)</para>
                  </listitem>
               </orderedlist>
               <para>В routers.ini (название секции параметров, заключённое в [])
оно нужно для поиска настроек станции по её имени. Тогда запустится
Маршрутизатор на нужных данных (и нормально подключится к базе данных).
Это имя обязательно должно совпадать с тем, что присылает станция
(которая берёт своё имя из прожига t40.040).</para>
               <para>В прожиге станции t40.040 оно нужно для того, чтобы станция
знала, как себя называть при общении с РМО. Если действовать стандартным
путём сборки и прожига станции, в прожиг попадает имя, указанное
в Конфигураторе, который не позволяет вводить имя, начинающееся
не со «station_».</para>
               <para>Т.о. необходимо обязательное соответствие друг другу этих
параметров. Если в прожиге указано station_000Молотино, то и в routers.ini
должно быть [station_000Молотино].</para>
               <para>Если то, что указано в прожиге, не начинается со «station_»,
не будет устанавливаться соединение между РМО и станцией.</para>
               <para>Если то, что указано в прожиге, не совпадает с тем, что написано
в routers.ini Маршрутизатор не запуститься на нужных данных и не
сможет подключиться к базе данных.</para>
            </section>
         </section>
      </chapter>
   </d:InfElement>
</d:DocumentationCore>