<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
  <d:InfElement id="monitoring" name="Мониторинг">
    <section><title>3.3. Мониторинг</title>
      <d:InfElemRef id="ref_service_panel" infelemid="service_panel"/>
      <d:InfElemRef id="ref_service_map" infelemid="service_map"/>
      <d:InfElemRef id="ref_bussing" infelemid="bussing"/>
      <d:InfElemRef id="ref_join_in_monitoring" infelemid="join_in_monitoring" optional="true"/>
    </section>
  </d:InfElement>
</d:DocumentationCore>