<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="plweb"
    nsURI="http://plweb/2.0" nsPrefix="plweb">
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="docTopic" upperBound="-1"
        eType="#//DocTopic" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetRefElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//SourceRefElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceRefElement" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//TargetRefElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupType">
    <eLiterals name="OR" literal="OR"/>
    <eLiterals name="XOR" value="1" literal="XOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiagramType">
    <eLiterals name="MODEL" literal="MODEL"/>
    <eLiterals name="PRODUCT" value="1" literal="PRODUCT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//TargetRefElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//SourceRefElement #//TargetRefElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//GroupType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//SourceRefElement #//TargetRefElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//SourceRefElement #//TargetRefElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SiteView" eSuperTypes="#//SourceRefElement #//TargetRefElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//SourceRefElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Root"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DiagramType" eType="#//DiagramType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocTopic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="docTopicName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
