<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" filename="Drugie_funkcii_monitoringa.drl">
   <d:InfElement id="join_in_monitoring" name="Другие функции Мониторинга"
                 parenttype="DocumentationCore"
                 filename="Drugie_funkcii_monitoringa.drl">









      <section>
         <title id="tri_tri_4et" xreflabel="3.3.4. Монитор">3.3.4.
Монитор</title>
         <section>
            <title>Обзор</title>
            <para>Приложение Монитор позволяет вести комплексное наблюдение
за состоянием различных элементов нескольких<xref linkend="АТС" role="Undefined Cross-Reference"/>одновременно. При наличии<xref linkend="ТАС" role="Undefined Cross-Reference"/>приложение
может оповещать об авариях визуальной и звуковой сигнализацией.
Ниже приведен список элементов находящихся под наблюдением Монитора:</para>
            <itemizedlist>
               <listitem>
                  <para>Маршрутизатор<xref linkend="РМО" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>Серверы<xref linkend="РМО" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>Модули станции типов:<xref linkend="БАЛ" role="Undefined Cross-Reference"/>и Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>Характеристики внешних цифровых трактов станции:</para>
                  <itemizedlist>
                     <listitem>
                        <para>Отсутствие тракта</para>
                     </listitem>
                     <listitem>
                        <para>Высокий уровень ошибок</para>
                     </listitem>
                     <listitem>
                        <para>Отсутствие кадровой синхронизации</para>
                     </listitem>
                     <listitem>
                        <para>Отсутствие сверхкадровой синхронизации</para>
                     </listitem>
                     <listitem>
                        <para>Авария удаленного конца</para>
                     </listitem>
                     <listitem>
                        <para>Отсутствие сверхцикла на дальнем конце</para>
                     </listitem>
                     <listitem>
                        <para>Проскальзывание</para>
                     </listitem>
                  </itemizedlist>
               </listitem>
               <listitem>
                  <para>Внешние датчики (пожарная, охранная и т.п. сигнализация)</para>
               </listitem>
            </itemizedlist>
            <para>Приложение Монитор (см. разд. «<xref endterm="tri_tri_4et" linkend="tri_tri_4et" role="Undefined Cross-Reference"/>»)
запрашивает информацию о состоянии станции у приложения Серверы
(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»), которое работает на
компьютере непосредственно соединенном со станцией и постоянно сканирует перечисленные
выше элементы станции (см. рисунок). Как правило, приложение Монитор используется
в центре технической эксплуатации<xref linkend="АТС" role="Undefined Cross-Reference"/>, на удаленном от станции<xref linkend="РМО" role="Undefined Cross-Reference"/>, но
не обязательно, т.е. Монитор может работать на одном компьютере
с Серверами, но в этом случае управлять<xref linkend="АТС" role="Undefined Cross-Reference"/>может лишь одно из этих
приложений (см. разд. «<xref endterm="tri_tri_5" linkend="tri_tri_5" role="Undefined Cross-Reference"/>»). Приложение работает
одновременно со всеми имеющимися в файле<filename moreinfo="none">osmain.ini</filename>станциями,
поэтому устанавливать соединение в Панели<xref linkend="РМО" role="Undefined Cross-Reference"/>(см. разд. «<xref linkend="tri_odin_4etn" role="Undefined Cross-Reference"/>») не
требуется.</para>
            <informalfigure float="0">
               <graphic width="9.917in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/MonitorSheme.jpg"/>
            </informalfigure>
            <para>Подключенное к Монитору<xref linkend="АТС" role="Undefined Cross-Reference"/>отображает состояние всей
телефонной сети, объединяя полученную со всех станций информацию.
Например,<xref linkend="ТАС" role="Undefined Cross-Reference"/>1
показывает «Аварию модуля» – индикатор А, а<xref linkend="ТАС" role="Undefined Cross-Reference"/>3 показывает «Аварию тракта»
– индикатор Б, тогда на<xref linkend="ТАС" role="Undefined Cross-Reference"/>4 будут показаны обе аварии
– активны индикаторы А и Б.</para>
         </section>
         <section>
            <title>Главное окно</title>
            <para>Панель монитора состоит из окон:</para>
            <informalfigure float="0">
               <graphic width="10.778in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/monitor.gif"/>
            </informalfigure>
            <para>
               <command moreinfo="none">Окна панели монитора</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Текущие состояния объектов</entry>
                        <entry colname="2">Содержит дерево всех объектов Вся сеть и дерево аварийных объектов Аварии</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Журнал состояний объектов</entry>
                        <entry colname="2">Содержит историю выбранного в дереве объекта. Существует возможность
выбора временного интервала для отображения истории</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Окно содержит панель управления со следующими кнопками:</para>
            <itemizedlist>
               <listitem>
                  <para>Сохранить историю в файл</para>
               </listitem>
               <listitem>
                  <para>Включить/отключить запись истории</para>
               </listitem>
               <listitem>
                  <para>Настроить режим работы с<xref linkend="ТАС" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>Настроить параметры отображения аварий на<xref linkend="ТАС" role="Undefined Cross-Reference"/>
                  </para>
               </listitem>
               <listitem>
                  <para>Отбой аварии</para>
               </listitem>
            </itemizedlist>
         </section>
         <section>
            <title>Аварийная панель</title>
            <para>Запускается настройка аварийной панели (см. разд. «<xref endterm="tri_tri_5" linkend="tri_tri_5" role="Undefined Cross-Reference"/>»).</para>
         </section>
         <section>
            <title>Отбой</title>
            <para>Отбой осуществляется нажатием пункта<emphasis>Отбой</emphasis>во
всплывающем меню.</para>
            <para>Отбой применяется при наличии табло аварийной сигнализации
и приводит к выключению аварийных индикаторов и включению индикатора
нормального состояния.</para>
         </section>
      </section>
      <section>
         <title id="tri_tri_5" xreflabel="3.3.5. Панель аварийной сигнализации">3.3.5.
Панель аварийной сигнализации</title>
         <section>
            <title>Обзор</title>
            <para>Аварийная панель (или табло аварийной) сигнализации это периферийное
устройство, предназначенное для визуальной и звуковой сигнализации
аварийных ситуаций. Табло имеет несколько индикаторов, каждый из
которых соответствует некоторой аварии в зависимости от заданных
пользователем настроек. Существует несколько видов аварийной панели,
которые имеют кроме индикаторов звуковую сирену и набор аварийных
датчиков.</para>
         </section>
         <section>
            <title>Аварии</title>
            <para>Отслеживание аварийных ситуаций выполняется приложениями Серверы
(см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>») и Монитор (см. разд.
«<xref linkend="tri_tri_4" role="Undefined Cross-Reference"/>»),
здесь приведен список сигнализаций, которые могут генерироваться
при работе этих приложений:</para>
            <para>
               <command moreinfo="none">Список сигнализаций</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Авария маршрутизатора</entry>
                        <entry colname="2">Пропала связь с Маршрутизатором (см. разд.
«<xref linkend="tri_odin_odin" role="Undefined Cross-Reference"/>»)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Авария серверов</entry>
                        <entry colname="2">Пропала связь с Серверами (см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Авария модуля</entry>
                        <entry colname="2">Пропала связь с модулем.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Авария тракта</entry>
                        <entry colname="2">Произошел сбой в работе тракта</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Авария датчика</entry>
                        <entry colname="2">Сработал аварийный датчик табло</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Авария датчика консоли</entry>
                        <entry colname="2">На консоль пришло аварийное сообщение</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Авария удаленной сигнализации</entry>
                        <entry colname="2">Показывает состояния охранной сигнализации
на различных удаленных объектах</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Авария маршрутизатора и серверов проверяется только в приложении
Монитор (см. разд. «<xref linkend="tri_tri_4" role="Undefined Cross-Reference"/>»). Сервера работают с одной
станцией, тогда как Монитор сразу с несколькими, поэтому он объединяет
результаты, полученные по всем станциям, например, генерируется авария
модуля, если пропала связь с хотя бы одним модулем<command moreinfo="none">какой-либо</command>станции.</para>
            <para>Сообщения об аварии модуля, тракта и датчиков содержат дополнительную информацию
соответственно название модуля, номер тракта и причина сбоя, название датчика.</para>
            <para>Существует специальный вид сигнализации «Отбой аварии», которая
используется для отображения нормального состояния станции. Как
правило, для этой сигнализации отводиться один из индикаторов табло,
хотя это не обязательное требование. Если произошла авария и загорелся
аварийный индикатор, то оператор может вернуть табло в исходное
состояние выполнив операцию «Отбой аварии» (см. справку по приложениям Сервера
– «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»
и Монитор – «<xref linkend="tri_tri_4" role="Undefined Cross-Reference"/>»), тогда все индикаторы
погаснут и загорится индикатор отбоя, а если индикатор отбоя не
назначен, то табло погаснет полностью.</para>
         </section>
         <section>
            <title>Настройка</title>
            <para>Настройка аварийной сигнализации выполняется с помощью редактора,
который можно вызвать из приложения Серверы (см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>»)
и Монитор (см. разд. «<xref linkend="tri_tri_4" role="Undefined Cross-Reference"/>»), выбрав соответствующий
пункт меню.</para>
            <para>В редакторе в виде таблицы отображен список имеющихся аварий
и их параметры, ниже приведен пример и описание параметров:</para>
            <informalfigure float="0">
               <graphic width="7.778in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/панель-станции-настройка-та.gif"/>
            </informalfigure>
            <para>
               <command moreinfo="none">Описание параметров аварий</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Параметр</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Сигнализация</entry>
                        <entry colname="2">
                           <para>Название аварии, оно же сообщение, которое выдается
в консоли Серверов (см. разд. «<xref linkend="tri_odin_4" role="Undefined Cross-Reference"/>»).</para>
                           <para>Название можно изменять только
для датчиков</para>
                        </entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Включено</entry>
                        <entry colname="2">Значения<command moreinfo="none">Да/Нет</command>означают состояние аварии соответственно включено/выключено.
Если авария выключена, то она не отслеживается и не будет сгенерирована</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Индикатор</entry>
                        <entry colname="2">Номер индикатора на табло, который будет загораться при возникновении
аварии. Значение<command moreinfo="none">Нет</command>означает, что индикатор не
задан</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Звонок</entry>
                        <entry colname="2">Определяет должна ли авария сопровождаться сиреной</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Замкнутый</entry>
                        <entry colname="2">Используется только для датчиков, значение<command moreinfo="none">Да/Нет</command>определяют
тип датчика – соответственно замкнутый/разомкнутый</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Параметры имеющие значение «–» не подлежат изменению и не
влияют на работу аварийной панели.</para>
            <para>Реально данные настройки панели аварийной сигнализации хранятся
в файле<filename moreinfo="none">tablo.xml</filename>. Пытаться изменять этот файл
вручную, а не через редактор ламп, настоятельно<command moreinfo="none">НЕ рекомендуется</command>,
за исключением одного случая – добавления информации об удаленной
аварийной сигнализации. Все записи об авариях удаленной сигнализации
в этом файле должны взаимно однозначно соответствовать записям об авариях
удаленной сигнализации в базе данных<xref linkend="РМО" role="Undefined Cross-Reference"/>. Инструкция по заполнению
базы данных<xref linkend="РМО" role="Undefined Cross-Reference"/>содержится
в справке для базы данных<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
            <para>Запись об удаленной аварии в<xref linkend="XML" role="Undefined Cross-Reference"/>файле выглядит так:</para>
            <programlisting format="linespecific">&lt;Alarm Name="AL_Advanced.2" Enabled="Да" Lamp="0"
Message="" Modify="Нет" Category="Servers" Ring="Нет" Loop="-"/&gt;</programlisting>
            <para>Где единственным элементом, не редактируемым через редактор
ламп является внутреннее имя аварии AL_Advanced.2. Первая часть
имени является общим префиксом для всех аварий удаленной сигнализации.
Индекс, следующий после префикса должен соответствовать идентификатору
аварии в базе данных. При этом стоит обратить внимание на то, что
в графе<emphasis>Сигнализация</emphasis>редактора ламп отображается
не внутренее имя аварии, а строка с описанием аварии, взятая из
соответствующей записи в базе данных<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
            <para>
               <emphasis>Настройка табло аварийной сигнализации</emphasis>
            </para>
            <para>Аварийную панель можно подключать к портам COM1, COM2 и т.д.,
после чего, необходимо указать, к какому именно порту произведено
подключение. Одновременно управлять аварийной сигнализацией может
только одно приложение. Ниже приведено окно настроек, которое позволяет
настроить порт, тип и управляющее приложение для табло.</para>
            <informalfigure float="0">
               <graphic width="4.931in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/панель-станции-табло-настро.gif"/>
            </informalfigure>
            <para>
               <command moreinfo="none">Параметры настройки</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Тип</entry>
                        <entry colname="2">Новое или старое табло</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Владелец</entry>
                        <entry colname="2">Приложение Сервера РМО (см. разд. «<xref linkend="tri_odin_dva" role="Undefined Cross-Reference"/>») или Монитор (см.
разд. «<xref linkend="tri_tri_4" role="Undefined Cross-Reference"/>»)</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Порт</entry>
                        <entry colname="2">Любой из COM портов (см. «COM-порт»), имеющихся
в системе</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
      </section>
      <section>
         <title>3.3.6.
Монитор промлиний</title>
         <section>
            <title>Обзор</title>
            <para>Монитор промлиний предназначен для наблюдения за распределением
нагрузки на промлинии телефонной станции, позволяет отслеживать
состояние отдельных промлиний и каналов. Также приложение предоставляет
оператору возможность блокировки и разблокировки промлиний и каналов.</para>
         </section>
         <section>
            <title>Главное окно</title>
            <para>Главное окно приложения отображает структуру телефонной станции
в виде модулей соединенных трактами, показывает их текущее состояние
и загруженность промлиний. Приложение может отображать одновременно
структуру, содержащую не менее одного и не более четырех главных
модулей. Для выбора отображаемых главных модулей используйте меню<emphasis>Вид
-&gt; Модули</emphasis>.</para>
            <informalfigure float="0">
               <graphic width="10.889in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/PromMonitor_Pich_01.gif"/>
            </informalfigure>
            <para>Состояние элементов станции определятся цветом, ниже приведено
описание цветов и их значение:</para>
            <para>Состояния модулей:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Серый</entry>
                        <entry colname="2">информация о модуле еще не прочитана, это изначальное состояние.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Зеленый</entry>
                        <entry colname="2">модуль активен.</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Красный</entry>
                        <entry colname="2">модуль не ответил на запрос.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Состояния трактов:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Серый</entry>
                        <entry colname="2">нет информации о тракте по одной из причин:<itemizedlist>
                              <listitem>
                                 <para>информация о тракте еще не прочитана, это изначальное состояние;</para>
                              </listitem>
                              <listitem>
                                 <para>один из модулей, с которыми соединён тракт, не отвечает (красный);</para>
                              </listitem>
                              <listitem>
                                 <para>тракт не является промлинией.</para>
                              </listitem>
                           </itemizedlist>
                        </entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Синий, белый и красный цвета</entry>
                        <entry colname="2">в процентном соотношении отображают количество занятых, свободных и заблокированных каналов соответственно.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Направление - совокупность трактов соединяющих два модуля.
На схеме направления показаны в виде прямоугольников, которые соединены
с соседними модулями и объединяют в себе группу трактов. Состояния
направлений:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Серый</entry>
                        <entry colname="2">направление обычных трактов.</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Сиреневый</entry>
                        <entry colname="2">направление виртуальных трактов.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <important>
               <para>Виртуальные тракты соединяют главный модуль (например,
УКС) основной станции и главный модуль (например, УКС) или БАЛД
выноса. В действительности соединение построено таким образом: [ГлавныйМодуль
(например, УКС)(осн. станции)]---[ЦСЛ]---[ЦСЛ]---[ГлавныйМодуль(например,
УКС)/БАЛД(вынос)], где каналы модулей ЦСЛ соединены один в один
без коммутации, поэтому цепочка [ЦСЛ]---[ЦСЛ] не отображается на
схеме.</para>
            </important>
            <para>Изначально все модули и промлинии имеют серый цвет, после
загрузки и анализа данных они отображают действительные состояния.</para>
            <para>Используйте окно "Локальный мониторинг" для наблюдения за
отдельными трактами и каналами.</para>
         </section>
         <section>
            <title>Локальный мониторинг</title>
            <para>Локальный мониторинг позволяет следить за состоянием и распределением
нагрузки между каналами выбранных пользователем трактов.</para>
            <para>Чтобы добавить тракт в окно просмотра дважды щелкните правой
кнопкой мыши на необходимый тракт в главном окне. Повторите это
действие, и тракт будет удален из окна, то же самое действие можно
выполнить в окне "Локального мониторинга". Двойным нажатием на модуль
в главном окне пользователь может добавить сразу все тракты модуля.</para>
            <informalfigure float="0">
               <graphic width="10.944in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/PromMonitor_Pich_02.gif"/>
            </informalfigure>
            <para>Каждый канал может находиться в одном из следующих состояний:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Серый</entry>
                        <entry colname="2">нет информации о тракте по одной из причин:<itemizedlist>
                              <listitem>
                                 <para>информация о канале еще не прочитана, это изначальное состояние;</para>
                              </listitem>
                              <listitem>
                                 <para>один из модулей, с которыми соединён тракт, не отвечает (красный),
в этом случае все каналы будут серого цвета;</para>
                              </listitem>
                              <listitem>
                                 <para>тракт не является промлинией, в этом случае все каналы будут серого цвета;</para>
                              </listitem>
                              <listitem>
                                 <para>0 и 16 каналы являются управляющими</para>
                              </listitem>
                           </itemizedlist>
                        </entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Белый</entry>
                        <entry colname="2">канал свободен</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Синий</entry>
                        <entry colname="2">канал занят</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Красный</entry>
                        <entry colname="2">канал заблокирован</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Используйте кнопку главного меню<command moreinfo="none">Обновить Локально</command>для
обновления содержимого окна.</para>
         </section>
         <section>
            <title>Меню</title>
            <para>
               <emphasis>Меню главного окна :</emphasis>
            </para>
            <para>
               <command moreinfo="none">Главное меню окна «Монитор промлиний»</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню/подменю</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Все модули</entry>
                        <entry colname="2">обновить информацию о всех отображённых в окне «Монитор промлиний»
модулях и о всех отображённых в окне «Локальный мониторинг» промлиниях.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Активные модули</entry>
                        <entry colname="2">обновить информацию о всех активных отображённых
в окне «Монитор промлиний» модулях (зеленого цвета) и о всех отображённых
в окне «Локальный мониторинг» промлиниях.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Таймер -&gt; Стоп</entry>
                        <entry colname="2">остановить обновление и таймер.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Таймер -&gt; Непрерывно</entry>
                        <entry colname="2">обновлять информацию непрерывно.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Таймер -&gt; 0:05</entry>
                        <entry colname="2">обновлять информацию с интервалом 5 секунд.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Таймер -&gt; 0:10</entry>
                        <entry colname="2">обновлять информацию с интервалом 10 секунд.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Таймер -&gt; Другое время</entry>
                        <entry colname="2">обновлять информацию с интервалом указанным пользователем.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Обновить -&gt; Выход</entry>
                        <entry colname="2">закрыть приложение.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вид -&gt; Локальный мониторинг</entry>
                        <entry colname="2">показать окно "Локальный мониторинг".</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вид -&gt; Автомасштабирование</entry>
                        <entry colname="2">если опция включена, то каждый раз при соединении
со станцией будет автоматически выполнено масштабирование окна.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вид -&gt; Масштабировать</entry>
                        <entry colname="2">установить оптимальные размеры и центрировать
окно на экране.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Вид -&gt; Модули</entry>
                        <entry colname="2">выбрать в окне «Модули» главные модули для отображения
в окне «Монитор промлиний». Используйте эту функцию, если структура станции состоит более
чем из четырех главных модулей. Главные модули определяются типом станции. Нажатие кнопки «ОК»
в окне «Модули» приведёт к полному обновлению информации, отображённой
в окнах «Монитор промлиний» и «Локальный мониторинг».</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Справка</entry>
                        <entry colname="2">показать справку по приложению.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <important>
               <para>При обновлении по таймеру используется режим обновления,
применявшийся пользователем в последний раз, иначе будут обновляться
все модули. Например, чтобы непрерывно выполнять локальное обновление
нажмите кнопку<command moreinfo="none">"Обновить локально"</command>в окне "Локальный
мониторинг", а затем<command moreinfo="none">"Таймер -&gt; Непрерывно"</command>.</para>
            </important>
            <para>
               <emphasis>Главное меню окна "Локальный мониторинг":</emphasis>
            </para>
            <para>
               <command moreinfo="none">Главное меню окна «Локальный мониторинг»</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню/подменю</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Обновить локально</entry>
                        <entry colname="2">обновить информацию о всех отображённых в окне "Локальный мониторинг"
трактах и о соответствующих трактах и модулях в окне «Монитор промлиний».</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Таймер</entry>
                        <entry colname="2">см. соответствующий пункт описания меню главного окна</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Удалить всё</entry>
                        <entry colname="2">удалить все тракты</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Всплывающее меню окна "Локальный мониторинг":</emphasis>
            </para>
            <para>
               <command moreinfo="none">Всплывающее меню окна «Локальный мониторинг»</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню/подменю</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">удаляет выбранный тракт</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Удалить всё</entry>
                        <entry colname="2">удаляет все тракты</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Заблокировать № канал (или все каналы)</entry>
                        <entry colname="2">выполняется скрипт для блокировки/разблокировки каналов chlock.js</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Разблокировать № канал (или все каналы)</entry>
                        <entry colname="2">выполняется скрипт для блокировки/разблокировки каналов chlock.js</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <important>
               <para>
                  <command moreinfo="none">Примечение:</command>
               </para>
            </important>
         </section>
      </section>
   </d:InfElement>
</d:DocumentationCore>