<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl">
   <d:InfElement id="permissions" name="Права доступа">









      <section>
         <title id="tri_odin_p9t" xreflabel="3.1.15. Права доступа">3.1.15. Права
доступа</title>
         <section>
            <title>Обзор</title>
            <para>Приложение<emphasis>Права доступа</emphasis>служит для выполнения
следующих функций:</para>
            <itemizedlist>
               <listitem>
                  <para>Создание/изменение списка пользователей
и групп</para>
               </listitem>
               <listitem>
                  <para>Назначение прав пользователям и группам</para>
               </listitem>
            </itemizedlist>
            <para>Приложение представляет собой систему администрирования для
обеспечения безопасности работы с<xref linkend="РМО" role="Undefined Cross-Reference"/>. С помощью него возможно
регестрирование пользователей<xref linkend="РМО" role="Undefined Cross-Reference"/>, создание групп пользователей
с различными правами на выполнение операций в<xref linkend="РМО" role="Undefined Cross-Reference"/>и непосредственно операций
с телефонной станцией.</para>
            <para>
               <emphasis>Пользователи</emphasis>
            </para>
            <para>
               <command moreinfo="none">Набор атрибутов пользователей</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Атрибут</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Имя</entry>
                        <entry colname="2">Имя – логин пользователя используемый для его идентификации</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Полное имя</entry>
                        <entry colname="2">Информация о полном имени данного пользователя (необязательная информация)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Описание</entry>
                        <entry colname="2">Какой-либо комментарий о данном пользователе (необязательная информация)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Домейн</entry>
                        <entry colname="2">Домейн пользователя</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Пароль</entry>
                        <entry colname="2">Пароль пользователя для входа в<xref linkend="РМО" role="Undefined Cross-Reference"/>
                        </entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Группы</emphasis>
            </para>
            <para>Каждая группа содержит список принадлежащих ей пользователей.
Так же для группы характерны ее аттрибуты:</para>
            <para>
               <command moreinfo="none">Набор атрибутов групп пользователей</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Атрибут</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Имя</entry>
                        <entry colname="2">Имя – логин пользователя используемый для его идентификации</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Описание</entry>
                        <entry colname="2">Какой-либо комментарий о данном пользователе (необязательная информация)</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Операции</emphasis>
            </para>
            <para>Для каждого приложения в составе<xref linkend="РМО" role="Undefined Cross-Reference"/>существует набор операций/действий,
которые может выполнить пользователь. Каждая операция содержит список
пользователей и групп, в котором для каждого пользователя (или группы)
прописано право доступа на выполнение данной операции.</para>
         </section>
         <section>
            <title>Главное окно</title>
            <para>Главное окно приложения «Права доступа» выглядит следующим
образом:</para>
            <informalfigure float="0">
               <graphic width="8.181in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-prava.gif"/>
            </informalfigure>
            <para>Рабочая область приложения разделена на 2 части:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Список пользователей</entry>
                        <entry colname="2">Список локальных пользователей на данном компьютере</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Список групп</entry>
                        <entry colname="2">Список групп на данном компьютере</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Главное меню</emphasis>
            </para>
            <para>Меню<emphasis>Пользователи</emphasis>служит для работы со
списком пользователей и групп.</para>
            <para>
               <command moreinfo="none">Меню пользователи</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Новый пользователь</entry>
                        <entry colname="2">Открыть окно<emphasis>Свойства пользователя</emphasis>для создания нового пользователя</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Новая группа</entry>
                        <entry colname="2">Открыть форму для создания новой группы</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">Удалить выделенного пользователя или выделенную
группу</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Изменить имя</entry>
                        <entry colname="2">Открыть форму для изменения имени выделенного пользователя</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Изменить пароль</entry>
                        <entry colname="2">Открыть форму для изменения пароля выделенного пользователя</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Сохранить</entry>
                        <entry colname="2">Сохранить все изменения в<filename moreinfo="none">xml</filename>файл</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Выход</entry>
                        <entry colname="2">Выход из программы</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Примерный вид диалога изменения имени:</para>
            <informalfigure float="0">
               <graphic width="3.375in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-izmenit-imja.gif"/>
            </informalfigure>
            <para>Примерный вид диалога изменения пароля:</para>
            <informalfigure float="0">
               <graphic width="3.792in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-smena-parolja.gif"/>
            </informalfigure>
            <para>Меню<emphasis>Политики</emphasis>служит для работы со списком
прав пользователей и групп а так же для работы со списком доменов.</para>
            <para>
               <command moreinfo="none">Меню Политики</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Права</entry>
                        <entry colname="2">Открыть форму для работы с назначением прав</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Домены</entry>
                        <entry colname="2">Открыть форму для работы со списком доменов</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">История</entry>
                        <entry colname="2">Открыть форму для работы с историей действий оператора</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Меню Справка</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Содержание</entry>
                        <entry colname="2">Открыть содержание справки</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Поиск</entry>
                        <entry colname="2">Открыть окно поиска по справке</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Справка Windows</entry>
                        <entry colname="2">Как пользоваться справкой</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>В окне пользователей доступно контекстное меню, которое можно
вызвать нажатием правой кнопки мыши.</para>
            <para>
               <command moreinfo="none">Пункты контекстного меню</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Удалить</entry>
                        <entry colname="2">Удалить выделенного пользователя или выделенную
группу</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Изменить пароль</entry>
                        <entry colname="2">Открыть форму для изменения пароля выделенного пользователя</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Изменить имя</entry>
                        <entry colname="2">Открыть форму для изменения имени выделенного пользователя</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Свойства</entry>
                        <entry colname="2">Открыть окно<emphasis>Свойства пользователя</emphasis>со свойствами данного пользователя</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
         </section>
         <section>
            <title>Группа</title>
            <para>Окно<emphasis>Свойства группы</emphasis>выглядит следующим
образом:</para>
            <informalfigure float="0">
               <graphic width="5.111in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/свойства-группы-(новая-груп.gif"/>
            </informalfigure>
            <para>Работает в двух режимах:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Создание новой группы</entry>
                        <entry colname="2">Вызывается из меню<emphasis>Пользователи -&gt; Новая группа</emphasis>главного
окна</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Посмотр свойств группы</entry>
                        <entry colname="2">Вызывается при помощи двойного нажатия на выделенную
группу в главном окне</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Создание новой группы</emphasis>
            </para>
            <para>В этом режиме следует поля, идентифицирующие группу. Если
у новой группы будет уникальное имя, то она добавляется к списку
всех групп. Данной группе приводится в соответствие входящие в ее
состав пользователи.</para>
            <para>
               <emphasis>Просмотр свойств группы</emphasis>
            </para>
            <para>В этом режиме администартор может поменять значение поля<emphasis>Комментарий</emphasis>выбранной группы.
Так же оператор может изменить состав принадлежащих ей пользователей.</para>
            <para>
               <emphasis>Редактирование списка входящих пользователей</emphasis>
            </para>
            <para>Пользователей можно удалять, для этого нужно выбрать желаемого
пользователя и нажать кнопку<emphasis>Удалить</emphasis>. Так же
пользователей можно добавлять c помощью кнопки Добавить. При нажатии
вызывается окно<emphasis>Добавление</emphasis>пользователей.</para>
         </section>
         <section>
            <title>Пользователь</title>
            <para>Окно<emphasis>Свойства пользователя</emphasis>выглядит следующим
образом:</para>
            <informalfigure float="0">
               <graphic width="5.347in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-sovjstva-polzovatel.gif"/>
            </informalfigure>
            <para>Работает в двух режимах:</para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="1.000in"/>
                  <colspec colnum="2" colname="2" colwidth="1.000in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Создание нового пользователя</entry>
                        <entry colname="2">Вызывается из меню<emphasis>Пользователи -&gt; Новый пользователь</emphasis>главного окна</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Просмотр свойств пользователя</entry>
                        <entry colname="2">Вызывается из выпадающего меню<emphasis>Свойства</emphasis>главного
окна, или при помощи двойного нажатия на выделенного пользователя
в главном окне</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Создание нового пользователя</emphasis>
            </para>
            <para>В этом режиме следует заполнить все поля, кроме необязательных.
Если у нового пользователя уникальное имя в указанном домене, то
новый пользователь добавляется к списку всех пользователей. Данному
пользователю приводится в соответствие группы, членом которых он
будет являться.</para>
            <para>
               <emphasis>Просмотр свойств пользователя</emphasis>
            </para>
            <para>В этом режиме администартор может поменять значения некоторых
полей выбранного пользователя, таких как<emphasis>Полное имя</emphasis>,<emphasis>Описание</emphasis>и<emphasis>Домен</emphasis>.
Так же оператор может изменить состав групп, соответствующих данному
пользователю.</para>
            <para>
               <emphasis>Добавление пользователей</emphasis>
            </para>
            <para>Окно<emphasis>Добавление пользователей</emphasis>выглядит
следующим образом:</para>
            <informalfigure float="0">
               <graphic width="4.764in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/dobavit-polzovatelja.gif"/>
            </informalfigure>
            <para>В окошке<emphasis>Домен</emphasis>находится выпадающий список
доступных доменов. При выборе определенного домена в окне<emphasis>Пользователи</emphasis>появляется
список пользователей данного домена. Пустое значения домена соответствует
локальному списку пользователей. Чтобы добавить пользователя в список
«добавленных», нужно выбрать его из списка и нажать кнопку<emphasis>Добавить</emphasis>(
Можно выбрать сразу несколько пользователей удерживая кнопку<command moreinfo="none">Ctrl</command>на
клавиатуре). Когда в списке «добавленные» все желаемые пользователи нужно
нажать кнопку<emphasis>ОК</emphasis>
            </para>
            <para>
               <emphasis>Домены</emphasis>
            </para>
            <para>Окно<emphasis>Домены</emphasis>выглядит следующим образом:</para>
            <informalfigure float="0">
               <graphic width="3.944in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-domeny.gif"/>
            </informalfigure>
            <para>Данное окно предназначено для работы со списком доступных
доменов. Домены можно удалять, для этого нужно выбрать желаемый,
нажать правую кнопку мыши и в выпадающем меню выбрать пункт<emphasis>Удалить</emphasis>.
Так можно создавать новые домены c помощью кнопки<emphasis>Добавить</emphasis>.
При нажатии вызывается окно<emphasis>Домен</emphasis>.</para>
            <informalfigure float="0">
               <graphic width="3.375in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-domen-2.gif"/>
            </informalfigure>
            <para>Так же в этом же окне можно изменять пароль уже существующего
домена , для этого нужно выбрать желаемый в окне<emphasis>Домены</emphasis>,
нажать правую кнопку мыши и в выпадающем меню выбрать пункт<emphasis>Изменить
пароль</emphasis>.</para>
            <para>
               <emphasis>Права пользователей</emphasis>
            </para>
            <para>Окно<emphasis>Права пользователей</emphasis>выглядит следующим
образом:</para>
            <informalfigure float="0">
               <graphic width="7.722in" align="aleft"
                        fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/klient-prava-polzovatelej.gif"/>
            </informalfigure>
            <para>В окне<emphasis>Операции</emphasis>дерево приложений и соответствующих
им операций. При выборе какой-либо операции в окне<emphasis>Пользователи</emphasis>высвечивается
список пользователей с правами на данную операцию. Двойным щелчком
мыши можно поменять права. Для назначения прав новым пользователям
нужно нажать кнопку<emphasis>Добавить</emphasis>, при этом откроется окно<emphasis>Добавление
пользователей</emphasis>, в котором можно выбрать желаемых пользователей.</para>
         </section>
      </section>
   </d:InfElement>
</d:DocumentationCore>