<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns="http://docbook.org/ns/docbook" xmlns:d="http://math.spbu.ru/drl">
   <d:InfElement id="bussing" name="Соединительные линии">









      <section >
         <title id="tri_tri_tri" xreflabel="3.3.3. Соединительные линии">3.3.3.
Соединительные линии</title>
         <d:InfElemRef id="ref_review_b" infelemid="review_b"/>
         <d:InfElemRef id="ref_main_window_b" infelemid="main_window_b"/>
         <d:InfElemRef id="ref_state_sections_b" infelemid="state_sections_b"/>
      </section>
   </d:InfElement>
   <d:InfElement id="main_window_b" name="Главное окно">









      <section >
         <title>Главное окно</title>
         <para>Главное окно программы<emphasis>Соединительные линии</emphasis>выглядит
следующим образом:</para>
         <informalfigure float="0">
            <graphic width="10.833in" align="aleft"
                     fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-СЛ.gif"/>
         </informalfigure>
         <para>Слева расположена панель с закладками:</para>
         <para>
            <command moreinfo="none">Закладки</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <thead>
                  <row rowsep="1">
                     <entry colname="1">Закладка</entry>
                     <entry colname="2">Описание</entry>
                  </row>
               </thead>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">
                        <xref linkend="СЛ" role="Undefined Cross-Reference"/>
                     </entry>
                     <entry colname="2">Дерево соединительных линий</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">АБ</entry>
                     <entry colname="2">Список абонентов</entry>
                  </row>
                  <row rowsep="0">
                     <entry colname="1">Индекс</entry>
                     <entry colname="2">Индекс всех трактов, каналов и абонентов</entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <para>Справа расположена панель свойств текущего выбранного объекта.
Она представляет собой список, содержимое которого зависит от текущего
объекта.</para>
         <para>Главное окно программы c активной закладкой<emphasis>Индекс</emphasis>выглядит
следующим образом:</para>
         <informalfigure float="0">
            <graphic width="10.833in" align="aleft"
                     fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-индексы.gif"/>
         </informalfigure>
         <para>Перед списком индекса объектов расположено поле быстрого поиска
объекта.</para>
         <para>Кнопка Состояние тракта открывает панель состояния трактов.</para>
         <para>Кнопка<emphasis>Указать</emphasis>служит для того, чтобы после
выбора объекта в индексе можно было перейти на него в дереве. Например,
найдя канал по конструктивному адресу (см. «<xref linkend="stradd" role="Undefined Cross-Reference"/>») в панели<emphasis>Индекс</emphasis>и
нажав на<emphasis>Указать</emphasis>попадаем в дереве<xref linkend="СЛ" role="Undefined Cross-Reference"/>на этот
канал.</para>
         <para>Кнопка<emphasis>Предыдущий</emphasis>служит для выбора предыдущего
элемента.</para>
         <para>Кнопка<emphasis>Следующий</emphasis>служит для выбора следующего
элемента.</para>
         <para>
            <emphasis>Идентификация<xref linkend="СЛ" role="Undefined Cross-Reference"/>
            </emphasis>
         </para>
         <para>В приложениях<xref linkend="РМО" role="Undefined Cross-Reference"/>используется несколько способов
идентификации соединительных линий:</para>
         <para>
            <command moreinfo="none">Способы идентификации соединительных линий</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">По номеру</entry>
                     <entry colname="2">Номер представляет собой число в десятичной системе счисления; в характеристиках<xref linkend="СЛ" role="Undefined Cross-Reference"/>он отображается
в поле<emphasis>Номер</emphasis>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">По конструктивному адресу</entry>
                     <entry colname="2">
                        <para>Конструктивный адрес (см. «<xref linkend="stradd" role="Undefined Cross-Reference"/>») представляет
собой четыре числа в десятичной с/с, разделенные точками; опционально
он может быть заключен в квадратные скобки; в характеристиках<xref linkend="СЛ" role="Undefined Cross-Reference"/>он отображается
в поле<emphasis>Конструктивный адрес</emphasis>
                        </para>
                        <para>Для цифровых каналов конструктивный
адрес является логическим понятием, поскольку физическую сущность имеет только
сам тракт</para>
                     </entry>
                  </row>
                  <row rowsep="0">
                     <entry colname="1">По адресу включения в коммутационное поле</entry>
                     <entry colname="2">
                        <itemizedlist>
                           <listitem>
                              <para>Для цифровых каналов
это адрес включения в коммутационное поле модуля УКС; представляет собой число в шестнадцатеричной
с/с (номер группового тракта УКС) и число в десятичной с/с (временная позиция), разделенные точкой и заключенные
в круглые скобки</para>
                           </listitem>
                           <listitem>
                              <para>Для аналоговых линий это адрес включения в коммутационное поле модуля<xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д; представляет собой число в шестнадцатеричной
с/с (номер модуля<xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д), число в десятичной с/с (номер тракта в<xref linkend="КП" role="Undefined Cross-Reference"/>
                                 <xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д) и еще одно число в десятичной с/с (временная позиция
в<xref linkend="КП" role="Undefined Cross-Reference"/>
                                 <xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д), разделенные точкой и заключенные
в круглые скобки</para>
                           </listitem>
                        </itemizedlist>
                        <para>В характеристиках<xref linkend="СЛ" role="Undefined Cross-Reference"/>адрес включения в<xref linkend="КП" role="Undefined Cross-Reference"/>отображается
в поле<emphasis>Адрес включения в<xref linkend="КП" role="Undefined Cross-Reference"/>
                           </emphasis>
                        </para>
                     </entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <para>Можно производить поиск<xref linkend="СЛ" role="Undefined Cross-Reference"/>по конструктивному адресу
(см. «<xref linkend="stradd" role="Undefined Cross-Reference"/>»)
и адресу включения в<xref linkend="КП" role="Undefined Cross-Reference"/>. Для этого в левой половине
главного окна приложения на панели закладок нужно выбрать закладку<emphasis>Индекс</emphasis>,
затем в поле ввода начать набирать конструктивный адрес линии или адрес
включения в<xref linkend="КП" role="Undefined Cross-Reference"/>(вместе
со скобками), тогда список автоматически позиционируется на линию
с указанным конструктивным адресом или адресом включения в<xref linkend="КП" role="Undefined Cross-Reference"/>, и справа
можно будет увидеть всю информацию о выбранной линии.</para>
         <d:Nest id="switching_on_trace"/>
      </section>
   </d:InfElement>
   <d:InfElement id="review_b" name="Обзор">









      <section >
         <title>Обзор</title>
         <para>Программа<emphasis>Соединительные линии</emphasis>предназначена
для просмотра конфигурации и состояния внешних соединительных линий
станции.</para>
         <para>С помощью программы Вы можете:</para>
         <itemizedlist>
            <listitem>
               <para>Просматривать информацию о внешних
направлениях, пучках, трактах и каналах станции.</para>
            </listitem>
            <listitem>
               <para>Просматривать динамическое состояние внешних соединительных
линий (каналов) и<xref linkend="СУВ" role="Undefined Cross-Reference"/>.</para>
            </listitem>
            <listitem>
               <para>Производить следующие операции над каналами:</para>
               <itemizedlist>
                  <listitem>
                     <para>блокировать входящую связь</para>
                  </listitem>
                  <listitem>
                     <para>блокировать исходящую связь</para>
                  </listitem>
                  <listitem>
                     <para>производить сброс состояния</para>
                  </listitem>
                  <d:Nest id="occupy_channel_ftesting"/>
                  <listitem>
                     <para>и др.</para>
                  </listitem>
               </itemizedlist>
            </listitem>
         </itemizedlist>
      </section>
   </d:InfElement>
   <d:InfElement id="state_sections_b" name="Панель состояния трактов">









      <section >
         <title>Панель состояния трактов</title>
         <para>
            <emphasis>Обзор</emphasis>
         </para>
         <para>Приложение<emphasis>Состояние трактов/канальных групп</emphasis>предназначено
для отображения состояния<xref linkend="СЛ" role="Undefined Cross-Reference"/>станции и управления ими.</para>
         <para>С помощью программы вы можете:</para>
         <itemizedlist>
            <listitem>
               <para>просматривать текущее состояние различных
параметров каждой<xref linkend="СЛ" role="Undefined Cross-Reference"/>(зависит от сигнализации)</para>
            </listitem>
            <listitem>
               <para>просматривать текущее состояние различных параметров
трактов (зависит от сигнализации)</para>
            </listitem>
            <listitem>
               <para>выполнять различные команды над трактами, отдельными<xref linkend="СЛ" role="Undefined Cross-Reference"/>и группами<xref linkend="СЛ" role="Undefined Cross-Reference"/>(зависит
от сигнализации)</para>
            </listitem>
         </itemizedlist>
         <para>
            <emphasis>Главное окно</emphasis>
         </para>
         <para>Главное окно приложения выглядит следующим образом:</para>
         <informalfigure float="0">
            <graphic width="10.833in" align="aleft"
                     fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-состояние-трактов.gif"/>
         </informalfigure>
         <para>Окно разделено на три части:</para>
         <itemizedlist>
            <listitem>
               <para>выбор тракта</para>
            </listitem>
            <listitem>
               <para>состояние тракта (динамическая информация)</para>
            </listitem>
            <listitem>
               <para>состояние каналов тракта (динамическая информация)</para>
            </listitem>
         </itemizedlist>
         <para>В окне выбора тракта также отображается информация о текущем
захваченном для прозвонки канале. У тракта, в котором есть захваченный
канал, в графе<emphasis>Захвачен канал</emphasis>будет написан номер<xref linkend="ВК" role="Undefined Cross-Reference"/>и линейный
номер захваченного канала.</para>
         <para>Главное меню содержит следующие команды:</para>
         <para>
            <command moreinfo="none">Команды главного меню</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <thead>
                  <row rowsep="1">
                     <entry colname="1">Элемент меню/подменю</entry>
                     <entry colname="2">Описание</entry>
                  </row>
               </thead>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">Обновить</entry>
                     <entry colname="2">Обновить динамическую информацию</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Правка -&gt; Выделить все каналы</entry>
                     <entry colname="2">Для всех каналов в текущем открытом списке каналов тракта выполнить операцию выделения</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Настройки -&gt; Обновлять при переходе на тракт</entry>
                     <entry colname="2">Если этот пункт меню включен, то при выборе тракта
в списке трактов после перехода на него автоматически выполняется команда<emphasis>Обновить</emphasis>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Настройки -&gt; Показывать внутренние состояния</entry>
                     <entry colname="2">При отображении состояний объектов использовать внутренние имена состояний, понятные только
их разработчикам</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Настройки -&gt; Показывать полные значения полей
In/Out</entry>
                     <entry colname="2">Отображать значения<xref linkend="СУВ" role="Undefined Cross-Reference"/>, прочитанных из сканеров, целиком. По умолчанию отображаются
только биты<xref linkend="СК" role="Undefined Cross-Reference"/>(один бит,
два бита, либо байт, в зависимости от сигнализации)</entry>
                  </row>
                  <row rowsep="0">
                     <entry colname="1">Справка</entry>
                     <entry colname="2">Показать справку</entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <para>Установка автоматического обновления имитирует периодическое
выполнение команды Обновить для данного тракта. Не следует ей злоупотреблять,
так как она нагружает каналы обмена служебной информацией внутри
станции и канал обмена между станцией и<xref linkend="РМО" role="Undefined Cross-Reference"/>.</para>
         <para>
            <emphasis>Выполнение операций над трактами и каналами</emphasis>
         </para>
         <para>Для выполнения операций над трактом, нужно перейти на него
(выбрать в верхней части окна), затем подвести мышь к его состоянию
(средней части окна) и нажать правую кнопку. Если над трактом можно
производить какие-либо операции, то появится контекстное меню со
списком этих операций:</para>
         <informalfigure float="0">
            <graphic width="4.792in" align="aleft"
                     fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-действия-над-трактами.gif"/>
         </informalfigure>
         <para>Для выполнения операций над каналом или несколькими каналами
нужно нажать правую кнопку мыши над требуемым каналом. Можно выбирать
сразу несколько каналов для выполнения операций над ними. Выбор
каналов производится мышью с нажатыми клавишами<command moreinfo="none">Ctrl</command>(для
выбора одиночных каналов) или<command moreinfo="none">Shift</command>(для выбора
диапазона каналов). Ниже представлен пример такого выбора:</para>
         <informalfigure float="0">
            <graphic width="10.722in" align="aleft"
                     fileref="file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-операции-над-каналами.gif"/>
         </informalfigure>
         <para>Следует обратить внимание на то, что часть команд над каналами
воздействует только на один канал (самый первый из выбранных). Эта
особенность команды специально отмечается в документации по ней.</para>
         <d:Nest id="attention_operation"/>
         <para>
            <emphasis>Информация о тракте</emphasis>
         </para>
         <para>
            <command moreinfo="none">Список всех возможных типов статической информации
о тракте</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <row rowsep="0">
                     <entry colname="1">Лин. #</entry>
                     <entry colname="2">Линейный номер тракта</entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <d:Nest id="mov_info_section"/>
         <d:Nest id="operation_on_sections"/>
         <para>
            <emphasis>Информация о канале</emphasis>
         </para>
         <para>
            <command moreinfo="none">Список всех возможных типов статической информации
о канале</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">Лин. #</entry>
                     <entry colname="2">Линейный номер канала</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">
                        <xref linkend="ВК" role="Undefined Cross-Reference"/>
                     </entry>
                     <entry colname="2">Временная позиция канала</entry>
                  </row>
                  <row rowsep="0">
                     <entry colname="1">Тип</entry>
                     <entry colname="2">Направленность канала – описана в таблице «Виды направленности канала»</entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <para>
            <command moreinfo="none">Виды направленности канала</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">
                        <xref linkend="ВК" role="Undefined Cross-Reference"/>
                     </entry>
                     <entry colname="2">Входящий</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ИК</entry>
                     <entry colname="2">Исходящий</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ДК</entry>
                     <entry colname="2">Двунаправленный</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">СЛМ</entry>
                     <entry colname="2">Входящий<xref linkend="МГ" role="Undefined Cross-Reference"/>
                     </entry>
                  </row>
                  <row rowsep="0">
                     <entry colname="1">ЗСЛ</entry>
                     <entry colname="2">Исходящий<xref linkend="МГ" role="Undefined Cross-Reference"/>
                     </entry>
                  </row>
               </tbody>
            </tgroup>
         </informaltable>
         <para>
            <command moreinfo="none">Список всех возможных типов динамической информации
о канале</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <FakeRow>
                     <FakeEntry>
                        <d:Nest id="mov_info_restart"/>
                     </FakeEntry>
                     <entry colname="2"/>
                  </FakeRow>
                  <row rowsep="1">
                     <entry colname="1">In, Out</entry>
                     <entry colname="2">Состояния<xref linkend="СУВ" role="Undefined Cross-Reference"/>. Для<xref linkend="BCKu" role="Undefined Cross-Reference"/>показываются значения 2СК
1СК, для<xref linkend="BCK1" role="Undefined Cross-Reference"/>–
1СК, для трехпроводной (см. «<xref linkend="wire" role="Undefined Cross-Reference"/>») и шлейфной (см. «<xref linkend="loops" role="Undefined Cross-Reference"/>») – байты</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">АппБлк</entry>
                     <entry colname="2">Аппаратная блокировка</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ИсхБлк</entry>
                     <entry colname="2">Блокировка исходящей связи (с внешней стороны)</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ВхБлк</entry>
                     <entry colname="2">Блокировка входящей связи</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">АдмИсхБлк</entry>
                     <entry colname="2">Административная блокировка исходящей связи
(с нашей стороны)</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Сост. ЗО<xref linkend="ВС" role="Undefined Cross-Reference"/>л</entry>
                     <entry colname="2">Состояние объекта ЗОВСл</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Сост. сигнализации</entry>
                     <entry colname="2">Состояние объекта сигнализации</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ТЗСл</entry>
                     <entry colname="2">Флаг трассировки объекта ЗОВСл</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">ТСгн</entry>
                     <entry colname="2">Флаг трассировки объекта сигнализации</entry>
                  </row>
                  <FakeRow>
                     <FakeEntry>
                        <d:Nest id="mov_info_flag"/>
                     </FakeEntry>
                     <entry colname="2"/>
                  </FakeRow>
               </tbody>
            </tgroup>
         </informaltable>
         <para>
            <emphasis>Операции над каналами</emphasis>
         </para>
         <para>
            <command moreinfo="none">Список всех возможных операций над каналами</command>
         </para>
         <informaltable frame="all" colsep="1" rowsep="1">
            <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
               <colspec colnum="1" colname="1" colwidth="1.000in"/>
               <colspec colnum="2" colname="2" colwidth="1.000in"/>
               <tbody>
                  <row rowsep="1">
                     <entry colname="1">Блокировать входящую связь</entry>
                     <entry colname="2">Для всех выделенных каналов, предоставляющих такую возможность</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Разблокировать входящую связь</entry>
                     <entry colname="2">Для всех выделенных каналов, предоставляющих такую возможность</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Блокировать исходящую связь</entry>
                     <entry colname="2">Для всех выделенных каналов, предоставляющих такую возможность</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Разблокировать исходящую связь</entry>
                     <entry colname="2">Для всех выделенных каналов, предоставляющих такую возможность</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Сбросить канал(ы)</entry>
                     <entry colname="2">Послать команду сброс для всех выделенных каналов<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Захватить канал</entry>
                     <entry colname="2">Захватить канал для прозвонки. После захвата канала
и установки у одного из абонентов станции класса обслуживания 2 выход
на внешние направления с этого абонента будет осуществляться только через
этот канал. Внимание! если после того, как канал был захвачен, произошел рестарт одного
или нескольких модулей, участвующих в управлении или распределении
канала (модули Ц<xref linkend="СЛ" role="Undefined Cross-Reference"/>, УКС,<xref linkend="БАЛ" role="Undefined Cross-Reference"/>Д<xref linkend="СЛ" role="Undefined Cross-Reference"/>), то захват следует либо отменить, либо повторить. Для повтора захвата нужно повторно выполнить эту
же команду<d:Nest id="where_use"/>.</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Снять захват</entry>
                     <entry colname="2">Отменить действие предыдущей команды. На абонентов эта команда
не воздействует<d:Nest id="where_use"/>.</entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Включить трассу объекта(ов) ЗОВСл</entry>
                     <entry colname="2">Для всех выделенных каналов<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Выключить трассу объекта(ов) ЗОВСл</entry>
                     <entry colname="2">Для всех выделенных каналов<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Включить трассу объекта(ов) сигнализации</entry>
                     <entry colname="2">Для всех выделенных каналов<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Выключить трассу объекта(ов) сигнализации</entry>
                     <entry colname="2">Для всех выделенных каналов<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <row rowsep="1">
                     <entry colname="1">Пройти по шнуру</entry>
                     <entry colname="2">Вызвать панель прохода по шнуру для канала<d:Nest id="where_use"/>
                     </entry>
                  </row>
                  <FakeRow>
                     <FakeEntry>
                        <d:Nest id="operation_channel_15"/>
                     </FakeEntry>
                     <entry colname="2"/>
                  </FakeRow>
               </tbody>
            </tgroup>
         </informaltable>
      </section>
   </d:InfElement>
</d:DocumentationCore>