<?xml version="1.0" encoding="UTF-8"?>
<d:ProductDocumentation xmlns:d="http://math.spbu.ru/drl" productid="based"
                        filename="UserManual_based.drl">
   <d:FinalInfProduct id="UserManual_based" infproductid="UserManual">
      <d:Adapter infelemrefid="ref_state_sections_b">
         <d:Insert-After nestid="where_use">
            <para xmlns="http://docbook.org/ns/docbook">(используется для отладки
на предприятии-изготовителе)</para>
         </d:Insert-After>
      </d:Adapter>
      <d:Adapter infelemrefid="ref_main_window_sm">
         <d:Insert-After nestid="soboj"/>
         <d:Insert-After nestid="sooner"/>
      </d:Adapter>
      <d:Adapter infelemrefid="ref_sentence_443_sm"/>
      <d:Adapter infelemrefid="ref_renewal_443_sm"/>
      <d:Adapter infelemrefid="ref_identif_443_sm"/>
   </d:FinalInfProduct>
   <d:Dictionary id="main" name="main_dictionary">
      <d:Entry id="productname">РМО П-443</d:Entry>
   </d:Dictionary>
</d:ProductDocumentation>