<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" filename="Модули_станции.drl">
   <d:InfElement id="station_modules" name="Модули станции">









      <section>
         <title>3.2.1. Модули станции</title>
         <section>
            <title>Главное окно</title>
            <informalfigure float="0">
               <graphic entityref="graphic1" width="10.083in" align="aleft"/>
            </informalfigure>
            <para>Программа управления модулями предназначена для отображения
состояния всех модулей станции и предоставляет возможность программно
рестартовать модули, а также загружать программы и данные в микросхемы
флэш-памяти модулей.</para>
            <para>Главное окно состоит из трех списков.</para>
            <para>
               <emphasis>Список модулей станции</emphasis>
            </para>
            <para>Список модулей станции расположен в левой части окна. Для
неработающих модулей в правом столбце будет отображен прочерк «-».
Нажав на модуле из списка правую кнопку мыши появляется всплывающее
меню списка модулей, которое предоставляет оператору возможность
рестартовать соответствующий модуль или загрузить новую программу
во флэш.</para>
            <para>Список содержит следующую информацию по каждому модулю:</para>
            <para>
               <command moreinfo="none">Информация о модулях</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Имя модуля</entry>
                        <entry colname="2">Символьное имя модуля в соответствии с<xref linkend="БД" role="Undefined Cross-Reference"/>
                           <xref linkend="РМО" role="Undefined Cross-Reference"/>
                        </entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Адрес</entry>
                        <entry colname="2">Числовой идентификатор модуля</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">@</entry>
                        <entry colname="2">Состояние модуля. Может быть «-» либо «+» в зависимости
от наличия связи с модулем</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Список файлов для выбранного модуля</emphasis>
            </para>
            <para>Список файлов для выбранного модуля находится в правой части
окна, сверху. Нажав на файле из списка правую кнопку мыши появляется
всплывающее меню списка файлов, в котором есть команды для скачивания
файлов и конфигов из станции.</para>
            <para>Список содержит следующую информацию по каждому файлу:</para>
            <para>
               <command moreinfo="none">Информация о файлах</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Имя</entry>
                        <entry colname="2">Двухсимвольное внутристанционное имя файла</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Состояние</entry>
                        <entry colname="2">Отражает состояние файла. Возможные состояния описаны
в таблице « Возможные состояния файлов модулей»</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Адрес</entry>
                        <entry colname="2">Адрес в памяти модуля, где расположен данный файл</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Длина</entry>
                        <entry colname="2">Длина файла в памяти модуля</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Файл</entry>
                        <entry colname="2">Файл на диске, с которым происходит сравнение</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Возможные состояния файлов модулей</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Модуль физически поврежден</entry>
                        <entry colname="2">Файл, хранящийся в микросхеме FLASH, был поврежден. Необходима перепрошивка
FLASH и, возможно, замена микросхемы</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Файл не найден</entry>
                        <entry colname="2">На диске в указанном месте файл отсутствует, программа не
может выполнить сравнение версий. Чтобы это сообщение не появлялось,
поместите соответствующий файл в указанную директорию</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Несоответствие версий</entry>
                        <entry colname="2">Файл на диске не соответствует файлу в станции</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Соответствие версий</entry>
                        <entry colname="2">Файл на диске соответствует файлу в станции</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Список задач</emphasis>
            </para>
            <para>Список задач расположен в правой части окна, снизу. Для работы
с этим списком предназначено меню списка задач</para>
            <para>Список задач содержит следующую информацию по каждой задаче:</para>
            <para>
               <command moreinfo="none">Информация о задачах</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Название задачи</entry>
                        <entry colname="2">Текстовое описание класса задачи (например: выкачка модуля, прошивка…)</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Описание задачи</entry>
                        <entry colname="2">Более подробное описание задачи (например: выкачка файла 20.prg
из модуля 20).</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Состояние задачи</entry>
                        <entry colname="2">Индикация (в %) выполнения задачи либо индикация ошибочной ситуации.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>Далее приведено описание контекстных меню.</para>
            <para>
               <command moreinfo="none">Всплывающее меню списка модулей</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Рестарт модуля</entry>
                        <entry colname="2">Программный рестарт модуля. Для модулей УКС выполняется
рестарт активного УУС, при этом не происходит обновления информации
с дискеты. Для обновления памяти с дискеты требуется «холодный»
рестарт кнопкой на лицевой панели.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Загрузка программного модуля</entry>
                        <entry colname="2">Позволяет загрузить файл в свободную оперативную
память модуля. При выборе данного пункта появляется диалог, запрашивающий параметры загрузки.</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обновить</entry>
                        <entry colname="2">Обновление информации в списке.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Всплывающее меню списка файлов</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Скачать модуль</entry>
                        <entry colname="2">Выкачать файл из станции и сохранить его на диске.
При выполнении команды на экране появляется диалог сохранения файла.</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Скачать конфиг (см. «<xref linkend="config" role="Undefined Cross-Reference"/>»)</entry>
                        <entry colname="2">Для модулей c микросхемой FLASH когфигурационный файл модуля
не отображается в списке модулей. Для его выкачки служит эта команда,
в остальном аналогичная команде<emphasis>Скачать модуль</emphasis>.</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Обновить</entry>
                        <entry colname="2">Обновление информации в списке.</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <command moreinfo="none">Примечание:</command>если выкачанный конфигурационный
файл имеет нулевой размер, произведите рестарт модуля и повторите
выкачку.</para>
            <para>
               <command moreinfo="none">Всплывающее меню списка файлов</command>
            </para>
            <informaltable frame="all" colsep="1" rowsep="1">
               <tgroup cols="2" tgroupstyle="Format A" colsep="1" rowsep="1" align="left">
                  <colspec colnum="1" colname="1" colwidth="0.984in"/>
                  <colspec colnum="2" colname="2" colwidth="0.984in"/>
                  <thead>
                     <row rowsep="1">
                        <entry colname="1">Элемент меню</entry>
                        <entry colname="2">Описание</entry>
                     </row>
                  </thead>
                  <tbody>
                     <row rowsep="1">
                        <entry colname="1">Закрыть нерабочие</entry>
                        <entry colname="2">Закрыть задачи со статусом «Завершено»</entry>
                     </row>
                     <row rowsep="1">
                        <entry colname="1">Завершить</entry>
                        <entry colname="2">Прервать выполнение выделенной задачи</entry>
                     </row>
                     <row rowsep="0">
                        <entry colname="1">Остальные пункты</entry>
                        <entry colname="2">Управляют форматом отображения информации в
списке</entry>
                     </row>
                  </tbody>
               </tgroup>
            </informaltable>
            <para>
               <emphasis>Стандартные задачи</emphasis>
            </para>
            <para>
               <command moreinfo="none">Задача 1. Скачать конфиг или модуль</command>
            </para>
            <itemizedlist>
               <listitem>
                  <para>
                     <emphasis>Шаг 5a)</emphasis>Выбрать
из списка, расположенного в левой части окна, нужный модуль</para>
               </listitem>
               <listitem>
                  <para>
                     <emphasis>Шаг 5b)</emphasis>В правой части окна
по нажать правую кнопку мыши</para>
               </listitem>
               <listitem>
                  <para>
                     <emphasis>Шаг 5c)</emphasis>В появившемся меню выбрать
команду<emphasis>Скачать конфиг</emphasis>или<emphasis>Скачать модуль</emphasis>
                  </para>
               </listitem>
               <listitem>
                  <para>
                     <emphasis>Шаг 5d)</emphasis>Выбрать папку, в которой
конфиг (см. «<xref linkend="config" role="Undefined Cross-Reference"/>»)
или модуль будет сохранен</para>
               </listitem>
               <listitem>
                  <para>
                     <emphasis>Шаг 5e)</emphasis>При этом в нижней части
окна появится сообщение о начале выполнения задачи</para>
               </listitem>
            </itemizedlist>
         </section>
      </section>
   </d:InfElement>
</d:DocumentationCore>