<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="join_in_embsoft" name="Проводник СММ, скрипты РМО">
  
    <section><title id="tri_dva_dva" xreflabel="3.2.2. Проводник CMM">3.2.2. Проводник CMM</title>
    
      <section><title>Обзор</title>
        <para>Программа Проводник CMM предназначена для управления скриптами CMM. Скрипты CMM представляют собой небольшие программы, способные общаться с <xref linkend="ПО"/> телефонной станции и предназначены, в основном, для диагностических целей.</para>
        <para>С помощью проводника можно:</para>
        <itemizedlist>
          <listitem><para>Создавать, переименовывать и удалять файлы скриптов</para></listitem>
          <listitem><para>Группировать файлы скриптов</para></listitem>
          <listitem><para>Запускать скрипты на исполнение</para></listitem>
          <listitem><para>Вызывать файлы скриптов на редактирование</para></listitem>
        </itemizedlist>
      </section>
      
      <section><title>Главное окно</title>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\проводник-смм.gif"/>
        </informalfigure>
        <para>По внешнему виду программа очень похожа на Проводник, входящий в состав операционной системы Windows®. Операции над файлами скриптов и папками, содержащими скрипты можно производить используя команды главного меню программы и контекстного меню, вызываемого щелчком правой кнопки мыши. В каждый момент времени одна из папок или один из файлов скриптов могут являются текущими, о чем свидетельствует измененный значок (для папки) и подсвечивание названия (для папки и файла).</para>
      </section>
      
      <section><title>Главное меню</title>
         <para><command>Меню Файл</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
              <row>
                <entry>Создать -> Папку</entry>
                <entry>Создать подпапку в текущей папке</entry>
              </row>
              <row>
                <entry>Создать -> Скрипт</entry>
                <entry>Создать новый файл скрипта в текущей папке</entry>
              </row>
              <row>
                <entry>Создать связь</entry>
                <entry>Создать в текущей папке файл-ссылку на выделенный файл; после создания ссылку можно переместить в другую папку и использовать для вызова скрипта</entry>
              </row>
              <row>
                <entry>Удалить</entry>
                <entry>Удалить текущий файл или папку</entry>
              </row>
              <row>
                <entry>Переименовать</entry>
                <entry>Переименовать текущий файл или папку (доступно и через одинарный щелчок мышью на названии папки или файла)</entry>
              </row>
              <row>
                <entry>Свойства</entry>
                <entry>Вызвать панель свойств файла или папки</entry>
              </row>
              <row>
                <entry>Закрыть</entry>
                <entry>Выйти из программы</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>  
        <para><command>Меню Правка</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
              <row>
                <entry>Вырезать</entry>
                <entry>Пометить файл(ы) для последующего перемещения по команде вставить</entry>
              </row>
              <row>
                <entry>Копировать</entry>
                <entry>Пометить файл(ы) для последующего копирования по команде вставить</entry>
              </row>
              <row>
                <entry>Вставить</entry>
                <entry>Произвести операцию перемещения или копирования для файлов, ранее помеченных командой вырезать или копировать</entry>
              </row>
              <row>
                <entry>Выделить все</entry>
                <entry>Выделить все файлы в текущей папке</entry>
              </row>
              <row>
                <entry>Обратить выделение</entry>
                <entry>Обратить состояние выделения для файлов текущей папки</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Меню Вид – управление показом значков файлов</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Крупные значки</entry>
                <entry>Отображать файлы в виде крупных значков</entry>
              </row>
              <row>
                <entry>Мелкие значки</entry>
                <entry>Отображать файлы в виде мелких значков</entry>
              </row>
              <row>
                <entry>Список</entry>
                <entry>Отображать файлы в виде списка</entry>
              </row>
              <row>
                <entry>Таблица</entry>
                <entry>Отображать файлы в виде таблицы</entry>
              </row>
              <row>
                <entry>На один уровень вверх</entry>
                <entry>Перейти в родительскую папку</entry>
              </row>
              <row>
                <entry>Обновить</entry>
                <entry>Обновить содержимое окна</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Контекстное меню</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Выполнить</entry>
                <entry>Запустить скрипт на выполнение</entry>
              </row>
              <row>
                <entry>Редактировать</entry>
                <entry>Вызвать редактор для файла скрипта</entry>
              </row>
              <row>
                <entry>Создать связь</entry>
                <entry>Создать в текущей папке файл-ссылку на выделенный файл. После создания ссылку можно переместить в другую папку и использовать для вызова скрипта</entry>
              </row>
              <row>
                <entry>Удалить</entry>
                <entry>Удалить текущий файл или папку</entry>
              </row>
              <row>
                <entry>Переименовать</entry>
                <entry>Переименовать текущий файл или папку (доступно и через одинарный щелчок мышью на названии папки или файла)</entry>
              </row>
              <row>
                <entry>Свойства</entry>
                <entry>Вызвать панель свойств файла</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para>Язык CMM-скриптов</para>
        <para><command>Описание языка CMM-скриптов</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <tbody>
             <row>
                <entry>Набор символов</entry>
                <entry>Идентификаторы и ключевые слова не чувствительны к регистру. Русские буквы в них не допускаются.</entry>
              </row>
              <row>
                <entry>Константы</entry>
                <entry>Целочисленные записываются либо в десятичном представлении, либо в шестнадцатиричном (с префиксом $). Строковые записываются в одинарных кавычках ('), чтобы включить в строку этот символ, следует написать его дважды.</entry>
              </row>
              <row>
                <entry>Переменные</entry>
                <entry>Тип только целочисленный (знаковый 32-битный), предварительное описание не требуется, инициализируются нулем, имя не может быть зарезервированным словом.</entry>
              </row>
              <row>
                <entry>Операции</entry>
                <entry>Присваивание: :=, сравнение: = &lt;> &lt; > >= &lt;=, арифметика: + - * /, сдвиги: &lt;&lt; >>, логика: &amp;&amp; || ^ NOT, скобки: ( ).</entry>
              </row>
              <row>
                <entry>Операторы</entry>
                <entry><para>Каждый оператор должен завершаться точкой с запятой (;). Метка оператора задается указанием идентификатора с двоеточием (:).</para><para>IF &lt;условие> THEN &lt;операторы> [ELSE &lt;операторы>] FI.</para><para>FOR &lt;переменная> FROM &lt;значение> TO &lt;значение> DO &lt;операторы> OD.</para><para>GOTO &lt;метка оператора>.</para></entry>
              </row>
              <row>
                <entry>Функции</entry>
                <entry>Имеются только внешние. Параметры при вызове отделяются запятой. Вызов: &lt;имя функции> (&lt;параметры>)</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
      </section>
      
    </section>
    
    <section><title>3.2.3. Скрипты РМО</title>
    
      <section><title>Обзор</title>
        <para>Приложение Скрипты <xref linkend="РМО"/> подключается к Серверу скриптов <xref linkend="РМО"/> (см. разд. «<xref linkend="tri_odin_10"/>») и предоставляет следующую функциональность:</para>
        <itemizedlist>
          <listitem><para>Управление файлами сценариев (создание, удаление и т.д.)</para></listitem>
          <listitem><para>Запуск сценария на выполнение</para></listitem>
          <listitem><para>Управление ходом выполнения сценария</para></listitem>
          <listitem><para>Отображение результатов работы сценария</para></listitem>
          <listitem><para>Редактирование сценария</para></listitem>
        </itemizedlist>
      </section>
        
      <section><title>Главное окно и окно проводника</title>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипты-РМО-общ.-вид1.gif"/>
        </informalfigure>
        <para>Главное окно позволяет проводить операции с дочерними окнами, такими как окно проводника или окнами исполнения и редактирования сценариев. Проводник предназначен для управления файлами сценариев. По своему внешнему виду и функциональности напоминает проводник Windows. Главное окно и окно проводника содержат следующие элементы управления:</para>
        <itemizedlist>
          <listitem><para>Дерево каталогов</para></listitem>
          <listitem><para>Список содержимого папки</para></listitem>
          <listitem><para>Главное меню</para></listitem>
          <listitem><para>Контекстное меню (вызывается нажатием) правой кнопки</para></listitem>
          <listitem><para>Панель управления</para></listitem>
          <listitem><para>Строка состояния</para></listitem>
        </itemizedlist>
        <para>Дерево каталогов предназначено для отображения структуры папок и внесение в нее изменений. Находится в левой части окна проводника и имеет вид дерева.</para>
        <para>Список содержимого папки отображает содержимое папки, выбранной в дереве каталогов и позволяет изменять его.</para>
      </section>
      
      <section><title>Главное меню</title>
        <para><command>Меню Файл</command></para>
         <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Сохранить</entry>
                <entry>Сохранить изменения в сценарии</entry>
              </row>
              <row>
                <entry>Сохранить все</entry>
                <entry>Сохранить все измененные сценарии</entry>
              </row>
              <row>
                <entry>Выход</entry>
                <entry>Завершить работу приложения</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Меню Правка</command></para>
        <d:Nest id="vid"/>
        <para>Меню <emphasis>Вид</emphasis> доступно только если активно окно проводника.</para>
        <para><command>Меню Вид</command></para>
        <d:Nest id="vid"/>
        <para><command>Меню Скрипт</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Крупные значки</entry>
                <entry>Отображать содержимое в виде крупных значков</entry>
              </row>
              <row>
                <entry>Мелкие значки</entry>
                <entry>Отображать содержимое в виде мелких значков</entry>
              </row>
              <row>
                <entry>Список</entry>
                <entry>Отображать содержимое в виде списка</entry>
              </row>
              <row>
                <entry>Таблица</entry>
                <entry>Отображать содержимое в виде таблицы</entry>
              </row>
              <row>
                <entry>Обновить</entry>
                <entry>Обновить содержимое</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para>Меню <emphasis>Скрипт</emphasis> доступно только если активно окно исполнения и редактирования сценария.</para>
        <para><command>Меню Окна</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Каскадом</entry>
                <entry>Расположить окна каскадом</entry>
              </row>
              <row>
                <entry>Горизонтально</entry>
                <entry>Расположить окна горизонтально</entry>
              </row>
              <row>
                <entry>Вертикально</entry>
                <entry>Расположить окна вертикально</entry>
              </row>
              <row>
                <entry>Проводник</entry>
                <entry>Перейти к окну проводника</entry>
              </row>
              <row>
                <entry>1 – Проверка Трактов.js<footnote><para>Данный пункт позволяет перйти к окну сценария Проверка Трактов.js. Если открыто несколько окон сценариев, то в меню каждому такому окну будет соответствовать отдельный пункт, позволяюший к нему перейти</para></footnote></entry>
                <entry>Перейти к окну исполнения сценария</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Меню Справка</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Содержание</entry>
                <entry>Показать эту справку</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
      </section>
      
      <section><title>Контекстное меню проводника</title>
        <para><command>Контекстное меню проводника</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>Выполнить</entry>
                <entry>Выполнить выбранный сценарий. Выбор этой операции аналогичен двойному щелчку по объекту. При этом будет открыто окно исполнения сценария</entry>
              </row>
              <row>
                <entry>Открыть</entry>
                <entry>Начать редактировать выбранный сценарий</entry>
              </row>
              <row>
                <entry>Вырезать</entry>
                <entry>Перемещает выделенные объекты в буфер обмена</entry>
              </row>
              <row>
                <entry>Копировать</entry>
                <entry>Копирует выделенные объекты в буфер обмена</entry>
              </row>
              <row>
                <entry>Вставить</entry>
                <entry>Вставляет содержимое буфера обмена</entry>
              </row>
              <row>
                <entry>Удалить</entry>
                <entry>Удаляет выделенные объекты</entry>
              </row>
              <row>
                <entry>Переименовать</entry>
                <entry>Переименовать выделенный объект</entry>
              </row>
              <row>
                <entry>Создать</entry>
                <entry>Создать объект</entry>
              </row>
              <row>
                <entry>Создать -> Папку</entry>
                <entry>Создать папку</entry>
              </row>
              <row>
                <entry>Создать -> VBScript файл</entry>
                <entry>Создать сценарий на языке VBScript</entry>
              </row>
              <row>
                <entry>Создать -> JScript файл</entry>
                <entry>Создать сценарий на языке JScript</entry>
              </row>
              <row>
                <entry>Создать -> WSF файл</entry>
                <entry>Создать Windows Script Host файл</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
      </section>
      
      <section><title>Панель управления</title>
        <para><command>Элементы панели управления</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Кнопка</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипты-РМО-кнопка-сохранит.gif"/>
                </entry>
                <entry>Сохранить изменения в сценарии</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-сохранить-вс.gif"/>
                </entry>
                <entry>Сохранить изменения во всех сценариях</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-переместить.gif"/>
                </entry>
                <entry>Переместить выделенное в буфер</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-копировать.gif"/>
                </entry>
                <entry>Копировать выделенное в буфер</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-вставить.gif"/>
                </entry>
                <entry>Вставить содержимое буфера</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-выполнить.gif"/>
                </entry>
                <entry>Начать выполнение сценария</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-прервать.gif"/>
                </entry>
                <entry>Прервать выполнение сценария</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-папка.gif"/>
                </entry>
                <entry>Подняться на уровень вверх</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипРМОкнопка-обновить.gif"/>
                </entry>
                <entry>Обновить содержимое</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
      </section>
      
      <section><title>Строка состояния</title>
        <para>Строка состояния состоит из двух областей. В левой части отображается количество выделенных объектов, в правой – их суммарный размер, без учета вложенных папок.</para>
        <para>Окно выполнения сценария</para>
        <para>Окно исполнения и редактирования сценария отображает результаты выполнения сценария, а также позволяет редактировать и отлаживать код сценария. Состоит из четырех вкладок:</para>
        <para><command>Вкладки окна выполнения сценария</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Примерный вид окна</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
             <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скрипты-РМО-вывод.gif"/>
                </entry>
                <entry><emphasis>Поле вывода сценария.</emphasis> Отображает результаты совершенной в процессе выполнения сценария работы. Может отображать как простой текст, так и HTML, в зависимости от формата вывода заданного сценария. Результаты отображаются после завершения работы сценария, для отображения промежуточных результатов воспользуйтесь кнопкой <command>Обновить</command> из панели управления</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\skriptyrmolog.gif"/>
                </entry>
                <entry><emphasis>Список сообщений лога.</emphasis> Отображает список сообщений, добавленных в лог сценарием. В случае если в логе нет ни одного сообщения соответствующая вкладка не видна</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скриптыРМОошибки.gif"/>
                </entry>
                <entry><emphasis>Список ошибок времени выполнения.</emphasis> Отображает список ошибок возникших в процессе выполнения сценария, с указанием места их возникновения – скрипта, строки и символа. Список виден только в случае возникновения ошибок, при успешном выполнении сценария список не выводится</entry>
              </row>
              <row>
                <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\скриптыРМОполе-редакт.gif"/>
                </entry>
                <entry><emphasis>Поле редактирования сценария.</emphasis> Отображает текст сценария и позволяет его редактировать. По умолчание не показывается. Для того чтобы показать поле редактирования воспользуйтесь командой <command>Редактировать</command> меню <emphasis>Скрипт</emphasis>. Сделанные изменения необходимо отослать на сервер используя команды <command>Сохранить</command> или <command>Сохранить все</command> меню <emphasis>Файл</emphasis></entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para>Передача аргументов в сценарий</para>
        <para>Сценарий может принять произвольное количество аргументов типа «строка». Аргументы передаются в сценарий одной строчкой в формате SDF, и автоматически разбиваются на отдельные пары «имя=значение». Формат SDF предполагает:</para>
        <itemizedlist>
          <listitem><para>Передаваемая строка имеет вид: Имя1=Значение1,Имя2=Значение1…</para></listitem>
          <listitem><para>Если в значении аргумента содержатся пробелы или знак «,», то ВСЯ ПАРА должна быть взята в кавычки: «Имя=значение».</para></listitem>
          <listitem><para>Если в значении аргумента содержатся кавычки ("), то ВСЯ ПАРА должна быть взята в кавычки, а внутренний символ " должен быть продублирован: «Имя=значе""ние».</para></listitem>
        </itemizedlist>
        <para>Визуальная библиотека</para>
        <para>Описание визуальной библиотеки см. в Разделе «<xref linkend="vb"/>».</para>
      </section>
            
    </section>
    
  </d:InfElement>

</d:DocumentationCore>