<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

      <d:InfProduct name="Руководство пользователя" id="UserManual">
          <book lang="ru">
            <bookinfo>
              <subtitle>
                Электронная автоматическая телефонная станция «Квант-Е-Сокол»
              </subtitle>
              <subtitle>
                Программное обеспечение
              </subtitle>
              <subtitle>
                Рабочее место техобслуживания и эксплуатации
              </subtitle>
              <title>
                Руководство оператора <d:DictRef dictid="main" entryid="productname"/>
              </title>
              <legalnotice><para>УТВЕРЖДЕН</para></legalnotice>
              <edition>ЫЯ1.220.0001-01 20 01 ЛУ</edition>
              <copyright>
                <year>2004</year>
                <holder>ЗАО ЛАНИТ-ТЕРКОМ</holder>
              </copyright>              
            </bookinfo>
            <d:InfElemRef id="ref_implementation_specification" infelemid="implementation_specification" optional="true"/>
            <d:InfElemRef id="ref_users_problem_description" infelemid="users_problem_description" optional="true"/>
            <d:InfElemRef id="ref_applications" infelemid="applications"/>
            <d:InfElemRef id="ref_rate_CTO" infelemid="rate_CTO" optional="true"/>
            <d:InfElemRef id="ref_script_language" infelemid="script_language" optional="true"/>
            <d:InfElemRef id="ref_visual_library" infelemid="visual_library" optional="true"/>
            <d:InfElemRef id="ref_fails" infelemid="fails" optional="true"/>
            <d:InfElemRef id="ref_example_trasses" infelemid="example_trasses" optional="true"/>
            <d:InfElemRef id="ref_decoding" infelemid="decoding"/>
          </book>
      </d:InfProduct>
      
    <d:Dictionary id="main" name="main_dictionary">
      <d:Entry id="productname">РМО</d:Entry>
    </d:Dictionary>

</d:DocumentationCore>