<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="visual_library" name="Визуальная библиотека">
    <chapter>
      <title id="vb" xreflabel="Визуальная библиотека">Визуальная библиотека</title>
      
      <section><title>6.1. Интерфейсы визуальных компонентов</title>
        <para>Иерархия</para>
        <itemizedlist>
            <listitem><para>IScriptControl</para>
              <itemizedlist>
                <listitem><para>IScriptButton</para></listitem>
                <listitem><para>IScriptFrame</para></listitem>
                <listitem><para>IScriptEdit</para></listitem>
                <listitem><para>IScriptCheckBox</para></listitem>
                <listitem><para>IScriptGroupBox</para></listitem>
                <listitem><para>IScriptLabel</para></listitem>
                <listitem><para>IScriptBevel</para></listitem>
                <listitem><para>IScriptRadioButton</para></listitem>
                <listitem><para>IScriptRadioGroup</para></listitem>
                <listitem><para>IScriptRadioButtonOfGroup</para></listitem>
                <listitem><para>IScriptListBox</para></listitem>
                <listitem><para>IScriptListBoxItem</para></listitem>
                <listitem><para>IScriptComboBox</para></listitem>
                <listitem><para>IScriptComboBoxItem</para></listitem>
              </itemizedlist>    
            </listitem>
            <listitem><para>IScriptControls</para></listitem>
        </itemizedlist>
        
        <section><title>6.1.1. Интерфейс IScriptControl</title>
          <para>Предок: IDispatch</para>
          <para>Базовый интерфейс, от которого наследуются интерфейсы всех остальных визуальных компонентов.</para>
          <para><command>Свойства интерфейса IScriptControl</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>BSTR Type_</entry>
                  <entry>(read-only)</entry>
                  <entry>Текстовое название типа компоненты. В случае, если тип не известен возвращает undefined. Обычно в этом свойстве храниться название <xref linkend="XML"/>-тага, с помощью которого определялась компонента</entry>
                </row>
                <row>
                  <entry>BSTR Name</entry>
                  <entry></entry>
                  <entry>Имя компоненты. Соответствует <xref linkend="XML"/>-атрибуту name</entry>
                </row>
                <row>
                  <entry>WORD Top</entry>
                  <entry></entry>
                  <entry>Верхняя точка компоненты относительно контейнера. Соответствует <xref linkend="XML"/>-атрибуту top</entry>
                </row>
                <row>
                  <entry>SHORT Left</entry>
                  <entry></entry>
                  <entry>Левая точка формы относительно контейнера. Соответствует <xref linkend="XML"/>-атрибуту left</entry>
                </row>
                <row>
                  <entry>WORD Width</entry>
                  <entry></entry>
                  <entry>Ширина компоненты. Соответствует <xref linkend="XML"/>-атрибуту width</entry>
                </row>
                <row>
                  <entry>WORD Height</entry>
                  <entry></entry>
                  <entry>Высота компоненты. Соответствует <xref linkend="XML"/>-атрибуту height</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Visible</entry>
                  <entry></entry>
                  <entry>Свойство, показывающее будет ли видна компонента а экране или нет. Соответствует <xref linkend="XML"/>-атрибуту visible. По умолчанию true</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Enabled</entry>
                  <entry></entry>
                  <entry>Свойство, показывающее будет ли компонента доступна или закрашена серым. Соответствует <xref linkend="XML"/>-атрибуту enabled. По умолчанию true</entry>
                </row>
                <row>
                  <entry>INT Align</entry>
                  <entry></entry>
                  <entry>Задает параметры выравнивания компоненты. Возможные значения: 0 – нет выравнивания (по умолчанию), 1 – выравнивание по верху контейнера, 2 – выравнивание по низу контейнера, 3 – выравнивание по левой части контейнера, 4 – выравнивание по правой части контейнера, 5 – полное заполнение клиентской области контейнера. Соответствует <xref linkend="XML"/>-атрибуту align</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.2. Интерфейс IScriptButton</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение обычной кнопки. В <xref linkend="XML"/> соответствует элементу button.</para>
          <para><command>Свойства интерфейса IScriptButton</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptButton</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.3. Интерфейс IScriptFrame</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех форм. В <xref linkend="XML"/> соответствует элементу form.</para>
          <para><command>Методы интерфейса IScriptFrame</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Метод</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>HRESULT Show</entry>
                  <entry>Создает форму и выводит её на экран. Если форма уже показана, то создается новая форма и содержимое переносится в нее. Выход из метода происходит только после скрытия формы</entry>
                </row>
                <row>
                  <entry>HRESULT Hide</entry>
                  <entry>Убирает форму с экрана. Если форма показана несколько раз, то произойдет возвращение к прошлому содержимому. Если форма показана в одном экземпляре, то она убирается с экрана полностью</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>Свойства интерфейса IScriptFrame</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption3"/>
                <row>
                  <entry>IScriptControls *Controls</entry>
                  <entry>(read-only)</entry>
                  <entry>Коллекция дочерних компонент формы. В <xref linkend="XML"/> соответствует вложенному элементу controls</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptFrame</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>onLoad</entry>
                  <entry>Вызывается при загрузке формы из <xref linkend="XML"/>. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
                </row>
                <row>
                  <entry>onUnload</entry>
                  <entry>Вызывается при выгрузке формы из памяти.. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
                </row>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
                <d:Nest id="mouse"/>
                <row>
                  <entry>onMouseWheel</entry>
                  <entry>Показывает, что пользователь крутит колесико мыши. Параметры в это событие передаются с помощью интерфейса IScriptMouseWheelEventParams</entry>
                </row>
                <row>
                  <entry>onMouseWheelDown</entry>
                  <entry>Показывает, что пользователь нажал на колесико мыши. Параметры в это событие передаются с помощью интерфейса IScriptMouseWheelUpDownEventParams</entry>
                </row>
                <row>
                  <entry>onMouseWheelUp</entry>
                  <entry>Показывает, что пользователь отпустил колесико мыши. Параметры в это событие передаются с помощью интерфейса IScriptMouseWheelUpDownEventParams</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.4. Интерфейс IScriptEdit</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение полей ввода текста. В <xref linkend="XML"/> соответствует элементу edit.</para>
          <para><command>Свойства интерфейса IScriptEdit</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>BSTR Text</entry>
                  <entry>Содержимое поля ввода. Соответствует <xref linkend="XML"/>-атрибуту text</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptEdit</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="cange"/>
                <d:Nest id="dblclick"/>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.5. Интерфейс IScriptCheckBox</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение галочек с текстом. В <xref linkend="XML"/> соответствует элементу checkBox.</para>
          <para><command>Свойства интерфейса IScriptCheckBox</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <d:Nest id="checked"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptCheckBox</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.6. Интерфейс IScriptGroupBox</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех рамок-контейнеров. В <xref linkend="XML"/> соответствует элементу groupBox.</para>
          <para><command>Свойства интерфейса IScriptGroupBox</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption3"/>
                <d:Nest id="controls"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptGroupBox</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="dblclick"/>
                <d:Nest id="click"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.7. Интерфейс IScriptLabel</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех надписей. В <xref linkend="XML"/> соответствует элементу label.</para>
          <para><command>Свойства интерфейса IScriptLabel</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <row>
                  <entry>VARIANT_BOOL AutoSize</entry>
                  <entry>Показывает, будет ли размер области, занимаемой надписью автоматически изменяться при изменении текста надписи. Соответствует <xref linkend="XML"/>-атрибуту autoSize</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptLabel</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="dblclick"/>
                <d:Nest id="click"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.8. Интерфейс IScriptBevel</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех бордюров. В <xref linkend="XML"/> соответствует элементу bevel.</para>
          <para><command>Свойства интерфейса IScriptBevel</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>INT Shape</entry>
                  <entry>Форма бордюра. Допустимые значения: 0 – вид коробки (значение по умолчанию), 1 – вид рамки, 2 – верхняя часть рамки, 3 – нижняя часть рамки, 4 – левая часть рамки, 5 – правая часть рамки, 5 – пунктирная рамка. Соответствует <xref linkend="XML"/>-атрибуту shape</entry>
                </row>
                <row>
                  <entry>INT Style</entry>
                  <entry>Стиль бордюра. Допустимые значения: 0 – понижающий (значение по умочанию), 1 – повышающий. Соответствует <xref linkend="XML"/>-атрибуту style</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.9. Интерфейс IScriptRadioButton</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение альтернатив вне группы. В <xref linkend="XML"/> соответствует элементу radioButton.</para>
          <para><command>Свойства интерфейса IScriptRadioButton</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <d:Nest id="checked"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptRadioButton</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
                <d:Nest id="mouse"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.10. Интерфейс IScriptRadioGroup</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех контейнеров альтернатив. В <xref linkend="XML"/> соответствует элементу radioGroup.</para>
          <para><command>Свойства интерфейса IScriptRadioGroup</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption3"/>
                <row>
                  <entry>LONG Columns</entry>
                  <entry></entry>
                  <entry>Количество колонок в контейнере</entry>
                </row>
                <d:Nest id="controls"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptRadioGroup</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="dblclick"/>
                <d:Nest id="click"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.11. Интерфейс IScriptRadioButtonOfGroup</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение альтернатив в группе. В <xref linkend="XML"/> соответствует элементу radioButton.</para>
          <para><command>Свойства интерфейса IScriptRadioButtonOfGroup</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <d:Nest id="checked"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.12. Интерфейс IScriptListBox</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех списков элементов. В <xref linkend="XML"/> соответствует элементу listBox.</para>
          <para><command>Свойства интерфейса IScriptControl</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="sorted"/>
                <row>
                  <entry>VARIANT_BOOL MultiSelect</entry>
                  <entry></entry>
                  <entry>Флаг, разрешающий или запрещающий выбор нескольких элементов списка одновременно. Соответствует <xref linkend="XML"/>-атрибуту multiSelect. Значение по умолчанию false</entry>
                </row>
                <d:Nest id="current"/>
                <d:Nest id="controls"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.13. Интерфейс IScriptListBoxItem</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех элементов списков. В <xref linkend="XML"/> соответствует элементу listBoxItem.</para>
          <para><command>Свойства интерфейса IScriptListBoxItem</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <row>
                  <entry>BSTR Value</entry>
                  <entry>Строковые данные, ассоциированные с элементом. Соответствует <xref linkend="XML"/>-атрибуту value</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Current</entry>
                  <entry>Флаг, показывающий, выбран ли этот элемент списка. Соответствует <xref linkend="XML"/>-атрибуту current. Значение по умолчанию false</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.14. Интерфейс IScriptComboBox</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение раскрывающихся списков. В <xref linkend="XML"/> соответствует элементу comboBox.</para>
          <para><command>Свойства интерфейса IScriptComboBox</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="sorted"/>
                <row>
                  <entry>INT Style</entry>
                  <entry></entry>
                  <entry>Стиль раскрывающегося списка. Допустимые значения: 0 – раскрывающийся с возможностью редактирования (значение по умолчанию), 1 – раскрывающийся без возможности редактирования, 2 – простой. Соответствует <xref linkend="XML"/>-атрибуту style</entry>
                </row>
                <d:Nest id="current"/>
                <d:Nest id="controls"/>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>События интерфейса IScriptComboBox</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Событие</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="cange"/>
                <d:Nest id="dblclick"/>
                <d:Nest id="click"/>
                <d:Nest id="key"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.15. Интерфейс IScriptComboBoxItem</title>
          <para>Предок: IScriptControl</para>
          <para>Интерфейс, описывающий поведение всех элементов раскрывающихся списков. В <xref linkend="XML"/> соответствует элементу comboBoxItem.</para>
          <para><command>Свойства интерфейса IScriptComboBoxItem</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="caption"/>
                <row>
                  <entry>BSTR Value</entry>
                  <entry>Строковые данные, ассоциированные с элементом. Соответствует <xref linkend="XML"/>-атрибуту value</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Current</entry>
                  <entry>Флаг, показывающий, выбран ли этот элемент списка. Соответствует <xref linkend="XML"/>-атрибуту current. Значение по умолчанию false</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.1.16. Интерфейс IScriptControls</title>
          <para>Предок: IDispatch</para>
          <para>Коллекция дочерних элементов контейнера. В <xref linkend="XML"/> соответствует вложеному элементу controls.</para>
          <para><command>Свойства интерфейса IScriptControls</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG Count </entry>
                  <entry>(read-only)</entry>
                  <entry>Количество элементов в списке</entry>
                </row>
                <row>
                  <entry>IDispatch *Item[VARIANT Index] </entry>
                  <entry>(read-only)</entry>
                  <entry>Элемент коллекции по имени или индексу</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
      </section>
      
      <section><title>6.2. Интерфейсы, передаваемые обработчикам событий</title>
      
        <section><title>6.2.1. Иерархия</title>
          <itemizedlist>
            <listitem><para>IScriptEventParams</para>
              <itemizedlist>
              <listitem><para>IScriptCanResizeEventParams</para></listitem>
              <listitem><para>IScriptConstrainedResizeEventParams</para></listitem>
              <listitem><para>IScriptContextPopupEventParams</para></listitem>
              <listitem><para>IScriptKeyEventParams</para></listitem>
              <listitem><para>IScriptKeyPressEventParams</para></listitem>
              <listitem><para>IScriptMouseEventParams</para></listitem>
              <listitem><para>IScriptMouseMoveEventParams</para></listitem>
              <listitem><para>IScriptMouseWheelEventParams</para></listitem>
              <listitem><para>IScriptMouseWheelUpDownEventParams</para></listitem>
              </itemizedlist>
            </listitem>
          </itemizedlist>
        </section>
        
        <section><title>6.2.2. Интерфейс IScriptEventParams</title>
          <para>Предок: IDispatch</para>
          <para>Базовый интерфейс, с общей информацией для обработчиков. От него наследуются все остальные интерфейсы.</para>
          <para><command>Свойства интерфейса IScriptEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>IDispatch *Sender</entry>
                  <entry>(read-only)</entry>
                  <entry>Диспетчерский интерфейс объекта, вызвавшего событие</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.3. Интерфейс IScriptCanResizeEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчик запроса на возможность изменения размера формы.</para>
          <para><command>Свойства интерфейса IScriptCanResizeEventParams</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG NewWidth</entry>
                  <entry>Новая ширина формы</entry>
                </row>
                <row>
                  <entry>LONG NewHeight</entry>
                  <entry>Новая высота формы</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Resize</entry>
                  <entry>Флаг, показывающий, разрешать изменение размера или нет</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.4. Интерфейс IScriptConstrainedResizeEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры-ограничения на размер формы.</para>
          <para><command>Свойства интерфейса IScriptConstrainedResizeEventParams</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG MinWidth</entry>
                  <entry>Минимальная ширина формы</entry>
                </row>
                <row>
                  <entry>LONG MinHeight</entry>
                  <entry>Минимальная высота формы</entry>
                </row>
                <row>
                  <entry>LONG MaxWidth</entry>
                  <entry>Максимальная ширина формы</entry>
                </row>
                <row>
                  <entry>LONG MaxHeight</entry>
                  <entry>Максимальная высота формы</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.5. Интерфейс IScriptContextPopupEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики события onContextPopup.</para>
          <para><command>Свойства интерфейса IScriptContextPopupEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG MousePosX</entry>
                  <entry>(read-only)</entry>
                  <entry>Горизонтальная координата курсора мыши</entry>
                </row>
                <row>
                  <entry>LONG MousePosY</entry>
                  <entry>(read-only)</entry>
                  <entry>Вертикальная координата курсора мыши</entry>
                </row>
                <row>
                  <entry>VARIANT_BOOL Handled</entry>
                  <entry></entry>
                  <entry>Флаг, показывающий, обработано это сообщение каким-либо обработчиком, или еще нет</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.6. Интерфейс IScriptKeyEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики событий клавиатуры.</para>
          <para><command>Свойства интерфейса IScriptKeyEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG Key</entry>
                  <entry></entry>
                  <entry>Код нажатой клавиши</entry>
                </row>
                <d:Nest id="alt"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.7. Интерфейс IScriptKeyPressEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики события onKeyPress.</para>
          <para><command>Свойства интерфейса IScriptKeyPressEventParams</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Свойство</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>LONG Key</entry>
                  <entry>Код нажатой клавиши</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.8. Интерфейс IScriptMouseEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики событий мыши.</para>
          <para><command>Свойства интерфейса IScriptMouseEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>INT Button</entry>
                  <entry>(read-only)</entry>
                  <entry>Параметр, показывающий, какая кнопка мыши инициировала сообщение. Допустимые значения: 0 – левая, 1 – правая, 2 – средняя</entry>
                </row>
                <d:Nest id="alt"/>
                <d:Nest id="long"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.9. Интерфейс IScriptMouseMoveEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики событий движения мыши.</para>
          <para><command>Свойства интерфейса IScriptMouseMoveEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="alt"/>
                <d:Nest id="long"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.10. Интерфейс IScriptMouseWheelEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики событий движения колесика мыши.</para>
          <para><command>Свойства интерфейса IScriptMouseWheelEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="alt"/>
                <row>
                  <entry>LONG WheelDelta</entry>
                  <entry>(read-only)</entry>
                  <entry>Изменение положения колесика</entry>
                </row>
                <d:Nest id="pos"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
        
        <section><title>6.2.11. Интерфейс IScriptMouseWheelUpDownEventParams</title>
          <para>Предок: IScriptEventParams</para>
          <para>Интерфейс, описывающий параметры, передаваемые в обработчики событий зажатия и отпускания колесика мыши.</para>
          <para><command>Свойства интерфейса IScriptMouseWheelUpDownEventParams</command></para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Свойство</entry><entry></entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <d:Nest id="alt"/>
                <d:Nest id="pos"/>
              </tbody>
            </tgroup>
          </informaltable>
        </section>
      
      </section>
      
    </chapter>
  </d:InfElement>

</d:DocumentationCore>
