<?xml version="1.0" encoding="UTF-8"?>
<ProductDocumentation productid="enterprise" xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
<FinalInfProduct id="UserManual_enterprise" infproductid="UserManual">
<Adapter infelemrefid="ref_antivirus">
<Replace-Nest nestid="extended_actions">
<listitem><para>put to carantin</para></listitem>
<listitem><para>help request</para></listitem>
</Replace-Nest>
</Adapter>
<Adapter infelemrefid="ref_firewall_config"/>
<Adapter infelemrefid="ref_antivirus_config"/>
<Adapter infelemrefid="ref_update_local"/>
<Adapter infelemrefid="ref_components_update">
<Insert-After nestid="av-update">
<para>
All was made by admin.
</para>
</Insert-After>
<Insert-After nestid="as-update">
<para>
Uses central server.
</para>
</Insert-After>
</Adapter>
<Adapter infelemrefid="ref_antispam"/>
</FinalInfProduct>
<Dictionary id="main" name="Main Dictionary">
<Entry id="productname">Corporative</Entry>
</Dictionary>
</ProductDocumentation>
