<?xml version="1.0" encoding="UTF-8"?>
<ProductDocumentation productid="enterprise" xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
<FinalInfProduct id="UserManual_enterprise" infproductid="UserManual">
<Adapter infelemrefid="ref_antivirus">
<Replace-Nest nestid="extended_actions">
<listitem><para>помещение в карантин</para></listitem>
<listitem><para>запрос о помощи у представителя ИнтерБез в вашей фирме</para></listitem>
</Replace-Nest>
</Adapter>
<Adapter infelemrefid="ref_firewall_config"/>
<Adapter infelemrefid="ref_antivirus_config"/>
<Adapter infelemrefid="ref_update_local"/>
<Adapter infelemrefid="ref_components_update">
<Insert-After nestid="av-update">
<para>
Скорее всего все настройки уже произведены Вашим системным администратором.
</para>
</Insert-After>
<Insert-After nestid="as-update">
<para>
ИнтерБез Корпоративный использует центральный локальный сервер для обнаружения
спама. В настройках необходимо указать его адрес. Для получения адреса
обратитесь с системному администратору.
</para>
</Insert-After>
</Adapter>
<Adapter infelemrefid="ref_antispam"/>
</FinalInfProduct>

<Dictionary id="main" name="Главный Словарь">
<Entry id="productname">ИнтерБез Корпоративный</Entry>
</Dictionary>
</ProductDocumentation>
