<?xml version="1.0" encoding="UTF-8"?>
<DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
<InfProduct id="UserManual" name="Руководство Пользователя">
<book>
<bookinfo>
<title>Руководство Пользователя <DictRef dictid="main" entryid="productname"/></title>
</bookinfo>
<InfElemRef id="ref_preface" infelemid="preface"/>
<InfElemRef id="ref_control_center" infelemid="control_center"/>
<InfElemRef id="ref_firewall" infelemid="firewall"/>

<InfElemRefGroup id="optional_components" modifier="OR" name="опции"/>
<InfElemRef groupid="optional_components" id="ref_antivirus" infelemid="antivirus" optional="true"/>
<InfElemRef groupid="optional_components" id="ref_antispam" infelemid="antispam" optional="true"/>
</book>
</InfProduct>
</DocumentationCore>
