<?xml version="1.0" encoding="UTF-8"?>
<d:ProductDocumentation productid="home" xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
  <d:FinalInfProduct id="UserManual_home" infproductid="UserManual">
    <d:Adapter infelemrefid="ref_antivirus"/>
    <d:Adapter infelemrefid="ref_update_inet"/>
    <d:Adapter infelemrefid="ref_components_update">
      <d:Replace-Nest nestid="as-update"/>
    </d:Adapter>
  </d:FinalInfProduct>
  
  <d:Dictionary id="main" name="Главный Словарь">
    <d:Entry id="productname">ИнтерБез Домашний</d:Entry>
  </d:Dictionary>
</d:ProductDocumentation>
