<?xml version="1.0" encoding="UTF-8"?>
<d:ProductDocumentation productid="professional" xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
	<d:FinalInfProduct id="UserManual_professional" infproductid="UserManual">
		<d:Adapter infelemrefid="ref_antivirus">
			<d:Replace-Nest nestid="extended_actions">
				<listitem><para>put to carantin</para></listitem>
				<listitem><para>online-help request</para></listitem>
			</d:Replace-Nest>
		</d:Adapter>
		<d:Adapter infelemrefid="ref_firewall_config"/>
		<d:Adapter infelemrefid="ref_antivirus_config"/>
		<d:Adapter infelemrefid="ref_update_inet"/>
		<d:Adapter infelemrefid="ref_antispam"/>
	</d:FinalInfProduct>

	<d:Dictionary id="main" name="Main Dictionary">
		<d:Entry id="productname">InterBez Professional</d:Entry>
	</d:Dictionary>
</d:ProductDocumentation>
