<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!ENTITY bkc1 SYSTEM "UserManual.e01">
<!ENTITY bkc2 SYSTEM "main1.e02">

<!-- End Document Specific Declarations -->

]>
<DocumentationCore filename = "User_manual.drl">&bkc1;&bkc2;</DocumentationCore>
