<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->


<!ENTITY bkc1 SYSTEM "join_in_sysappl.e01">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/router.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/otkrytie-serverov.gif" NDATA gif>
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/zakladka-serverarmo.gif" NDATA gif>
<!ENTITY graphic4 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/otkrytie-serverov-2.gif" NDATA gif>
<!ENTITY graphic5 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/spispok-stativov.gif" NDATA gif>
<!ENTITY graphic6 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Панель-станции(приложение).gif" NDATA gif>
<!ENTITY graphic7 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/панель-станции-обзор.gif" NDATA gif>
<!ENTITY graphic8 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Панель-станции(прилож.)-рег.gif" NDATA gif>
<!ENTITY graphic9 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/панель-станции-абоненты.gif" NDATA gif>
<!ENTITY graphic10 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/панель-станции-тракты.gif" NDATA gif>
<!ENTITY graphic11 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-kanaly.gif" NDATA gif>
<!ENTITY graphic12 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-testy.gif" NDATA gif>
<!ENTITY graphic13 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-knopki-panel.gif" NDATA gif>
<!ENTITY graphic14 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-knopka1.gif" NDATA gif>
<!ENTITY graphic15 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-knopka2.gif" NDATA gif>
<!ENTITY graphic16 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stanzii-knopka3.gif" NDATA gif>
<!ENTITY graphic17 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-nastrojka-ta.gif" NDATA gif>
<!ENTITY graphic18 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/panel-stantzii-tablo-nastro.gif" NDATA gif>
<!ENTITY graphic19 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/konsol-server.gif" NDATA gif>
<!ENTITY graphic20 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Тарификация-сервер.gif" NDATA gif>
<!ENTITY graphic21 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Сервер-времени.gif" NDATA gif>
<!ENTITY graphic22 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Синхронизация-станция.gif" NDATA gif>
<!ENTITY graphic23 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/синхронизация-синхронизация.gif" NDATA gif>
<!ENTITY graphic24 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/синхронизация-файлы.gif" NDATA gif>
<!ENTITY graphic25 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/синхронизация-программатор.gif" NDATA gif>
<!ENTITY graphic26 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/синхронизация-настройки.gif" NDATA gif>
<!ENTITY graphic27 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/х25-сервер.gif" NDATA gif>
<!ENTITY graphic28 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/statistika-server.gif" NDATA gif>
<!ENTITY graphic29 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/Сервер-скриптов-общ.-вид.gif" NDATA gif>
<!ENTITY graphic30 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmosborkamusora%20copy.gif" NDATA gif>
<!ENTITY graphic31 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmoknopka-priostanovit%20copy.gif" NDATA gif>
<!ENTITY graphic32 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmoknopka-vypolnit%20copy.gif" NDATA gif>
<!ENTITY graphic33 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmoknopka-prervat_copy.gif" NDATA gif>
<!ENTITY graphic34 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmoprervatvsjo.gif" NDATA gif>
<!ENTITY graphic35 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriprmoknopka-svojstva-servera_copy.gif" NDATA gif>
<!ENTITY graphic36 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/сервер-скриптов-настройки.gif" NDATA gif>
<!ENTITY graphic37 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/журнал-общий-вид.gif" NDATA gif>
<!ENTITY graphic38 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/журнал-установки-журнала.gif" NDATA gif>
<!ENTITY graphic39 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/журнал-внешний-вид.gif" NDATA gif>
<!ENTITY graphic40 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/журнал-фильтр.gif" NDATA gif>
<!ENTITY graphic41 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/dispecher-zadanij1.gif" NDATA gif>
<!ENTITY graphic42 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/dispecher-zadach-zadanie.gif" NDATA gif>
<!ENTITY graphic43 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/dispecher-zadanij-redaktor-z.gif" NDATA gif>
<!NOTATION cgm SYSTEM "">
<!ENTITY graphic44 SYSTEM "file:///F:/runtime-New_configuration/rmo/Result/ScreenShots-full/dispecher-zadach-raspisanie.gif" NDATA cgm>
<!ENTITY graphic45 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/trassa-obtshij-vid.gif" NDATA gif>
<?Fm Validation Off?>


<!-- End Document Specific Declarations -->

]>
<DocumentationCore
    filename = "Другие_функции_Системных_приложений.drl">&bkc1;</DocumentationCore>
