<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->


<!ENTITY bkc1 SYSTEM "users_problem_description.e01">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/безопасность.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/nasledovanie.gif" NDATA gif>
<!NOTATION cgm SYSTEM "">
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/Result/illustrations/u_p_d/safety.jpg" NDATA cgm>

<!-- End Document Specific Declarations -->

]>
<DocumentationCore
    filename = "Описание_задач_пользователя.drl">&bkc1;</DocumentationCore>
