<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!ENTITY bkc1 SYSTEM "bussing.e01">
<!ENTITY bkc2 SYSTEM "review_b.e02">
<!ENTITY bkc3 SYSTEM "main_window_b.e03">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-СЛ.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-индексы.gif" NDATA gif>
<!ENTITY bkc4 SYSTEM "state_sections_b.e04">
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-состояние-трактов.gif" NDATA gif>
<!ENTITY graphic4 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-действия-над-трактами.gif" NDATA gif>
<!ENTITY graphic5 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/СЛ-операции-над-каналами.gif" NDATA gif>

<!-- End Document Specific Declarations -->

]>
<DocumentationCore
    filename = "Соединительные_линии.drl">&bkc1;&bkc2;&bkc3;&bkc4;</DocumentationCore>
