<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->


<!ENTITY bkc1 SYSTEM "embedded_software.e01">
<?Fm Validation Off?>


<!-- End Document Specific Declarations -->

]>
<DocumentationCore
    filename = "Управление_встроенным_ПО.drl">&bkc1;</DocumentationCore>
