/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.spbu.pldoctoolkit.graph.validation;

import org.spbu.pldoctoolkit.graph.InfElemRefGroup;
import org.spbu.pldoctoolkit.graph.InfElement;

/**
 * A sample validator interface for {@link org.spbu.pldoctoolkit.graph.InfElemRef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfElemRefValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateInfelem(InfElement value);
	boolean validateGroup(InfElemRefGroup value);
	boolean validateOptional(boolean value);
}
