<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="fails" name="Состав файлов">
    <chapter>
      <title>Состав файлов</title>
      <para>Файлы <xref linkend="ПО"/> <xref linkend="РМО"/> делятся на две группы:</para>
      <itemizedlist>
        <listitem><para>Файлы установочного пакета <xref linkend="ПО"/> <xref linkend="РМО"/> </para></listitem>
        <listitem><para>Файлы установочного пакета данных <xref linkend="АТС"/> </para></listitem>
      </itemizedlist>
      
      <section><title>7.1. Файлы пакета данных АТС</title>
        <para>Файлы, входящие в пакет установки данных АТС можно разделить на следующие категории:</para>
        <itemizedlist>
          <listitem><para>Программные файлы <xref linkend="ФПО"/> (встроенное <xref linkend="ПО"/> <xref linkend="АТС"/>)</para></listitem>
          <listitem><para>Файлы настройки <xref linkend="РМО"/> на <xref linkend="ФПО"/></para></listitem>
          <listitem><para>Файлы настроек приложения Серверы <xref linkend="РМО"/> (см. разд. «<xref linkend="tri_odin_dva"/>»)</para></listitem>
          <listitem><para>Файл <xref linkend="БД"/> <xref linkend="РМО"/></para></listitem>
          <listitem><para>Вспомогательные файлы</para></listitem>
          <listitem><para>Файлы, создаваемые приложениями <xref linkend="РМО"/></para></listitem>
        </itemizedlist>
        
        <section><title>7.1.1. Программные файлы ФПО (встроенное ПО АТС)</title>
          <para>Находятся в подкаталоге <command>Bin</command>. Программные файлы <xref linkend="РМО"/> делятся на два вида: файлы кода объектов (каждому объекту соответствует свой файл с именем, совпадающим с именем объекта), файлы конфигурации модулей (каждому модулю соответствует свой файл с именем, совпадающим с номером модуля) и файлы <xref linkend="ОС1"/>.</para>
          <para>Файлы загрузочных образов модулей находятся в каталоге <command>Flash</command>. Каждому программируемому модулю станции соответствует файл с именем вида <filename>tNN.040</filename>. Загрузочные образы могут быть прошиты во flash-память модуля с помощью аппаратного программатора.</para>
        </section>
        
        <section><title>7.1.2. Файлы настройки РМО на ФПО</title>
          <para>Находятся в подкаталоге <command>Classes_Win</command>. Внутри на каждый объект <xref linkend="ФПО"/> заводится свой подкаталог с именем, совпадающим с именем объекта. В этом подкаталоге находятся следующие файлы:</para>
          <para><command>Файлы настройки</command> <xref linkend="РМО"/> на <xref linkend="ФПО"/></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Файл</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry><filename>Objects.lst</filename></entry>
                  <entry>Список экземпляров этого объекта</entry>
                </row>
                <row>
                  <entry><filename>Ofs.a68</filename></entry>
                  <entry>Список адресов полей объекта</entry>
                </row>
                <row>
                  <entry><filename>State.lst</filename></entry>
                  <entry>Список внутренних состояний объекта</entry>
                </row>
                <row>
                  <entry><filename>UsrState.ini</filename></entry>
                  <entry>Описание, необходимое для приложений Абонентская панель (см. разд. «<xref linkend="tri_tri_odin"/>»), Карта состояния абонентов (см. разд. «<xref linkend="tri_tri_dva"/>»), Соединительные линии (см. разд. «<xref linkend="tri_tri_tri"/>») для вывода удобочитаемых состояний объекта. Нужен лишь для некоторых объектов</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>Примечание</command>: не следует пытаться самостоятельно вносить изменения, перемещать, переименовывать или удалять эти файлы, т.к. это приведет к некорректной работе приложений <xref linkend="РМО"/>.</para>
        </section>
        
        <section><title>7.1.3. Файлы настроек приложения. Серверы РМО</title>
          <para>Находятся в подкаталоге <command>Servers</command>. Это файлы: <filename>AbonentStatistics.ini</filename>; <filename>ChannelStatistics.ini</filename>; <filename>CLStat.ini</filename>; <filename>Stat.ini</filename>; <filename>Tarif.ini</filename>.</para>
          <para>Вносить изменения в эти файлы, кроме <filename>Tarif.ini</filename>, пользователю не требуется, параметры файла <filename>Tarif.ini</filename> описаны в разделе «<xref linkend="tri_odin_5"/>».</para>
        </section>
        
        <section><title>7.1.4. Файлы БД РМО</title>
          <para>Файлы <filename>ats.mdb</filename>, <filename>dictionary.mdb</filename>, <filename>rmodb.mdb</filename>. Не следует пытаться вносить в них изменения вручную, т.к. это приведет к некорректной работе приложений <xref linkend="РМО"/>.</para>
        </section>
        
        <section><title>7.1.5. Вспомогательные файлы</title>
          <para>Приложение добавления новых станций – файлы <filename>AddData.exe</filename>, <filename>adddata15.exe</filename>. Приложение, настраивающее <xref linkend="РМО"/> на использование пакета данных. Запускается автоматически программой-инсталлятором пакета данных в конце процесса установки данных <xref linkend="АТС"/>.</para>
          <para>Файл расшифровки системных сообщений – файл <filename>Console.xml</filename>. Несколько атрибутов тега &lt;Console> конфигурируют выносное табло. Ниже приведено их описание:</para>
          <para>Атрибуты тега &lt;Console></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <thead>
                <row><entry>Атрибут</entry><entry>Описание</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>Ioport</entry>
                  <entry>Порт ввода/вывода релейной платы. О настройке платы на конкретный порт см. документацию к плате. В версии <xref linkend="РМО"/> после 30.03.2002 этот параметр используется и для настройки выносного табло. В случае, если значение этого параметра меньше 256, программа будет использовать драйвер для выносного табло, а в качестве имени порта будет использована строчка: «COM» + указанный порт. Нулевое значение этого параметра отключает использование табло</entry>
                </row>
                <row>
                  <entry>Mask</entry>
                  <entry>Маска использования табло. Для использования табло на сервере должен быть установлен первый бит этого параметра. Для использования табло на клиентской машине – второй. Значение по умолчанию: 3</entry>
                </row>
                <row>
                  <entry>Permute</entry>
                  <entry>Определяет преобразование битов байта при посылке в порт релейной платы. Значение по умолчанию: $76543210. Менять это значение нужно в том случае, если неверно осуществлена распайка проводов от платы на аварийное табло. Каждая шестнадцатеричная цифра определяет, на какую позицию перемещать соответствующий бит посылаемого байта. Таким образом, значение по умолчанию определяет нормальное расположение битов. Если, например, требуется поменять местами 4-й и 6-й биты, значение будет выглядеть так: $74563210</entry>
                </row>
                <row>
                  <entry>Fade</entry>
                  <entry>Определяет действие компоненты Консоль Серверов <xref linkend="РМО"/> при нажатии на кнопку <command>Погасить табло</command>. Первый байт определяет те реле, которые следует открыть, второй байт – те реле, которые следует закрыть. Значение по умолчанию: $01fe означает, что при нажатии на кнопку <command>Погасить табло</command> будет включено первое реле, а остальные – выключены</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para>Кроме того, управление табло из файла <filename>Console.xml</filename> производится с помощью атрибута level тэга attr. Значение атрибута level распространяется на все сообщения, описанные внутри тэга attr. В случае вложенных тэгов attr используется значение атрибута level внутреннего тэга attr.</para>
          <para>Значение атрибута level интерпретируется <xref linkend="ПО"/> <xref linkend="РМО"/> как двойное слово. Для записи значения в шестнадцатеричном представлении используется префикс $. Значение интерпретируется следующим образом:</para>
          <itemizedlist>
            <listitem><para>младшие 16 бит определяют категорию сообщения (информационное, авария, ошибка, системное). Каждой категории соответствует тетрада (от младшей к старшей соответственно). Сообщение относится к категории, если значение соответствующей тетрады ненулевое. Например, сообщение с атрибутом level="$00001010" относится к категориям «Авария» и «Системное».</para></listitem>
            <listitem><para>старшие 16 бит используются для управления табло. Младшие 8 бит указывают, какие лампы должны быть погашены на табло при получении команды. Старшие 8 бит указывают, какие лампы должны быть зажжены при получении команды. Например, в результате получения сообщения с атрибутом level="$40010000" будет зажжена лампа №7 и погашена лампа №1.</para></listitem>
          </itemizedlist>
          <para>Дополнительное соответствие логических и физических битов устанавливается атрибутом permute тэга console.</para>
          <para>Файл конфигурации аварий - <filename>tablo.xml</filename>. Настройка аварий производится с помощью панели (см. разд. «<xref linkend="tri_tri_5"/>»).</para>
        </section>
        
        <section><title>7.1.6. Файлы, создаваемые приложениями РМО</title>
          <para>Каталог <command>Tarif</command>: Создается приложением Тарификация: клиент, содержит данные тарификации, скачанные с сервера тарификации. Об использовании см. раздел «<xref linkend="tri_odin_5"/>».</para>
          <para>Файлы <filename>*.cdb</filename> в каталоге <command>Servers</command>: Файлы взаимодействия компонент Серверов <xref linkend="РМО"/> со своими клиентскими частями.</para>
          <para>Файлы <filename>*.bin</filename>, подкаталог <command>Talks</command> в каталоге <command>Servers</command>: Временные файлы компоненты Тарификация Серверов <xref linkend="РМО"/></para>
          <para>Суточные файлы и файлы прямого доступа тарификации: Местоположение задается в конфигурационном файле <filename>Tarif.ini</filename>, см. раздел «<xref linkend="tri_odin_5"/>».</para>
        </section>
      
      </section>            
      
    </chapter>
  </d:InfElement>

</d:DocumentationCore>