<?xml version="1.0" encoding="UTF-8"?>
<d:ProductDocumentation productid="complete" xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

    <d:FinalInfProduct id="UserManual_complete" infproductid="UserManual">
      
      <d:Adapter infelemrefid="ref_implementation_specification"/>
      <d:Adapter infelemrefid="ref_users_problem_description"/>

      <d:Adapter infelemrefid="ref_rate_CTO"/>
      <d:Adapter infelemrefid="ref_script_language"/>
      
      <d:Adapter infelemrefid="ref_visual_library">
        <d:Insert-After nestid="current">
          <row>
            <entry>IScriptListBoxItem * CurrentItem</entry>
            <entry></entry>
            <entry>Выбранный элемент списка</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="sorted">
          <row>
            <entry>VARIANT_BOOL Sorted</entry>
            <entry></entry>
            <entry>Флаг, показывающий будет ли производится сортировка элементов по имени. Соответствует <xref linkend="XML"/>-атрибуту sorted. Значение по умолчанию false</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="checked">
          <row>
            <entry>VARIANT_BOOL Checked</entry>
            <entry>Показывает, выбрана альтернатива или нет. Соответствует <xref linkend="XML"/>-атрибуту checked</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="controls">
          <row>
            <entry>IScriptControls *Controls</entry>
            <entry>(read-only)</entry>
            <entry>Коллекция альтернатив. Содержит элементы типа IScriptRadioButtonOfGroup. В <xref linkend="XML"/> соответствует вложенному элементу controls</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="caption3">
          <row>
            <entry>BSTR Caption</entry>
            <entry></entry>
            <entry>Надпись на компоненте. Соответствует <xref linkend="XML"/>-атрибуту caption</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="caption">
          <row>
            <entry>BSTR Caption</entry>
            <entry>Надпись на компоненте. Соответствует <xref linkend="XML"/>-атрибуту caption</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="cange">
          <row>
            <entry>onCange</entry>
            <entry>Вызывается при изменении содержимого поля ввода. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="dblclick">
          <row>
            <entry>onDblClick</entry>
            <entry>Событие, показывающее, что пользователь дважды щелкнул мышью по компоненте. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="click">
          <row>
            <entry>onClick</entry>
            <entry>Событие, показывающее, что пользователь щелкнул мышью по компоненте. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
          </row>
          <row>
            <entry>onContextPopup</entry>
            <entry>Показывает, что пользователь вывел контекстное меню для этого компонента. Параметры в это событие передаются с помощью интерфейса IScriptContextPopupEventParams</entry>
          </row>
          <row>
            <entry>onEnter</entry>
            <entry>Показывает, что компонента получила фокус ввода. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
          </row>
          <row>
            <entry>onExit</entry>
            <entry>Показывает, что компонента потеряла фокус ввода. Параметры в это событие передаются с помощью интерфейса IScriptEventParams</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="key">
          <row>
            <entry>onKeyDown</entry>
            <entry>Показывает, что пользователь зажал кнопку на клавиатуре. Параметры в это событие передаются с помощью интерфейса IScriptKeyEventParams</entry>
          </row>
          <row>
            <entry>onKeyPress</entry>
            <entry>Показывает, что пользователь нажал и отпустил кнопку на клавиатуре. Параметры в это событие передаются с помощью интерфейса IScriptKeyPressEventParams</entry>
          </row>
          <row>
            <entry>onKeyUp</entry>
            <entry>Показывает, что пользователь отпустил кнопку на клавиатуре. Параметры в это событие передаются с помощью интерфейса IScriptKeyEventParams</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="mouse">
          <row>
            <entry>onMouseDown</entry>
            <entry>Показывает, что пользователь нажал кнопку мыши. Параметры в это событие передаются с помощью интерфейса IScriptMouseMoveEventParams</entry>
          </row>
          <row>
            <entry>onMouseMove</entry>
            <entry>Показывает, что пользователь двигает мышь над компонентой. Параметры в это событие передаются с помощью интерфейса IScriptMouseMoveEventParams</entry>
          </row>
          <row>
            <entry>onMouseUp</entry>
            <entry>Показывает, что пользователь отпустил кнопку мыши. Параметры в это событие передаются с помощью интерфейса IScriptMouseMoveEventParams</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="alt">
          <row>
            <entry>VARIANT_BOOL Alt</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата клавиша <command>Alt</command></entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Shift</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата клавиша <command>Shift</command></entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Ctrl</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата клавиша Ctrl</entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Left</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата левая кнопка мыши</entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Right</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата правая кнопка мыши</entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Middle</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, была ли зажата средняя кнопка мыши</entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Double</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, был ли осуществлен двойной щелчок</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="long">
          <row>
            <entry>LONG X</entry>
            <entry>(read-only)</entry>
            <entry>Горизонтальная координата мыши</entry>
          </row>
          <row>
            <entry>LONG Y</entry>
            <entry>(read-only)</entry>
            <entry>Вертикальная координата мыши</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="pos">
          <row>
            <entry>LONG MousePosX</entry>
            <entry>(read-only)</entry>
            <entry>Горизонтальная координата мыши</entry>
          </row>
          <row>
            <entry>LONG MousePosY</entry>
            <entry>(read-only)</entry>
            <entry>Вертикальная координата мыши</entry>
          </row>
          <row>
            <entry>VARIANT_BOOL Handled</entry>
            <entry>(read-only)</entry>
            <entry>Флаг, показывающий, было ли событие уже обработано каким-либо обработчиком</entry>
          </row>
        </d:Insert-After>
      </d:Adapter>
      
      <d:Adapter infelemrefid="ref_fails"/>
      <d:Adapter infelemrefid="ref_example_trasses"/>


        <d:Adapter infelemrefid="ref_join_in_applications"/>


          <d:Adapter infelemrefid="ref_join_in_sysappl"/>
          <d:Adapter infelemrefid="ref_join_in_embsoft">
            <d:Insert-After nestid="vid">
              <informaltable>
                <tgroup cols="2" align="left" colsep="1" rowsep="1">
                  <colspec colnum="2" colname="c2"/>
                  <thead>
                    <row><entry>Элемент меню</entry><entry>Описание</entry></row>
                  </thead>
                  <tbody>
                   <row>
                      <entry>Отменить</entry>
                      <entry>Отменить последнюю операцию</entry>
                    </row>
                    <row>
                      <entry>Вырезать</entry>
                      <entry>Перемещает выделенное в буфер обмена</entry>
                    </row>
                    <row>
                      <entry>Копировать</entry>
                      <entry>Копирует выделенное в буфер обмена</entry>
                    </row>
                    <row>
                      <entry>Вставить</entry>
                      <entry>Вставляет содержимое буфера обмена</entry>
                    </row>
                    <row>
                      <entry>Удалить</entry>
                      <entry>Удаляет выделенное</entry>
                    </row>
                    <row>
                      <entry>Выделить все</entry>
                      <entry>Выделяет все содержимое</entry>
                    </row>
                  </tbody>
                </tgroup>
              </informaltable>
            </d:Insert-After>            
            <d:Insert-After nestid="script">
            </d:Insert-After>
          </d:Adapter>
          <d:Adapter infelemrefid="ref_join_in_monitoring"/>


      <d:Adapter infelemrefid="ref_review_sp">
        <d:Insert-After nestid="change_characteristic">
          <para><command>Изменение характеристик абонента производится из приложения Конфигуратор.</command></para>
        </d:Insert-After>
        <d:Replace-Nest nestid="cordway_activ_trass">
          <listitem><para>активизировать для текущего абонента средства управления статистикой, тарификацией и тестированием</para></listitem>
          <listitem><para>активизировать для модуля, в котором находится данный абонент, средства просмотра трассы</para></listitem>
          <listitem><para>выполнять «проход по шнуру»</para></listitem>
        </d:Replace-Nest>
      </d:Adapter>

      <d:Adapter infelemrefid="ref_main_window_sp">
        <d:Insert-After nestid="alarm_clock">
           <row>
             <entry>Флажок активации будильника</entry>
             <entry> </entry>
           </row>
           <row>
             <entry>Будильник</entry>
             <entry>Время на которое заказан <xref linkend="ДВО"/> «Будильник»</entry>
           </row>
        </d:Insert-After>
        <d:Insert-After nestid="alarm_clock_a">
           <row>
             <entry>Будильник</entry>
             <entry>Автопобудка</entry>
           </row>
        </d:Insert-After>
        <d:Insert-After nestid="appl_from_com">
          <para><command>Приложения РМО, запускаемые из меню Команды</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <tbody>
                <row>
                  <entry>Пройти по шнуру</entry>
                  <entry>Нажмите эту кнопку, если вы хотите посмотреть последовательное проключение (цепочку) в поле начиная с текущего абонента</entry>
                </row>
                <row>
                  <entry>Проключить</entry>
                  <entry>Вызывается приложение, с помощью которого можно проключить тракт-канал этого абонента в необходимый тракт-канал</entry>
                </row>
                <row>
                  <entry>Тест <xref linkend="АК"/></entry>
                  <entry>Нажатием этой кнопки активизируется панель теста абонентской линии, которая предназначена для измерения параметров линии</entry>
                </row>
                <row>
                  <entry>Трасса</entry>
                  <entry>Вызывается приложение, с помощью которого можно посмотреть трассу модуля, в котором находится данный абонент</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para>При запуске любого из первых 3-х перечисленных приложений производится автофокусировка на текущего абонента. Причем, так же имеется и обратная возможность активизации абонентской панели из указанных панелей. Более подробную информацию об этой возможности читайте в разделах описания соответствующих приложений.</para>
        </d:Insert-After>
      </d:Adapter>

      <d:Adapter infelemrefid="ref_standart_tasks_sp">
        <d:Insert-After nestid="z7_inclus_trass">
          <section><title id="zad_7" xreflabel="Задача 7. Включение трассировки абонентов">Задача 7. Включение трассировки абонентов</title>
            <itemizedlist>
              <listitem><para><emphasis>Шаг 7a)</emphasis> Выберите в списке <emphasis>Номер</emphasis> требуемого абонента</para></listitem>
              <listitem><para><emphasis>Шаг 7b)</emphasis> Нажмите кнопку <emphasis>Заблокировать</emphasis></para></listitem>
              <listitem><para><emphasis>Шаг 7c)</emphasis> Включите флаг <emphasis>Признак трассировки</emphasis></para></listitem>
              <listitem><para><emphasis>Шаг 7d)</emphasis> Нажмите кнопку <emphasis>Записать</emphasis></para></listitem>
              <listitem><para><emphasis>Шаг 7e)</emphasis> Нажмите кнопку <emphasis>Разблокировать</emphasis></para></listitem>
            </itemizedlist> 
            <important><para><emphasis>Замечание:</emphasis> Выключение трассировки выполняется аналогично, но на шаге 4 следует выключить флаг <emphasis>Признак трассировки</emphasis>.</para></important> 
          </section>
        </d:Insert-After>
      </d:Adapter>



      <d:Adapter infelemrefid="ref_review_b">
        <d:Insert-After nestid="occupy_channel_ftesting">
          <listitem><para>захватывать канал для тестирования</para></listitem>
        </d:Insert-After>
      </d:Adapter>

      <d:Adapter infelemrefid="ref_main_window_b">
        <d:Insert-After nestid="switching_on_trace">
          <para id="zad_1" xreflabel="Задача 1. Включение трассировки каналов"><command>Задача 1. Включение трассировки каналов</command></para>
          <itemizedlist>
            <listitem><para><emphasis>Шаг 1a)</emphasis> Запустите приложение <emphasis>Соединительные линии</emphasis> (см. разд. «<xref linkend="tri_tri_tri"/>»)</para></listitem>
            <listitem><para><emphasis>Шаг 1b)</emphasis> Нажмите кнопку <emphasis>Состояние тракта</emphasis>, появиться окно <emphasis>Состояние трактов/канальных групп</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1c)</emphasis> Выберите в списке в верхней части окна нужный тракт, после чего в нижней части окна появиться список существующих каналов</para></listitem>
            <listitem><para><emphasis>Шаг 1d)</emphasis> Выберите в списке в нижней части окна нужный канал или группу каналов</para></listitem>
            <listitem><para><emphasis>Шаг 1e)</emphasis> Во всплывающем меню выберите пункты <emphasis>Включить трассу объекта(ов) ЗОВСл</emphasis> и <emphasis>Включить трассу объекта(ов) сигнализации</emphasis></para></listitem>
          </itemizedlist>  
          <tip><para>Замечание: Выключение трассировки выполняется аналогично, но на шаге 5 следует выбрать пункт <emphasis>Выключить трассу объекта(ов) ЗОВСл</emphasis> и <emphasis>сигнализации</emphasis> соответственно.</para></tip>        
        </d:Insert-After>
      </d:Adapter>

      <d:Adapter infelemrefid="ref_state_sections_b">
        <d:Insert-After nestid="attention_operation">
          <tip><para>Внимание! Некоторые операции над трактами и каналами могут быть реализованы скриптами. Описание таких команд находится в разделе справки Скрипты и тесты (см. разд. «<xref linkend="tri_4_4"/>»).</para></tip>
        </d:Insert-After>
        <d:Insert-After nestid="mov_info_section">
          <para><command>Список всех возможных типов динамической информации о тракте</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <tbody>
                <row>
                  <entry>Есть DL соед.</entry>
                  <entry>Наличие DL-соединения (см. «<xref linkend="DL-j"/>») <xref linkend="DSS-1"/></entry>
                </row>
                <row>
                  <entry>BRI/PRI</entry>
                  <entry>Режим <xref linkend="DSS-1"/></entry>
                </row>
                <row>
                  <entry>Тек. B</entry>
                  <entry>Канал – номер B-канала (см. «<xref linkend="B-c"/>»), предназначенного для следующего вызова (<xref linkend="DSS-1"/>)</entry>
                </row>
                <row>
                  <entry>Тек. <xref linkend="CR"/></entry>
                  <entry>Указатель на <xref linkend="CR"/>, предназначенную для назначения, равный численной величине <xref linkend="CR"/> (<xref linkend="DSS-1"/>)</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </d:Insert-After>
        <d:Insert-After nestid="operation_on_sections">
          <para><emphasis>Информация о тракте</emphasis></para>
          <para><command>Список всех возможных операций над трактами</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <tbody>
                <row>
                  <entry>Сбросить интерфейс</entry>
                  <entry>Послать команду "сброс" интерфейсу <xref linkend="DSS-1"/></entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </d:Insert-After>
        <d:Insert-After nestid="mov_info_restart">
          <row>
            <entry>Рестарт</entry>
            <entry>Рестарт по каналу (<xref linkend="DSS-1"/>)</entry>
          </row>
          <row>
            <entry>П/п пр.</entry>
            <entry>Полупостоянное проключение (<xref linkend="DSS-1"/>)</entry>
          </row>
          <row>
            <entry>Блокир</entry>
            <entry>Канал заблокирован (<xref linkend="DSS-1"/>)</entry>
          </row>
          <row>
            <entry>Занят</entry>
            <entry>Канал занят (<xref linkend="DSS-1"/>)</entry>
          </row>
          <row>
            <entry>Инд.</entry>
            <entry>Индекс пары объектов, выделенных для обслуживания вызова (<xref linkend="DSS-1"/>)</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="mov_info_flag">
          <row>
            <entry>ПриоИсх</entry>
            <entry>Флаг приоритета исходящей связи (<xref linkend="ОКС7"/>)</entry>
          </row>
        </d:Insert-After>
        <d:Insert-After nestid="operation_channel_15">
          <row>
            <entry>Установить каналу(ам) признак «Блокирован»</entry>
            <entry>Для всех выделенных каналов</entry>
          </row>
          <row>
            <entry>Сбросить каналу(ам) признак «Блокирован»</entry>
            <entry>Для всех выделенных каналов</entry>
          </row>
        </d:Insert-After>
      </d:Adapter>
      
      <d:Adapter infelemrefid="ref_review_sm">
        <d:Insert-After nestid="ordered_modules">
          <para>Приложение позволяет заказать модули, информация о состоянии которых будет загружаться из станции.</para>
        </d:Insert-After>
      </d:Adapter>        
        
      <d:Adapter infelemrefid="ref_main_window_sm">
        <d:Replace-Nest nestid="main_win">
          <title>Главное окно "Состояния абонентов"</title>
          <para>Главное окно программы имеет следующий вид:</para>
          <informalfigure>
            <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\AbnStatesPich01.gif"/>
          </informalfigure>
        </d:Replace-Nest>
        <d:Replace-Nest nestid="refl">отображены</d:Replace-Nest>
        <d:Replace-Nest nestid="mult">набор</d:Replace-Nest>
        <d:Insert-After nestid="balk_20">
          <informalfigure>
            <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\AbnStatesPich03.gif"/>
          </informalfigure>
        </d:Insert-After>
        <d:Replace-Nest nestid="color">цвет квадратика</d:Replace-Nest>
        <d:Insert-After nestid="color_info">, полная информация о расцветках отражена в окне «Легенда»</d:Insert-After>
        <d:Insert-After nestid="color_name">
          <para><command>Цвет заголовка названия модуля соответствует состоянию модуля :</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <tbody>
                <row>
                  <entry>Серый</entry>
                  <entry>информация о модуле еще не прочитана, это изначальное состояние</entry>
                </row>
                <row>
                  <entry>Зелёный</entry>
                  <entry>модуль активен</entry>
                </row>
                <row>
                  <entry>Красный</entry>
                  <entry>модуль не ответил на запрос</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>Цвет текста названия модуля соответсвтвует заказанности модуля :</command></para>
          <informaltable>
            <tgroup cols="2" align="left" colsep="1" rowsep="1">
              <colspec colnum="2" colname="c2"/>
              <tbody>
                <row>
                  <entry>Черный</entry>
                  <entry>модуль заказан в списке опрашиваемых модулей</entry>
                </row>
                <row>
                  <entry>Белый</entry>
                  <entry>модуль не заказан в списке опрашиваемых модулей</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
        </d:Insert-After>
        <d:Insert-After nestid="win_legend"><para><emphasis>Окно "Легенда"</emphasis></para></d:Insert-After>
        <d:Insert-After nestid="renew_ab">Для обновления состояния конкретного модуля необходимо подвести указатель мыши на название модуля и нажать правую кнопку, во всплывающем меню выбрать пункт <emphasis>Обновить модуль</emphasis>. Приложение предоставляет возможность активировать(деактивировать) загрузку состояний выбранного модуля. Данная возможность реализуется выбором соответствующего пункта всплывающего меню на названии модуля. Список опрашиваемых модулей отображается в окне «Выбор модулей». </d:Insert-After>
        <d:Replace-Nest nestid="at_that">После нажатия на кнопку</d:Replace-Nest>
        <d:Insert-After nestid="win_curstat"><para><emphasis>Окно "Текущая статистика по абонентским линиям"</emphasis></para></d:Insert-After>
        <d:Replace-Nest nestid="for_it">просмотра</d:Replace-Nest>
        <d:Replace-Nest nestid="whereupon">нажатие вызовет</d:Replace-Nest>
        <d:Insert-After nestid="choise_module">
          <para><emphasis>Окно "Выбор модулей"</emphasis></para>
          <para>Пользователь имеет возможность сформировать список модулей, информация о состоянии которых будет загружаться из станции. Нажатие дополнительной секции кнопки <emphasis>Обновить</emphasis> ( <inlinegraphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sostojanie-ab-knopka-obnovit.gif"/> ) в верхней части окна и выбор пункта <emphasis>Модули</emphasis> вызовет появление окна «Выбор модулей»:</para>
          <informalfigure>
            <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\AbnStatesPich02.gif"/>
          </informalfigure> 
          <para>Для заказа модулей, информация о состоянии которых будет загружаться из станции, неодходимо подвести указатель мыши к полю активации и нажать правую кнопку. Цвет текста названий модулей, отображённых в главном окне «Состояния абонентов», примет соответствующую окраску.</para> 
          <para>В левом нижнем углу окна находится кнопка групповой операции <emphasis>Выбрать все</emphasis>(<emphasis>Очистить все</emphasis>), нажатие которой вызывает активацию(деактивацию) всех модулей списка «Опрашиваемые модули».</para>
          <para>Кнопки <emphasis>Обновить</emphasis> и <emphasis>Не Обновлять</emphasis> закрывают окно «Выбор модулей», обновляя и, соответственно, не обновляя состояния абонентов.</para>
        </d:Insert-After>
      </d:Adapter>
      
        <d:Adapter infelemrefid="ref_sentence_15_sm"/>
        <d:Adapter infelemrefid="ref_renewal_15_sm"/>
        <d:Adapter infelemrefid="ref_identif_15_sm"/>
      
      <d:Adapter infelemrefid="ref_menu_sm"/>
    
    </d:FinalInfProduct>

    <d:Dictionary id="main" name="main_dictionary">
      <d:Entry id="productname">РМО 1.5</d:Entry>
    </d:Dictionary>


</d:ProductDocumentation>