<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="RMO_panel" name="Панель РМО">
    <section><title id="tri_odin_4etn" xreflabel="3.1.14. Панель РМО">3.1.14. Панель РМО</title>

    <section><title>Главное окно</title>
      <para>Главное окно <xref linkend="РМО"/> выглядит следующим образом:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\klient.gif"/>
        </informalfigure>
      <para>В строке заголовка отображается информация о текущем пользователе.</para>
      <para>Пункты главного меню:</para>
        <itemizedlist>
          <listitem><para>Файл</para></listitem>
          <listitem><para>Станция</para></listitem>
          <listitem><para>Настройки</para></listitem>
          <listitem><para>Справка</para></listitem>
          <listitem><para>Пуск</para></listitem>
        </itemizedlist>
      <para>В строке состояния отображается информация о текущем соединении со станцией.</para>
      <para><command>Меню Файл</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Пункт меню</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Завершить сеанс</entry>
              <entry>Перерегистрироваться для изменения текущих прав</entry>
            </row>
            <row>
              <entry>Версии</entry>
              <entry>Просмотреть версии программных компонент</entry>
            </row>
            <row>
              <entry>Выход</entry>
              <entry>Завершить работу с <xref linkend="РМО"/></entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>  
      <para><command>Меню Станция</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Пункт меню</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Имя станции</entry>
              <entry>Соединиться с указанной станцией</entry>
            </row>
            <row>
              <entry>Разорвать соединение</entry>
              <entry>Разорвать текущее соединение со станцией</entry>
            </row>
            <row>
              <entry>Новая станция</entry>
              <entry>Добавить в список новую станцию</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable> 
      <para>В меню <emphasis>Настройки</emphasis> перечислен набор параметров, каждый из которых может быть либо «включен» (тогда напротив него ставится галочка), либо «выключен»:</para>
      <para><command>Меню Настройки</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Пункт меню</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Права</entry>
              <entry>Вызов приложения Права доступа (см. разд. «<xref linkend="tri_odin_p9t"/>»)</entry>
            </row>
            <row>
              <entry>Главное окно -> Располагать поверх остальных окон</entry>
              <entry>Располагать данное окно поверх остальных</entry>
            </row>
            <row>
              <entry>Главное окно -> Зафиксировать положение окна</entry>
              <entry>Предотвратить нежелательные перемещения окна по экрану</entry>
            </row>
            <row>
              <entry>Главное окно -> Зафиксировать позицию окна</entry>
              <entry>Запоминать позицию окна при выходе из <xref linkend="РМО"/></entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para><command>Меню Справка</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Пункт меню</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Содержание</entry>
              <entry>Открыть содержание справки</entry>
            </row>
            <row>
              <entry>Поиск</entry>
              <entry>Открыть окно поиска по справке</entry>
            </row>
            <row>
              <entry>Справка Windows</entry>
              <entry>Как пользоваться справкой</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para>В меню <emphasis>Пуск</emphasis> перечислены клиентские приложения <xref linkend="РМО"/>. Выбор какого-либо пункта меню приводит к запуску соответствующего приложения.</para>
    </section>

    <section><title>Идентификация пользователя</title>
      <para>После запуска <xref linkend="РМО"/> или при выборе пункта меню <emphasis>Файл -> Завершить сеанс</emphasis> появляется панель Идентификация пользователя:</para>
      <informalfigure>
        <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\klient-idetifikatzija-polzov.gif"/>
      </informalfigure>
      <para>Каждому типу пользователей <xref linkend="РМО"/> предоставлен свой набор прав (возможность выполнять определенные действия). После ввода правильного имени пользователя и подтверждающего имя пароля осуществляется вход пользователя в систему с предоставлением ему соответствующих прав.</para>
      <para>В результате недокументированой ошибки Программного Интерфейса Windows при старте <xref linkend="РМО"/> окно идентификации пользователя может не появиться на экране. В этом случае для идентификации нужно принудительно открыть это окно, выбрав в меню <emphasis>Файл</emphasis> команду <emphasis>Завершить сеанс</emphasis>.</para>
    </section>

    <section><title>Соединение со станцией</title>
      <para>Для работы со станцией необходимо установить с ней соединение. После выбора желаемой станции в меню <emphasis>Станция</emphasis> <xref linkend="РМО"/> пытается подключиться к ней. Подключение состоит из нескольких этапов, которые при отсутствии проблем проходят достаточно быстро. Если панель <emphasis>Установка соединения со станцией…</emphasis> долгое время не исчезает с экрана, то существуют проблемы с установкой соединения.</para>
      <para>В этом случае рекомендуется проверить соединительные кабели, идущие от <xref linkend="ПК"/> к станции. Процесс установки соединения можно прервать в любое время нажатием кнопки <emphasis>Отмена</emphasis>.</para>
      <informalfigure>
        <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\клиент-соединение-со-станци.gif"/>
      </informalfigure>
      <para>Во время установки соединения в окне соединения со станцией отображается индикатор, отображающий текущее состояние соединения:</para>
      <para><command>Состояние соединения</command></para>
      <informaltable>
        <tgroup cols="3" align="left" colsep="1" rowsep="1">
          <colspec colnum="3" colname="c3"/>
          <thead>
            <row><entry> </entry><entry>Цвет</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\Circle-Red.jpg"/>
              </entry>
              <entry>Красный</entry>
              <entry>Произошла ошибка</entry>
            </row>
            <row>
              <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\Circle-Magenta.jpg"/>
              </entry>
              <entry>Розовый</entry>
              <entry>Программа пытается инициализировать COM порт (см. "<xref linkend="COM-p"/>")</entry>
            </row>
            <row>
              <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\Circle-Yellow.jpg"/>
              </entry>
              <entry>Желтый</entry>
              <entry>Производится установка соединения со станцией</entry>
            </row>
            <row>
              <entry>
                  <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\Circle-Cyan.jpg"/>
              </entry>
              <entry>Голубой</entry>
              <entry>Завершающая стадия установки соединения</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
    </section>

    <section><title>Версии</title>
      <para>Используйте панель Версии для проверки состояния версии <xref linkend="РМО"/>. Вы можете получить следующую информацию:</para>
        <itemizedlist>
          <listitem><para>Версия <xref linkend="РМО"/></para></listitem>
          <listitem><para>Дата сборки</para></listitem>
          <listitem><para>Общее состояние версии</para></listitem>
          <listitem><para>Справка</para></listitem>
          <listitem><para>Состояние каждого файла в отдельности</para></listitem>
        </itemizedlist>
      <para>Проверка версии <xref linkend="РМО"/> выполняется с помощью контрольного файла <filename>Version.xml</filename>, который входит в поставку <xref linkend="РМО"/>. Состояние версии устанавливается в «OK», если все файлы <xref linkend="РМО"/> соответствуют контрольному файлу, в противном случае указывается количество ошибок.</para>
      <para>Панель содержит дерево из двух веток:</para>
        <itemizedlist>
          <listitem>
            <para><emphasis>Файлы <xref linkend="РМО"/></emphasis> – содержит все файлы, входящие в поставку <xref linkend="РМО"/> (кроме файла <filename>Version.xml</filename>).</para></listitem>
          <listitem><para><emphasis>Аварийные файлы</emphasis> – содержит только те файлы, состояние которых отлично от ОК.</para></listitem>
          <listitem><para><emphasis>Файл</emphasis> – имя файла <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\panel-rmo-versija.gif"/></para></listitem>
          <listitem><para><emphasis>Версия</emphasis> – десятичное число, обозначающее номер версии</para></listitem>
          <listitem><para><emphasis>Тип</emphasis> – способ контроля версии файла</para>
            <itemizedlist>
              <listitem><para>- – версия файла не контролируется, значения поля <emphasis>Версия</emphasis> будет всегда пусто</para></listitem>
              <listitem><para>ins – номер версии прошит в файл</para></listitem>
              <listitem><para>crc – проверка контрольной суммы файла</para></listitem>
            </itemizedlist>
          </listitem>
          <listitem><para><emphasis>Состояние</emphasis> – результат проверки версии</para>
            <itemizedlist>
              <listitem><para>OK – правильная версия файла</para></listitem>
              <listitem><para>Неизвестная версия – версия не прошита в файл, либо не совпадает контрольная сумма файла</para></listitem>
              <listitem><para>Версия не совпадает – версия файла отличается от версии указанной в контрольном файле</para></listitem>
              <listitem><para>Ошибка при чтении версии – не удалось прочитать версию, возможно файл кем-то используется, например, открыт файл справки, в этом случае его следует закрыть и повторить проверку</para></listitem>
              <listitem><para>Файл не найден – файл не найден в папке</para></listitem>
            </itemizedlist>
          </listitem>
        </itemizedlist>
        <para>Чтобы повторно выполнить проверку версий выберите во всплывающем меню <emphasis>Обновить</emphasis>.</para>
    </section>

    </section>
  </d:InfElement>

</d:DocumentationCore>