<?xml version = "1.0" encoding = "UTF-8"?>
<d:ProductDocumentation xmlns="http://docbook.org/ns/docbook" xmlns:d="http://math.spbu.ru/drl" productid = "enterprise">
   <d:FinalInfProduct id = "UserManual_enterprise" infproductid = "UserManual">
     <d:Adapter infelemrefid = "ref_antivirus">
       <d:Replace-Nest nestid = "extended_actions">
         <listitem> <para> placement in quarantine </para> </listitem>
         <listitem> <para> request for assistance from the representative InterBez in your firm </para> </listitem>
       </d:Replace-Nest>
     </d:Adapter>
     <d:Adapter infelemrefid = "ref_firewall_config"> </d:Adapter>
     <d:Adapter infelemrefid = "ref_antivirus_config"> </d:Adapter>
     <d:Adapter infelemrefid = "ref_update_local"> </d:Adapter>
     <d:Adapter infelemrefid = "ref_components_update">
       <d:Insert-After nestid = "av-update">
         <para>
           Most likely all the settings already made your system administrator.
         </para>
       </d:Insert-After>
       <d:Insert-After nestid = "as-update">
         <para>
           InterBez Corporate central local server uses to detect
           spam. In settings need to specify its address. To obtain the addresses
           contact with the system administrator.
         </para>
       </d:Insert-After>
     </d:Adapter>
     <d:Adapter infelemrefid = "ref_antispam"> 
     </d:Adapter>
   </d:FinalInfProduct>
  
   <d:Dictionary id = "main" name = "Chief Slovar">
     <d:Entry id = "productname">InterBez Corporate </d:Entry>
   </d:Dictionary>
</d:ProductDocumentation>