<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

 <d:InfElement id="service_map" name="Карта обслуживания абонентских линий">
    <section><title id="tri_tri_dva" xreflabel="3.3.2. Карта обслуживания абонентских линий">3.3.2. Карта обслуживания абонентских линий</title>
      <d:InfElemRef id="ref_review_sm" infelemid="review_sm"/>
      <d:InfElemRef id="ref_main_window_sm" infelemid="main_window_sm"/>
      <d:InfElemRef id="ref_menu_sm" infelemid="menu_sm" optional="true"/>
    </section>
  </d:InfElement>
  
  <d:InfElement id="review_sm" name="Обзор">
    <section><title>Обзор</title>
      <para>Данное приложение предназначено для просмотра и анализа состояний абонентских линий станции.</para>
      <para>C его помощью оператор может посмотреть текущую статистику состояний в виде диаграммы.</para>      
      <d:Nest id="ordered_modules"/>
      <para>Приложение также включает в себя возможность атоматического обновления текущих состояний через определённые оператором промежутки времени.</para>
    </section>
  </d:InfElement>
  
  <d:InfElement id="main_window_sm" name="Главное окно">
    <section>
      <d:Nest id="main_win">
        <title>Главное окно</title>
        <para>Главное окно программы выглядит так:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sostojanie-abonenta.gif"/>
        </informalfigure>
      </d:Nest>
      <d:InfElemRefGroup id="sent" modifier="XOR" name="Предложение"/>
      <para><d:InfElemRef id="ref_sentence_15_sm" infelemid="sentence_15_sm" groupid="sent" optional="true"/> На форме этого приложения <d:Nest id="refl">вы увидите</d:Nest> все абонентские модули станции, каждому из которых соответствует <d:Nest id="mult">некоторое множество</d:Nest> квадратиков (как правило 128), расположенных ниже названия этого модуля.</para>
      <d:Nest id="balk_20"/>
      <para>Каждый из квадратиков символизирует <d:Nest id="soboj"/> абонента этого модуля, <d:Nest id="color">а его цвет</d:Nest> – состояние этого абонента (белым цветом отображаются абоненты, состояния которых не удалось прочитать из станции<d:Nest id="color_info"/>). <d:InfElemRef id="ref_sentence_443_sm" infelemid="sentence_443_sm" groupid="sent" optional="true"/></para>
      <d:Nest id="color_name"/>
      <d:InfElemRefGroup id="renewal" modifier="XOR" name="Обновление абонентов"/>
      <d:InfElemRefGroup id="identif" modifier="XOR" name="Идентификация абонентов"/>
      <para><d:InfElemRef id="ref_renewal_15_sm" infelemid="renewal_15_sm" groupid="renewal" optional="true"/> <d:Nest id="renew_ab"/><d:InfElemRef id="ref_identif_15_sm" infelemid="identif_15_sm" groupid="identif" optional="true"/></para>
      <d:Nest id="win_legend"/>
      <para>Для просмотра легенды цветов состояний нужно нажать на кнопку <emphasis>Легенда</emphasis> ( <inlinegraphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sost-ab-knopka-legenda.gif"/> ) в верхней части окна приложения.</para>
      <para><d:Nest id="at_that">При этом</d:Nest> появится окно в котором каждому цвету квадратика сопоставлено состояние абонента. В появившейся панели вы увидите список, которым устанавливаются однозначные соответствия : номер – цвет и цвет – Состояние Абонента.</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sost-ab-legenda.gif"/>
        </informalfigure>
      <d:Nest id="win_curstat"/>
      <d:InfElemRef id="ref_identif_443_sm" infelemid="identif_443_sm" groupid="identif" optional="true"/>
      <para><d:Nest id="sooner"/>Имеется возможность посмотреть диаграмму состояний абонентских линий и статистику по ним. Для <d:Nest id="for_it">этого</d:Nest> необходимо нажать на кнопку <emphasis>Диаграмма</emphasis> ( <inlinegraphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sost-ab-knopka-statistika.gif"/> ) верхней части окна приложения, <d:Nest id="whereupon">после чего</d:Nest> появится панель с диаграммой, на которой будет изображена диаграмма по цветам состояний и количеству абонентских линий, находящихся в соответствующем состоянии.</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sost-ab-statistika.gif"/>
        </informalfigure>
      <para>Для обновления состояний абонентских линий необходимо нажать кнопку <emphasis>Обновить</emphasis> ( <inlinegraphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\sostojanie-ab-knopka-obnovit.gif"/> ) в верхней части окна.</para>
      <d:InfElemRef id="ref_renewal_443_sm" infelemid="renewal_443_sm" groupid="renewal" optional="true"/>
      <d:Nest id="choise_module"/>
    </section>
  </d:InfElement>
  

  
  <d:InfElement id="sentence_15_sm" name="предложение15">
    В нижней части окна приложения есть информация о названии станции.
  </d:InfElement>
  
  <d:InfElement id="sentence_443_sm" name="предложение443">
    В нижней части окна приложения есть информация о названии станции.
  </d:InfElement>
  
  <d:InfElement id="renewal_15_sm" name="обновление15">
    Чтобы активизировать автоматическое обновление состояний абонентских линий необходимо нажать на правую часть этой кнопки и в появившемся меню выбрать необходимый период времени обновления (из представленных: 5, 10 или 30 секунд). При этом будут обновляться состояния абонентов, которые заказаны в списке опрашиваемых модулей. Для обновления состояния всех абонентских модулей станции (в случае если какой-то модуль во время последней загрузки был недоступен), то необходимо выбрать пункт меню <emphasis>Обновить все</emphasis>. Для прекращения автоматического обновления необходимо в том же меню выбрать <emphasis>Стоп</emphasis>. Следует заметить, что после обновления состояний и при открытом окне статистики абонентских линий, последняя обновляется автоматически.
  </d:InfElement>
  
  <d:InfElement id="renewal_443_sm" name="обновление443">
    <para>Чтобы активизировать автоматическое обновление состояний абонентских линий необходимо нажать на правую часть этой кнопки и в появившемся меню выбрать необходимый период времени обновления (из представленных: 1, 5, 10 или 30 секунд). При этом будут обновляться состояния только тех абонентов, которые были доступны при последней загрузке данных из станции. Если же хочется обновить состояния по всем абонентским модулям станции (в случае если какой-то модуль во время последней загрузки был недоступен), то необходимо выбрать пункт меню <emphasis>Обновить все</emphasis>. Для прекращения автоматического обновления необходимо в том же меню выбрать <emphasis>Стоп</emphasis>. Следует заметить, что после обновления состояний и при открытом окне статистики абонентских линий, последняя обновляется автоматически.</para>
  </d:InfElement>
  
  <d:InfElement id="identif_15_sm" name="идентификация15">
    Для удобства идентификации абонента есть возможность посмотреть его номер и расшифровку состояния. Для этого подведите указатель мыши к соответствующему абоненту, вызовется всплывающая подсказка, которая содержит указанную выше информацию. Для получения более полной информации по интересующему вас абоненту имеется возможность перейти в приложение Абонентская панель (см. разд. «3.3.1 Абонентская панель»). Переход в приложение Абонентская панель осуществляется нажатием правой кнопки мыши на интересующем абоненте и в появившемся меню нажать на пункт <emphasis>Абонент</emphasis>.
  </d:InfElement>
  
  <d:InfElement id="identif_443_sm" name="идентификация443">
    <para>Для удобства идентификации абонента есть возможность посмотреть его номер и названия состояния. Для этого просто подведите указатель мыши к соответствующему абоненту, после чего выплывет подсказка, в которой вы получите указанную выше информацию. Для получения более полной информации по интересующему вас абоненту имеется возможность перейти в приложение Абонентская панель (см. разд. « Абонентская панель»), для чего нужно нажать правую кнопку на интересующем абоненте и в появившемся меню нажать на пункт <emphasis>Абонент</emphasis>.</para>
  </d:InfElement>
  
  <d:InfElement id="menu_sm" name="Меню окна">
    <section><title>Меню</title>
      <para><emphasis>Главное меню окна «Состояния абонентов».</emphasis></para>
      <para>Главное меню окна «Состояния абонентов» представлено пиктограммами в верхней части окна.</para>
      <para><command>Главное меню окна «Состояния абонентов»</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Элемент меню/подменю</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Обновить</entry>
              <entry>Обновление состояний заказанных модулей</entry>
            </row>
            <row>
              <entry>Обновить -> Стоп</entry>
              <entry>Остановка обновления состояний заказанных модулей</entry>
            </row>
            <row>
              <entry>Обновить -> 5 секунд</entry>
              <entry>Автоматическое обновление состояний заказанных модулей через каждые 5 секунд</entry>
            </row>
            <row>
              <entry>Обновить -> 10 секунд</entry>
              <entry>Автоматическое обновление состояний заказанных модулей через каждые 10секунд</entry>
            </row>
            <row>
              <entry>Обновить -> 30 секунд</entry>
              <entry>Автоматическое обновление состояний заказанных модулей через каждые 30секунд</entry>
            </row>
            <row>
              <entry>Обновить -> Обновить</entry>
              <entry>Обновление состояний заказанных модулей</entry>
            </row>
            <row>
              <entry>Обновить -> Обновить все</entry>
              <entry>Обновление состояний всех модулей</entry>
            </row>
            <row>
              <entry>Обновить -> Модули...</entry>
              <entry>Открытие окна «Выбор модулей»</entry>
            </row>
            <row>
              <entry>Легенда</entry>
              <entry>Открытие окна «Легенда»</entry>
            </row>
            <row>
              <entry>Статистика</entry>
              <entry>Открытие окна «Текущая статистика по абонентским линиям»</entry>
            </row>
            <row>
              <entry>Справка</entry>
              <entry>Открытие окна «Помощь»</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para><emphasis>Всплывающие меню окна «Состояния абонентов».</emphasis></para>
      <para>Окно «Состояния абонентов» имеет два всплывающих меню: «Модуль» и «Абонент». Всплывающее меню «Модуль» активизируется при установке указателя мышки на название выбранного модуля и нажатии правой кнопки. Всплывающее меню «Абонент» активизируется при установке указателя мышки квадратик абонента и нажатии правой кнопки</para>
      <para><command>Всплывающее меню «Модуль»</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Элемент меню/подменю</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Обновить модуль</entry>
              <entry>Обновление выбранного модуля</entry>
            </row>
            <row>
              <entry>Добавить в список</entry>
              <entry>Активирование заказа обновления модуля в списке опрашиваемых модулей</entry>
            </row>
            <row>
              <entry>Удалить из списка</entry>
              <entry>Деактивирование заказа обновления модуля в списке опрашиваемых модулей</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <important><para><emphasis>Замечание</emphasis>: Во время ожидания ответа станции всплывающее меню названия модуля не доступно.</para></important>
      <para><command>Всплывающее меню «Абонент»</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Элемент меню/подменю</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Абонент (номер абонента)</entry>
              <entry>Запуск приложения «Абонентская панель»</entry>
            </row>
            <row>
              <entry>Пройти по шнуру</entry>
              <entry>Проход по шнуру</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
    </section>
  </d:InfElement>

</d:DocumentationCore>