<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="users_problem_description" name="Описание задач пользователя">
    <chapter>
      <title>Описание задач пользователя</title>
      
      <section><title id="dva_odin" xreflabel="2.1. Установка и настройка">2.1. Установка и настройка</title>
      
        <section><title>2.1.1. Введение</title>
          <para>Данная инструкция относится к установке комплекса приложений «Рабочее Место Оператора 1.5» (далее <xref linkend="РМО"/> 1.5) под операционные системы Windows 2000 Professional (далее W2000) и Windows XP Professional (далее WXP). Под другими операционными системами <xref linkend="РМО"/> 1.5 работать не будет. Также возможен случай, когда <xref linkend="РМО"/> 1.5 не будет работать под W2000, вследствие сильного «засорения» реестра операционной системы. В таком случае рекомендуется переставить операционную систему. Если система «чистая», гарантируется корректная работа <xref linkend="РМО"/> 1.5. Описание представляет собой список компонент, которые необходимо установить.</para>
        </section>
        
        <section><title>2.1.2. Подготовка системы</title>
          <para>Если на машине была установлена предыдущая версия <xref linkend="РМО"/> или системных библиотек <xref linkend="РМО"/>, то их необходимо удалить. Сделать это можно с помощью команды <emphasis>Установка/удаление программ</emphasis> в контрольной панели. Перед удалением <xref linkend="РМО"/> и системных библиотек необходимо закрыть ВСЕ приложения <xref linkend="РМО"/> и файлы справки. Если в процессе удаления произошли какие-либо ошибки удаляющая программа предложит послать письмо в службу поддержки, что настоятельно рекомендуется сделать. После удаления в каталоге <xref linkend="РМО"/> могут остаться некоторые файлы, их рекомендуется удалить вручную.</para>
          <para>В случаи установки <xref linkend="РМО"/> 1.5 в операционной системе W2000 требуется убедится, что в системе установлен пакет сервисных обновлений (service pack) версии 4 или старше. Проверить наличие пакета можно щелкнув правой кнопкой мыши на значке <emphasis>Мой компьютер</emphasis> и выбрав пункт <emphasis>Свойства</emphasis> в открывшемся контекстном меню. Появившееся окно будет содержать информацию о версии установленной операционной системы (включая версию пакета сервисных обновлений), лицензии на операционную систему и основных параметров компьютера. Если в окне показана версия пакета обновлений менее 4 или не показана вообще, нужно установить пакет с помощью файла <command>w2ksp4_en.exe</command>. Корректность установки пакета следует проверить описанным выше способом, если информация о версии системы по прежнему указывает на более младшую версию пакета обновлений или не показывает информации о нем вообще следует обратиться к системному администратору.</para>
          <para>В случае установки <xref linkend="РМО"/> 1.5 в операционной системе WXP требуется убедится, что в системе установлен пакет сервисных обновлений (service pack) версии 1 или старше. Процесс проверки наличия пакета аналогичен вышеописанному, а для установки следует использовать файл <command>xpsp1_1106_Final.exe.</command></para>
        </section>
        
        <section><title>2.1.3. Установка сопутствующих приложений</title>
          <important><para>Внимание!!! Все сопутствующие приложения должны быть установлены <command>ДО</command> установки <xref linkend="РМО"/> 1.5.</para></important>
          <para>Для корректной работы некоторым приложениям <xref linkend="РМО"/> 1.5 необходим Интернет-браузер Internet Explorer версии 5.5 service pack 1 или старше. Браузер, поставляемы с операционной системой WXP удовлетворяет требованиям <xref linkend="РМО"/> 1.5 и обновлять его не нужно, но в операционной системе W2000 по умолчанию установлена более старая версия Internet Explorer, и его нужно обновить с помощью файла <command>ie55sp1\ie5setup.exe</command>.</para>
          <para>При работе с данными <xref linkend="РМО"/> 1.5 использует пакет Microsoft Data Access Components 2.6 service pack 2, поэтому он должен быть установлен в систему с помощью файла <command>mdac26sp2.exe</command>.</para>
          <para>При выполнении сценариев в <xref linkend="РМО"/> 1.5 и конфигурировании станции используется набор библиотек Windows Script Host 5.6, поэтому он должен быть установлен с помощью файла <command>W2K56_scripten.exe</command>.</para>
          <para>При обработке <xref linkend="XML"/> данных приложения <xref linkend="РМО"/> 1.5 используют библиотеку Microsoft <xref linkend="XML"/> Document Object Model (DOM) версии 4 service pack 2. Установить библиотеку можно с помощью файла <command>msxml4sp2.exe</command>. В состав операционных систем W2000 и WXP входит версия 3 данной библиотеки, которая обеспечивает достаточную функциональность для всех приложений <xref linkend="РМО"/> 1.5, кроме визуальной библиотеки сценариев <xref linkend="РМО"/> 1.5.</para>
          <para>Для работы с описанием схемы объектов <xref linkend="ФПО"/> приложениями <xref linkend="РМО"/> 1.5 используются системные библиотеки <xref linkend="РМО"/> версии 2.3. Установить их следует с помощью файла <command>RmoLib23.exe</command>.</para>
        </section>
        
        <section><title>2.1.4. Установка РМО</title>
          <para>После выполнения <command>ВСЕХ</command> вышеописанных действий можно перейти к установке комплекса приложений Рабочее Место Оператора 1.5. Установка комплекса происходит в автоматическом режиме – пользователю нужно лишь указать путь, куда следует скопировать приложения. Если в процессе установки произошли какие-либо ошибки, следует отправить письмо в службу поддержки.</para>
        </section>
        
        <section><title>2.1.5. Рекомендации по настройке системозависимых компонент РМО</title>
          <para>Системные службы</para>
          <para>Некоторые компоненты <xref linkend="РМО"/> используют технологию <xref linkend="DCOM"/>. Поэтому для их корректного функционирования необходимо, чтобы в рамках операционной системы были запущены определенный системные службы:</para>
          <itemizedlist>
            <listitem><para>Сервер </para></listitem>
            <listitem><para>Удаленный вызов процедур (RPC)</para></listitem>
            <listitem><para>Локатор удаленного вызова процедур (RPC Locator)</para></listitem>
          </itemizedlist>
          <para>Проверить состояние этих служб можно в диалоге <emphasis>Панель управления -> Административные инструменты -> Службы</emphasis>. В графе <emphasis>Тип запуска</emphasis> для этих служб должно стоять <emphasis>Автоматически</emphasis>, а в графе <emphasis>Состояние</emphasis> – <emphasis>Запущено</emphasis>. Если это не так, то нужно произвести их настройку, вызвав диалог свойств службы двойным щелчком мыши на ее названии.</para>
        </section>
        
        <section><title>2.1.6. Настройка пользователей</title>
          <para>Программа установки <xref linkend="РМО"/> автоматически создает две локальные группы пользователей: <emphasis>RMO Administrators</emphasis> и <emphasis>RMO Users</emphasis>, и выполняет для них настройку COM (см. «<xref linkend="COMs"/>») серверов и сервисов, входящих в поставку <xref linkend="РМО"/>.</para>
          <para>По умолчанию в группу <emphasis>RMO Administrators</emphasis> входит группа локальных администраторов компьютера (<emphasis>Administrators</emphasis>), на который выполняется установка. Группа <emphasis>RMO Users включает</emphasis> в себя группу <emphasis>RMO Administrators</emphasis>, таким образом добавлять пользователей в обе группы не надо.</para>
          <para>В группу <emphasis>RMO Administrators</emphasis> следует включить пользователей ответственных за установку, настройку и администрирование <xref linkend="РМО"/>. В группу <emphasis>RMO Users</emphasis> добавьте остальных пользователей работающих с <xref linkend="РМО"/>.</para>
          <para>Ниже приведена сравнительная таблица прав доступных различным категориям пользователей.</para>
          <informaltable>
            <tgroup cols="3" align="left" colsep="1" rowsep="1">
              <colspec colnum="3" colname="c3"/>
              <thead>
                <row><entry>Операция</entry><entry>Пользователи группы RMO Administrators</entry><entry>Пользователи группы RMO Users</entry></row>
              </thead>
              <tbody>
                <row>
                  <entry>Запуск и работа с <xref linkend="РМО"/></entry>
                  <entry>+</entry>
                  <entry>+</entry>
                </row>
                <row>
                  <entry>Удаленный доступ к приложению Сервер статистики</entry>
                  <entry>+</entry>
                  <entry>+</entry>
                </row>
                <row>
                  <entry>Доступ к административной папке Admin</entry>
                  <entry>+<footnote><para>Настройка не автоматизирована, см. Настройка файловой системы.</para></footnote></entry>
                  <entry>-</entry>
                </row>
              </tbody>
            </tgroup>
          </informaltable>
          <para><command>Задача 1. Настройка файловой системы</command></para>
          <para>Для обеспечения безопасности работы <xref linkend="РМО"/>, следует выполнить настройку файловой системы, а именно папки Admin, расположенной в корне <xref linkend="РМО"/>.</para>
          <itemizedlist>
            <listitem><para><emphasis>Шаг 1a)</emphasis> С помощью проводника Windows (Explorer) выберите папку <emphasis>Admin</emphasis> в директории РМО и во всплывающем меню выберите <emphasis>Свойства</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1b)</emphasis> Выберите закладку <emphasis>Безопасность</emphasis>.</para>
                      <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\безопасность.gif"/></listitem>                                                              
            <listitem><para><emphasis>Шаг 1c)</emphasis> Нажмите кнопку <emphasis>Дополнительно</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1d)</emphasis> В появившемся окне удалите флаг <emphasis>Наследовать от родительского объекта применимые к дочерним объектам разрешения...</emphasis>, появиться диалог где следует нажать кнопку <emphasis>Удалить</emphasis>.</para>
                      <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\nasledovanie.gif"/></listitem>                                         
            <listitem><para><emphasis>Шаг 1e)</emphasis> Используя кнопку <emphasis>Добавить</emphasis>, добавьте в список пользователя <emphasis>SYSTEM</emphasis> и установите права <emphasis>Полный доступ</emphasis>.</para></listitem>
            <listitem><para><emphasis>Шаг 1f)</emphasis> Аналогично добавьте группу <emphasis>RMO Administrators</emphasis>.</para></listitem>
            <listitem><para><emphasis>Шаг 1g)</emphasis> Добавите группу <emphasis>RMO Users</emphasis> с правами только на чтение («Чтение»).</para></listitem>
            <listitem><para><emphasis>Шаг 1h)</emphasis> Нажмите <emphasis>OK</emphasis></para></listitem>
          </itemizedlist>
        </section>
        
        <section><title>2.1.7. Использование РМО</title>
          <para>После установки <xref linkend="РМО"/> на обслуживающий компьютер в стандартном меню Windows <emphasis>Пуск</emphasis> в подменю <emphasis>Программы</emphasis> появляется подменю <xref linkend="РМО"/> <xref linkend="АТС"/>. После запуска <xref linkend="РМО"/> на экране появится диалог идентификации пользователя, в котором следует указать имя и пароль для начала работы с <xref linkend="РМО"/>. Непосредственно после установки <xref linkend="РМО"/> зарегистрирован единственный пользователь – администратор (Admin) с пустым паролем. Настоятельно рекомендуется в первую очередь задать пароль администратора и зарегистрировать обычных пользователей. Процесс работы со списком пользователей описан в разделе Права доступа (см. разд. «<xref linkend="tri_odin_p9t"/>»).</para>
        </section>
        
        <section><title>2.1.8. Конфигурирование мультипортовой платы</title>
          <important><para>Описанная ниже процедура относится к мультипортовой плате неизвестного производителя для шины ISA. Для установки новых плат следует воспользоваться инструкцией и драйверами, поставляемыми фирмой-производителем.</para></important>
          <para>Для установки платы необходимо добавить в систему четыре COM-порта (см. «<xref linkend="COM-p"/>»). Процедура добавления нового порта выглядит следующим образом:</para>
          <para><command>Задача 1. Добавление нового порта</command></para>
          <itemizedlist>
            <listitem><para><emphasis>Шаг 1a)</emphasis> Откройте <emphasis>Панель управления</emphasis> из меню <emphasis>Пуск</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1b)</emphasis> Откройте окно <emphasis>Система</emphasis>, выберите закладку <emphasis>Оборудование</emphasis>.</para></listitem>                                                              
            <listitem><para><emphasis>Шаг 1c)</emphasis> Нажмите кнопку <emphasis>Добавить оборудование...</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1d)</emphasis> Далее в появившемся мастере выбирайте <emphasis>Добавить устройство</emphasis>, Выбрать из списка, <emphasis>Порты COM и LPT</emphasis>, <emphasis>Коммуникационный порт</emphasis>.</para>
                      <graphic fileref="F:/runtime-New_configuration/rmo/Result/illustrations/u_p_d/safety.jpg"/></listitem>                                         
            <listitem><para><emphasis>Шаг 1e)</emphasis> В поле <emphasis>Порт ввода-вывода</emphasis> наберите требуемый адрес порта ввода-вывода, в поле <emphasis>Номер прерывания</emphasis> выберите значение прерывания</para></listitem>
            <listitem><para><emphasis>Шаг 1f)</emphasis> Нажмите <emphasis>ОК</emphasis></para></listitem>
            <listitem><para><emphasis>Шаг 1g)</emphasis> Система предложит перезагрузить компьютер. Имеет смысл выполнить перезагрузку лишь после добавления всех четырех портов.</para>
                      <para>Используя указанную процедуру, добавьте в систему четыре новых порта, заполняя поля формы в соответствии с таблицей:</para>
                      <informaltable>
                        <tgroup cols="2" align="left" colsep="1" rowsep="1">
                          <colspec colnum="2" colname="c2"/>
                          <thead>
                            <row><entry>Порт ввода-вывода</entry><entry>Номер прерывания</entry></row>
                          </thead>
                          <tbody>
                            <row>
                              <entry>0180</entry>
                              <entry>5</entry>
                            </row>
                            <row>
                              <entry>0188</entry>
                              <entry>5</entry>
                            </row>
                            <row>
                              <entry>0190</entry>
                              <entry>5</entry>
                            </row>
                            <row>
                              <entry>0198</entry>
                              <entry>5</entry>
                            </row>
                          </tbody>
                        </tgroup>
                      </informaltable>          
            </listitem>
            <listitem><para><emphasis>Шаг 1h)</emphasis> После установки всех четырех портов перезагрузите компьютер.</para></listitem>
          </itemizedlist>
        </section>
        
      </section>            
      
    </chapter>
  </d:InfElement>

</d:DocumentationCore>