<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="bussing" name="Соединительные линии">
    <section><title id="tri_tri_tri" xreflabel="3.3.3. Соединительные линии">3.3.3. Соединительные линии</title>
      <d:InfElemRef id="ref_review_b" infelemid="review_b"/>
      <d:InfElemRef id="ref_main_window_b" infelemid="main_window_b"/>
      <d:InfElemRef id="ref_state_sections_b" infelemid="state_sections_b"/>
    </section>
  </d:InfElement>



  <d:InfElement id="review_b" name="Обзор">
    <section><title>Обзор</title>
      <para>Программа <emphasis>Соединительные линии</emphasis> предназначена для просмотра конфигурации и состояния внешних соединительных линий станции.</para>
      <para>С помощью программы Вы можете:</para>
        <itemizedlist>
          <listitem><para>Просматривать информацию о внешних направлениях, пучках, трактах и каналах станции.</para></listitem>
          <listitem><para>Просматривать динамическое состояние внешних соединительных линий (каналов) и <xref linkend="СУВ"/>.</para></listitem>
          <listitem><para>Производить следующие операции над каналами:</para>
            <itemizedlist>
              <listitem><para>блокировать входящую связь</para></listitem>
              <listitem><para>блокировать исходящую связь</para></listitem>
              <listitem><para>производить сброс состояния</para></listitem>
              <d:Nest id="occupy_channel_ftesting"/>
              <listitem><para>и др.</para></listitem>
            </itemizedlist>
          </listitem>
        </itemizedlist>
    </section>
  </d:InfElement>

  <d:InfElement id="main_window_b" name="Главное окно">
    <section><title>Главное окно</title>
      <para>Главное окно программы <emphasis>Соединительные линии</emphasis> выглядит следующим образом:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\СЛ-СЛ.gif"/>
        </informalfigure>
      <para>Слева расположена панель с закладками:</para>
      <para><command>Закладки</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Закладка</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry><xref linkend="СЛ"/></entry>
              <entry>Дерево соединительных линий</entry>
            </row>
            <row>
              <entry>АБ</entry>
              <entry>Список абонентов</entry>
            </row>
            <row>
              <entry>Индекс</entry>
              <entry>Индекс всех трактов, каналов и абонентов</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para>Справа расположена панель свойств текущего выбранного объекта. Она представляет собой список, содержимое которого зависит от текущего объекта.</para>
      <para>Главное окно программы c активной закладкой <emphasis>Индекс</emphasis> выглядит следующим образом:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\СЛ-индексы.gif"/>
        </informalfigure>
      <para>Перед списком индекса объектов расположено поле быстрого поиска объекта.</para>
      <para>Кнопка Состояние тракта открывает панель состояния трактов.</para>
      <para>Кнопка <emphasis>Указать</emphasis> служит для того, чтобы после выбора объекта в индексе можно было перейти на него в дереве. Например, найдя канал по конструктивному адресу (см. «<xref linkend="stradd"/>») в панели <emphasis>Индекс</emphasis> и нажав на <emphasis>Указать</emphasis> попадаем в дереве <xref linkend="СЛ"/> на этот канал. </para>
      <para>Кнопка <emphasis>Предыдущий</emphasis> служит для выбора предыдущего элемента.</para>
      <para>Кнопка <emphasis>Следующий</emphasis> служит для выбора следующего элемента.</para>
      <para><emphasis>Идентификация <xref linkend="СЛ"/></emphasis></para>
      <para>В приложениях <xref linkend="РМО"/> используется несколько способов идентификации соединительных линий:</para>
      <para><command>Способы идентификации соединительных линий</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <row>
              <entry>По номеру</entry>
              <entry>Номер представляет собой число в десятичной системе счисления; в характеристиках <xref linkend="СЛ"/> он отображается в поле <emphasis>Номер</emphasis></entry>
            </row>
            <row>
              <entry>По конструктивному адресу</entry>
              <entry><para>Конструктивный адрес (см. «<xref linkend="stradd"/>») представляет собой четыре числа в десятичной с/с, разделенные точками; опционально он может быть заключен в квадратные скобки; в характеристиках <xref linkend="СЛ"/> он отображается в поле <emphasis>Конструктивный адрес</emphasis></para>
                     <para>Для цифровых каналов конструктивный адрес является логическим понятием, поскольку физическую сущность имеет только сам тракт</para></entry>
            </row>
            <row>
              <entry>По адресу включения в коммутационное поле</entry>
              <entry>
                <itemizedlist>
                  <listitem><para> Для цифровых каналов это адрес включения в коммутационное поле модуля УКС; представляет собой число в шестнадцатеричной с/с (номер группового тракта УКС) и число в десятичной с/с (временная позиция), разделенные точкой и заключенные в круглые скобки</para></listitem>
                  <listitem><para>Для аналоговых линий это адрес включения в коммутационное поле модуля <xref linkend="БАЛ"/>Д; представляет собой число в шестнадцатеричной с/с (номер модуля <xref linkend="БАЛ"/>Д), число в десятичной с/с (номер тракта в <xref linkend="КП"/> <xref linkend="БАЛ"/>Д) и еще одно число в десятичной с/с (временная позиция в <xref linkend="КП"/> <xref linkend="БАЛ"/>Д), разделенные точкой и заключенные в круглые скобки</para></listitem>
                </itemizedlist>
                <para>В характеристиках <xref linkend="СЛ"/> адрес включения в <xref linkend="КП"/> отображается в поле <emphasis>Адрес включения в <xref linkend="КП"/></emphasis></para>
              </entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para>Можно производить поиск <xref linkend="СЛ"/> по конструктивному адресу (см. «<xref linkend="stradd"/>») и адресу включения в <xref linkend="КП"/>. Для этого в левой половине главного окна приложения на панели закладок нужно выбрать закладку <emphasis>Индекс</emphasis>, затем в поле ввода начать набирать конструктивный адрес линии или адрес включения в <xref linkend="КП"/> (вместе со скобками), тогда список автоматически позиционируется на линию с указанным конструктивным адресом или адресом включения в <xref linkend="КП"/>, и справа можно будет увидеть всю информацию о выбранной линии.</para>
      <d:Nest id="switching_on_trace"/>
    </section>
  </d:InfElement>

  <d:InfElement id="state_sections_b" name="Панель состояния трактов">
    <section><title>Панель состояния трактов</title>
      <para><emphasis>Обзор</emphasis></para>
      <para>Приложение <emphasis>Состояние трактов/канальных групп</emphasis> предназначено для отображения состояния <xref linkend="СЛ"/> станции и управления ими.</para>
      <para>С помощью программы вы можете:</para>
        <itemizedlist>
          <listitem><para>просматривать текущее состояние различных параметров каждой <xref linkend="СЛ"/> (зависит от сигнализации)</para></listitem>
          <listitem><para>просматривать текущее состояние различных параметров трактов (зависит от сигнализации)</para></listitem>
          <listitem><para>выполнять различные команды над трактами, отдельными <xref linkend="СЛ"/> и группами <xref linkend="СЛ"/> (зависит от сигнализации)</para></listitem>
        </itemizedlist>
      <para><emphasis>Главное окно</emphasis></para>
      <para>Главное окно приложения выглядит следующим образом:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\СЛ-состояние-трактов.gif"/>
        </informalfigure>
      <para>Окно разделено на три части:</para>
        <itemizedlist>
          <listitem><para>выбор тракта</para></listitem>
          <listitem><para>состояние тракта (динамическая информация)</para></listitem>
          <listitem><para>состояние каналов тракта (динамическая информация)</para></listitem>
        </itemizedlist>
      <para>В окне выбора тракта также отображается информация о текущем захваченном для прозвонки канале. У тракта, в котором есть захваченный канал, в графе <emphasis>Захвачен канал</emphasis> будет написан номер <xref linkend="ВК"/> и линейный номер захваченного канала.</para>
      <para>Главное меню содержит следующие команды:</para>
      <para><command>Команды главного меню</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <thead>
            <row><entry>Элемент меню/подменю</entry><entry>Описание</entry></row>
          </thead>
          <tbody>
            <row>
              <entry>Обновить</entry>
              <entry>Обновить динамическую информацию</entry>
            </row>
            <row>
              <entry>Правка -> Выделить все каналы</entry>
              <entry>Для всех каналов в текущем открытом списке каналов тракта выполнить операцию выделения</entry>
            </row>
            <row>
              <entry>Настройки -> Обновлять при переходе на тракт</entry>
              <entry>Если этот пункт меню включен, то при выборе тракта в списке трактов после перехода на него автоматически выполняется команда <emphasis>Обновить</emphasis></entry>
            </row>
            <row>
              <entry>Настройки -> Показывать внутренние состояния</entry>
              <entry>При отображении состояний объектов использовать внутренние имена состояний, понятные только их разработчикам</entry>
            </row>
            <row>
              <entry>Настройки -> Показывать полные значения полей In/Out</entry>
              <entry>Отображать значения <xref linkend="СУВ"/>, прочитанных из сканеров, целиком. По умолчанию отображаются только биты <xref linkend="СК"/> (один бит, два бита, либо байт, в зависимости от сигнализации)</entry>
            </row>
            <row>
              <entry>Справка</entry>
              <entry>Показать справку</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para>Установка автоматического обновления имитирует периодическое выполнение команды Обновить для данного тракта. Не следует ей злоупотреблять, так как она нагружает каналы обмена служебной информацией внутри станции и канал обмена между станцией и <xref linkend="РМО"/>.</para>
      <para><emphasis>Выполнение операций над трактами и каналами</emphasis></para>
      <para>Для выполнения операций над трактом, нужно перейти на него (выбрать в верхней части окна), затем подвести мышь к его состоянию (средней части окна) и нажать правую кнопку. Если над трактом можно производить какие-либо операции, то появится контекстное меню со списком этих операций:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\СЛ-действия-над-трактами.gif"/>
        </informalfigure>
      <para>Для выполнения операций над каналом или несколькими каналами нужно нажать правую кнопку мыши над требуемым каналом. Можно выбирать сразу несколько каналов для выполнения операций над ними. Выбор каналов производится мышью с нажатыми клавишами <command>Ctrl</command> (для выбора одиночных каналов) или <command>Shift</command> (для выбора диапазона каналов). Ниже представлен пример такого выбора:</para>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\СЛ-операции-над-каналами.gif"/>
        </informalfigure>
      <para>Следует обратить внимание на то, что часть команд над каналами воздействует только на один канал (самый первый из выбранных). Эта особенность команды специально отмечается в документации по ней.</para>
      <d:Nest id="attention_operation"/>
      <para><emphasis>Информация о тракте</emphasis></para>
      <para><command>Список всех возможных типов статической информации о тракте</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <row>
              <entry>Лин. #</entry>
              <entry>Линейный номер тракта</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <d:Nest id="mov_info_section"/>
      <d:Nest id="operation_on_sections"/>
      <para><emphasis>Информация о канале</emphasis></para>
      <para><command>Список всех возможных типов статической информации о канале</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <row>
              <entry>Лин. #</entry>
              <entry>Линейный номер канала</entry>
            </row>
            <row>
              <entry><xref linkend="ВК"/></entry>
              <entry>Временная позиция канала</entry>
            </row>
            <row>
              <entry>Тип</entry>
              <entry>Направленность канала – описана в таблице «Виды направленности канала»</entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para><command>Виды направленности канала</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <row>
              <entry><xref linkend="ВК"/></entry>
              <entry>Входящий</entry>
            </row>
            <row>
              <entry>ИК</entry>
              <entry>Исходящий</entry>
            </row>
            <row>
              <entry>ДК</entry>
              <entry>Двунаправленный</entry>
            </row>
            <row>
              <entry>СЛМ</entry>
              <entry>Входящий <xref linkend="МГ"/></entry>
            </row>
            <row>
              <entry>ЗСЛ</entry>
              <entry>Исходящий <xref linkend="МГ"/></entry>
            </row>
          </tbody>
        </tgroup>
      </informaltable>
      <para><command>Список всех возможных типов динамической информации о канале</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <d:Nest id="mov_info_restart"/>
            <row>
              <entry>In, Out</entry>
              <entry>Состояния <xref linkend="СУВ"/>. Для <xref linkend="BCKu"/> показываются значения 2СК 1СК, для <xref linkend="BCK1"/> – 1СК, для трехпроводной (см. «<xref linkend="wire"/>») и шлейфной (см. «<xref linkend="loops"/>») – байты</entry>
            </row>
            <row>
              <entry>АппБлк</entry>
              <entry>Аппаратная блокировка</entry>
            </row>
            <row>
              <entry>ИсхБлк</entry>
              <entry>Блокировка исходящей связи (с внешней стороны)</entry>
            </row>
            <row>
              <entry>ВхБлк</entry>
              <entry>Блокировка входящей связи</entry>
            </row>
            <row>
              <entry>АдмИсхБлк</entry>
              <entry>Административная блокировка исходящей связи (с нашей стороны)</entry>
            </row>
            <row>
              <entry>Сост. ЗО<xref linkend="ВС"/>л</entry>
              <entry>Состояние объекта ЗОВСл</entry>
            </row>
            <row>
              <entry>Сост. сигнализации</entry>
              <entry>Состояние объекта сигнализации</entry>
            </row>
            <row>
              <entry>ТЗСл</entry>
              <entry>Флаг трассировки объекта ЗОВСл</entry>
            </row>
            <row>
              <entry>ТСгн</entry>
              <entry>Флаг трассировки объекта сигнализации</entry>
            </row>
            <d:Nest id="mov_info_flag"/>
          </tbody>
        </tgroup>
      </informaltable>
      <para><emphasis>Операции над каналами</emphasis></para>
      <para><command>Список всех возможных операций над каналами</command></para>
      <informaltable>
        <tgroup cols="2" align="left" colsep="1" rowsep="1">
          <colspec colnum="2" colname="c2"/>
          <tbody>
            <row>
              <entry>Блокировать входящую связь</entry>
              <entry>Для всех выделенных каналов, предоставляющих такую возможность</entry>
            </row>
            <row>
              <entry>Разблокировать входящую связь</entry>
              <entry>Для всех выделенных каналов, предоставляющих такую возможность</entry>
            </row>
            <row>
              <entry>Блокировать исходящую связь</entry>
              <entry>Для всех выделенных каналов, предоставляющих такую возможность</entry>
            </row>
            <row>
              <entry>Разблокировать исходящую связь</entry>
              <entry>Для всех выделенных каналов, предоставляющих такую возможность</entry>
            </row>
            <row>
              <entry>Сбросить канал(ы)</entry>
              <entry>Послать команду сброс для всех выделенных каналов <d:Nest id="where_use"/></entry>
            </row>
            <row>
              <entry>Захватить канал</entry>
              <entry>Захватить канал для прозвонки. После захвата канала и установки у одного из абонентов станции класса обслуживания 2 выход на внешние направления с этого абонента будет осуществляться только через этот канал. Внимание! если после того, как канал был захвачен, произошел рестарт одного или нескольких модулей, участвующих в управлении или распределении канала (модули Ц<xref linkend="СЛ"/>, УКС, <xref linkend="БАЛ"/>Д <xref linkend="СЛ"/>), то захват следует либо отменить, либо повторить. Для повтора захвата нужно повторно выполнить эту же команду <d:Nest id="where_use"/>.</entry>
            </row>
            <row>
              <entry>Снять захват</entry>
              <entry>Отменить действие предыдущей команды. На абонентов эта команда не воздействует <d:Nest id="where_use"/>.</entry>
            </row>
            <row>
              <entry>Включить трассу объекта(ов) ЗОВСл</entry>
              <entry>Для всех выделенных каналов <d:Nest id="where_use"/></entry>
            </row>
            <row>
              <entry>Выключить трассу объекта(ов) ЗОВСл</entry>
              <entry>Для всех выделенных каналов <d:Nest id="where_use"/></entry>
            </row>
            <row>
              <entry>Включить трассу объекта(ов) сигнализации</entry>
              <entry>Для всех выделенных каналов <d:Nest id="where_use"/></entry>
            </row>
            <row>
              <entry>Выключить трассу объекта(ов) сигнализации</entry>
              <entry>Для всех выделенных каналов <d:Nest id="where_use"/></entry>
            </row>
            <row>
              <entry>Пройти по шнуру</entry>
              <entry>Вызвать панель прохода по шнуру для канала <d:Nest id="where_use"/></entry>
            </row>
            <d:Nest id="operation_channel_15"/>
          </tbody>
        </tgroup>
      </informaltable>
    </section>
  </d:InfElement>

</d:DocumentationCore>