/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.spbu.pldoctoolkit.graph.validation;

import org.spbu.pldoctoolkit.graph.ProductLine;
import org.w3c.dom.Node;


/**
 * A sample validator interface for {@link org.spbu.pldoctoolkit.graph.Product}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateId(String value);

	boolean validateProductLine(ProductLine value);

	boolean validateNode(Node value);
}
