<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
	<d:InfElement id="about_company" name="О компании">
		<para xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			Компания <d:DictRef dictid="company" entryid="name"/> занимается разработкой комплексных
			средств защиты от сетевых угроз с 1990 года и на данный момент является безусловным лидером
			в этой области.
		</para>
	</d:InfElement>
	
	<d:InfElement id="preface" name="Вступление">
		<preface xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<title>Встепление</title>
			<para>
				Благодарим за приобретение <d:DictRef dictid="main" entryid="productname"/>!
			</para>
			<d:InfElemRef groupid="" id="ref_about" infelemid="about_company" optional="true"/>
		</preface>
	</d:InfElement>
	
	
	<d:InfElement id="firewall" name="Брандмауэр">
		<chapter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<title>Брандмауэр</title>
			<d:InfElemRef groupid="" id="ref_firewall_What_is_firewall" infelemid="what_is_firewall" optional="true"/>
			<d:InfElemRef groupid="" id="ref_config_firewall_Config_firewall" infelemid="configuring_firewall" optional="false"/>
		</chapter>
	</d:InfElement>
	
	<d:InfElement id="what_is_firewall" name="Что такое брандмауэр">
		<para>
			Брандмауэр (firewall) - перегородка из огнеупорного материала, 
			возводимая на пути распространения пожара. Также данный термин 
			стал использоваться для обозначения аппаратных и программных 
			средств сетевой защиты (сетевой экран). Пожалуй, такое название 
			было выбрано из маркетинговых соображений: "Пусть за стеной 
			бушует пожар или беснуются варвары, но вам за надежной защитой 
			ничего не грозит". В действительности сетевой экран походит не 
			на сплошную стену, а на таможенный пост, где в соответствии с 
			предписаниями проверяется багаж путешественников. Если груз к 
			ввозу или вывозу разрешен, его пропускают. Если нет - извините. 
			Причем решения принимаются на основе адресов получателя/отправителя, 
			а не содержимого груза. Так что доверенный отправитель может 
			отправить своему визави не только поздравительную открытку, но и 
			грамм триста тротилового эквивалента. Таможня "посылочку" 
			пропустит, если связь разрешена в предписании.
		</para>
	</d:InfElement>
	
	<d:InfElement id="configuring_firewall" name="Конфигурирование брандмауэра">
		<para>
			Конфигурация нашего брандмауэра является интуитивно понятной и не должна
			вызвать каких-либо трудностей. Если у вас возникнут какие-либо трудности 
			с настройках обращайтесь в нашу Службу Поддержки!
		</para>
	</d:InfElement>
	
	<d:InfElement id="antivirus" name="Анти-вирус">
		<chapter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<title>Антивирус</title>
			<d:InfElemRef groupid="" id="ref_antivirus_What_is_antivirus" infelemid="what_is_antivirus" optional="true"/>
			<!--d:InfElemRef groupid="" id="ref_antivirus_Config_antivirus" infelemid="configuring_antivirus" optional="false"/-->
			<para>
				Действия при обнаружении вируса или другой угрозы.
				- доступны следующие виды действий: <d:Nest id="danger_actions_list"/>
				- удаление
				<d:Nest id="advanced_features">
					- карантинной зоной
				</d:Nest>
				- просмотр журнала событий
			</para>
		</chapter>
	</d:InfElement>
	
	<d:InfElement id="what_is_antivirus" name="Что такое анти-вирус">
		<para>
			Антивирусная программа (антивирус) — программа для обнаружения и удаления компьютерных вирусов и других вредоносных программ, предотвращения их распространения, а также лечения программ зараженных ими.
		</para>
		<para>
			Первые, наиболее простые антивирусные программы появились почти сразу после появления вирусов. Сейчас разработкой антивирусов занимаются крупные компании. Как и у создателей вирусов, в этой сфере также сформировались оригинальные приемы - но уже для поиска и борьбы с вирусами. Современные антивирусные программы могут обнаруживать десятки тысяч вирусов.
			Основные задачи современных антивирусных программ:
			<itemizedlist mark="opencircle">
				<listitem><para>Сканирование файлов и программ в режиме реального времени.</para></listitem>
				<listitem><para>Сканирование компьютера по требованию.</para></listitem>
				<listitem><para>Сканирование интернет-трафика.</para></listitem>
				<listitem><para>Сканирование электронной почты.</para></listitem>
				<listitem><para>Защита от атак враждебных веб-узлов.</para></listitem>
				<listitem><para>Восстановление поврежденных файлов (лечение).</para></listitem>
			</itemizedlist>		
		</para>
	</d:InfElement>
	
	<d:InfElement id="configuring_antivirus" name="Конфигурирование антивируса">
		<!-- ... -->
	</d:InfElement>
	
	<d:InfElement id="controlcenter" name="Центр управления">
		<chapter>
			<title>Центр управления</title>
			<para>
				Центр управления предоставляет единый интерфейс для управления всеми компонентами системы безопасности
				<d:DictRef dictid="main" entryid="productname"/>.
			</para>
			<d:InfElemRef groupid="" id="ref_components_update" infelemid="components_update" optional="true"/>
		</chapter>
	</d:InfElement>
	
	<d:InfElement id="components_update" name="Обновление компонент">
		<para>
			<!--d:InfElemRef groupid="update_methods" id="ref_components_update_common" infelemid="components_update_сommon" optional="false"/>
			<d:InfElemRef groupid="update_methods" id="ref_components_update_centralized" infelemid="components_update_centralized" optional="false"/>
			<d:InfElemRefGroup id="update_methods" modifier="XOR" name="способы обновления"/-->
			
			<d:Nest id="av-update">
				<!-- Настройки обновления антивируса -->
			</d:Nest>
			<d:Nest id="as-update">
				<!-- Настройки обновления антиспама-->
			</d:Nest>
		</para>
	</d:InfElement>
	
	<d:InfElement id="components_update_centralized" name="Централизованные обновления">
		<!-- ... -->
	</d:InfElement>
	
	<d:InfElement id="components_update_сommon" name="Обновления с сервера компании">
		<!-- ... -->
	</d:InfElement>
	
	<d:Dictionary id="company">
		<d:Element id="name">ИнтерБез Солюшнз</d:Element>
	</d:Dictionary>
</d:DocumentationCore>