#!/bin/bash
export LANG=en_US.UTF-8
man -P cat ber_alloc_t >> _libldap_2.4.44_man.txt
man -P cat ber_bvarray_add >> _libldap_2.4.44_man.txt
man -P cat ber_bvarray_free >> _libldap_2.4.44_man.txt
man -P cat ber_bvdup >> _libldap_2.4.44_man.txt
man -P cat ber_bvecadd >> _libldap_2.4.44_man.txt
man -P cat ber_bvecfree >> _libldap_2.4.44_man.txt
man -P cat ber_bvfree >> _libldap_2.4.44_man.txt
man -P cat ber_bvstr >> _libldap_2.4.44_man.txt
man -P cat ber_bvstrdup >> _libldap_2.4.44_man.txt
man -P cat ber_dupbv >> _libldap_2.4.44_man.txt
man -P cat ber_first_element >> _libldap_2.4.44_man.txt
man -P cat ber_flush >> _libldap_2.4.44_man.txt
man -P cat ber_free >> _libldap_2.4.44_man.txt
man -P cat ber_get_bitstring >> _libldap_2.4.44_man.txt
man -P cat ber_get_boolean >> _libldap_2.4.44_man.txt
man -P cat ber_get_enum >> _libldap_2.4.44_man.txt
man -P cat ber_get_int >> _libldap_2.4.44_man.txt
man -P cat ber_get_next >> _libldap_2.4.44_man.txt
man -P cat ber_get_null >> _libldap_2.4.44_man.txt
man -P cat ber_get_stringa >> _libldap_2.4.44_man.txt
man -P cat ber_get_stringb >> _libldap_2.4.44_man.txt
man -P cat ber_next_element >> _libldap_2.4.44_man.txt
man -P cat ber_peek_tag >> _libldap_2.4.44_man.txt
man -P cat ber_printf >> _libldap_2.4.44_man.txt
man -P cat ber_put_enum >> _libldap_2.4.44_man.txt
man -P cat ber_put_int >> _libldap_2.4.44_man.txt
man -P cat ber_put_null >> _libldap_2.4.44_man.txt
man -P cat ber_put_ostring >> _libldap_2.4.44_man.txt
man -P cat ber_put_seq >> _libldap_2.4.44_man.txt
man -P cat ber_put_set >> _libldap_2.4.44_man.txt
man -P cat ber_put_string >> _libldap_2.4.44_man.txt
man -P cat ber_scanf >> _libldap_2.4.44_man.txt
man -P cat ber_skip_tag >> _libldap_2.4.44_man.txt
man -P cat ber_start_set >> _libldap_2.4.44_man.txt
man -P cat ber_str2bv >> _libldap_2.4.44_man.txt
man -P cat lber-decode >> _libldap_2.4.44_man.txt
man -P cat lber-encode >> _libldap_2.4.44_man.txt
man -P cat lber-memory >> _libldap_2.4.44_man.txt
man -P cat lber-sockbuf >> _libldap_2.4.44_man.txt
man -P cat lber-types >> _libldap_2.4.44_man.txt
man -P cat ld_errno >> _libldap_2.4.44_man.txt
man -P cat ldap >> _libldap_2.4.44_man.txt
man -P cat ldap_abandon >> _libldap_2.4.44_man.txt
man -P cat ldap_abandon_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_add >> _libldap_2.4.44_man.txt
man -P cat ldap_add_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_add_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_add_s >> _libldap_2.4.44_man.txt
man -P cat ldap_attributetype2name >> _libldap_2.4.44_man.txt
man -P cat ldap_attributetype2str >> _libldap_2.4.44_man.txt
man -P cat ldap_attributetype_free >> _libldap_2.4.44_man.txt
man -P cat ldap_bind >> _libldap_2.4.44_man.txt
man -P cat ldap_bind_s >> _libldap_2.4.44_man.txt
man -P cat ldap_compare >> _libldap_2.4.44_man.txt
man -P cat ldap_compare_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_compare_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_compare_s >> _libldap_2.4.44_man.txt
man -P cat ldap_control_create >> _libldap_2.4.44_man.txt
man -P cat ldap_control_dup >> _libldap_2.4.44_man.txt
man -P cat ldap_control_find >> _libldap_2.4.44_man.txt
man -P cat ldap_control_free >> _libldap_2.4.44_man.txt
man -P cat ldap_controls >> _libldap_2.4.44_man.txt
man -P cat ldap_controls_dup >> _libldap_2.4.44_man.txt
man -P cat ldap_controls_free >> _libldap_2.4.44_man.txt
man -P cat ldap_count_entries >> _libldap_2.4.44_man.txt
man -P cat ldap_count_messages >> _libldap_2.4.44_man.txt
man -P cat ldap_count_references >> _libldap_2.4.44_man.txt
man -P cat ldap_count_values >> _libldap_2.4.44_man.txt
man -P cat ldap_count_values_len >> _libldap_2.4.44_man.txt
man -P cat ldap_dcedn2dn >> _libldap_2.4.44_man.txt
man -P cat ldap_delete >> _libldap_2.4.44_man.txt
man -P cat ldap_delete_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_delete_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_delete_s >> _libldap_2.4.44_man.txt
man -P cat ldap_destroy >> _libldap_2.4.44_man.txt
man -P cat ldap_dn2ad_canonical >> _libldap_2.4.44_man.txt
man -P cat ldap_dn2dcedn >> _libldap_2.4.44_man.txt
man -P cat ldap_dn2str >> _libldap_2.4.44_man.txt
man -P cat ldap_dn2ufn >> _libldap_2.4.44_man.txt
man -P cat ldap_dnfree >> _libldap_2.4.44_man.txt
man -P cat ldap_dup >> _libldap_2.4.44_man.txt
man -P cat ldap_err2string >> _libldap_2.4.44_man.txt
man -P cat ldap_errlist >> _libldap_2.4.44_man.txt
man -P cat ldap_error >> _libldap_2.4.44_man.txt
man -P cat ldap_explode_dn >> _libldap_2.4.44_man.txt
man -P cat ldap_explode_rdn >> _libldap_2.4.44_man.txt
man -P cat ldap_extended_operation >> _libldap_2.4.44_man.txt
man -P cat ldap_extended_operation_s >> _libldap_2.4.44_man.txt
man -P cat ldap_first_attribute >> _libldap_2.4.44_man.txt
man -P cat ldap_first_entry >> _libldap_2.4.44_man.txt
man -P cat ldap_first_message >> _libldap_2.4.44_man.txt
man -P cat ldap_first_reference >> _libldap_2.4.44_man.txt
man -P cat ldap_free_urldesc >> _libldap_2.4.44_man.txt
man -P cat ldap_get_dn >> _libldap_2.4.44_man.txt
man -P cat ldap_get_option >> _libldap_2.4.44_man.txt
man -P cat ldap_get_values >> _libldap_2.4.44_man.txt
man -P cat ldap_get_values_len >> _libldap_2.4.44_man.txt
man -P cat ldap_init >> _libldap_2.4.44_man.txt
man -P cat ldap_init_fd >> _libldap_2.4.44_man.txt
man -P cat ldap_initialize >> _libldap_2.4.44_man.txt
man -P cat ldap_install_tls >> _libldap_2.4.44_man.txt
man -P cat ldap_is_ldap_url >> _libldap_2.4.44_man.txt
man -P cat ldap_matchingrule2name >> _libldap_2.4.44_man.txt
man -P cat ldap_matchingrule2str >> _libldap_2.4.44_man.txt
man -P cat ldap_matchingrule_free >> _libldap_2.4.44_man.txt
man -P cat ldap_memalloc >> _libldap_2.4.44_man.txt
man -P cat ldap_memcalloc >> _libldap_2.4.44_man.txt
man -P cat ldap_memfree >> _libldap_2.4.44_man.txt
man -P cat ldap_memory >> _libldap_2.4.44_man.txt
man -P cat ldap_memrealloc >> _libldap_2.4.44_man.txt
man -P cat ldap_memvfree >> _libldap_2.4.44_man.txt
man -P cat ldap_modify >> _libldap_2.4.44_man.txt
man -P cat ldap_modify_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_modify_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_modify_s >> _libldap_2.4.44_man.txt
man -P cat ldap_modrdn >> _libldap_2.4.44_man.txt
man -P cat ldap_modrdn2 >> _libldap_2.4.44_man.txt
man -P cat ldap_modrdn2_s >> _libldap_2.4.44_man.txt
man -P cat ldap_modrdn_s >> _libldap_2.4.44_man.txt
man -P cat ldap_mods_free >> _libldap_2.4.44_man.txt
man -P cat ldap_msgfree >> _libldap_2.4.44_man.txt
man -P cat ldap_msgid >> _libldap_2.4.44_man.txt
man -P cat ldap_msgtype >> _libldap_2.4.44_man.txt
man -P cat ldap_next_attribute >> _libldap_2.4.44_man.txt
man -P cat ldap_next_entry >> _libldap_2.4.44_man.txt
man -P cat ldap_next_message >> _libldap_2.4.44_man.txt
man -P cat ldap_next_reference >> _libldap_2.4.44_man.txt
man -P cat ldap_objectclass2name >> _libldap_2.4.44_man.txt
man -P cat ldap_objectclass2str >> _libldap_2.4.44_man.txt
man -P cat ldap_objectclass_free >> _libldap_2.4.44_man.txt
man -P cat ldap_open >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_extended_result >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_reference >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_result >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_sasl_bind_result >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_sort_control >> _libldap_2.4.44_man.txt
man -P cat ldap_parse_vlv_control >> _libldap_2.4.44_man.txt
man -P cat ldap_perror >> _libldap_2.4.44_man.txt
man -P cat ldap_rename >> _libldap_2.4.44_man.txt
man -P cat ldap_rename_s >> _libldap_2.4.44_man.txt
man -P cat ldap_result >> _libldap_2.4.44_man.txt
man -P cat ldap_result2error >> _libldap_2.4.44_man.txt
man -P cat ldap_sasl_bind >> _libldap_2.4.44_man.txt
man -P cat ldap_sasl_bind_s >> _libldap_2.4.44_man.txt
man -P cat ldap_schema >> _libldap_2.4.44_man.txt
man -P cat ldap_scherr2str >> _libldap_2.4.44_man.txt
man -P cat ldap_search >> _libldap_2.4.44_man.txt
man -P cat ldap_search_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_search_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_search_s >> _libldap_2.4.44_man.txt
man -P cat ldap_search_st >> _libldap_2.4.44_man.txt
man -P cat ldap_set_option >> _libldap_2.4.44_man.txt
man -P cat ldap_set_rebind_proc >> _libldap_2.4.44_man.txt
man -P cat ldap_set_urllist_proc >> _libldap_2.4.44_man.txt
man -P cat ldap_simple_bind >> _libldap_2.4.44_man.txt
man -P cat ldap_simple_bind_s >> _libldap_2.4.44_man.txt
man -P cat ldap_sort >> _libldap_2.4.44_man.txt
man -P cat ldap_sort_entries >> _libldap_2.4.44_man.txt
man -P cat ldap_sort_strcasecmp >> _libldap_2.4.44_man.txt
man -P cat ldap_sort_values >> _libldap_2.4.44_man.txt
man -P cat ldap_start_tls >> _libldap_2.4.44_man.txt
man -P cat ldap_start_tls_s >> _libldap_2.4.44_man.txt
man -P cat ldap_str2attributetype >> _libldap_2.4.44_man.txt
man -P cat ldap_str2dn >> _libldap_2.4.44_man.txt
man -P cat ldap_str2matchingrule >> _libldap_2.4.44_man.txt
man -P cat ldap_str2objectclass >> _libldap_2.4.44_man.txt
man -P cat ldap_str2syntax >> _libldap_2.4.44_man.txt
man -P cat ldap_strdup >> _libldap_2.4.44_man.txt
man -P cat ldap_sync >> _libldap_2.4.44_man.txt
man -P cat ldap_syntax2name >> _libldap_2.4.44_man.txt
man -P cat ldap_syntax2str >> _libldap_2.4.44_man.txt
man -P cat ldap_syntax_free >> _libldap_2.4.44_man.txt
man -P cat ldap_tls >> _libldap_2.4.44_man.txt
man -P cat ldap_tls_inplace >> _libldap_2.4.44_man.txt
man -P cat ldap_unbind >> _libldap_2.4.44_man.txt
man -P cat ldap_unbind_ext >> _libldap_2.4.44_man.txt
man -P cat ldap_unbind_ext_s >> _libldap_2.4.44_man.txt
man -P cat ldap_unbind_s >> _libldap_2.4.44_man.txt
man -P cat ldap_url >> _libldap_2.4.44_man.txt
man -P cat ldap_url_parse >> _libldap_2.4.44_man.txt
man -P cat ldap_value_free >> _libldap_2.4.44_man.txt
man -P cat ldap_value_free_len >> _libldap_2.4.44_man.txt
man -P cat ldap.conf >> _libldap_2.4.44_man.txt
