<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">
	<d:InfProduct id="UserManual" name="Руководство Пользователя">
		<book>
			<bookinfo>
				<title>Руководство Пользователя</title>
			</bookinfo>
			<d:InfElemRef id="preface" infelemid="preface"/>
			<d:InfElemRef id="controlcenter" infelemid="controlcenter"/>
			<d:InfElemRef id="firewall" infelemid="firewall"/>
			<d:InfElemRef id="antivirus" infelemid="antivirus" optional="true"/>
			<d:InfElemRef id="antispam" infelemid="antispam" optional="true"/>
		</book>
	</d:InfProduct>
</d:DocumentationCore>