<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->


<!ENTITY bkc1 SYSTEM "join_in_embsoft.e01">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/проводник-смм.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипты-РМО-общ.-вид1.gif" NDATA gif>
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипты-РМО-кнопка-сохранит.gif" NDATA gif>
<!ENTITY graphic4 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-сохранить-вс.gif" NDATA gif>
<!ENTITY graphic5 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-переместить.gif" NDATA gif>
<!ENTITY graphic6 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-копировать.gif" NDATA gif>
<!ENTITY graphic7 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-вставить.gif" NDATA gif>
<!ENTITY graphic8 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-выполнить.gif" NDATA gif>
<!ENTITY graphic9 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-прервать.gif" NDATA gif>
<!ENTITY graphic10 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-папка.gif" NDATA gif>
<!ENTITY graphic11 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипРМОкнопка-обновить.gif" NDATA gif>
<!ENTITY graphic12 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скрипты-РМО-вывод.gif" NDATA gif>
<!ENTITY graphic13 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/skriptyrmolog.gif" NDATA gif>
<!ENTITY graphic14 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скриптыРМОошибки.gif" NDATA gif>
<!ENTITY graphic15 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/скриптыРМОполе-редакт.gif" NDATA gif>
<?Fm Validation Off?>


<!-- End Document Specific Declarations -->

]>
<DocumentationCore filename = "Provodnik_CMM_scripti_MMO.drl">&bkc1;</DocumentationCore>
