<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ProductDocumentation SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!ENTITY bkc1 SYSTEM "UserManual_complete.e01">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/AbnStatesPich01.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/AbnStatesPich03.gif" NDATA gif>
<!ENTITY inlinegraphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sostojanie-ab-knopka-obnovit.gif" NDATA gif>
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/AbnStatesPich02.gif" NDATA gif>
<!ENTITY bkc2 SYSTEM "main0.e02">

<!-- End Document Specific Declarations -->

]>
<ProductDocumentation productid = "complete"
    filename = "UserManual_complete.drl">&bkc1;&bkc2;</ProductDocumentation>
