<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ProductDocumentation SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!ENTITY bkc1 SYSTEM "UserManual_based.e01">
<!ENTITY bkc2 SYSTEM "main.e02">

<!-- End Document Specific Declarations -->

]>
<ProductDocumentation productid = "based"
    filename = "UserManual_based.drl">&bkc1;&bkc2;</ProductDocumentation>
