<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!ENTITY bkc1 SYSTEM "service_map.e01">
<!ENTITY bkc2 SYSTEM "review_sm.e02">
<!ENTITY bkc3 SYSTEM "main_window_sm.e03">
<!NOTATION gif SYSTEM "">
<!ENTITY graphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sostojanie-abonenta.gif" NDATA gif>
<!ENTITY inlinegraphic1 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sost-ab-knopka-legenda.gif" NDATA gif>
<!ENTITY graphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sost-ab-legenda.gif" NDATA gif>
<!ENTITY inlinegraphic2 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sost-ab-knopka-statistika.gif" NDATA gif>
<!ENTITY graphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sost-ab-statistika.gif" NDATA gif>
<!ENTITY inlinegraphic3 SYSTEM "file:///F:/runtime-New_configuration/rmo/illustrations/ScreenShots-full/sostojanie-ab-knopka-obnovit.gif" NDATA gif>
<!ENTITY bkc4 SYSTEM "sentence_15_sm.e04">
<!ENTITY bkc5 SYSTEM "sentence_443_sm.e05">
<!ENTITY bkc6 SYSTEM "renewal_15_sm.e06">
<!ENTITY bkc7 SYSTEM "renewal_443_sm.e07">
<!ENTITY bkc8 SYSTEM "identif_15_sm.e08">
<!ENTITY bkc9 SYSTEM "identif_443_sm.e09">
<!ENTITY bkc10 SYSTEM "menu_sm.e10">

<!-- End Document Specific Declarations -->

]>
<DocumentationCore
    filename = "Карта_обслуживания_абонентских_линий.drl">&bkc1;&bkc2;&bkc3;&bkc4;&bkc5;&bkc6;&bkc7;&bkc8;&bkc9;&bkc10;</DocumentationCore>
