<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DocumentationCore SYSTEM "file:///C:/Program%20Files/Adobe/FrameMaker8/structure/xml/docline/docline.dtd" [

<!-- Begin Document Specific Declarations -->


<!ENTITY bkc1 SYSTEM "monitoring.e01">
<?Fm Validation Off?>


<!-- End Document Specific Declarations -->

]>
<DocumentationCore filename = "Мониторинг.drl">&bkc1;</DocumentationCore>
