<?xml version="1.0" encoding="UTF-8"?>
<d:DocumentationCore xmlns:d="http://math.spbu.ru/drl" xmlns="http://docbook.org/ns/docbook">

  <d:InfElement id="station_modules" name="Модули станции">
    <section><title>3.2.1. Модули станции</title>
      <section><title>Главное окно</title>
        <informalfigure>
          <graphic fileref="F:\runtime-New_configuration\rmo\illustrations\ScreenShots-full\upravl.-mod.-obtshij-vid.gif"/>
        </informalfigure>
        <para>Программа управления модулями предназначена для отображения состояния всех модулей станции и предоставляет возможность программно рестартовать модули, а также загружать программы и данные в микросхемы флэш-памяти модулей.</para>
        <para>Главное окно состоит из трех списков.</para>
        <para><emphasis>Список модулей станции</emphasis></para>
        <para>Список модулей станции расположен в левой части окна. Для неработающих модулей в правом столбце будет отображен прочерк «-». Нажав на модуле из списка правую кнопку мыши появляется всплывающее меню списка модулей, которое предоставляет оператору возможность рестартовать соответствующий модуль или загрузить новую программу во флэш.</para>
        <para>Список содержит следующую информацию по каждому модулю:</para>
        <para><command>Информация о модулях</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <tbody>
              <row>
                <entry>Имя модуля </entry>
                <entry>Символьное имя модуля в соответствии с <xref linkend="БД"/> <xref linkend="РМО"/></entry>
              </row>
              <row>
                <entry>Адрес</entry>
                <entry>Числовой идентификатор модуля</entry>
              </row>
              <row>
                <entry>@</entry>
                <entry>Состояние модуля. Может быть «-» либо «+» в зависимости от наличия связи с модулем</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><emphasis>Список файлов для выбранного модуля</emphasis></para>
        <para>Список файлов для выбранного модуля находится в правой части окна, сверху. Нажав на файле из списка правую кнопку мыши появляется всплывающее меню списка файлов, в котором есть команды для скачивания файлов и конфигов из станции.</para>
        <para>Список содержит следующую информацию по каждому файлу:</para>
        <para><command>Информация о файлах</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <tbody>
              <row>
                <entry>Имя</entry>
                <entry>Двухсимвольное внутристанционное имя файла</entry>
              </row>
              <row>
                <entry>Состояние</entry>
                <entry>Отражает состояние файла. Возможные состояния описаны в таблице « Возможные состояния файлов модулей»</entry>
              </row>
              <row>
                <entry>Адрес</entry>
                <entry>Адрес в памяти модуля, где расположен данный файл</entry>
              </row>
              <row>
                <entry>Длина</entry>
                <entry>Длина файла в памяти модуля</entry>
              </row>
              <row>
                <entry>Файл</entry>
                <entry>Файл на диске, с которым происходит сравнение</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Возможные состояния файлов модулей</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <tbody>
              <row>
                <entry>Модуль физически поврежден</entry>
                <entry>Файл, хранящийся в микросхеме FLASH, был поврежден. Необходима перепрошивка FLASH и, возможно, замена микросхемы</entry>
              </row>
              <row>
                <entry>Файл не найден</entry>
                <entry>На диске в указанном месте файл отсутствует, программа не может выполнить сравнение версий. Чтобы это сообщение не появлялось, поместите соответствующий файл в указанную директорию</entry>
              </row>
              <row>
                <entry>Несоответствие версий</entry>
                <entry>Файл на диске не соответствует файлу в станции</entry>
              </row>
              <row>
                <entry>Соответствие версий</entry>
                <entry>Файл на диске соответствует файлу в станции</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><emphasis>Список задач</emphasis></para>
        <para>Список задач расположен в правой части окна, снизу. Для работы с этим списком предназначено меню списка задач</para>
        <para>Список задач содержит следующую информацию по каждой задаче:</para>
        <para><command>Информация о задачах</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <tbody>
              <row>
                <entry>Название задачи</entry>
                <entry>Текстовое описание класса задачи (например: выкачка модуля, прошивка…)</entry>
              </row>
              <row>
                <entry>Описание задачи</entry>
                <entry>Более подробное описание задачи (например: выкачка файла 20.prg из модуля 20).</entry>
              </row>
              <row>
                <entry>Состояние задачи</entry>
                <entry>Индикация (в %) выполнения задачи либо индикация ошибочной ситуации.</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para>Далее приведено описание контекстных меню.</para>
        <para><command>Всплывающее меню списка модулей</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
              <row>
                <entry>Рестарт модуля</entry>
                <entry>Программный рестарт модуля. Для модулей УКС выполняется рестарт активного УУС, при этом не происходит обновления информации с дискеты. Для обновления памяти с дискеты требуется «холодный» рестарт кнопкой на лицевой панели.</entry>
              </row>
              <row>
                <entry>Загрузка программного модуля</entry>
                <entry>Позволяет загрузить файл в свободную оперативную память модуля. При выборе данного пункта появляется диалог, запрашивающий параметры загрузки.</entry>
              </row>
              <row>
                <entry>Обновить</entry>
                <entry>Обновление информации в списке.</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Всплывающее меню списка файлов</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
              <row>
                <entry>Скачать модуль</entry>
                <entry>Выкачать файл из станции и сохранить его на диске. При выполнении команды на экране появляется диалог сохранения файла.</entry>
              </row>
              <row>
                <entry>Скачать конфиг (см. «<xref linkend="config"/>»)</entry>
                <entry>Для модулей c микросхемой FLASH когфигурационный файл модуля не отображается в списке модулей. Для его выкачки служит эта команда, в остальном аналогичная команде <emphasis>Скачать модуль</emphasis>.</entry>
              </row>
              <row>
                <entry>Обновить</entry>
                <entry>Обновление информации в списке.</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><command>Примечание:</command> если выкачанный конфигурационный файл имеет нулевой размер, произведите рестарт модуля и повторите выкачку.</para>
        <para><command>Всплывающее меню списка файлов</command></para>
        <informaltable>
          <tgroup cols="2" align="left" colsep="1" rowsep="1">
            <colspec colnum="2" colname="c2"/>
            <thead>
              <row><entry>Элемент меню</entry><entry>Описание</entry></row>
            </thead>
            <tbody>
              <row>
                <entry>Закрыть нерабочие</entry>
                <entry>Закрыть задачи со статусом «Завершено»</entry>
              </row>
              <row>
                <entry>Завершить</entry>
                <entry>Прервать выполнение выделенной задачи</entry>
              </row>
              <row>
                <entry>Остальные пункты</entry>
                <entry>Управляют форматом отображения информации в списке</entry>
              </row>
            </tbody>
          </tgroup>
        </informaltable>
        <para><emphasis>Стандартные задачи</emphasis></para>
        <para><command>Задача 1. Скачать конфиг или модуль</command></para>
        <itemizedlist>
          <listitem><para><emphasis>Шаг 5a)</emphasis> Выбрать из списка, расположенного в левой части окна, нужный модуль</para></listitem>
          <listitem><para><emphasis>Шаг 5b)</emphasis> В правой части окна по нажать правую кнопку мыши</para></listitem>
          <listitem><para><emphasis>Шаг 5c)</emphasis> В появившемся меню выбрать команду <emphasis>Скачать конфиг</emphasis> или <emphasis>Скачать модуль</emphasis></para></listitem>
          <listitem><para><emphasis>Шаг 5d)</emphasis> Выбрать папку, в которой конфиг (см. «<xref linkend="config"/>») или модуль будет сохранен </para></listitem>
          <listitem><para><emphasis>Шаг 5e)</emphasis> При этом в нижней части окна появится сообщение о начале выполнения задачи</para></listitem>
        </itemizedlist>
      </section>
    </section>
    
  </d:InfElement>

</d:DocumentationCore>